### ISSUE TITLE
Is it possible to access the geometry library?

### ISSUE THREAD

**Issue by ism0080** [google-map-react/google-map-react#1002]
I am trying to create a driver tracking application where the Marker(driver) would move on the map with different geo locations every 5secs. I would like to use `google.maps.geometry.spherical.computeDistanceBetween` to calculate the distance between two geo locations so that i could try and smooth the transitions between each location

Is it possible to access this library?

**Comment by IBanda** [comment]
Yes it's possible to access the library, provided you add the 'geometry' library to the libraries array passed in the bootstrapURLKeys object.
The when google maps loads, you will be able to access it in the onGoogleApiLoaded callback, like this
`const onMapLoaded=({map,maps})=>{
maps.geometry.spherical.computeDistanceBetween
}`

I hope this helps

**Comment by ism0080** [comment]
@IBanda so that gets called once when the map is loaded and the API can't be accessed again unless the map is reloaded? I would ideally like to call the API when my marker lat/lng changes

**Comment by IBanda** [comment]
@ism0080 store the maps object in a ref ;
```
const mapsRef= useRef();

//when maps has loaded
mapsRef.current=maps;

//when lat/lng changes access it like so;
mapsRef.current.geometry...
```
That way you can access it later 
If you’re not familiar with the useRef hook, you can take a look [here](https://reactjs.org/docs/hooks-reference.html#useref)

**Comment by ism0080** [comment]
Cheers, that's exactly what i need

**Comment by ilhantekir** [comment]
load the geometry library for access;

bootstrapURLKeys={{ key: MY_API_KEY, libraries: ['geometry'] }}
