### ISSUE TITLE
defaultCenter is not updating

### ISSUE THREAD

**Issue by Harrrrry** [google-map-react/google-map-react#1013]
Hello,

I am trying to update the defaultCenter values but its not updating and showing the initial set values only.

`  const [defaultlatitude, setDefaultLatitude] = useState(25.2048);
  const [defaultlongitude, setDefaultLongitude] = useState(55.234);`

By useffect i set the below value
 ` setDefaultLatitude(stateObj.latitude);
  setDefaultLongitude(stateObj.longitude);`

Google code
`<GoogleMapReact
                  bootstrapURLKeys={{
                    key: "key for google",
                  }}
                  defaultCenter={{
                    lat: defaultlatitude,
                    lng: defaultlongitude,
                  }}
                  defaultZoom={zoom}
                >
                  <AnyReactComponent
                    lat={latitude}
                    lng={longitude}
                    text="My Marker"
                  />
                </GoogleMapReact>`

Any advice, thanks.

**Comment by IBanda** [comment]
Hey
You're not supposed to change the defaultCenter, use center instead.

**Comment by simplenotezy** [comment]
@IBanda , I am trying to update the `center` value using setState, however, when I call setCenter with some new lat/lng value, nothing happens.

```
  const [center, setCenter] = useState({
    lat: 55.41,
    lng: 12.34,
  });
<GoogleMapReact
center={center}
```

Am I doing something wrong?

**Comment by IBanda** [comment]
@simplenotezy That's strange, please take a look at this [Codesandbox](https://codesandbox.io/s/update-center-xdq4z) . Just incase you missed something

**Comment by simplenotezy** [comment]
@IBanda Here is an example from your provided link. It works the first time, but not the second. Not sure if this is related to my issue though, perhaps because the center I try to change to, is also the initial center.

![center not working](https://user-images.githubusercontent.com/3786627/115990891-0c18ed80-a5c6-11eb-9c60-3194e0d6046f.gif)

**Comment by IBanda** [comment]
@simplenotezy. I see, for that to work it means you need to keep the map's internal center in sync with the state center. In that case use the onChange prop on the map, it takes a function which is passed an object that contains the new center. I've updated the example I provided to match your case.

**Comment by simplenotezy** [comment]
@IBanda That's great. That resolved it 😊
