### ISSUE TITLE
[Help Needed] Warning: React does not recognize the `$X` prop on a DOM element

### ISSUE THREAD

**Issue by MohaElder** [google-map-react/google-map-react#1015]
Greetings!
I am receiving this several 'Warning: React does not recognize the `$getDimensions` prop on a DOM element.' when I'm trying to put constants/functions inside <GoogleMap />
`
const defaultMarkers = defaultItems.map((item) => (
        <div
            key={item.name}
            lat={college.lat}
            lng={college.lon}
            onClick={() => onSelect(item)}
        >
            {item.name}
        </div>
    ))

        <GoogleMap
            style={{ height: '100vh', width: '100%' }}
            bootstrapURLKeys={{ key: '' }}
            defaultCenter={{
                lat: 59.95,
                lng: 30.33
            }}
            defaultZoom={11}
        >
            {defaultMarkers}
        </GoogleMap>
`

The above code will produce the following errors:
_Warning: React does not recognize the `$getDimensions` prop on a DOM element. If you intentionally want it to appear in the DOM as a custom attribute
...
index.js:1 Warning: React does not recognize the `$dimensionKey` prop on a DOM element. If you intentionally want it to appear 
index.js:1 Warning: Invalid attribute name: `$onMouseAllow`
index.js:1 Warning: Invalid attribute name: `$prerender`_

After going through Stackoverflow and Official Documents, I find using
`{
   ()=>{
     //code
   }
}` 
can remove the errors, but then the map does not read my _defaultMarkers_ constant.
In Official document, I saw 
`{places.map((place) => (
              <Marker
                key={place.id}
                text={place.name}
                lat={place.geometry.location.lat}
                lng={place.geometry.location.lng}
              />
            ))}`
which is like how I coded.

I was wondering what have I done wrong or is this a library bug?
Looking forward to your reply! Many Thanks!

**Comment by Pixcell** [comment]
Linked to this: https://github.com/google-map-react/google-map-react/issues/213

Workaround is to encapsulate your div inside a React Component. 
See example below:

````js
    <div>
      <GoogleMapReact
        {...mapData}
      >
        {loading
          ? null
          : nodes.map(_buildNodeMarker)}
      </GoogleMapReact>
    </div>
````
````js
function _buildNodeMarker (node: ECNode): JSX.Element {
  const { getNodeCoordinates } = useMap()

  return (<NodeMarker key={node.uuid} {...getNodeCoordinates(node)} />)
}

const NodeMarker: React.FC = () => {
  return <div style={{ width: 20, height: 20, backgroundColor: '#ffffff' }} />
}
````

**Comment by NellyHaglund** [comment]
By wrapping my markers insida React component I do get the errors to disappear. But then the markers will moving around when I zoom or move around on the map, which was solved with `translate(-50%, -100%)` - but moving it into the component this will stop working. Anyone had the same issue?
