### ISSUE TITLE
Image as marker is not shown

### ISSUE THREAD

**Issue by mariosarbinov** [google-map-react/google-map-react#1018]
**Describe the bug 🐛**

The image in the component for the marker is not shown.

**To Reproduce 🔍**

`const AnyReactComponent = () => </escape tag/div></escape tag/img src="/src/images/marker.png" alt="marker"/></div>;

<GoogleMapReact
                    ...
                >
                    <AnyReactComponent
                        lat={44.672}
                        lng={43.314}
                    />
                </GoogleMapReact>`

**Expected behavior 💭**

The image to be shown properly.
![image](https://user-images.githubusercontent.com/9549335/113161091-bbbca300-9246-11eb-81ff-1c3adeb401ce.png)

**Comment by itsmichaeldiego** [comment]
I think your code is not correct, what is `escape tag`? You can check the example in the Readme, try to make it work that way, remember, place a div and inside of it place the image, something like:

```javascript
import React from "react";
import GoogleMapReact from 'google-map-react';

const AnyReactComponent = (props) => <div {...props}><img src="/src/images/marker.png" alt="marker"/></div>;

export default function SimpleMap(){
  const defaultProps = {
    center: {
      lat: 10.99835602,
      lng: 77.01502627
    },
    zoom: 11
  };

  return (
    // Important! Always set the container height explicitly
    <div style={{ height: '100vh', width: '100%' }}>
      <GoogleMapReact
        bootstrapURLKeys={{ key: "" }}
        defaultCenter={defaultProps.center}
        defaultZoom={defaultProps.zoom}
      >
        <AnyReactComponent
          lat={59.955413}
          lng={30.337844}
        />
      </GoogleMapReact>
    </div>
  );
}
```
