### ISSUE TITLE
IIFE package conflicts

### ISSUE THREAD

**Issue by CYchenyan** [google-map-react/google-map-react#1025]
I have two iife package depend on the google-map-react now, I used the both two packages on the same web page, there are conflict errors in console, the errors is :
![image](https://user-images.githubusercontent.com/13826103/116371870-75a33100-a83e-11eb-837a-9d3e05e9e305.png)
I think this error is caused by reloading map resources.
How could I solve this error, please ？

**Comment by itsmichaeldiego** [comment]
Hey @CYchenyan, could you please provide more information and a code example? I am not sure what can be causing this issue, there shouldn't be any problem using two instances of Google Maps.
