### ISSUE TITLE
Map not showing any google provided markers.  

### ISSUE THREAD

**Issue by ReactAndNode** [google-map-react/google-map-react#1031]
What I see: 
![Screen Shot 2021-05-12 at 9 22 11 PM](https://user-images.githubusercontent.com/30379713/118063965-1ed24700-b368-11eb-95c9-8ea63763e2f2.png)

No recommendation or any places on the map. 

What I see on the examples: 
![Screen Shot 2021-05-12 at 9 23 01 PM](https://user-images.githubusercontent.com/30379713/118064027-3d384280-b368-11eb-8734-203d819b9e04.png)

It shows you stores and places on the map. Provided by Google map

Is there a way to get my map to show these recommended place markers on the map?

**Comment by Nguyenvantu** [comment]
You need add this options to map's props
`options={{
  styles: [
            {
              featureType: "all",
              elementType: "labels",
              stylers: [
                {
                  visibility:  "on",
                }
              ]
            }
          ]
 }}`

**Comment by kamal-hossain** [comment]
> You need add this options to map's props `options={{ styles: [ { featureType: "all", elementType: "labels", stylers: [ { visibility: "on", } ] } ] }}`

Why it is not working if ` mapTypeId: 'satellite'` is provided in `options` like this:
```
 options={{
             mapTypeId: 'satellite',
              styles: [{
                    featureType: 'all',
                    elementType: 'labels',
                     stylers: [{ visibility: 'on' }],
                 }],
}}
```
It working without `satellite` option.
