### ISSUE TITLE
Google Javascript Warning about styles and mapid both being used 

### ISSUE THREAD

**Issue by jfarris587** [google-map-react/google-map-react#1039]
**Describe the bug 🐛**

Google Maps Javascript API is warning about styles and MapID for cloud styling being used together

**To Reproduce 🔍**

When passing `mapId` via `options` prop, google maps Javascript API complains with the following warning:

```
react_devtools_backend.js:2560 Google Maps JavaScript API: A Map's styles property cannot be set when a mapId is 

present. When a mapId is present Map styles are controlled via the cloud console. Please see documentation at 

https://developers.google.com/maps/documentation/javascript/styling#cloud_tooling
```

https://codesandbox.io/s/quirky-moser-7ylxu?file=/src/App.js

**Expected behavior 💭**

No warning

**Environment:**

 - OS: Mac
 - Browser Chrome
 - Version 92

**Additional context**

It seems as though because `google-map-react` is passing it a styles object, which is not permitted when a cloud mapid is being used

**Comment by gorkalaucirica** [comment]
You can disable styles when using `mapId`:

```
const keys: BootstrapURLKeys & { mapIds: string[] } = {
  key: API_KEY,
  mapIds: [MAP_ID],
};
// ...
 <GoogleMapReact
     bootstrapURLKeys={keys}
     options={{
         mapId: MAP_ID,
         styles: undefined,
     }}
/>
```
