### ISSUE TITLE
Add digital signature 

### ISSUE THREAD

**Issue by iepgnahz** [google-map-react/google-map-react#1040]
Hi team, and thanks for this lib, it works very well in our project.
## Describe the Feature  🔍
The current existing API allows us to pass in the API key to authenticate requests associated with our project for usage and billing purposes, that's good.
But there doesn't have any way to pass digital signature. According to google map's document:

```
To use the Maps Static API you must have an API key.
Depending on your usage, a digital signature may also be required (see Other Usage Limits) The digital signature allows our servers to verify that any site generating requests using your API key is authorized to do so.

We strongly recommend that you use both an API key and digital signature, regardless of your usage.
```
Our project is likely to get a lot of traffic, according to the google map's document: 

```
Requests up to 25,000 per day require an API key.
Requests exceeding 25,000 requests per day require an API key and a digital signature.
```

our requests may exceeding 25,000 requests per day, so we may need a digital signature to make sure our project works well under the high traffic.

## Expected behavior 💭
The Component can accept signature, and add the resulting signature to the map request URL within a signature parameter. like:

```
https://maps.googleapis.com/maps/api/staticmap?center=40.714%2c%20-73.998&zoom=12&size=400x400&key=YOUR_API_KEY&signature=BASE64_SIGNATURE
```

Thanks!

## Useful Link:

- https://developers.google.com/maps/documentation/maps-static/get-api-key#dig-sig-auto
- https://developers.google.com/maps/documentation/maps-static/usage-and-billing#other-usage-limits

**Comment by karldanninger** [comment]
Hi @iepgnahz I don't believe signatures are required or are even an option for use with the Google Maps Javascript API, those are specific for the Static API. I hope that helps.
