### ISSUE TITLE
How to show the Yard Type (F,B,L,R) once we complete the polygon drawing 

### ISSUE THREAD

**Issue by Singapuram** [google-map-react/google-map-react#1055]
Hello Experts,

How can I show the Yard Type (F,B,L,R) once we complete the polygon drawing, It would be great if you can suggest on this.

![image](https://user-images.githubusercontent.com/78669287/131237130-1581e9ca-fa68-406c-82b6-7c3d4adbdc4b.png)
![image](https://user-images.githubusercontent.com/78669287/131237212-5e67b335-2746-46f8-961c-84c04ec195a6.png)

![image](https://user-images.githubusercontent.com/78669287/131237231-a698e275-eebe-4af3-9826-df653f821e66.png)

Thanks
-Sri

**Comment by itsmichaeldiego** [comment]
@Singapuram Hey Sri! This is more a problem related to **google maps** and not this library. Our library just renders the map in React. I recommend you to find the solution for google maps and then just apply it to React.
