### ISSUE TITLE
Do not show places around.

### ISSUE THREAD

**Issue by linhho89** [google-map-react/google-map-react#1062]
why I have put libraries:['places'] but the map still doesn't show the places around, Is it a bug from the library or do I need to configure it somewhere, because other sites using the same key still show up.
Has anyone solved this problem please help me, thanks.

<img width="713" alt="Screen Shot 2021-09-15 at 09 48 33" src="https://user-images.githubusercontent.com/32919568/133362620-da02f6b6-a134-49d0-b53a-fdc794a0672a.png">

**Comment by SanipRijal** [comment]
@linhho89 you can refer to issue #1031.
