### ISSUE TITLE
Google Map React Defaultcenter dynamic value not support?

### ISSUE THREAD

**Issue by siamahnaf198** [google-map-react/google-map-react#1068]
I am building a next js application. Here I am facing one problem. I have an api from backend like this-
```
"rooms": [
        {
          "id": "6178f32148cdaf9caad775a5",
          "name": "Kelmot Villa",
          "lat": "22.7562851",
          "lng": "90.4109839"
        }
]
```
And this is my component-
```
import {Container, Heading, Image, Box} from "theme-ui";
import GoogleMapReact from 'google-map-react';
import {useSelector} from "react-redux";

const ResMaps = () => {
    const {rooms} = useSelector(state => state.roomsByName);
    return (
        <Container sx={styles.Container} className="Consfhru">
            <GoogleMapReact
                bootstrapURLKeys={{key: "API_KEY"}}
                center={{lat: 22.75, lng: 90.41}}
                defaultZoom={11}
            >
                {rooms.slice(0, 10).map((room, i) => (
                    <div
                        key={i}
                        lat={room.lat}
                        lng={room.lng}
                        sx={styles.MapImageContainer}
                    >
                        <Image
                            sx={styles.MapImages}
                            src={room.images[0].url}
                            alt="Images"
                        />
                        <Heading sx={styles.MapPrice} as="h3">${room.price}</Heading>
                    </div>
                ))
                }
            </GoogleMapReact>
        </Container>
    );
};
export default ResMaps;
```

Here in center value-

`center={{lat: 22.75, lng: 90.41}}`

When I hard coded lat and lng like above the map showing perfectly. 
![Screenshot 2021-10-29 014321](https://user-images.githubusercontent.com/78312010/139325489-8247c964-e298-4e3d-89f8-e646c164162b.png)

But I want to show center lat and lng from backend information like-

`center={{lat: rooms[0].lat, lng: rooms[0}.lng}`

Then it not showing map. It show only whitescreen like image- 

![Screenshot 2021-10-29 014255](https://user-images.githubusercontent.com/78312010/139325580-71a8ef9f-c5af-4a0e-8b2e-84c89d8755cc.png)

What I have to do. For dynamic center. here I not give dynamic center then marker go to the outside of map if the marker is far from center point. That's why it's need to give dynamic value to center.

**Comment by MzkZeeshan** [comment]
did you find any solution

**Comment by siamahnaf198** [comment]
Yes, I find the solutions. Actually 

`center={{lat: rooms[0].lat, lng: rooms[0}.lng}`

here `lat` and `lng` need number or integer format. But here it is string. Just convert it to number, like-

`number(rooms[0].lat)`
