### ISSUE TITLE
How to get layer data that already loaded?

### ISSUE THREAD

**Issue by ydhnwb** [google-map-react/google-map-react#1085]
I created a maps and then load some KML into it.
But I also want to get the value of kml ( I want to extract to coordinates of the polygon).

Can I achieve this like maps.getLayer (its just an example)?
Because I don't see any property to get the loaded layer.

Or Should I load the kml differently?

**Comment by giardb** [comment]
Hi,

I think you can access loaded map with this [onGoogleApiLoaded callback](https://github.com/google-map-react/google-map-react#use-google-maps-api)
