### ISSUE TITLE
Feature: add MapRestriction prop

### ISSUE THREAD

**Issue by devagja** [google-map-react/google-map-react#1087]
Hi, 
I would like to implement the following feature but I have not seen it in the propTypes, it would be great to be able to use it

https://developers.google.com/maps/documentation/javascript/reference/map#MapRestriction

thx so much!

**Comment by Saintpreston** [comment]
Hello @devagja, I'm just wondering if you ever figured out how to resolve this. I found a solution in vanilla js however not the React Component

**Comment by devagja** [comment]
Cool!
Thank you very much @Saintpreston for your effort, 
for my part I am satisfied and I consider the issue resolved
