### ISSUE TITLE
Warning: NaN is an invalid value for the left css style property. Check the render method of GoogleMapMarkers.

### ISSUE THREAD

**Issue by AJTJ** [google-map-react/google-map-react#1099]
The reason for this error is that the creator of this librarly mixed up `lat` and `lng`, and one of your values is off the map.

**Comment by AJTJ** [comment]
I might have got this wrong

**Comment by callamwilliams** [comment]
It means either a lat or lng value is invalid, double check your data.

If the lat lng is coming from a placesApi object, theres the potential that it's a function, and not a number
