### ISSUE TITLE
Marker moving from its position , on dragging the map

### ISSUE THREAD

**Issue by VenomFate-619** [google-map-react/google-map-react#1108]
**Describe the bug 🐛**
Marker moving from its position, on dragging the map

I had, tried making that marker placed at centre , solution but it doesn't work

**To Reproduce 🔍**

Just do simple, set up with marker

Video Proof:-

https://user-images.githubusercontent.com/67755128/163159334-038f216f-edf1-4a98-a0d5-83bca3caecdd.mp4

Code :- 
```
<GoogleMapReact
      bootstrapURLKeys={{ key: ""  }}
      defaultCenter={location}
      zoom={11}
    >
      <LocationPin text={location.address} />
    </GoogleMapReact>
```
LocationPin 

```
const useStyles = makeStyles(() => ({
  pin: {
    width: "40px",
    height: "40px",
  },
  pinText: {
    fontSize: "1.3rem",
  },
}));

const LocationPin = ({ text }) => {
  const classes = useStyles();

  return (
    <div className={classes.pin}>
      <img alt="pin" src={pin}></img>
    </div>
  );
};
```

Please, help me out it is  my college project , and my deadline is near

**Comment by Rafcin** [comment]
The child of the map needs to have a lat and lon attribute to be placed on the map properly. `<div lat={0} lon={0}/>`

**Comment by VenomFate-619** [comment]
thx for the help.
This need to be mention in the docs

**Comment by adnanhamzeh** [comment]
Facing the same issue, setting the lat and lng don't work.
