### ISSUE TITLE
Next.js: TypeError: Cannot read properties of undefined (reading 'getChildren')

### ISSUE THREAD

**Issue by BranChembah123** [google-map-react/google-map-react#1110]
The default component throws the error before rendering when using it with Next.js.

**Screenshots 🖥**

![Screenshot from 2022-04-22 02-11-41](https://user-images.githubusercontent.com/82242619/164545277-872c2dbf-cbf8-40a1-9254-1c6bb189ad55.png)

**Environment:**

 - OS: Linux
 - Browser Chrome
 - Version 100

**Comment by BranChembah123** [comment]
Turned out, that this is a version compatibility issue with React@18.

**Comment by IMPWNG** [comment]
Got the same issue .. I thing we need to downgrade to React@17 ..

**Comment by Feridun12** [comment]
Please fix this issue I am a junior dev and don't have that many options when it comes to adding maps to the website😅. Did anyone manage to solve this issue yet? If so please get in contact with me please.

**Comment by CrissAlvarezH** [comment]
Try remove StrictMode.

**Comment by Spencer-lolley** [comment]
> Try remove StrictMode. On **next.config.js** for Nextjs
> 
> ```
> const nextConfig = {
>   reactStrictMode: false,
> }
> 
> module.exports = nextConfig
> ```

still doesnt work

**Comment by siawfish** [comment]
Any fixes for this please?

**Comment by ASPeXP** [comment]
Thanks 

> Try remove StrictMode. On **next.config.js** for Nextjs
> 
> ```
> const nextConfig = {
>   reactStrictMode: false,
> }
> 
> module.exports = nextConfig
> ```

Thanks, it's work., You saved my day.

**Comment by joaogarin** [comment]
I think the solution mentioned here is not really a great one long term, `strictMode` can find things that are incompatible with React 18 features in your application, turning it off could have unwanted side effects.

From https://nextjs.org/docs/api-reference/next.config.js/react-strict-mode

> Suggested: We strongly suggest you enable Strict Mode in your Next.js application to better prepare your application for the future of React.

**Comment by skreutzberger** [comment]
Hi, disabling strict mode is not really developer friendly and may leave a Nexjs open to issues. Do you plan to upgrade the library to React 18 and if yes do you already have a potential ETA for it? Thank you 🙏

**Comment by antoniocosentino** [comment]
I saw that version 2.2.0 was just released (https://github.com/google-map-react/google-map-react/pull/1103) so I upgraded it in my project but I still get the same error. Anybody else experiencing the same issue even after upgrading?

So far I solved it by disabling `reactStrictMode` as it was suggested here, but I would like to re-enable it as soon as possible

**Comment by samfromaway** [comment]
I have the same issue
Using:
"google-map-react": "^2.2.0",
"react": "^18.2.0",
"next": "^12.2.0",

Error is: TypeError: Cannot read properties of undefined (reading 'getChildren')

If adding reactStrictMode: false it works but abviously this is not a long-term solution.

**Comment by LucidNinja** [comment]
Same issue. `reactStrictMode` is just a temporary workaround. Please resolve this.

**Comment by Hiti3** [comment]
same here... still nothing?

**Comment by WashingtonLuiz99** [comment]
same here... still nothing? 
help me

**Comment by financialvice** [comment]
pls fix this is so sad 😫

**Comment by Reyesnes** [comment]
Hello dears. Suddenly this problem started appearing for me. Every time I'm just writing the code, the terminal window (Output) opens and shows me this error:

`2022-09-27 15:27:40 Cannot read properties of undefined (reading 'getChildren0')`

Can you help me to solve this please!
I am working with SQL language


![Cannot read properties](https://user-images.githubusercontent.com/71111886/192639786-5872bcc4-76f1-4e96-b792-064d53807c1a.png)

**Comment by ifightcrime** [comment]
I ended up just dumping this library. Turns out it wasn't hard at all just using `@googlemaps/react-wrapper` and `@types/google.maps` (for typescript). Just follow these two guides:

- https://developers.google.com/maps/documentation/javascript/react-map
- https://developers.google.com/maps/documentation/javascript/using-typescript

**Comment by ckt22** [comment]
> I ended up just dumping this library. Turns out it wasn't hard at all just using `@googlemaps/react-wrapper` and `@types/google.maps` (for typescript). Just follow these two guides:
> 
> * https://developers.google.com/maps/documentation/javascript/react-map
> * https://developers.google.com/maps/documentation/javascript/using-typescript
> 
> Your code will end up looking something like this:
> 
> ```ts
> import {Wrapper} from '@googlemaps/react-wrapper';
> 
> const App = () => {
>   return (
>     <Wrapper apiKey={API_KEY}>
>       <Map latitude={0} longitude={0} />
>     </Wrapper>
>   );
> };
> 
> const Map = ({latitude, longitude}: {latitude: number; longitude: number}) => {
>   const ref = React.useRef(null);
>   const [map, setMap] = React.useState<google.maps.Map | null>(null);
> 
>   React.useEffect(() => {
>     if (ref.current && !map) {
>       setMap(
>         new google.maps.Map(ref.current, {
>           zoomControl: true,
>           mapTypeControl: false,
>           streetViewControl: false,
>           center: {
>             lat: latitude ?? 0,
>             lng: longitude ?? 0,
>           },
>           zoom: 11,
>         })
>       );
>     }
>   }, [ref, map, latitude, longitude]);
> 
>   return <div ref={ref} style={{height: '100%', width: '100%'}} />;
> };
> ```

Works for me. Thank you very much!

**Comment by jerachil** [comment]
Finally works for me (Next 13.4.8) by simply adding "use client" the top of the file. Not a really optimal solution though as you have to feed a public google API Key to the client side.

**Comment by azarshab** [comment]
> Try remove StrictMode. On **next.config.js** for Nextjs
> 
> ```
> const nextConfig = {
>   reactStrictMode: false,
> }
> 
> module.exports = nextConfig
> ```

It worked for me. thank you

**Comment by volfcan** [comment]
doing strictmode to false is a terrible idea as it helps you to detect unsafe lifecycles, legacy API usage, and other issues. it's like quick workaround but you'll eventually turn it on in the future.

**Comment by antoniocosentino** [comment]
@volfcan this is not necessary anymore. If you upgrade the library to `2.2.1` everything should work correctly, even with `reactStrictMode` enabled (at least, that's the case in my projects)

**Comment by TsuriH** [comment]
> @volfcan this is not necessary anymore. If you upgrade the library to `2.2.1` everything should work correctly, even with `reactStrictMode` enabled (at least, that's the case in my projects)

Upgrade what? Which library to upgrade, unfortunately I'm facing the same issue here

**Comment by antoniocosentino** [comment]
@TsuriH obviously talking about the `google-map-react` library, since we are in the issues section of that library

**Comment by Unknown47Dream** [comment]
this error still happening in my nextjs app. even with reactStrictMode: false
any solution?

**Comment by antoniocosentino** [comment]
@Unknown47Dream which versions are you running?

Specifically for these packages:

- google-map-react
- react
- next
