### ISSUE TITLE
Uncaught TypeError: Cannot read properties of undefined (reading 'getChildren') | Uncaught TypeError: Cannot read properties of undefined (reading 'dispose')

### ISSUE THREAD

**Issue by arifinsiam** [google-map-react/google-map-react#1128]
**Page going blank**

console error data: 
Uncaught TypeError: Cannot read properties of undefined (reading 'getChildren')  [ google_map_markers.js:100 ]
Uncaught TypeError: Cannot read properties of undefined (reading 'dispose')  [ react_devtools_backend.js:4026  ]

if I remove **React.StrictMode** errors go away, but nothing appears on the browser.

**Expected behavior 💭**

Load the map.

**Environment:**

 - OS: [windows]
 - Browser [chrome]

**Comment by arthwood** [comment]
@arifinsiam Please close this issue. There are already 3 issues open on the same topic on the first page:
https://github.com/google-map-react/google-map-react/issues/1116
https://github.com/google-map-react/google-map-react/issues/1113
https://github.com/google-map-react/google-map-react/issues/1110
