### ISSUE TITLE
My marker not position when zoom in/out ?

### ISSUE THREAD

**Issue by rubysky17** [google-map-react/google-map-react#1130]
hey all, i have a marker on google map and it not position right when i zoom in/out of my map.
this is my component .

import React from 'react'
import { GoogleMap, useJsApiLoader, Marker, InfoWindow } from '@react-google-maps/api'
import InfoObject from './components/InfoObject'

const containerStyle = {
  width: '100%',
  height: '100%',
  position: 'relative',
}

const MarkerList = [
  {
    lat: 10.791741,
    lng: 106.679504,
  },
  {
    lat: 10.798123171492117,
    lng: 106.72133527228104,
  },
  {
    lat: 10.7977651,
    lng: 106.7200726,
  },
]

function Maps() {
  const API_KEY_DEMO = ''
  const [activeMarker, setActiveMarker] = React.useState(null)

  const { isLoaded } = useJsApiLoader({
    id: 'google-map-script',
    googleMapsApiKey: API_KEY_DEMO,
  })

  const handleActiveMarker = (marker) => {
    setActiveMarker(marker)
  }

  return isLoaded ? (
    <GoogleMap
      id="marker-example"
      mapContainerStyle={containerStyle}
      zoom={14}
      center={MarkerList[0]}
    >
      {MarkerList.map((mark, idx) => {
        return (
          <Marker
            icon={{
              url: 'src/assets/icons/icon_google_marker.svg',
            }}
            position={mark}
            onClick={() => handleActiveMarker(idx)}
            key={`marker_${idx}`}
          >
            {activeMarker === idx && (
              <InfoWindow onCloseClick={() => setActiveMarker(null)}>
                <InfoObject />
              </InfoWindow>
            )}
          </Marker>
        )
      })}
    </GoogleMap>
  ) : (
    <></>
  )
}

export default React.memo(Maps)

**Comment by mickey8121** [comment]
You're talking about a different package, dude.

**Comment by rubysky17** [comment]
i using a right package and it not run
