### ISSUE TITLE
Module is not working

### ISSUE THREAD

**Issue by dragon7210** [google-map-react/google-map-react#1155]
**I am using this module but found this error🐛**

![image](https://user-images.githubusercontent.com/109200467/197654760-735171f7-5828-4bdd-9de1-fc23a01fc1a6.png)

**To Reproduce 🔍**

A live example helps a lot! 

**Expected behavior 💭**

**Screenshots 🖥**
![image](https://user-images.githubusercontent.com/109200467/197654778-b9dac72b-78af-4dac-9850-44eb52489079.png)

**Environment:**

 -OS: Win10
 
 "dependencies": {
    "@testing-library/jest-dom": "^5.14.1",
    "@testing-library/react": "^13.0.0",
    "@testing-library/user-event": "^13.2.1",
    "google-map-react": "^2.2.0",
    "react": "^18.2.0",
    "react-dom": "^18.2.0",
    "react-scripts": "5.0.1",
    "web-vitals": "^2.1.0"
  },
 
**Additional context**

**Comment by chyde** [comment]
react 18 isn't supported yet I think. . .
