### ISSUE TITLE
set MapTypeId not working

### ISSUE THREAD

**Issue by centratelemedia** [google-map-react/google-map-react#1162]
change default map type to hybrid not working
```
return {
    zoomControlOptions: {
      position: maps.ControlPosition.TOP_LEFT,
      style: maps.ZoomControlStyle.SMALL
    },
    MapTypeId:"hybrid",
    mapTypeControlOptions: {
      position: maps.ControlPosition.TOP_RIGHT
    },
    mapTypeControl: true
  };
```

**Comment by blinqwebstudio** [comment]
Shouldn't MapTypeId start with a lower case 'm'? I.e. mapTypeId

**Comment by Oracard** [comment]
Came here looking for another issue. @blinqwebstudio is correct, I just tried it and it works with "mapTypeId" in lower case.

**Comment by centratelemedia** [comment]
> Shouldn't MapTypeId start with a lower case 'm'? I.e. mapTypeId

Thanks very much, working now....
