### ISSUE TITLE
GoogleMapReact component suddenly stopped rendering yesterday - no changes made to my codebase for months

### ISSUE THREAD

**Issue by willresen** [google-map-react/google-map-react#1175]
I will close this if I am the only one having this issue, but the GoogleMapReact component has stopped rendering across all of my applications. This callback is never called:

`          onGoogleApiLoaded={({ map }) => {
            setMap(map);
          }}`

Is anyone else seeing this? Did Google drop support for something used by this package? My API keys are valid and work without issue when I use the vanilla JS API. I've made no changes to my codebases for a few months and yet everything suddenly stopped working yesterday. Any ideas?

**Comment by devagja** [comment]
Hi will,
I dont use recently these library but i saw that the demo actually works,

Can you share more details or prepare a demo on any code sandbox?

**Comment by willresen** [comment]
thanks @devagja, i believe i'm narrowing the issue down using the demo as a reference. closing this!
