### ISSUE TITLE
 Google together with Visgl and OpenJS has released the official react components for Google maps

### ISSUE THREAD

**Issue by Git-I985** [google-map-react/google-map-react#1211]
Google team blog post: https://cloud.google.com/blog/products/maps-platform/introducing-react-components-for-the-maps-javascript-api
Library docs: https://visgl.github.io/react-google-maps/docs/get-started

These libraries will be developed and maintained, there is no longer a need for third party libs like this

**Comment by giorgiabosello** [comment]
@Git-I985 this library doesn't support custom Markers. It's pretty basic! That's the reason why third party libraries exist in the first place.

**Comment by giorgiabosello** [comment]
@wangela any type of react component (anything you can do with the [OverlayView](https://developers.google.com/maps/documentation/javascript/customoverlays) class) plus clusters.

**Comment by Git-I985** [comment]
@giorgiabosello i think @wangela is right, and by the way, I also did not understand the problem. 
I think if community need something, it will be added to the Visgl library in the future. 
But I also think that almost official library from trusted developers, approved by the Google team, etc - is better than third-party solutions that may not be supported for years. 
I had a problem with the google-map-react library in integration with next.js some time ago, and I didnt know what to do because I didnt even know other similar solutions, and Visgl came to the rescue for me. Now it works perfect, even better than before
