### ISSUE TITLE
How to determine whether markers are too close to each other?

### ISSUE THREAD

**Issue by sunkaflek** [google-map-react/google-map-react#288]
Hi,

I'm trying to hide (ie. not render in the first place) markers, that are too close to a certain point on the map. Is there anything in the API that would be able to tell me "this point is xx pixels from that point", based on their lat, long and zoomlevel?

Thank you

**Comment by istarkov** [comment]
Math from this comment will help https://github.com/istarkov/google-map-react/issues/62#issuecomment-157181739

**Comment by itsmichaeldiego** [comment]
@sunkaflek Do you still need help with this? Let me know and we can re-open the issue!
