### ISSUE TITLE
Panning horizontally across the earth returns the incorrect longitude 

### ISSUE THREAD

**Issue by LRode** [google-map-react/google-map-react#292]
Hi there,
I don't believe this is a problem with my own code, but please correct me if there is solution for this.

I am using onChange to store the current centre of the map in my state, and noticed a problem when panning across the world. When I pan over the line where the longitude switched from -179 to 179, instead of returning the correct geo point, the map simply keeps adding onto the current longitude. 

For instance if I am scrolling from North America, it goes from -179 to -180 to -190 etc, etc. And the same is true for vice versa (179 to 180 to 190 etc).

This messes up all calculations, because I get the current centre of the map when I want to create a new pin on the map. 

If there is some solution I am unaware of please let me know! 
Thanks!

**Comment by istarkov** [comment]
This is expected behaviour, and needed in some situations, for example to avoid the same coordinates to be twice on the screen.
You can transform all that -190 to 170 by yourself, I see no problem.

**Comment by roura356a** [comment]
As @istarkov states, thats expected behaviour. Weird, but is how it works =)

**Comment by jeanclaudeyalap** [comment]
If some one need it : You can fix it by calling LatLng of google map 

````
/**
 * call LatLng of google map
 * @param  {Object} position
 * @return {Object} position
 */
export function LatLng(position) {
  if (window && window.google && window.google.maps && window.google.maps.LatLng) {
    const newP = new window.google.maps.LatLng(position.lat, position.lng, false);
    return {
      ...position,
      lat: newP.lat(),
      lng: newP.lng()
    };
  }
  return position;
}
```

**Comment by itsmichaeldiego** [comment]
@jeanclaudeyalap You can use google map internals for that, so instead you will have:

```

<GoogleMapReact 
  ...
  onGoogleApiLoaded={({ map, maps }) => apiIsLoaded(map, maps, props.position)}
  yesIWantToUseGoogleMapApiInternals
/>

...

export function LatLng(map, maps, position) {
  if (maps && maps.LatLng) {
    const newP = maps.LatLng(position.lat, position.lng, false);
    return {
      ...position,
      lat: newP.lat(),
      lng: newP.lng()
    };
  }
  return position;
}
```
