### ISSUE TITLE
Able to drag marker outside of Map onto another container

### ISSUE THREAD

**Issue by anilreddykatta** [google-map-react/google-map-react#313]
Can we drag marker to another container outside mapview? I tried using react-dnd, but as we are creating GoogleMapMarkers outside root component causing problems.

**Comment by istarkov** [comment]
Just use `HTML Drag and Drop API` and write your own solution it does not seems hard to do.

**Comment by istarkov** [comment]
The other way hide marker at onMouseDown event and implement your own simple drag over window component without using any api except onMouseMove onMouseUp

**Comment by anilreddykatta** [comment]
@istarkov Thanks for quick update.

**Comment by anilreddykatta** [comment]
@istarkov I loved your optimizations and performance centric design of this awesome library. Curious to know why we need to render GoogleMapMarkers outside GoogleMap component? I also tried to make HTML5 drag and drop to work with this component, I am not getting events into my component onDrag handlers 

`
<div draggable="true" onDrag={(e) => {console.log(e)}} />
`

I am not getting any log statments. Can you help me out?

**Comment by istarkov** [comment]
Markers are drawn inside google map Layers, otherwise you get a synchronisation issues, because google api provides events with significant delays. 
Have you tested does onDrag event works if you set draggable propery on the GoogleMapReact component to false?

**Comment by anilreddykatta** [comment]
@istarkov Yes. I set the draggable to false on GoogleMapReact and set draggable=true on markers to true. Still nothing on onDrag

**Comment by istarkov** [comment]
I have no idea why `onDrag` even does not work for `markers`, it need an investigation process where the problem is, is it a google api stops propagation of some events (and be sure it stops),
or the problem of current case is inside this library.

**Comment by malikasinger1** [comment]
any one have any solution for this issue?
i want to drag marker and get `lat` and `long` of drop

**Comment by istarkov** [comment]
@malikasinger1 You have not the same case as in this issue. Use search your issue was solved in other threads

**Comment by itsmichaeldiego** [comment]
@anilreddykatta Did you find a solution for this or are you still facing the issue? Let me know and we can re-open the issue and work on it! Thanks
