### ISSUE TITLE
Question - reset map center and zoom to the same values

### ISSUE THREAD

**Issue by yoadsn** [google-map-react/google-map-react#341]
I was wondering about how to do this - Say I have location presets A and B (center and zoom for each).
I would like to let the user:
- Click either A or B -> should set the center and zoom as defined
- Pan and zoom on the map freely after clicking any of the above
- Click on A or B to get back to the preset location.

When the user does A -> panning -> A the map would not reset back. Looking at the source the reason is that the nextProps and the Props both have the same center/zoom. The map panning by the user changed the internal center and zoom and not the "React" center and zoom.

I can see the reason not to control the real center/zoom with the React props - that would make navigating the map impossible. But I wonder if there is a way to "reset" the user panning/zooming to what React's props say.

I try to think of a declarative approach to do that. It's possible to have a "key" to a combination of "center/zoom" such that once this key changes - it resets the map to the specified props. So similar to how we have a "key" to a React mounted component there will be a "Preset Key" to a center/zoom" combination...

Any thoughts? Am I missing something big here?

**Comment by istarkov** [comment]
Use controllable way eg onChange event. In such case map works as any other react control

**Comment by istarkov** [comment]
Every example at Docs use controllable way

**Comment by yoadsn** [comment]
Sorry for you time - it's obvious now.

**Comment by andreivictor** [comment]
hello @yoadsn,

I'm having the same issue with the map. 
However, I couldn't understand from the examples what should I do in order to fix this issue.

Can you please give me some hints?

The code I've used is:

` 
    class EventsMapPage extends Component {
 
    //...

    _onChange (properties) {
        console.log( 'map changed, properties: ', properties );
        this.props.onCenterChange(properties.center);
        this.props.onZoomChange(properties.zoom);
    }

    render() {
       
        return (
             <GoogleMap
                    center={this.props.center}
                    zoom={this.props.zoom}
                    ref="googleMapReact"
                    onChange={this._onChange.bind(this)}
                >
                </GoogleMap>
        );

 
    }

   }
`
Thanks!

**Comment by williamli** [comment]
I am stuck at this part as well.
It seems onChange expect there are props on the current object for 
this.props.onZoomChange
this.props.onCenterChange


it should be related to
static propTypes = {
    center: PropTypes.array, // @controllable
    zoom: PropTypes.number, // @controllable
    hoverKey: PropTypes.string, // @controllable
    clickKey: PropTypes.string, // @controllable
    onCenterChange: PropTypes.func, // @controllable generated fn
    onZoomChange: PropTypes.func, // @controllable generated fn
    onHoverKeyChange: PropTypes.func, // @controllable generated fn

    greatPlaces: PropTypes.array
  };

and some @controllable function... I am trying to understand where these props come from right now.

**Comment by williamli** [comment]
got it now.

@andreivictor  it seems `react-controllables` is used to wrap React components and provide user controls to it. After this, feature like `this.props.onCenterChange` will become available to the React component...

**Comment by williamli** [comment]
got it.

@andreivictor  you need to know `react-controllables` that will wrap your elements with an extra layer and provide controllable functions as props.

```
this.props.onZoomChange
this.props.onZoomChange
```

are all functions created by `react-controllables`.

https://github.com/matthewwithanm/react-controllables

**Comment by andreivictor** [comment]
Thanks @williamli for your response. 
I've understood the `react-controllable` plugin and the functions created by it, but,  I'm still not sure how to resolve this issue. 

I'm including the component from the code [above](https://github.com/istarkov/google-map-react/issues/341#issuecomment-321203458) in the main component of the app like this:

     <GoogleMap
                 center={this.state.center}
                  zoom={this.state.zoom}
      />


Should I define the props `onZoomChange` and `onCenterChange` here and bind some functions that will update the state of the main component? 

     <GoogleMap
                 center={this.state.center}
                  zoom={this.state.zoom}
                 onZoomChange={this.updateMapZoom.bind(this)}
                 onCenterChange={this.updateMapCenter.bind(this)}
      />

     updateMapCenter(coords)  {
        this.setState({
            center: coords
        });
    } 


Thanks!

**Comment by itsmichaeldiego** [comment]
It seems that you guys found the solution, let me know if you need further help. Thanks!
