### ISSUE TITLE
Sprites not loaded correctly on zoom in / out buttons

### ISSUE THREAD

**Issue by mfrachet** [google-map-react/google-map-react#345]
I'm facing a strange behaviour while using the map. I have the following map :

```javascript
<GoogleMapReact
    bootstrapURLKeys={{key: Constants.GOOGLE_API_KEY}}
    center={Constants.GOOGLE_MAP_CENTER}
    onChildClick={this.handleClickOpen}
    zoom={1}
    >
/* ... */
</GoogleMapReact>
```

And I m having the following zoom in / out buttons :

<img width="181" alt="capture d ecran 2017-03-20 a 16 12 00" src="https://cloud.githubusercontent.com/assets/3874873/24106384/fed4f2c0-0d87-11e7-8c3d-9670f6a59f8e.png">

Do you have any idea ?

**Comment by istarkov** [comment]
jsbin?

**Comment by itsmichaeldiego** [comment]
@mfrachet Let me know if you still need help. I am closing the issue as for now, it is not reproducible on my end.
