### ISSUE TITLE
Adding circles on the map dynamically

### ISSUE THREAD

**Issue by xkd** [google-map-react/google-map-react#349]
Hello! IIUC, the only way to add circles is using onGoogleApiLoaded callback, which is being called only once. I've tried adding a circle as div, but its radius wont be bound to map scale. Is there another way to add a circle from the API?

Thanks.

**Comment by istarkov** [comment]
Hi, there is undocumented function exists in this library to calculate size of your marker `div`
[meters2ScreenPixels](https://github.com/istarkov/google-map-react/blob/7a9a8d3fb7f3d1bf4409bddd326f2cc0545857cc/src/utils/utils.js#L165-L174)

```javascript
import { meters2ScreenPixels } from 'google-map-react/utils';
const { w, h } = meters2ScreenPixels(sizeInMeters, { lat, lng } /* marker coords*/, zoom /* map zoom*/);
```

it returns `horizontal - w` and `vertical - h` sizes for given meters, point and zoom.
Having mercator map projection and that our world is not plane for some places w and h will be different, for most places almost the same.

**Comment by istarkov** [comment]
Now documented https://github.com/istarkov/google-map-react/blob/master/DOC.md#helper-utilities
¯\_(ツ)_/¯

**Comment by xkd** [comment]
It works for me, thanks.

**Comment by anderswag** [comment]
I seem to be getting NaN for the "w" and "h" values, is this function still working? Thanks

**Comment by istarkov** [comment]
Must work, check your args

**Comment by itsmichaeldiego** [comment]
It seems that the solution has been provided. Let me know if otherwise.
