### ISSUE TITLE
DrawingManager and editable options

### ISSUE THREAD

**Issue by mcjanowski** [google-map-react/google-map-react#351]
Hello,

Is it possible to set marker option 'editable' for rendered component inside <GoogleMapReact /> ?

google api allow to do something like 
`marker.setOptions({editable: true})`
after that you can change size of marker and move it to another place.
example: https://developers.google.com/maps/documentation/javascript/examples/drawing-tools

...or instead of creating components should I use normal google api ?
`new google.maps.Circle({...options})`

```
const MarkerCircle = ({ circle, zoom }) => {
  const { w, h } = meters2ScreenPixels(circle.radius * 2, { lat: circle.lat, lng: circle.lng }, zoom);
  return (
    <div className="marker" style={{ width: w, height: h, marginLeft: -w / 2, marginTop: -h / 2 }}>
      <div className="marker-inner"></div>
    </div>
  );
};

class SimpleMap extends Component {
 ....
 return (
 <GoogleMap 
  {this.state.markers.map(marker => <MarkerCircle key={marker.id} circle={marker} zoom={this.state.zoom}
  lat={marker.lat} lng={marker.lng} />)}
 </GoogleMap>
 )
}
```
I've assigned drawing manager but problem is with editable option of marker

**Comment by itsmichaeldiego** [comment]
@mcjanowski Did you figure out a solution to your problem?

**Comment by mcjanowski** [comment]
Yes, I've used normal google API.

**Comment by itsmichaeldiego** [comment]
Thanks @mcjanowski! You can always use `onGoogleMapAPILoaded` method.
