### ISSUE TITLE
Having hard time testing.

### ISSUE THREAD

**Issue by gviligvili** [google-map-react/google-map-react#359]
This i the situation: 
Just like air bnb [in this link](https://www.airbnb.com/s/Los-Angeles--CA--United-States/homes?af=43720035&atlastest5=true&c=A_TC%3Dq5wrqzxq9w%26G_MT%3De%26G_CR%3D77952641063%26G_N%3Dg%26G_K%3Dair.bnb%26G_P%3D%26G_D%3Dc&checkin=2017-05-26&checkout=2017-05-31&gclid=CjwKEAjw2qzHBRChloWxgoXDpyASJAB01Io0HH_DNQ4aiYPOe4OlzOcqrkQNWlagW9KZP6uOhv619xoCrqDw_wcB&place_id=ChIJE9on3F3HwoAR9AhGJW_fL-I)

A user can hover an item and his price tag in the map will change his color.
It's working well but I can't seem to test it. I can't find the item by key or id because it's isn't in the component.

I found the google map component with all the sub components by myself in the html as a sibling to my root component.   - which explains why I cant find it by key in my component.

How can I test this behavior?
Thank you very much !

**Comment by istarkov** [comment]
I have the same question, anyone? :-)

**Comment by zacck** [comment]
In my opinion, you would need to test this as two parts.
Something like having a state item that changes when an item is hovered over. 
test for this perhaps using the focus event?

The test that maps marker reacts to that change in state? Check the rendering of the marker to check that the color or shape changed?

**Comment by itsmichaeldiego** [comment]
@gviligvili Are you still facing this issue? We could add some option to pass some id or special class name, let me know and we will re-open the issue!
