### ISSUE TITLE
MinZoom override functionality breaks when this.props.options is a function

### ISSUE THREAD

**Issue by jaimieli** [google-map-react/google-map-react#366]
On [L678](https://github.com/istarkov/google-map-react/blob/master/src/google_map.js#L678) and L679, `this.props.options` is assumed to be an object. If `this.props.options` is a function, this `minZoomOverride` functionality breaks.

**Comment by istarkov** [comment]
Thank you, I'm waiting for Pull Request ;-)

**Comment by itsmichaeldiego** [comment]
@jaimieli Due to changes, your comment pointing at the lines got outdated @jaimieli, please let me know if this is still a problem for you and we'll re-open the issue!
