### ISSUE TITLE
how to draw and snip only to road ( direction )

### ISSUE THREAD

**Issue by xshadowlegendx** [google-map-react/google-map-react#376]
MeteorJS ( 1.4.4 ) + ReactJS

I'm doing a project of tracking traffic jam, I am able to draw polygon inside the map, but it is not convenient to draw it to match the road line ( direction ) easily, so i want to ask if there is way to be able to capture or snip to the road only, and be able to slide or edit the snipped line to tell how far it is the traffic jam is there.

Thanks for help.

PS: Very awesome package.

**Comment by itsmichaeldiego** [comment]
@xshadowlegendx Thanks for the good comments! Are you still facing this issue? Could you provide a live example? Thanks in advance!

**Comment by itsmichaeldiego** [comment]
@xshadowlegendx As no answer was provided, I am closing the issue, but please feel free to re-open it if you are still facing it! Thanks.
