### ISSUE TITLE
How to show place details on the map?

### ISSUE THREAD

**Issue by sanjevShakya** [google-map-react/google-map-react#389]
![placedetails](https://cloud.githubusercontent.com/assets/9900412/26364208/406abe4c-4003-11e7-92fc-309bd70cfcc1.png)

Small details of restaurants, health centers, etcs

**Comment by istarkov** [comment]
please read google docs, there are few ways in this library to extend gmap api like options or onGoogleApiLoaded callback.

**Comment by sanjevShakya** [comment]
Okay, will have a look into it thank you

**Comment by itsmichaeldiego** [comment]
@sanjevShakya Let me know if you still need help with this!
