### ISSUE TITLE
Using polygons on map

### ISSUE THREAD

**Issue by sepehraliakbary** [google-map-react/google-map-react#402]
Hi
I want to use polygons on react map. I read issue#62 but I can't understand what that mean.
what is "North West corner of SVG" exactly?

thank you

**Comment by istarkov** [comment]
Ideas?

**Comment by sepehraliakbary** [comment]
I want pass lat and lng to a function and it gives me a point to use a svg on map like this:

<svg height="210" width="500">
  <polygon points="200,10 250,190 160,210" style="fill:lime;stroke:purple;stroke-width:1" />
</svg>

**Comment by istarkov** [comment]
Having all the function to transform coordinates you can do it yourself.
There were other issues with similar questions and transforms, also some transforms you can get here https://github.com/istarkov/google-map-thousands-markers as drawing on the canvas is somehow similar.

**Comment by itsmichaeldiego** [comment]
@sepehraliakbary Do you still need help with this matter? Let me know and we can re-open the issue.

**Comment by itsmichaeldiego** [comment]
@cparello That is because you are accessing the bounds when the api is not loaded, to achieve that you need to do something like:

```
const apiIsLoaded = (map, maps) => {
  // do your thing with either map or maps 
};

const GoogleMap = props => (
  <GoogleMapReact
    zoom={props.zoom}
    center={props.center}
    bootstrapURLKeys={{
      key: [MAP_KEY],
    }}
    yesIWantToUseGoogleMapApiInternals
    onGoogleApiLoaded={({ map, maps }) => apiIsLoaded(map, maps)}
  >
    {props.children}
  </GoogleMapReact>
);
```
