### ISSUE TITLE
Using PanTo or another method for smooth panning?

### ISSUE THREAD

**Issue by maxwellbenton** [google-map-react/google-map-react#407]
Hi,

Is there anyway to access or replicate the behavior of panTo() in the Google API?  I am trying to set the map to automatically move slowly but smoothly in a specific direction.  Right now I have the center being reset by props on render, which pans but is resulting in choppy movement:

 <GoogleMap
        center={[this.props.panY,this.props.panX]}
        ...

I've been looking through the examples and previous issues and haven't found anything similar.  Thank you for maintaining this and continuing to help out with issues!

**Comment by Delindel** [comment]
Man, did you ever found out how to do this?

**Comment by tquiroga** [comment]
Looking to that too

**Comment by itsmichaeldiego** [comment]
@maxwellbenton @Delindel @tquiroga What about using the google maps api? Something like:

```

const apiIsLoaded = (map, maps, lat, lng) => {
  if (map) {
    const latLng = maps.LatLng(lat, lng); // Makes a latlng
    map.panTo(latLng);
  }
};

const GoogleMap = props => (
  <GoogleMapReact
    defaultCenter={props.defaultCenter} // Set a default center in case there's an error.
    bootstrapURLKeys={{
      key: [YOUR_KEY]
      language: 'en',
    }}
    yesIWantToUseGoogleMapApiInternals
    onGoogleApiLoaded={({ map, maps }) => apiIsLoaded(map, maps, props.lat, props.lng)}
  >
    {props.children}
  </GoogleMapReact>
);
```

**Comment by tquiroga** [comment]
@itsmichaeldiego Yes sounds like a good solution, I also saw some folks using `ref` to access the map api and use `panTo` from there.

**Comment by itsmichaeldiego** [comment]
@tquiroga Let me know if any of those solutions work for you, I am looking forward to close this issue. CC @maxwellbenton @Delindel

**Comment by jamiegau** [comment]
@tquiroga can you explain what you mean by using `ref`?

**Comment by itsmichaeldiego** [comment]
@jamiegau @tquiroga We don't recommend using `ref`, that is why we have the `onGoogleApiLoaded` function attribute. As `onGoogleApiLoaded` is called when the api is actually loaded, by using `ref` you need to check if its defined or not. 

BTW: I am closing this issue as it seems to be solved.
