### ISSUE TITLE
Server side rendering markup

### ISSUE THREAD

**Issue by JavoByte** [google-map-react/google-map-react#409]
Thanks for this awesome library. It's very useful. However, I detected a little bit problem while rendering on the server side. 

I noticed there is a `<div>` containing my marker with a calculated `top`. This `top` style do not match in the server generated content and the client side. It differs by a tiny amount but if differs, so the markup is not valid generating this error:

https://www.dropbox.com/s/msiafi5mmr7qi6j/Captura%20de%20pantalla%202017-07-04%2022.47.24.png?dl=0

**Comment by malaman** [comment]
@JavoByte we have same issue.
As a workaround we use small wrapper, which renders GoogleMapReact only after mounting on client side.

**Comment by valorize** [comment]
@malaman could you share how you wrote the wrapper?

**Comment by malaman** [comment]
@valorize in simplest case you can use something like
```TypeScript
import GoogleMapReact from 'google-map-react';

export class GoogleMap extends React.Component<IProps, IState> {
    constructor(props) {
        super(props);
        this.state = {
            mounted: false
        };
    }

    componentDidMount() {
        this.setState({mounted: true});
    }

    render() {
        return (
            <div>
                {this.state.mounted > 0 &&
                    <GoogleMapReact
                        bootstrapURLKeys={{key: 'XXXX'}}
                        zoom={this.props.zoom}
                        options={this.props.options}
                        center={this.props.center}                        
                    >
                        {this.props.markers}
                    </GoogleMapReact>
                }
            </div>
        );
    }
}

```

**Comment by itsmichaeldiego** [comment]
@JavoByte @malaman @valorize Guys, it seems that you found the solution to your problem. Let me know if any of you need further help.
