### ISSUE TITLE
Show info window asynchoronous

### ISSUE THREAD

**Issue by sepehr1313** [google-map-react/google-map-react#422]
Hello,
I want to show an info window that show data from an API. for example when I click on a marker it will send a request to API and get data and then show that data on the map as info window.
How can I do for this feature?

thanks

**Comment by istarkov** [comment]
As like as in examples. Your marker is a react component, render info window as a child of marker using React.

**Comment by Sepehr-Aliakbary70** [comment]
I do this, but before data fetching ,when the child component has no value (before clicking on marker) google-map-react does not render marker itself! I don't know why

**Comment by istarkov** [comment]
How you click on marker if it is not rendered?

**Comment by Sepehr-Aliakbary70** [comment]
when I use child component the markers not rendered. but I can fetch API on marker click.
for example :
```
                        entityList.RentableEstateList.map((item, index) => {
                            markers.push(
                                <div
                                    id={`${item.IdEstateFile}-key`}
                                    key={item.IdEstateFile}
                                    lat={item.Coordinates.Latitude}
                                    lng={item.Coordinates.Longitude}
                                    className="pin-container"
                                >
                                    <Marker
                                        cssClass={'orange'}
                                    />
                                    <div
                                        className={`Info-window list-style ${this.props.hoverKey == item.IdEstateFile ? 'show' : 'hide'}`}>
                                        {this.state.mapEntityDetail}
                                    </div>
                                </div>
                            );
                        });
```
and my child click function:
```
    onChildClick(key, childProps) { // I fetch data and set my redux store
        this.props.onHoverKeyChange(key);
        if (typeof this.props.onMapChildClick != 'undefined') {
            this.props.onMapChildClick(key);
            this.setState({
                mapEntityDetail: this.props.mapEntityDetail
            });
            this.showPopUp(key);
        }
    }
```
In this case markers not rendered. But when I delete {this.state.mapEntityDetail} section, They will be rendered.

**Comment by istarkov** [comment]
`markers.push`  does not change the reference to markers array, so for internal optimizations `markers` array has not changed. 

Also please provide an example using https://codesandbox.io or jsbin, I don't understand what your code pieces above is about.

**Comment by Sepehr-Aliakbary70** [comment]
What do you do if you want to do this functionality?
(fetch from API and show that data on an info window)
