### ISSUE TITLE
MapType and Custom Drawing Layer

### ISSUE THREAD

**Issue by colafati** [google-map-react/google-map-react#432]
Hi, 

I'm having a hard time trying to customize the Map Type button; I just can't find any property on this module that changes the MapType. I only see one that triggers if the map type was changed.

Another important feature that I can't integrate is the custom draw function; I want to provide the user a free hand tool where he can select the area to search on the map. I also want a custom button to do it.

I appreciate any help you can provide.

Thanks

**Comment by colafati** [comment]
I have success with the mapType button with this solution:
https://github.com/istarkov/google-map-react/issues/102#issuecomment-193398765

Still having problems with the Custom Drawing layer.

**Comment by itsmichaeldiego** [comment]
Please if you're still facing this issue open a new one with a live code example, thanks!
