### ISSUE TITLE
Implement clustering

### ISSUE THREAD

**Issue by maksimgm** [google-map-react/google-map-react#473]
The documentation does not state how to implement clustering support. The only thing the documentation provides regarding clustering, is a UI with an example. Furthermore, there is no example in the source code of how to wire up clustering either.
@istarkov any idea?

**Comment by edward-hong** [comment]
I agree. The example is too opinionated. Why use kotatsu and recompose when you can just use webpack instead of kotatsu and not use recompose altogether? It makes understanding the example more difficult.

The whole point of the example is so other people can do clustering as well right? I just don't think using esoteric packages was a good idea.

**Comment by digitalh2o2** [comment]
I have yet to implement clustering but @Tim152 built and shared his clustering example without recompose
https://github.com/Tim152/clustering-google-map-react

**Comment by itsmichaeldiego** [comment]
@maksimgm Sorry for my late response, @istarkov created an example of this here: https://github.com/istarkov/google-map-clustering-example

You can also see the example live in here http://istarkov.github.io/google-map-clustering-example/

Let me know if that helps you out

**Comment by ChaitanyaKrishnaPappala** [comment]
I tried to directly load/add the google MarkerCluster script to my DOM during componentDidMount and it worked for me perfectly.

This is my working code:

import React, {Component} from 'react'
import GoogleMapReact from 'google-map-react'

export default class GoogleMapContainer extends Component {

  componentDidMount () {
    const script = document.createElement('script')
    script.src = 'https://developers.google.com/maps/documentation/javascript/examples/markerclusterer/markerclusterer.js'
    script.async = true
    document.body.appendChild(script)
  }

  setGoogleMapRef (map, maps) {
    this.googleMapRef = map
    this.googleRef = maps
   let locations = [
        {lat: -31.563910, lng: 147.154312},
        {lat: -33.718234, lng: 150.363181},
        {lat: -33.727111, lng: 150.371124}]
    let markers = locations && locations.map((location) => {
      return new this.googleRef.Marker({position: location.position})
    })
    let markerCluster = new MarkerClusterer(map, markers, {
      imagePath: 'https://googlemaps.github.io/js-marker-clusterer/images/m',
      gridSize: 10,
      minimumClusterSize: 2
    })
  }

  static defaultProps = {
    center: {
      lat: 59.95,
      lng: 30.33
    },
    zoom: 11
  }

  render () {
    return (
        <GoogleMapReact
          bootstrapURLKeys={{key: GOOGLE_MAPS_API_KEY}}
          yesIWantToUseGoogleMapApiInternals
          onGoogleApiLoaded={({map, maps}) => this.setGoogleMapRef(map, maps)}
          defaultCenter={{lat: -31.563910, lng: 147.154312}}
          defaultZoom={15}
          options={{streetViewControl: true}}
        >
        </GoogleMapReact>
    )
  }
}

**Comment by ChaitanyaKrishnaPappala** [comment]
> The documentation does not state how to implement clustering support. The only thing the documentation provides regarding clustering, is a UI with an example. Furthermore, there is no example in the source code of how to wire up clustering either.
> @istarkov any idea?

This example will work independent of any other packages:

```
import React, {Component} from 'react'
import GoogleMapReact from 'google-map-react'

export default class GoogleMapContainer extends Component {

  componentDidMount () {
    const script = document.createElement('script')
    script.src = 'https://developers.google.com/maps/documentation/javascript/examples/markerclusterer/markerclusterer.js'
    script.async = true
    document.body.appendChild(script)
  }

  setGoogleMapRef (map, maps) {
    this.googleMapRef = map
    this.googleRef = maps
   let locations = [
        {lat: -31.563910, lng: 147.154312},
        {lat: -33.718234, lng: 150.363181},
        {lat: -33.727111, lng: 150.371124}]
    let markers = locations && locations.map((location) => {
      return new this.googleRef.Marker({position: location.position})
    })
    let markerCluster = new MarkerClusterer(map, markers, {
      imagePath: 'https://googlemaps.github.io/js-marker-clusterer/images/m',
      gridSize: 10,
      minimumClusterSize: 2
    })
  }

  static defaultProps = {
    center: {
      lat: 59.95,
      lng: 30.33
    },
    zoom: 11
  }

  render () {
    return (
        <GoogleMapReact
          bootstrapURLKeys={{key: GOOGLE_MAPS_API_KEY}}
          yesIWantToUseGoogleMapApiInternals
          onGoogleApiLoaded={({map, maps}) => this.setGoogleMapRef(map, maps)}
          defaultCenter={{lat: -31.563910, lng: 147.154312}}
          defaultZoom={15}
          options={{streetViewControl: true}}
        >
        </GoogleMapReact>
    )
  }
}

```

**Comment by lunvjp** [comment]
![image](https://user-images.githubusercontent.com/23715737/61148753-b155f500-a509-11e9-953c-232f8088cf2c.png)
---
Hey @ChaitanyaKrishnaPappala I've just imported your way to work on the same thing but it doesn't work with me. Still not sure why for now.

**Comment by ChaitanyaKrishnaPappala** [comment]
Google map has changed a few things, I updated my code accordingly, as a separate npm package is added for marker clusters. 
Below is the updated code @lunvjp @ankitasingh170190 

import React, {Component} from 'react'
import GoogleMapReact from 'google-map-react'
import MarkerClusterer from '@google/markerclusterer'

export default class GoogleMapContainer extends Component {
  componentDidMount () {
    const script = document.createElement('script')
    script.src = 'https://developers.google.com/maps/documentation/javascript/examples/markerclusterer/markerclusterer.js'
    script.async = true
    document.body.appendChild(script)
  }

  setGoogleMapRef (map, maps) {
    this.googleMapRef = map
    this.googleRef = maps
    let locations = [
      {lat: -31.563910, lng: 147.154312},
      {lat: -33.718234, lng: 150.363181},
      {lat: -33.727111, lng: 150.371124}]
    let markers = locations && locations.map((location) => {
      return new this.googleRef.Marker({position: location})
    })
    let markerCluster = new MarkerClusterer(map, markers, {
      imagePath: 'https://developers.google.com/maps/documentation/javascript/examples/markerclusterer/m',
      gridSize: 10,
      minimumClusterSize: 2
    })
  }

  static defaultProps = {
    center: {
      lat: 59.95,
      lng: 30.33
    },
    zoom: 11
  }

  render () {
    return (
      <GoogleMapReact
        bootstrapURLKeys={{key: `PLACE_HOLDER`}}
        yesIWantToUseGoogleMapApiInternals
        onGoogleApiLoaded={({map, maps}) => this.setGoogleMapRef(map, maps)}
        defaultCenter={{lat: -31.563910, lng: 147.154312}}
        defaultZoom={15}
        options={{streetViewControl: true}}
      />
    )
  }
}

**Comment by SimantoR** [comment]
I say we add that to documentation for future. I talked to the owner of the repo and I should be joining as a contributor. I'll get a list of things done and this should be top of it along with some more PRs to go along with it.

**Comment by chawes13** [comment]
@ChaitanyaKrishnaPappala Any luck implementing the `MarkerClusterer` when rendering with custom markers? Instead of creating new markers in `setGoogleMapRef` I'd like to reference the **existing markers** created during the rendering of `<GoogleMapReact />`s children. So far I have not been able to figure out how to access them, however.

**Comment by itsmichaeldiego** [comment]
@SimantoR If you want to be a contributor you can just send me an email / message. We co-own the repo with @istarkov but he hasn't been active for a while.

**Comment by ankitasingh170190** [comment]
I implemented it with Typescript and was able to get desired results. Thank
you

**Comment by maximilianoforlenza** [comment]
@chawes13 have you fixed that problem? Because I have the same issue.

**Comment by maximilianoforlenza** [comment]
@chawes13 I don't know if it is the best solution but is working for me. https://gist.github.com/maximilianoforlenza/61a705609bb6e9351ede3b68d6486390

**Comment by PlanB007** [comment]
Any update on this?

**Comment by mengqing** [comment]
Is there anyway to render custom marker components as well as using clusters. All the examples in this issue are for rendering marker icons and clusters, but I want to be able to render custom marker component for both markers and clusters

**Comment by spyshower** [comment]
@mengqing yea wanted to ask the same thing..
