### ISSUE TITLE
Cannot read property 'addEventListener' of null when render testing component

### ISSUE THREAD

**Issue by drdpedroso** [google-map-react/google-map-react#474]
I'm having some trouble render testing one of my components because of the following error:
`Cannot read property 'addEventListener' of null`

Happening at `at GoogleMap.componentDidMount (node_modules/google-map-react/lib/google_map.js:791:57)`

I'm not sure about how to test my component with google-map-react. My test file is really simple:

```
import React from 'react'
import renderer from 'react-test-renderer'

describe('<PartnerLocalConfirmation />', () => {
  it('should render correctly', () => {
    const component = renderer.create(
        <MockedProvider>
            <PartnerLocalConfirmation {...props}/>
        </MockedProvider>)
    expect(component).toMatchSnapshot()
  })
})
```

Can someone help me with that?

**Comment by mistaguy** [comment]
Your mock must be wrong and most likely it is not returning google maps object. See some tests i have worked on from here.
[Google maps react test](https://github.com/FlockOfBirds/google-maps/blob/master/src/components/__tests__/Map.spec.tshttps://github.com/FlockOfBirds/google-maps/blob/master/src/components/__tests__/Map.spec.ts)

You can also see how i use the library

**Comment by itsmichaeldiego** [comment]
@drdpedroso Let me know if you need further help, closing issue.
