### ISSUE TITLE
Is google auto Calculating cluster support ?

### ISSUE THREAD

**Issue by wahengchang** [google-map-react/google-map-react#478]
I have dig into the code of this example, and realized that number of cluster of markers is calculated by yourself but not using the cluster API provided by Google. Can you share some detail about this?

https://developers.google.com/maps/documentation/javascript/marker-clustering

**Comment by itsmichaeldiego** [comment]
@tbaustin So, google clustering works with coordinates, but we are working on positioning the markers in the dom depending on their coordinates.
