### ISSUE TITLE
Draggable & editable polygons (and other shapes), and drawing tools

### ISSUE THREAD

**Issue by palashkaria** [google-map-react/google-map-react#492]
I was trying to add some draggable/editable polygons to the map, and also using drawing tools, but I noticed some weird behaviour when setting polygon options.

This is a demo with draggable polygons from [google's docs](https://developers.google.com/maps/documentation/javascript/examples/polygon-draggable)

(I have made them editable too, and added another polygon):
https://codesandbox.io/s/k388mmoo4v
Here, none of the polygons are draggable/editable, as they should be.

I also tried adding them via drawing tools, here's the demo:
EDIT: fixed demo
https://codesandbox.io/s/91vqqnyo1p

Here, if you create a polygon/rectangle/circle, the first 1st instance you create will not be editable/or draggable (the middle handles wont work), the 2nd instance is editable, but not draggable. The 3rd instance works fine.

I'm not sure what might be causing this behaviour, and I have tried things like resetting the 'draggable' option on polygon on click, but nothing seems to work. The only thing that got it working (while testing) was removing random things (like the edit handles on the polygon) from DOM and adding them back (not feasible of course).

Any ideas on what might this issue be, or any potential fix?

**Comment by sayaf007** [comment]
thank you so much palashkaria

**Comment by itsmichaeldiego** [comment]
@palashkaria Thanks! It seems that many people is interested in this so we should pay attention to this. PRS are welcome therefore I would love to help any of you to make a PR, let me know.

**Comment by cybercoder** [comment]
@palashkaria Thanks for awesome codes. And how can access to data?
