### ISSUE TITLE
Event onChildClick does not work in fullscreen mode

### ISSUE THREAD

**Issue by ibtsoft** [google-map-react/google-map-react#539]
I am using onChildClick to handle click on a marker to show additional information:
```
<GoogleMapReact
   onChildClick={this._onChildClick}
>
   {this.state.items && this.state.items.map((row) => (
         <Mark
                  key={row.id}
                  lat={row.latitude}
...
````

Everything works fine until I switch to the fullscreen mode. I tried to put a breakpoint in the _onChildClick but looks like it is never fired. Once I switch fullscreen mode off everything works fine again.

**Comment by itsmichaeldiego** [comment]
@ibtsoft Please provide a codePen or any live example.

**Comment by ibtsoft** [comment]
I think I was able to reproduce it on the example here: http://istarkov.github.io/google-map-react/map/events/

The onChildClick behaviour is different when map is in fullscreen mode.

I am using Chrome Version 64.0.3282.186 (Official Build) (64-bit) on Mac OS X 10.11.6

**Comment by itsmichaeldiego** [comment]
@ibtsoft There is an issue with fullscreen mode, you're right, but it is not the `onChildClick`. Actually, I think its the position of the marker that is changed. We weren't supporting full-screen mode until version `0.26.0`. So this problem was introduced in  #452.

**Comment by itsmichaeldiego** [comment]
@ibtsoft Please let me know if you need further help.

**Comment by itsmichaeldiego** [comment]
@ibtsoft Closing issue, let me know if you need any extra help.
