### ISSUE TITLE
Low precision latitude in onClick event

### ISSUE THREAD

**Issue by TannerPerrien** [google-map-react/google-map-react#550]
The latitude values coming back in the onClick event seem to be off by a small margin of error.

I plotted a polyline using the gmaps api (similar to https://github.com/istarkov/google-map-react/issues/149). The longitudinal accuracy seems fine, but the latitude is off by a dynamic amount. The `lat` accuracy improves as the clicks move closer to the vertical center of the screen. As the clicks move toward the upper or lower bounds of the map, the `lat` is off by `0.000004` (give or take).

Is it possible that a bug exists when [unprojecting](https://github.com/istarkov/google-map-react/blob/master/src/utils/geo.js#L35) the cursor's position? Could the `display` (absolute/relative) of parent `<div>`s affect this projection?

**Comment by TannerPerrien** [comment]
It turns out this was an issue with the map being "tilted" and throwing off the projection. It works as expected when the tilt is 0.

```
function createMapOptions(maps) {
  return {
    mapTypeId: 'satellite',
    tilt: 0
  };
};
```

**Comment by itsmichaeldiego** [comment]
@TannerPerrien That is a great observation, I am glad you found the solution. Thanks for your contribution!
