### ISSUE TITLE
Heatmap generates red square 

### ISSUE THREAD

**Issue by FrenchBully** [google-map-react/google-map-react#551]
Something I've come across is when there is one data point 
```positions: [{lat: 34.022306, lng: -118.294556}]```
a large red square is generated and not a dot for heatmap.
![screen shot 2018-04-03 at 6 35 35 pm](https://user-images.githubusercontent.com/5194698/38283968-d586ff6a-376d-11e8-8a51-8b0f5fd464fd.png)

**Comment by FrenchBully** [comment]
I guess doesn't really make sense to have a heatmap in the case there's only one data point.

**Comment by itsmichaeldiego** [comment]
I agree, let me know if you face any other issue @FrenchBully
