### ISSUE TITLE
Fix zoom animation with Google Maps API v3.32

### ISSUE THREAD

**Issue by stephenfarrar** [google-map-react/google-map-react#552]
This is a new issue to discuss a long-term solution to the zoom animation problem that started with v3.32 of the Google Maps API. See also #490 #510 #530 

I've begun work in https://github.com/stephenfarrar/google-map-react/tree/zoom-animation
Someone could start a branch here, and I'll create a pull request.

So far, here are some of the issues I'm confused about:

* The markers are children of `overlay.div` in `src/google_map.js` . That div used to be positioned & sized so that it was the size of the map. I don't think that's necessary, and I've removed it, but perhaps it's causing problems elsewhere.

* I'm not totally sure what coordinate system is used in the geo service `project()` and `unproject()` when `projectFromLeftTop` is false. Did it mean 'relative to the map center'? I've made it mean 'relative to the MapPanes'. This makes sense for markers, but I'm not sure that it makes sense elsewhere.

* My branch has problems with markers disappearing and reappearing. Perhaps this indicates some problems with keeping track of the current map bounds.

**Comment by stephenfarrar** [comment]
@itsmichaeldiego please take a look... and maybe you have answers to some of my confused questions :-)

**Comment by istarkov** [comment]
I have answers :-)
To solve the problem all you need is to check modern google layer examples - and just compare why layers in google map examples zooms correctly and here is not.
Now about coordinate system from left top and center - when you rendering on server you have 0 information about client screen size so you cant use usual left top for screen coordinates (imagine u need to place marker at screen center) but you can place div at center using css and use coordinate system from center. But on client to have coirdinate system compatible with google you can use left too coorfinates. So there are 2 coords system - for SSR and for browser.

**Comment by nickpolet** [comment]
@stephenfarrar Thanks for looking into this. The zooming icons bug has been driving me mad for a while and we've switched out this component for an alternative for the time being. Such an annoying bug for such a great component.

Hopefully a good solution can be found soon. The smooth zoom on the newer libraries is really quite nice, and stepping back into the old world feels like a massive step backwards.

**Comment by jsprow** [comment]
@nickpolet 
I can confirm that I'm still getting the issue in v0.34. I'm working on a mac with Chrome and Firefox. Both are having the issue. Here's what I'm looking at (sorry for the gross markers):
![apr-11-2018 09-44-03](https://user-images.githubusercontent.com/15620432/38620623-e9047fea-3d6c-11e8-85ae-26c1315806c1.gif)

I'm using this component in a backburner project right now and don't have enough time to really dig into finding a fix, but I should have some cycles in a week or so.

Some Details:

- macOS: Version 10.13.4 (17E199)
- Google Chrome: Version 65.0.3325.181
- Firefox: 60.0b11
- Using `create-react-app`, here's my package.json:
```json
"dependencies": {
    "google-map-react": "^0.34.0",
    "prop-types": "^15.6.0",
    "radium": "^0.23.0",
    "react": "^16.2.0",
    "react-dom": "^16.2.0",
    "react-geosuggest": "^2.7.0",
    "react-google-recaptcha": "^0.9.9",
    "react-places-autocomplete": "^6.1.2",
    "react-router": "^4.2.0",
    "react-router-dom": "^4.2.2",
    "react-scripts": "1.1.0",
    "react-text-mask": "^5.1.0",
    "webfontloader": "^1.6.28"
}
```
- The component, as implemented:
```javascript
<GoogleMapReact
  style={{ position: 'relative', width: '100%', height: '40vh' }}
  bootstrapURLKeys={{ key: 'not your key' }}
  defaultCenter={defaultCenter}
  defaultZoom={defaultZoom}
  center={center}
  resetBoundsOnResize={true}
  zoom={zoom}>
  {businesses.map((business, index) => (
    <Marker key={index} text={name} lat={position.lat} lng={position.lng} />
  ))}
</GoogleMapReact>
```
Hope this helps in the short-term. When I get some time, I'll see if I can do more than just confirm the thing's borked.

**Comment by stephenfarrar** [comment]
Here is my next and better attempt:
https://github.com/stephenfarrar/google-map-react/tree/zoom2

This branch aims to change less things, and be compatible with both 3.31 and 3.32.

It exhibits the same strange behaviour, though, where markers mysteriously disappear and reappear when you pan the map. Everything works fine on zoom though. I can't explain that.

@istarkov You're saying that on the server, markers are positioned relative to the map centre. Actually, in 3.32, elements are positioned relative to the map centre too. Could we just get rid of positioning relative to top-left?

**Comment by istarkov** [comment]
@stephenfarrar I'm now far far away from map theme and can't say much 
as I created this 3+ years ago and seems like my memory have some limitations ;-)
IMO if it works, you can use any coordinate system you like.

**Comment by pbwuxus** [comment]
+1

**Comment by stephenfarrar** [comment]
@itsmichaeldiego No worries, I've also been on vacation the last week! Thanks for reviewing and leaving comments. I've tried to address them all, but let me know if things are still unclear.

**Comment by nickpolet** [comment]
@stephenfarrar nice job on getting this issue fixed (or at least ready for review). Really awesome to see. Pulled your commits and they seem to work great on the new maps API.

@itsmichaeldiego do you have any idea on when this will be reviewed? Keen to see it merged soonish.

**Comment by itsmichaeldiego** [comment]
@nickpolet @pbwuxus @stephenfarrar Fixed and published. please upgrade to version `1.0.0` of google-map-react and let me know.
