### ISSUE TITLE
Not displaying museums, cafes and etc

### ISSUE THREAD

**Issue by abraztsov** [google-map-react/google-map-react#557]
google-maps-react version 0.31.0

My code below, what can I do/test ? Map not displaying any places (bars, parks, museums...)

```
<Map
 className={styles.Map}
 bootstrapURLKeys={{
  key: MAP_API_KEY,
  language: 'en',
  region: 'en'
 }}
 center={{ lat: latitude, lng: longitude }}
 onGoogleApiLoaded={this.props.onGoogleApiLoaded}
 defaultZoom={17}
>
 ...
</Map>
```

**Comment by itsmichaeldiego** [comment]
@abraztsov Please we require a live example or the whole code, this is not enough for me to understand what is going on, but it could be your markers, or anything. Here is a working example: https://github.com/itsmichaeldiego/google-map-react-examples/blob/master/src/components/GoogleMap.js

**Comment by abraztsov** [comment]
So, this is my full code and as you can see on pic. 2 map have some places that doesn't appear on pic. 1 (ivy complex, King Street Wharf,....)
```
<GoogleMap
  className={styles.Map}
  bootstrapURLKeys={{
  key: MAP_API_KEY,
    language: 'en',
    region: 'en'
  }}
  center={{ lat: latitude - 0.00019, lng: longitude + 0.00015 }}
  defaultZoom={showPoint ? 17 : 12}
>
</GoogleMap>
```

My MAP **(pic. 1)**
<img width="373" alt="2018-04-20 18 28 06" src="https://user-images.githubusercontent.com/19175580/39059939-9ad7263e-44c8-11e8-97d8-7a45b8553ad3.png">

MAP **(pic. 2)** from https://developers.google.com/maps/documentation/javascript/adding-a-google-map
<img width="381" alt="2018-04-20 18 27 59" src="https://user-images.githubusercontent.com/19175580/39059940-9b1bcfbe-44c8-11e8-88f3-fd7e777493eb.png">

**Comment by Haroenv** [comment]
You might try setting the `styles` property: https://developers.google.com/maps/documentation/javascript/examples/hiding-features

**Comment by itsmichaeldiego** [comment]
@abraztsov That makes sense, sorry for the delay on the answer. I think what @Haroenv recommended would be the way to go. Something like:

```
<GoogleMap
  bootstrapURLKeys={{
  key: MAP_API_KEY,
    language: 'en',
    region: 'en'
  }}
  center={[YOUR_CENTER]}
  defaultZoom={YOUR_ZOOM}
  options={{
    styles: [
      {
        featureType: 'all',
        stylers: [{ visibility: 'on' }],
      },
  }
>
</GoogleMap>
```

**Comment by abraztsov** [comment]
Thats worked. Thanks!
