### ISSUE TITLE
All of lodash included with google-map-react

### ISSUE THREAD

**Issue by prakashsanker** [google-map-react/google-map-react#558]
I just noticed this.

Even though this package uses `lodash.omit`, it introduces the whole lodash package into the project.

I created a minimal example here so that you can see this https://github.com/prakashsanker/google-map-react-test.

The relevant code sits in the 

> App.js

, where I do this

> import "google-map-react";

When that line is commented out, this is what my webpack bundle analyzer spits out 

<img width="1369" alt="screen shot 2018-04-11 at 4 52 42 pm" src="https://user-images.githubusercontent.com/3914624/38642716-e1be5922-3da8-11e8-8c0a-cc97e0ac3e6f.png">

When that line is included it spits out

<img width="1382" alt="screen shot 2018-04-11 at 4 53 10 pm" src="https://user-images.githubusercontent.com/3914624/38642726-ec017338-3da8-11e8-90fe-a77b244fdad7.png">

You can see for yourself by pulling down that repo and running 

> node profile.js

I did a quick search through your code and found that you are including only the omit function like so

> import omit from "lodash.omit";

and I would've expected this to prevent what we are seeing.

Could I get some help diagnosing this? I really like this package and I use it for a couple of startups in the developing world, where kilobytes matter, so I'd like to continue using it. 

I've used create-react-app for this minimal example, so I'm not sure if that does anything.

**Comment by itsmichaeldiego** [comment]
@prakashsanker First of all, thanks for your contribution. Luckily I handled this in #535 already and its going to be on our next release. Please for the next time, check the changes in latest master before submitting an issue.

**Comment by itsmichaeldiego** [comment]
@prakashsanker Regarding your second comment, if omit goes away in lodash 5, I will just use mine. Thanks for the tip.

**Comment by JustFly1984** [comment]
I'm still seeing whole lodash in my app, and it adds up 152kb! in latest v9.4.5.

**Comment by itsmichaeldiego** [comment]
Please upgrade @JustFly1984
