### ISSUE TITLE
 Can't call setState on a component that is not yet mounted. This is a no-op ...

### ISSUE THREAD

**Issue by stunaz** [google-map-react/google-map-react#565]
Hello,
I have this error warning when using `google-map-react`

I did a little investigation, it looks like the `kON_CHANGE ` event from [here](https://github.com/google-map-react/google-map-react/blob/aec0c08aae1dd29bc7fc7eee693b1687deb1c59b/src/google_map_markers.js#L51) is fired when the component is still mounting, which is resulting in calling `setState` [here](https://github.com/google-map-react/google-map-react/blob/aec0c08aae1dd29bc7fc7eee693b1687deb1c59b/src/google_map_markers.js#L105)

**Comment by itsmichaeldiego** [comment]
Please, create a proper issue. The description is short and the title its just a copy and paste. Would love to look into it.
