### ISSUE TITLE
Street View doesn't work anymore (since v0.34)

### ISSUE THREAD

**Issue by vertic4l** [google-map-react/google-map-react#567]
Seems like Street View stopped working with latest release:

![bildschirmfoto 2018-04-24 um 09 01 07](https://user-images.githubusercontent.com/1771763/39171179-441e3cbe-479e-11e8-89c9-e0b2ace06db9.png)
![bildschirmfoto 2018-04-24 um 09 01 12](https://user-images.githubusercontent.com/1771763/39171180-44393956-479e-11e8-950c-d1031bab15d9.png)

**Comment by vertic4l** [comment]
Nevermind, it's Google Maps own issue: https://issuetracker.google.com/issues/73397412

**Comment by vertic4l** [comment]
@itsmichaeldiego What do you say? Do we have to add something?

**Comment by itsmichaeldiego** [comment]
@vertic4l I think the error in the screenshots is not related to the error in [Google's issue tracker]( https://issuetracker.google.com/issues/73397412), would you agree?

I need a [jsfiddle](https://jsfiddle.net) or something reproducing the error in order to check what's happening.

**Comment by itsmichaeldiego** [comment]
Lets close it until you've more info @vertic4l, feel free to re-open later.
