### ISSUE TITLE
Example did not work.

### ISSUE THREAD

**Issue by gornyyvladimir** [google-map-react/google-map-react#568]
Hello! Examples did not work, please check it http://google-map-react.github.io/google-map-react/map/main/ . `Google Maps API error: MissingKeyMapError`

**Comment by itsmichaeldiego** [comment]
@gornyyvladimir This was a problem with Google maps, now they've provided a development mode, so we can see the example and play with the map without having an API key. Anyways, I am working in a new example and it will be out soon: https://github.com/itsmichaeldiego/google-map-react-examples
