### ISSUE TITLE
React Developer Tools shows that all GoogleMapMarkers update in 0.29, but why?

### ISSUE THREAD

**Issue by gpolyn** [google-map-react/google-map-react#569]
Why does React Developer Tools show _all_ `GoogleMapMarkers` updating in response to any UI interaction in 0.29, for example, as shown in the following linked .mov file?

 &nbsp; &nbsp; &nbsp;https://drive.google.com/file/d/1t4aVxOTCDRBJ5JxalMg6mp6XJeW3_O3Z/view?usp=sharing

You can see the `$hover` property for a selected marker changing in response to UI action&mdash;I understand that part&mdash;but why are all markers updating?

**Comment by nickpolet** [comment]
Can't really answer the "why" it does this, but remember that you have the flexibility of **shouldComponentUpdate** within react.

We used **shouldComponentUpdate** to greatly improve the performance of the map in this module. We render thousands of custom map markers by checking if the component needs to update based on the data being piped into the props. Before we did this we were battling with a pretty slow map implementation, but this sped things up perfectly.

**Comment by gpolyn** [comment]
@nickpolet can you please refer me to any example of selectively rendering map children, for example, with `shouldComponentUpdate`? Because in the `.mov` I linked you can see that the map doesn't update, just the children. I would like to control rendering of the children, but I don't know how.

(Your suggestion reminds me of a question I recently raised, but then closed due to lack of specificity: https://github.com/google-map-react/google-map-react/issues/560.)

**Comment by itsmichaeldiego** [comment]
@gpolyn I would suggest you to update to `1.0.0` though.

**Comment by gpolyn** [comment]
@itsmichaeldiego you're right.

I'll close for now and work up a demo in 1.0.0 to see if I can dupe.

Depending on the result from that, I'll comment back here.

**Comment by itsmichaeldiego** [comment]
@gpolyn Let me know and I will help you out.

**Comment by nickpolet** [comment]
@gpolyn, not sure I'll have time to code up an example in a timespan that will be useful to you, although I can say that we essentially just check if the markers array has changed in shouldComponentUpdate and pass back true if it has. We also have a range of other props that can trigger a render, but that is just specific to our application. 

In fact, using shouldComponentUpdate alone and checking if the marker array has changed provided a huge speed increase on it's own. The map went from completely unusable to being incredibly performant and a joy to use.

I might have some time to put together a simple example in a few weeks when I have a bit more time, but you will be quicker working through it yourself.

**Comment by gpolyn** [comment]
Related example/issue linked at https://github.com/google-map-react/google-map-react/issues/575

**Comment by itsmichaeldiego** [comment]
@gpolyn Does @nickpolet's comment helps?
