### ISSUE TITLE
Various examples not running or has a bug

### ISSUE THREAD

**Issue by carpben** [google-map-react/google-map-react#573]
http://google-map-react.github.io/google-map-react/map/main/ - Initially loads on the browser, but then presents a message: "Oops, something went wrong". This applies to the various examples under http://google-map-react.github.io/
https://jsbin.com/gaxapezowo/1/edit?js,output - Doesn't zoom out beyond level 3. 
http://istarkov.github.io/google-map-react/map/main/ - 404.

**Comment by itsmichaeldiego** [comment]
@carpben You're right, we're having a problem with that, I will take care of this asap.

**Comment by janhoeck** [comment]
I need some examples too. Hope this will be fixed soon

**Comment by itsmichaeldiego** [comment]
@carpben The fact that https://jsbin.com/gaxapezowo/1/edit?js,output - Doesn't zoom out beyond level 3 its rather intended, please check the [api documentation here](https://github.com/google-map-react/google-map-react/blob/master/API.md#override-the-default-minimum-zoom) for further information.

**Comment by itsmichaeldiego** [comment]
@carpben Why is createOptions receiving map as a parameter? Is the function `createOptions` being called? Also, keep in mind what it says in the [documentation here](https://github.com/google-map-react/google-map-react/blob/master/API.md#override-the-default-minimum-zoom):

> Setting this option can break markers calculation, causing no homeomorphism between screen coordinates and map.

**Comment by itsmichaeldiego** [comment]
@marr @carpben @janhoeck Main example is fixed thanks to Google maps, now they provide a _development mode_ when you don't need a key to play around with the app.

I've been working on a brand-new example and it will be out soon: https://github.com/itsmichaeldiego/google-map-react-examples/

Also, we're tracking examples problems in #524, so I am closing this one as for now.
