### ISSUE TITLE
support for China

### ISSUE THREAD

**Issue by 2yung** [google-map-react/google-map-react#574]
I do：
`bootstrapURLKeys={{ 
                        region:"cn",
                        key:"my key" 
                    }}`

but the request contain:
https://maps.googleapis.com/maps/api/js/ViewportInfoService.GetViewportInfo?...
https://maps.googleapis.com/maps/api/js/AuthenticationService.Authenticate?...

How to solve this problem.

**Comment by 2yung** [comment]
It seems to be the problem of the Google map API.

**Comment by itsmichaeldiego** [comment]
@2yung Im glad you found out the issue!

**Comment by sj1126** [comment]
i have the same propblem ,have you solve this problem?@2yung

**Comment by itsmichaeldiego** [comment]
@sj1126 If you set region to cn it will work, check https://github.com/google-map-react/google-map-react/blob/master/src/loaders/google_map_loader.js#L6
