### ISSUE TITLE
Custom Marker Does Not Appear With 3D Rotation

### ISSUE THREAD

**Issue by pkprosol** [google-map-react/google-map-react#576]
I have a custom marker set up similarly to the following:

```<div style={{ height: '100vh', width: '100%' }}>
        <GoogleMapReact
          bootstrapURLKeys={{ key: /* YOUR KEY HERE */ }}
          defaultCenter={this.props.center}
          defaultZoom={this.props.zoom}
        >
          <AnyReactComponent
            lat={59.955413}
            lng={30.337844}
            text={'Kreyser Avrora'}
          />
        </GoogleMapReact>
      </div>
```

I'm using it on a map zoomed in to appear as 3D. The marker appears fine on the initial map. But if I rotate the map, the marker goes offscreen despite having the same lat and lng. I think there might be an error in calculating the marker position given a rotated map position.

**Comment by itsmichaeldiego** [comment]
@pkprosol Thank you for reporting this, would you be so kind to provide a video? Also, if this is a feature you need, we encourage you to create your own PR, we will help you to merge and deploy it! Otherwise, as we haven't been working on 3D yet, this is a low-priority-issue and will be taken care in the future.

**Comment by mlucool** [comment]
I see something similar here with this code. See how it drifts as you zoom out.


![ezgif com-crop](https://user-images.githubusercontent.com/1813603/50058028-bbb13b80-0140-11e9-9e05-480a5e4184a5.gif)

```
import React, { Component } from 'react';
import GoogleMapReact from 'google-map-react';
import PlaceIcon from '@material-ui/icons/Place';

class SimpleMap extends Component {
  static defaultProps = {
    center: {
      lat: 40.75,
      lng: -73.99
    },
    zoom: 17
  };

  render() {
    return (
      // Important! Always set the container height explicitly
      <div style={{ height: '100vh', width: '100%' }}>
        <GoogleMapReact
          bootstrapURLKeys={{ key: 'KEY' }}
          defaultCenter={this.props.center}
          defaultZoom={this.props.zoom}
        >
          <PlaceIcon
            lat={40.75}
            lng={-73.99}
            color="secondary"
          />
        </GoogleMapReact>
      </div>
    );
  }
}

export default SimpleMap;
```

**Comment by aamorozov** [comment]
I think I am experiencing the exact same issue with a marker being an svg or svg wrapped with div(without using any 3d rotations). Relevant code:
```
        <GoogleMap
          bootstrapURLKeys={{key: GOOGLE_API_KEY}}
          defaultCenter={{lat: 40.7831, lng: -73.9712}}
          defaultZoom={15}
          yesIWantToUseGoogleMapApiInternals
        >
          <MapMarker lat={lat} lng={lng} />
        </GoogleMap>
```

**Comment by itsmichaeldiego** [comment]
@mlucool @aamorozov This is because the map marker position is default to top-left, if you want to change it, just change the css by doing `transform: (-50%, -50%)`

**Comment by mlucool** [comment]
That solves this! Thanks!
