### ISSUE TITLE
Can't change center of the map

### ISSUE THREAD

**Issue by fgatti675** [google-map-react/google-map-react#579]
Hi, I know it has been asked before but I can't seem to find a solution.

I have made a short example that should fix the center of the map by updating the center state property onChange, but it doesn't work as I would expect. What am I missing? Thanks!

    const AnyReactComponent = ({text}) => (
        <div style={{
            color: 'white',
            background: 'grey',
            padding: '15px 10px',
            display: 'inline-flex',
            textAlign: 'center',
            alignItems: 'center',
            justifyContent: 'center',
            borderRadius: '100%',
            transform: 'translate(-50%, -50%)'
        }}>
            {text}
        </div>
    );
    
    class SimpleMap extends React.Component {
        static defaultProps = {
            center: {lat: 59.95, lng: 30.33},
            zoom: 11
        };
    
        state = {
            center: {
                lat: 40.7831,
                lng: -73.9712
            }
        }
    
        _onChange = ({center, zoom}) => {
            this.setState({
                center: {
                    lat: 40.7831,
                    lng: -73.9712
                },
                zoom: zoom,
            });
        };
    
        render() {
            console.log(this.state.center);
            return (
                <GoogleMapReact
                    onChange={this._onChange}
                    center={this.state.center}
                    defaultZoom={this.props.zoom}
                >
                    <AnyReactComponent
                        lat={40.7831}
                        lng={-73.9712}
                        text={'Kreyser Avrora'}
                    />
                </GoogleMapReact>
            );
        }
    }
    
    
    ReactDOM.render(
        <div style={{width: '100%', height: '400px'}}>
            <SimpleMap/>
        </div>,
        document.getElementById('main')
    );

**Comment by ivanquirino** [comment]
Same, can't change center of map on state or props update. Zoom works, though. This really breaks the API...

**Comment by itsmichaeldiego** [comment]
@ivanquirino @fgatti675 Guys, this has already been solved here https://github.com/google-map-react/google-map-react/issues/546#issuecomment-375789488

**Comment by itsmichaeldiego** [comment]
@ivanquirino @fgatti675 Here is a live example:
https://codesandbox.io/s/2oy1nj9kyy

**Comment by fgatti675** [comment]
@itsmichaeldiego Thanks for your contribution. In your example you can change the center once. If you click on the update button once it works. If you move the camera and click on the update button again without changing any value it doesn't work I'm afraid.
I experience a similar behaviour in my app.

**Comment by itsmichaeldiego** [comment]
@fgatti675 Some time ago I created a project that handles changing the center multiple times, here it is: https://github.com/itsmichaeldiego/earthquaker

**Comment by uuykay** [comment]
Hey guys, experiencing a similar issue here. @itsmichaeldiego I read the code in your earthquaker app as well as clicked your sandbox example, but I'm honestly still confused. In your docs https://www.npmjs.com/package/google-maps-react you:
import {Map, InfoWindow, Marker, GoogleApiWrapper} from 'google-maps-react';
however in your listed solution you import
import GoogleMap from "google-map-react";

Looking at the code, I'm confused about what exactly is different here, in terms of any additional props I might need to pass in if I was to use the Map component only. If you could point me in the right direction that's appreciated.

**Comment by uuykay** [comment]
This is the component I am trying to get to work:

![image](https://user-images.githubusercontent.com/32381131/58748908-78fed800-84c2-11e9-81e9-72ff6476b918.png)

I have it structured so that the 2 addresses have a click event in a parent component called InteractiveAddresses:
![image](https://user-images.githubusercontent.com/32381131/58748927-b2cfde80-84c2-11e9-98ba-e078603c69c6.png)

And here is my GoogleMaps component:
![image](https://user-images.githubusercontent.com/32381131/58748935-d430ca80-84c2-11e9-9217-bb72917f78b9.png)

InteractiveAddresses changes state properly:
![image](https://user-images.githubusercontent.com/32381131/58748945-ef9bd580-84c2-11e9-85b9-39df0d25cf54.png)

However check out the state inside the Map component itself, it is using initial lat / lng value instead of updating:

![image](https://user-images.githubusercontent.com/32381131/58748988-5de09800-84c3-11e9-9c1c-62eb58273d1f.png)

**Comment by uuykay** [comment]
Ok this was silly, I didn't pass in the center prop, and only used initialCenter

![image](https://user-images.githubusercontent.com/32381131/58749070-5ec5f980-84c4-11e9-901e-c8c062e12011.png)

Hope this helps someone in the future.

**Comment by itsmichaeldiego** [comment]
@uuykay I am happy you found the solution!

**Comment by ihsanmaulanahamdani** [comment]
I have the same issue and solve the issue with @uuykay way but a bit different in my case

`
<GoogleMapReact
    bootstrapURLKeys={{
      key: "YOUR_KEY"
    }}
    defaultCenter={[lat, lng]} // Before solve I just use this
    defaultZoom={18}
    center={[campus.lat, campus.lng]} // I add this and problem solved
    >
`

Thanks to @uuykay

**Comment by uuykay** [comment]
> I have the same issue and solve the issue with @uuykay way but a bit different in my case
> 
> ```js
> <GoogleMapReact
>     bootstrapURLKeys={{
>       key: "YOUR_KEY"
>     }}
>     defaultCenter={[lat, lng]} // Before solve I just use this
>     defaultZoom={18}
>     center={[campus.lat, campus.lng]} // I add this and problem solved
> >
> ```
> 
> Thanks to @uuykay

No problem @ihsanmaulanahamdani ! I'm glad my comments helped someone :)

**Comment by iamcoreyg** [comment]
Just adding another comment here for future – the lat and long have to be a `number` type. It won't work with strings.

**Comment by rem0nfawzi** [comment]
In case anyone is facing same issue with functional component in which there's no render method .. You can do something like that
{
    lat && (
                  <GoogleMapReact
                         bootstrapURLKeys={{
                         key: "YOUR_KEY"
                         }}
                         defaultCenter={[lat, lng]} // Before solve I just use this
                         defaultZoom={18}
                         center={{lat , lng}} // I add this and problem solved
                   >
   )
}

This will enforce the component to rerender each time lat is changed

**Comment by Rybecki** [comment]
> Ok this was silly, I didn't pass in the center prop, and only used initialCenter
> 
> ![image](https://user-images.githubusercontent.com/32381131/58749070-5ec5f980-84c4-11e9-901e-c8c062e12011.png)
> 
> Hope this helps someone in the future.

I just want to say that you saved my project (and the problem I fought for last few hours), so yes, you helped someone! ;)

**Comment by uuykay** [comment]
> > Ok this was silly, I didn't pass in the center prop, and only used initialCenter
> > ![image](https://user-images.githubusercontent.com/32381131/58749070-5ec5f980-84c4-11e9-901e-c8c062e12011.png)
> > Hope this helps someone in the future.
> 
> I just want to say that you saved my project (and the problem I fought for last few hours), so yes, you helped someone! ;)

Thanks for leaving a reply! It is much appreciated, and the community aspects of development are the best!

**Comment by chengen0612** [comment]
> Just adding another comment here for future – the lat and long have to be a `number` type. It won't work with strings.
@iamcoreyg Thanks for the reply. Changed the strings to number and solve the problem!
