### ISSUE TITLE
Google Maps API 3.32 New base map

### ISSUE THREAD

**Issue by MiloMagnus475** [google-map-react/google-map-react#581]
Great component and simple to use! Thank you for maintaining a fantastic repository. 

I couldn't find any documentation regarding the new features rolling out to [Google Maps API](https://developers.google.com/maps/documentation/javascript/basemap#how-to-opt-out-until-august-2018). 

Looking at the get requests in the browser I was able to find that the component still fetches version 3.31. In order to access the new base map and rendering functionalities I found that adding "&v=3.32" to the bootstrapURLKeys key object did the trick! Maybe someone can add this step to the documentation? 

```
<GoogleMapReact
     bootstrapURLKeys={{
           key: "YOUR_API_KEY&v=3.32"
     }}
```

**Comment by itsmichaeldiego** [comment]
@MiloMagnus475 Back in `0.34.0` we used to force the version to `3.31` as default, but not anymore since `1.0.0`, are you using latest version? `v1.0.2` ?

**Comment by MiloMagnus475** [comment]
Looks like I was using the older version! After updating I no longer need to clarify which API version to fetch. Thank you so much @itsmichaeldiego!

**Comment by itsmichaeldiego** [comment]
@MiloMagnus475 No worries my friend! Let me know if you need further help.
