### ISSUE TITLE
Is "satellite" view option available?

### ISSUE THREAD

**Issue by kstulgys** [google-map-react/google-map-react#585]
I just see that default "Map" view. Can I change it to "Satellite"? Can't find where I can pass the prop

**Comment by itsmichaeldiego** [comment]
@kstulgys Could you provide an example of what you want to achieve with plain google maps?

**Comment by vertic4l** [comment]
```
<GoogleMapReact
    options={this.getMapOptions}
>
    ...render something in here
</GoogleMapReact>



private getMapOptions = (maps: Maps) => {

    return {
        streetViewControl: false,
        scaleControl: true,
        fullscreenControl: false,
        styles: [{
            featureType: "poi.business",
            elementType: "labels",
            stylers: [{
                visibility: "off"
            }]
        }],
        gestureHandling: "greedy",
        disableDoubleClickZoom: true,
        minZoom: 11,
        maxZoom: 18,

        mapTypeControl: true,
        mapTypeId: maps.MapTypeId.ROADMAP,
        mapTypeControlOptions: {
            style: maps.MapTypeControlStyle.HORIZONTAL_BAR,
            position: maps.ControlPosition.BOTTOM_CENTER,
            mapTypeIds: [
                maps.MapTypeId.ROADMAP,
                maps.MapTypeId.SATELLITE,
                maps.MapTypeId.HYBRID
            ]
        },

        zoomControl: true,
        clickableIcons: false
    };
}
```

**Comment by itsmichaeldiego** [comment]
Thanks for your answer @vertic4l!

**Comment by itsmichaeldiego** [comment]
@kstulgys I think @vertic4l provided the solution for you, I am closing the issue as for now.

**Comment by rajdeepratan** [comment]
My mapTypeControlOptions button disappears after the page gets loaded. 

`const getMapOptions = function (maps) {
    return {
        streetViewControl: true,
        scaleControl: true,
      fullscreenControl: false,
        styles: [{ stylers: [{ 'saturation': -100 }, { 'gamma': 0.8 }, { 'lightness': 4 }, { 'visibility': 'on' }] }],
        mapTypeControl: true,
        mapTypeId: maps.MapTypeId.MAP,
        mapTypeControlOptions: {
            style: maps.MapTypeControlStyle.DROPDOWN_MENU,
            position: maps.ControlPosition.CENTER,
            mapTypeIds: [
                maps.MapTypeId.ROADMAP,
                maps.MapTypeId.SATELLITE,
                maps.MapTypeId.HYBRID
            ]
        },
        
    };
}`


`<GoogleMapReact
              bootstrapURLKeys={{ key: '' }}
              defaultCenter={center}
              center={center}
              defaultZoom={zoom}
              onClick={this.onClickOuter}
              onChildClick={this.onClickPin}
              onBoundsChange={this.onDragMap}
              prerender
              onGoogleApiLoaded={({ map, maps }) => {
                this.setState({
                  map, maps, mapLoaded: true, isKmlLoaded: false,
                });
              }}
              options={getMapOptions}
            >
              {mapData.map((edge, i) => (
                <MapPin
                  key={i}
                  lat={edge.lat}
                  lng={edge.lng}
                  data={edge.data}
                  selectedId={currentClickPinId}
                />
              ))}
            </GoogleMapReact>`

**Comment by JLee21** [comment]
@vertic4l 

I'm having some trouble with one of the values from `maps`

```
TypeError: Cannot read property 'HORIZONTAL_BAR' of undefined
```

Strange though, the [Google Maps API](https://developers.google.com/maps/documentation/javascript/controls) seems to spell it out correctly:
`maps.MapTypeControlStyle.HORIZONTAL_BAR`

Which leads me to believe, is my `maps` object missing something for some reason?

**Comment by vertic4l** [comment]
@JLee21 Try setting a breakpoint in DevTools or debug it the oldschool way with `console.log()`.

`maps`should look like this:
![Bildschirmfoto 2019-03-18 um 10 54 45](https://user-images.githubusercontent.com/1771763/54521929-4dad2800-496c-11e9-94ea-b467bab8f2d6.png)

**Comment by JLee21** [comment]
Ah thanks for that screenshot @vertic4l 

I was looking at the `map` object and not the `maps` object 🤦‍♂️

```
onGoogleApiLoaded={({ map, maps }) => this.getMapOptions(maps)}
```

**Comment by jim-alexander** [comment]
just a short version `options={map => ({ mapTypeId: map.MapTypeId.SATELLITE })}`

**Comment by cindylouwhovian** [comment]
how do you change map type through say a button click?  

<form>
   <select onChange={this.handleMapTypeChange}>
      <option value={0}>Terrain</option>
       <option value={1}>Satellite</option>
    </select>
</form> 


is the following needed??
onMapTypeIdChange={this.handleMapTypeChange}

and what would handleMapTypeChange look like??

**Comment by cmwetherell** [comment]
I’m here because GPT4 didn’t figure it out. Thanks!
