### ISSUE TITLE
Detect "long press"?

### ISSUE THREAD

**Issue by kaycebasques** [google-map-react/google-map-react#587]
Hi, thanks for the library.

I'm trying to dynamically add markers on "long press" gestures.

The usual way to do this is with a timer, a `mousedown` event, and a `mouseup` event.

But it doesn't look like this lib's API supports these events. I only see `onClick`.

Suggested workarounds?

**Comment by itsmichaeldiego** [comment]
@kaycebasques You can always set event listeners, by using `onGoogleAPILoaded`:

```
const apiIsLoaded = (map, maps) => {
  if (maps) {
    maps.event.addDomListener(window, 'mousedown', () => {
      // do your thing
    });
  }
};

const GoogleMap = props => (
  <GoogleMapReact
    zoom={props.zoom}
    center={props.center}
    bootstrapURLKeys={{
      key: process.env.MAP_KEY,
      language: 'en',
    }}
    yesIWantToUseGoogleMapApiInternals
    onGoogleApiLoaded={({ map, maps }) => apiIsLoaded(map, maps, props.places)}
  >
    {props.children}
  </GoogleMapReact>
);
```

**Comment by itsmichaeldiego** [comment]
@kaycebasques Let me know if my answer was helpful, otherwise re-open the issue. Thanks
