### ISSUE TITLE
Clicking map controls triggers onClick 

### ISSUE THREAD

**Issue by jonirautiainen** [google-map-react/google-map-react#588]
I can't figure out why this is happening. When on mobile device any of the map control buttons is clicked, onClick (func) triggers. I'm moving the pin based on user clicks and this leads to unwanted behaviour. There is no issue when using desktop device. I'm using gestureHandling: "greedy" option.

![issuee](https://user-images.githubusercontent.com/28143700/40659655-927e4f6e-6357-11e8-85a6-14bcfa0ed833.gif)

**Comment by itsmichaeldiego** [comment]
@jonirautiainen Could you please provide a codepen or any live example? I need to take a look at the code to be able to know what is happening!

Feel free to re-open the issue when providing the example and I will help you out! Kiitos.
