### ISSUE TITLE
Animation on marker click 

### ISSUE THREAD

**Issue by Amalkh5** [google-map-react/google-map-react#589]
Hello, 
I want to do animation on marker click  so i try to is  this 

 ```
  onMarkerClick(lat, lng, title) {

this.setState({
            animation: '2',
        });
    }
<Marker
                                    animation={this.state.animation}
                                    onClick={() => this.onMarkerClick(place.lat, place.lng, place.name)}
                                    title={place.name}
                                    position={{ lat: place.lat, lng: place.lng }}
                                    name={place.name}
                                    key={index}
                                />
```
but the **problem** that all marker get trigger at the **same time.**

**Comment by itsmichaeldiego** [comment]
@Amalkh5 Could you provide a working example? This piece of code is not that descriptive. I think your problem is more related to the usage of React instead of the map itself, but will be happy to help.

Please re-open the issue when having a better example and I will help you out.
