### ISSUE TITLE
Initializing map with fitBounds when map size is dynamic

### ISSUE THREAD

**Issue by SachaG** [google-map-react/google-map-react#590]
I know there's other threads about this issue but I couldn't really find a clear answer there, so I thought I'd post my current solution to get feedback, and in case it helps anybody else.

I have a search box where users can type a location, which could be a city, country, neighborhood, etc. In order to handle the different zoom levels better I thought I would use the bounds returned by Google Maps' API instead of the center coordinate. 

The issue here is that my map size is dynamic, and depends on the viewport size. So I actually need to do a two-step process. 

First in `componentDidMount` I need to figure out the size of the map's container:

```js
  componentDidMount() {
    const element = document.getElementById('MyMap');
    this.setState({ size: { height: element.clientHeight, width: element.clientWidth } });
  }
```

On the first render `this.props.size` will not yet be defined so you shouldn't try to render the map. Instead, if you just return an empty `div`, that will be enough to figure out the size:

```js
if (!this.state.size) {
  return <div id="MyMap"/>;
}
```

Once `size` has been calculated and passed down by the parent component though, you can safely call `fitBounds` to figure out the `center` and `zoom`:

```js
const { center, zoom } = fitBounds({ this.props.sw, this.props.ne }, this.state.size);
```

And from there pass them on to the `GoogleMap` component. 

```js
return <div id="MyMap"><GoogleMap center={center} zoom={zoom}/></div>;
```

This feels a bit hacky but it seems to work. I'd be curious to know if there are any better solutions though?

### Related Issues

- https://github.com/google-map-react/google-map-react/issues/312
- https://github.com/google-map-react/google-map-react/issues/3

**Comment by itsmichaeldiego** [comment]
@SachaG You can access the google map's api to re-center the map afterwards instead. I have been working on and achieve this here: https://github.com/itsmichaeldiego/google-map-react-examples/pull/6/files#diff-3271ac660008ae079c294e51278ce53eR41

```
// Return map bounds based on list of places
const getMapBounds = (map, maps, places) => {
  const bounds = new maps.LatLngBounds();

  places.forEach((place) => {
    bounds.extend(new maps.LatLng(
      place.geometry.location.lat,
      place.geometry.location.lng,
    ));
  });
  return bounds;
};

// Re-center map when resizing the window
const bindResizeListener = (map, maps, bounds) => {
  maps.event.addDomListenerOnce(map, 'idle', () => {
    maps.event.addDomListener(window, 'resize', () => {
      map.fitBounds(bounds);
    });
  });
};

// Fit map to its bounds after the api is loaded
const apiIsLoaded = (map, maps, places) => {
  // Get bounds by our places
  const bounds = getMapBounds(map, maps, places);
  // Fit map to bounds
  map.fitBounds(bounds);
  // Bind the resize listener
  bindResizeListener(map, maps, bounds);
};

class App extends Component {
  constructor(props) {
    super(props);

    this.state = {
      places: [],
    };
  }

  componentDidMount() {
    fetch('/places.json')
      .then(response => response.json())
      .then(data => this.setState({ places: data.results }));
  }

  render() {
    return (
      <Wrapper>
          <GoogleMap
            defaultZoom={10}
            defaultCenter={YOUR_DEFAULT_CENTER}
            yesIWantToUseGoogleMapApiInternals
            onGoogleApiLoaded={({ map, maps }) => apiIsLoaded(map, maps, this.state.places)}
          >
            {places.map(place => (
              <Marker
                key={place.id}
                text={place.name}
                lat={place.geometry.location.lat}
                lng={place.geometry.location.lng}
              />
            ))}
          </GoogleMap>
      </Wrapper>
    );
  }
}

export default App;
```

**Comment by itsmichaeldiego** [comment]
@SachaG Let me know if that helps, otherwise re-open the issue and I will help you out. Thanks.

**Comment by SachaG** [comment]
Thanks, I'll try your way when I have time to revisit this.

**Comment by itsmichaeldiego** [comment]
@SachaG No worries, please let me know and I'll try to help you out.

**Comment by djamesfar** [comment]
I am using the example above, but I am finding that when I re-render with a new set of places (in state rather than from fetch), the map does not re-center or fit to bounds with new places.  Any tips?

**Comment by itsmichaeldiego** [comment]
@djamesfar That makes sense because here we are re-centering when the window resizes. In order to achieve what you want you will need to re-fit bounds when places change, I think you can do that by using `shouldComponentUpdate` and `componentDidMount`? For that you will need to set the map with refs.

**Comment by natcodes** [comment]
@djamesfar Did this last suggestion work for you? I'm not sure how to implement it. If you figured it out, please share. I have the same issue where the map will not re-center.

**Comment by itsmichaeldiego** [comment]
@natcodes Here is an example https://github.com/google-map-react/google-map-react-examples/blob/master/src/examples/Main.js#L40

**Comment by FarhathAli** [comment]
how to use google map fitbound by using react-google-map/api in class component can someone tel me...???
