### ISSUE TITLE
Google Maps JavaScript API error: DeletedApiProjectMapError 

### ISSUE THREAD

**Issue by jooj123** [google-map-react/google-map-react#591]
Hi,

Getting error:

```
Google Maps JavaScript API error: DeletedApiProjectMapError https://developers.google.com/maps/documentation/javascript/error-messages#deleted-api-project-map-error
``` 

in console when i run the examples.

If I check what this means (https://developers.google.com/maps/documentation/javascript/error-messages) it says:

"Your API project may have been deleted from the Google API Console. Please check the project for which you generated the API key that's included in JavaScript API loader. You can create a new API project and get a new key on the Google API Console."

Was the project removed from your google api console by accident ?

I can throw up a PR to fix this if needed

**Comment by itsmichaeldiego** [comment]
@jooj123 I think the project was deprecated, not removed, we need to use a new Api key. Feel free to add a PR, I would love that, thanks <3

**Comment by itsmichaeldiego** [comment]
@jooj123 This should be ok by now, let me know if otherwise and we can re-open and re-visit.

**Comment by itsmichaeldiego** [comment]
Example project? The example project is currently out of date, we're working on new examples in #524
