### ISSUE TITLE
missing key error on demo website

### ISSUE THREAD

**Issue by DoctorHowser** [google-map-react/google-map-react#595]
Getting this error on http://google-map-react.github.io/google-map-react/map/main/

The script element that loads the API is missing the required authentication parameter. If you are using the standard Maps JavaScript API, you must use a key parameter with a valid API key. If you are a Premium Plan customer, you must use either a client parameter with your client ID or a key parameter with a valid API key.
--

Might want to get that fixed -- gonna scare away people from using this.

**Comment by itsmichaeldiego** [comment]
@DoctorHowser We're aware of the problem but we're working in new examples, soon enough we will have shining new examples for this!

**Comment by jooj123** [comment]
@itsmichaeldiego any feedback as to when this is coming ?

**Comment by itsmichaeldiego** [comment]
@jooj123 Still working on them, are you interested on providing help?
