### ISSUE TITLE
Is there a way to override the onClick for the fullscreen [ ] icon?

### ISSUE THREAD

**Issue by nbkhope** [google-map-react/google-map-react#597]
I would like to override the fullscreen icon click event so that I do custom things instead of it opening up the map on full screen. Is that possible? Possible use cases: when you want to display a larger version of the map on a modal.

**Comment by itsmichaeldiego** [comment]
@nbkhope You can totally do that, but this is more related to google maps itself than this library. 
Here is a helpful link: https://stackoverflow.com/questions/48613450/custom-full-screen-control-behaviour-with-google-maps-api

Basically, you will need to modify the `options` and set `fullscreenControl: false`. And then bind that button using [onGoogleApiLoaded](https://github.com/google-map-react/google-map-react/blob/master/API.md#ongoogleapiloaded-func)

Let me know if that helps!

**Comment by itsmichaeldiego** [comment]
@nbkhope Im closing the issue, please re-open it if the problem persists.
