### ISSUE TITLE
Fix lodash usage (in google_map_loader.js + google-map-react itself)

### ISSUE THREAD

**Issue by vertic4l** [google-map-react/google-map-react#602]
@itsmichaeldiego 
`var _lodash = require('lodash');`

`
if ((0, _lodash.isEmpty)(bootstrapURLKeys.v)) {
      queryString += '&v=3.31';
    }
`

Due to this implementation webpack bundles the whole lodash library in my bundle.

Could you please get rid of this or fix it to a cherry-picking method approach?
e.g.

`var _isEmpty = require('lodash/isEmpty');`

<img width="775" alt="bildschirmfoto 2018-06-20 um 15 53 38" src="https://user-images.githubusercontent.com/1771763/41666075-e52a5fa6-74a9-11e8-82c6-46dbc0763b1f.png">

before, after commenting this out:

<img width="382" alt="bildschirmfoto 2018-06-20 um 16 34 25" src="https://user-images.githubusercontent.com/1771763/41665271-dec026f2-74a7-11e8-856a-6e7c10965669.png">

It's gone... lodash.min.js will be another package...

Edit:

It's the dist package of google-map-react... which gets imported by webpack.
lodash.min.js was bundled there inside...

`import GoogleMapReact from "google-map-react";`

imports lodash.js through google_map_loader.js and lodash.min.js through dist-package of google-map-react.

Please fix this huge dependency... :)

**Comment by vertic4l** [comment]
@itsmichaeldiego Sorry, seems like it is solved in version 1.0.4. Was still at 0.23.4!

**Comment by itsmichaeldiego** [comment]
@vertic4l Oh, thanks god, you got me worried! I removed the whole `lodash` library and only exported `isEmpty` in #535
