### ISSUE TITLE
defaultProps center lat and long render maps, but passed props passed do not

### ISSUE THREAD

**Issue by m-riley** [google-map-react/google-map-react#604]
In the simpleMaps example, I have found that hardcoded values for default lat, lng props renders the map correctly, however as soon as I use non-hardcoded values, (i.e. passed in props) then no map is rendered.
Parent:
``` <SimpleMap center={{center: {lat: restaurant.lat, lng: restaurant.long}}} zoom={15} />```
Component:
```
class SimpleMap extends Component {
    render() {
        console.log('this.props.restaurant.center', this.props.center);
        console.log('this.props.restaurant.zoom', this.props.zoom);
        return (
            // Important! Always set the container height explicitly
            <div style={{ height: '100vh', width: '100%' }}>
                <GoogleMapReact
                    bootstrapURLKeys={{
                        key: my-key-here...',
                    }}
                    center={this.props.center}
                    defaultZoom={this.props.zoom}
                >
                </GoogleMapReact>
            </div>
        );
    }
}
```
Any ideas?

**Comment by itsmichaeldiego** [comment]
@m-riley Well, you're nesting center again here:

```<SimpleMap center={{center: {lat: restaurant.lat, lng: restaurant.long}}} zoom={15} />```

It should be:

```<SimpleMap center={{lat: restaurant.lat, lng: restaurant.long}} zoom={15} />```

**Comment by m-riley** [comment]
OK, my bad - was passing strings instead of floats! Example works as expected :-)

**Comment by m-riley** [comment]
Make sure to pass correct propTypes

**Comment by itsmichaeldiego** [comment]
@m-riley Perfect, glad it worked! Let us know if you need more help!
