### ISSUE TITLE
Draggable Marker Problem - Mouse position is weird

### ISSUE THREAD

**Issue by caioaletroca** [google-map-react/google-map-react#612]
## Problem
I made a simple draggable marker some months ago but when I updated google-map-react package from version 1.0.4 to 1.0.5 with npm things get weird.

I made a code to show the problem:
https://codesandbox.io/s/53vvzj0mjp

## Expected
When click on the marker, I pass the LatLng Mouse's position to the marker, that the marker can follow mouse movement.

## Current
For some reason the marker seens to be offseted from the mouse position by half of map's size. He pops to the bottom right map portion (see the codesandbox for example).

Anyway, this is awesome package, thank you devs!!

**Comment by itsmichaeldiego** [comment]
@caioaletroca Thanks for pointing that out!

@stephenfarrar It seems that our change in #603 might have affected dragging. Would you mind checking?

**Comment by AliMamed** [comment]
these issue seem have the same problem https://github.com/google-map-react/google-map-react/issues/614

**Comment by stephenfarrar** [comment]
Perhaps this will also be fixed by #620 ?

**Comment by itsmichaeldiego** [comment]
I just published version `1.0.6` that includes @stephenfarrar's fix: #620 

Let me know if it works for you guys.

Thanks @stephenfarrar <3

**Comment by caioaletroca** [comment]
Yes it worked, the code in the sandbox worked perfectily.

**Comment by itsmichaeldiego** [comment]
Glad to hear that @caioaletroca! Let us know if you have any other problem
