### ISSUE TITLE
logo proporsal for google map react 

### ISSUE THREAD

**Issue by anablog** [google-map-react/google-map-react#616]
Hello a pleasure in greeting you, I wanted to introduce myself I am Ana Medina Graphic Web Designer, I am very interested in your new open source project for me it would be a pleasure to provide my services as a designer and collaborate without commitments, You require a new logo for your brand I can help him?

I well be pleased to collaborate with you.

**Comment by itsmichaeldiego** [comment]
@anablog Hey Ana, I love hearing that you want to help us from a design point of view, we need that! 

I will be happy to collaborate with you on the logo and there are some other things we can do, like designs for the examples I am creating.

Feel free to contact me to my email itsmichaeldiego@gmail.com

**Comment by itsmichaeldiego** [comment]
I am closing this issue, thanks @anablog

**Comment by anablog** [comment]
137/5000
perfect friend then if you require, of my services as a designer, you tell
me where to start, if you like the idel of the logo?


2018-07-22 8:04 GMT-04:00 Michael Diego <notifications@github.com>:

**Comment by itsmichaeldiego** [comment]
@anablog I would prefer email, as this area is for issues related to the library. But the idea is to mix the logo of Google Maps with the logo of [React.js](https://reactjs.org/)

**Comment by itsmichaeldiego** [comment]
Perfect @anablog, I am from Uruguay also so it would be easier by email where we can use Spanish 🇪🇸to talk about the ideas for the logo.

**Comment by anablog** [comment]
Hola espero estes bien Michael, ya estoy por aca, entonces comenzemos;),
conversame un poco hacerca de tu proyecto, quiero tener recursos para
elaborarle una buena idea de su logotipo

2018-07-27 10:09 GMT-04:00 Michael Diego <notifications@github.com>:

**Comment by itsmichaeldiego** [comment]
@anablog Este comentario esta en github todavia, hablemos por mail comun itsmichaeldiego@gmail.com
