### ISSUE TITLE
Animate to center not always animated

### ISSUE THREAD

**Issue by brianlaw033** [google-map-react/google-map-react#622]
I have some problems animate the marker to center, like this
![2018-08-06 19 39 58](https://user-images.githubusercontent.com/25007087/43714730-9c94151c-99b0-11e8-8221-ec29b5742704.gif)

sometimes it animates some times it doesn't.

**Comment by johnhult** [comment]
I suppose you're using panTo?

From the docs:

panTo(latLng)
Parameters: latLng:  LatLng\|LatLngLiteral
Return Value:  None
Changes the center of the map to the given LatLng. If the change is less than both the width and height of the map, the transition will be smoothly animated.

I don't think this is something to do with google-map-react in itself.

**Comment by brianlaw033** [comment]
no bro, according to #107 
when I change center prop, map makes pan to that position.

**Comment by brianlaw033** [comment]
looks like it is a performance issue on dev mode, it works smoothly on production, ill close this issue

**Comment by itsmichaeldiego** [comment]
Glad you found a solution @brianlaw033
