### ISSUE TITLE
overlapping marker spiderfier with google-map-react

### ISSUE THREAD

**Issue by makethisbuildthat** [google-map-react/google-map-react#627]
I really prefer this google-map-react module over some others but I seem to have trouble getting overlapping marker spiderfier to work with google map react.

Has anyone able to get overlapping marker spiderfier to work with google-map-react?

**Comment by itsmichaeldiego** [comment]
@makethisbuildthat Can you provide a live example so I can try to help you?

**Comment by makethisbuildthat** [comment]
@itsmichaeldiego I have it semi-working in which the google.maps.Markers objects would show and spiderfy. However, right now my problem is to create custom marker objects as Overlapping-Marker-Spiderfier only seem to take google.maps.Markers object and not custom react components. Below is how I implemented my code (everything related to this is in render():

`render() {
        const { projects } = this.props;

        if (this.state.mounted > 0) {
            if (OverlappingMarkerSpiderfier != null) {
                console.log("OverlappingMarkerSpiderfier", OverlappingMarkerSpiderfier);
                const options = {
                    legWeight: 3,
                    keepSpiderfied: true,
                    nearbyDistance: 30 //in pixels 
                };
                oms = new OverlappingMarkerSpiderfier(this.state.map, options);

                markers = projects.map((p) => {

// ideally marker should be <ProjectMarker> instead of google.maps.Marker
                    /*marker = (<ProjectMarker
                        key={p._id}
                        projectId={p._id}
                        iconType={p.projectStage === stages.DONE ? "done" : "build"}
                        lat={p.coordinate.lat}
                        lng={p.coordinate.lng}
                        title={p.summary}
                        imageUrl={p.projectStage === stages.DONE ? p.showcaseImg[0] : p.workImg[0]}
                    />);*/


                    const marker = new google.maps.Marker({
                        position: { lat: p.coordinate.lat, lng: p.coordinate.lng },
                        map: this.state.map
                    });
                    oms.addMarker(marker);

                    const iw = new google.maps.InfoWindow();
                    oms.addListener('click', function (marker, event) {
                        iw.setContent(marker.desc);
                        iw.open(this.state.map, marker);
                    });


                    console.log("before add marker", marker);
                    oms.addMarker(marker);
                });
                console.log("after oms", oms);

                oms.addListener('spiderfy', function (markers) {
                    //iw.close();
                });
            }
        }

        return (
            <div className={cx("google-map-canvas")} className={cx("google-map")} style={{ height: `calc(100vh - 50px)` }}>
                {this.state.mounted > 0 && <GoogleMapReact
                    bootstrapURLKeys={{ key: [googleMapApiKey] }}
                    center={this.props.coord}
                    zoom={this.props.zoom}
                    options={createMapOptions}
                    onGoogleApiLoaded={({ map, maps }) => this.initMap(map, maps)}
                    onChange={this.mapOnChange}
                    yesIWantToUseGoogleMapApiInternals
                >
                    {markers}
                </GoogleMapReact>}
            </div>
        )
    }`

**Comment by itsmichaeldiego** [comment]
@makethisbuildthat I would love to help you but in order to do so, I need a *live* code example, is very hard otherwise.

You can create one easily using https://codesandbox.io/

[Here is an example](https://codesandbox.io/s/j7r9mz4nx9).

**Comment by makethisbuildthat** [comment]
@itsmichaeldiego Here is a live example: 

https://codesandbox.io/s/7ojz6q856

As you can see, I got Overlapping-Marker-Spiderfier working on the map, but in my "TODO" comment I would want the marker to be a custom react component instead of google.maps.Marker.

Thanks for helping out!

**Comment by itsmichaeldiego** [comment]
@makethisbuildthat Oh okey, I get you know, in the example you provided, you are creating the markers as React components, but Google Maps doesn't support that, so that won't work. We currently don't support spiderify, but one of our members did an integration a couple of years ago that you can fork: https://github.com/google-map-react/google-map-react/pull/284

We would really like to merge this PR soon as it has been opened for quite a bit, but we need to test it thoroughly and given that its not such a common feature (spiderify) we haven't paid much attention to it. I will put my hands on it to see if I can merge it any time soon. But you're the perfect tester for this, would you mind checking testing PR #284 and see if you can achieve it? And we can work together to merge and make this feature part of the library 👍

**Comment by makethisbuildthat** [comment]
@itsmichaeldiego i looked at the PR from @mukulb90 i only see that the it supports clustering, but i don't see anything for spiderfy in his examples... please advise.

**Comment by itsmichaeldiego** [comment]
@makethisbuildthat Did you check? I just did a find in page and found it https://github.com/google-map-react/google-map-react/pull/284/files#diff-e8b86504901df43bfb0218a9db49bb7bR95

**Comment by ArcadeRenegade** [comment]
For any fellow Googlers such as myself, this SO answer may help you:
https://stackoverflow.com/a/55592760/3185018

**Comment by huzaifa-ahmed** [comment]
> @itsmichaeldiego I have it semi-working in which the google.maps.Markers objects would show and spiderfy. However, right now my problem is to create custom marker objects as Overlapping-Marker-Spiderfier only seem to take google.maps.Markers object and not custom react components. Below is how I implemented my code (everything related to this is in render():
> 
> `render() {
> const { projects } = this.props;
> 
> ```
>     if (this.state.mounted > 0) {
>         if (OverlappingMarkerSpiderfier != null) {
>             const options = {
>                 legWeight: 3,
>                 keepSpiderfied: true,
>                 nearbyDistance: 30 //in pixels 
>             };
>             oms = new OverlappingMarkerSpiderfier(this.state.map, options);
> 
>             markers = projects.map((p) => {
> 
>                 // ideally marker should be <ProjectMarker> instead of google.maps.Marker
>                 /*marker = (<ProjectMarker
>                     key={p._id}
>                     projectId={p._id}
>                     iconType={p.projectStage === stages.DONE ? "done" : "build"}
>                     lat={p.coordinate.lat}
>                     lng={p.coordinate.lng}
>                     title={p.summary}
>                     imageUrl={p.projectStage === stages.DONE ? p.showcaseImg[0] : p.workImg[0]}
>                 />);*/
>                 const marker = new google.maps.Marker({
>                     position: { lat: p.coordinate.lat, lng: p.coordinate.lng },
>                     map: this.state.map
>                 });
>                 oms.addMarker(marker);
> 
>                 const iw = new google.maps.InfoWindow();
>                 oms.addListener('click', function (marker, event) {
>                     iw.setContent(marker.desc);
>                     iw.open(this.state.map, marker);
>                 });
> 
> 
>                 console.log("before add marker", marker);
>                 oms.addMarker(marker);
>             });
> 
>             oms.addListener('spiderfy', function (markers) {
>                 iw.close();
>             });
>         }
>     }
> 
> 
>     return (
>         <div className={cx("google-map-canvas")} className={cx("google-map")} style={{ height: `calc(100vh - 50px)` }}>
>             {this.state.mounted > 0 && <GoogleMapReact
>                 bootstrapURLKeys={{ key: [googleMapApiKey] }}
>                 center={this.props.coord}
>                 zoom={this.props.zoom}
>                 options={createMapOptions}
>                 onGoogleApiLoaded={({ map, maps }) => this.initMap(map, maps)}
>                 onChange={this.mapOnChange}
>                 yesIWantToUseGoogleMapApiInternals
>             >
>                 {markers}
>             </GoogleMapReact>}
>         </div>
>     )
> }`
> ```

can you please provide full code ?

**Comment by itsmichaeldiego** [comment]
@huzaifa-ahmed I think you were trying to tag @makethisbuildthat
