### ISSUE TITLE
Uncaught TypeError: Cannot read property 'fromLatLngToDivPixel' of undefined

### ISSUE THREAD

**Issue by rbrahul** [google-map-react/google-map-react#628]
We are using `"google-map-react": "^1.0.4"` found that exception in production on Safari browser in Mobile. It is not reproducible locally.
```js
"Uncaught TypeError: Cannot read property 'fromLatLngToDivPixel' of undefined"
```

**Comment by itsmichaeldiego** [comment]
@rbrahul Latest version is `1.0.5`, could you verify this is still an issue in latest version? If its still an issue, please provide a live example and we'll take care of it, thanks in advance 😃

**Comment by rbrahul** [comment]
@itsmichaeldiego we have upgraded to 1.0.5 now. Since it's only happening in production , I am waiting for Raygun error log and let you know. Thank you 👍

**Comment by itsmichaeldiego** [comment]
@rbrahul Ok, please let me know when you've more info and we can re-open the issue. Closing it as for now.
