### ISSUE TITLE
ZoomControls after GoogleUpdate broken

### ISSUE THREAD

**Issue by ZeroCool-85** [google-map-react/google-map-react#629]
Hello, the google zoom controls are broken after the last update. Could it be possible to set  v=quarterly, v=3, v=3.33 or v=3.32 on API loading to fix this issue? 

https://issuetracker.google.com/issues/112520084

<img width="295" alt="bildschirmfoto 2018-08-14 um 10 02 32" src="https://user-images.githubusercontent.com/9364777/44079479-7a5e2024-9fa9-11e8-91eb-a9fea2046895.png">

**Comment by mporkola** [comment]
You can fix the version yourself by giving it as a value in the `bootstrapURLKeys` initialisation parameter, like this:

```
        bootstrapURLKeys={{
          ...
          v: '3.33',
        }}
```

**Comment by ZeroCool-85** [comment]
I know, but it has no effect. :/

**Comment by itsmichaeldiego** [comment]
@ZeroCool-85 Setting it to `3.32` as @mporkola described should fix the issue. 

But, the weird thing is that controls is working perfectly for me, check: https://jsbin.com/dufuzozapa/edit?html,js,console,output

**Comment by itsmichaeldiego** [comment]
@ZeroCool-85 I am closing this issue as I cannot see it being reproduced. Let me know if you need more help, I will be here to provide it.
