### ISSUE TITLE
Custom overlayview style attributes

### ISSUE THREAD

**Issue by jurgenzz** [google-map-react/google-map-react#632]
Would be great if it would be possible to add custom style properties to div or panes.

https://github.com/google-map-react/google-map-react/blob/master/src/google_map.js#L589

In my case I need to add `pointer-events: none` (an overlapping issue with custom tiles and an interesting way of rendering stuff in general).

Could that be possible? I can get there trough refs, but i would prefer an API.

**Comment by itsmichaeldiego** [comment]
@jurgenzz Yes! It should be an easy change and a great opportunity to collaborate to this library. Let me know if you need any help!
