### ISSUE TITLE
Prevent markers from teleporting when map is zoomed

### ISSUE THREAD

**Issue by experimatt** [google-map-react/google-map-react#636]
Since Google Maps version 3.32, rendered map markers have been "teleporting" when the map is zoomed. Some of the example maps linked in the README [have this problem](http://google-map-react.github.io/google-map-react/map/simple/), while others [do not](https://jsbin.com/ruwogapuke/1/edit?js,output). 

There may not actually be a code change necessary to fix this - updating the documentation so it's clear how to prevent this from happening would be an acceptable solution.

Live example from my project: https://omgtransit.com/#/map
Live example from this repo: http://google-map-react.github.io/google-map-react/map/simple/

**Repro steps:**
1. View map with markers
2. Zoom in or out

**Expected behavior:**
- Markers stay fixed at their coordinates on the map

**Actual behavior:**
- Markers "teleport" to their coordinates on the map (from top-left when zooming out, and bottom right when zooming in).

**Comment by experimatt** [comment]
I've been looking through this repo, and the Google Maps Javascript API docs, and haven't found a specific setting that would cause/prevent this from happening. What's interesting is that some example maps in this repo have this problem, while others do not.

* [jsbin](https://jsbin.com/ruwogapuke/1/edit?js,output) example map markers do not teleport.
* [simple](http://google-map-react.github.io/google-map-react/map/simple/), [option](http://google-map-react.github.io/google-map-react/map/options/), [simple_hover](http://google-map-react.github.io/google-map-react/map/simple_hover/),  [events](http://google-map-react.github.io/google-map-react/map/events/), [main](http://google-map-react.github.io/google-map-react/map/main/), [map-clustering](http://istarkov.github.io/google-map-clustering-example/), [thousand-markers](https://istarkov.github.io/google-map-thousands-markers/), example map markers all teleport

I haven't yet figured out why the jsbin example does not teleport while all the others do, but I'll keep looking into it to see if I can figure it out.

Also, I'd be happy to help either implement a solution in the code or update the docs to reflect how to prevent this, once we figure out the solution.

**Comment by itsmichaeldiego** [comment]
@experimatt The answer is easy, the examples that are "teleporting" are using an outdated version of google-map-react. please update your google-map-react library to latest version (currently `1.0.6`) and it will work, this has already been fixed in #510

**Comment by experimatt** [comment]
@itsmichaeldiego Oops, I really should have tried updating package before opening an issue. Thanks for fixing it, and for the quick response!

**Comment by itsmichaeldiego** [comment]
@experimatt No worries man! That happens

**Comment by itsmichaeldiego** [comment]
@experimatt Glad it worked! Let me know if you need help with anything. Thanks for choosing our library.

**Comment by Devon-Peroutky** [comment]
@itsmichaeldiego I'm currently getting the same issue, but I'm on `"google-map-react": "^1.1.4"`. Could this be related to an out-of-date dependency even if I'm on a new version?

**Comment by itsmichaeldiego** [comment]
@Devon-Peroutky Mm nope, maybe you've specified a version in your map? Otherwise try cleaning your yarn cache, something like `rm -rf node_modules/ && yarn cache clean && yarn`

**Comment by pawelotto** [comment]
> @experimatt Glad it worked! Let me know if you need help with anything. Thanks for choosing our library.

Using ver 1.1.4, deleted node_modules, cleaned up yarn cache, and my markers are still teleporting like crazy. Any ideas how to fix this?

**Comment by itsmichaeldiego** [comment]
@pawelotto I can confirm this is fixed, can you provide a live example? Otherwise I can't help
