### ISSUE TITLE
Billing is growing so hard

### ISSUE THREAD

**Issue by RanKey1496** [google-map-react/google-map-react#638]
Hi, recently I realized that Google was disabling my map cuz I didn't put a credit card on cloud platform.
I did it but after that the billing growth a LOT.
So I had to restrict my map API key to only javascript (Also restricted to URL) but i didn't work.

![image](https://user-images.githubusercontent.com/6834703/45056052-62bd0c00-b057-11e8-970c-b1e4f6d6fee8.png)

When I go to Billing tab on Google Console, I just realize there is a option that say Group by, so selecting group by SKU and it let me see what product is consuming my money.

![image](https://user-images.githubusercontent.com/6834703/45056459-951b3900-b058-11e8-86b8-338ec5ef8026.png)

The only thing I don't know is if the library is using Street View for some reason or if I need to disable some option for reach that.

This is my config object:
![image](https://user-images.githubusercontent.com/6834703/45056513-b67c2500-b058-11e8-8822-08e87612ef24.png)

I would appreciate very much if you guys can help me, thanks :)
Sorry for bad english, btw

**Comment by itsmichaeldiego** [comment]
@RanKey1496 Thanks for providing a proper description, we appreciate that.

Your problem is with Google Maps itself, you have to use a key that only uses what you want to use, in this case only map and not street view, but keep in mind that billing for Google Maps is not cheap. 

Regards
