### ISSUE TITLE
How to apply border-radius to the map?

### ISSUE THREAD

**Issue by drebits** [google-map-react/google-map-react#639]
I'm trying with a container with styles
```
<div style={{
      borderRadius: '4px',
      height: '500px',
      width: '720px'
    }}
    >
      <GoogleMapReact {...props} />
</div>
```
But this not work when appears the map.
Any idea? Thanks.

**Comment by itsmichaeldiego** [comment]
@drebits I need a live example in order to help you, but I think you might need to add `overflow: 'hidden'` and it will work.

If that does not help, feel free to re-open the issue when live example is provided.
