### ISSUE TITLE
wrong marker position

### ISSUE THREAD

**Issue by alieslamifard** [google-map-react/google-map-react#648]
i find a point in map.google.com and set it in marker. what i get was far from my real point.
i see some closed issue about wrong calculation, but isn't it done yet?

**Comment by itsmichaeldiego** [comment]
@alieslamifard Please provide a live example in order for me to help you, for me they work perfectly so I need to see what you are doing.

Feel free to re-open the issue when providing a live example, and please add more description if possible.

**Comment by alieslamifard** [comment]
actually this is my mistake. cause i get lat,lng from "what's here" in google map, and it give me place location, not that exact point.
Thank you kindly @itsmichaeldiego

**Comment by itsmichaeldiego** [comment]
@alieslamifard No problem man! Let me know if you need further help, I will be here
