### ISSUE TITLE
LatLng object with strings raises invalid props error 

### ISSUE THREAD

**Issue by julian-rachmann** [google-map-react/google-map-react#649]
I know this is a simple enough issue to avoid before calling the component, but ideally a user should be able to pass either a string or a number into a latlng object and it should be converted as needed. 

Alternatively, the error thrown should be more clear as to what the problem is.

Steps to reproduce:

```
<div className="google-map" style={{ height: '100vh', width: '100%' }}>
    <GoogleMapReact
     bootstrapURLKeys={{ key: '' }}
     center={{lat: "-30.5595", lng: "22.9375"}}
     zoom={this.props.zoom}
    />
</div>
```
Throws error: `Failed prop type: Invalid prop 'center' supplied to 'GoogleMap'.`

But this works:

```
<div className="google-map" style={{ height: '100vh', width: '100%' }}>
    <GoogleMapReact
     bootstrapURLKeys={{ key: '' }}
     center={{lat: -30.5595, lng: 22.9375}}
     zoom={this.props.zoom}
    />
</div>
```

**Comment by itsmichaeldiego** [comment]
@julian-rachmann I have to say I disagree, lat and long are numbers and therefore we should threat them as numbers. 

The error provided is the default error thrown by React, although I agree we could make it more descriptive, its pretty obvious and there is an example showing how center should be passed. 

Therefore, I am closing this issue as its not an issue and does not prevent the lib from working, but I will keep it in mind when I work on some other error messages.

Thanks
