### ISSUE TITLE
React error #170

### ISSUE THREAD

**Issue by kbalus** [google-map-react/google-map-react#650]
I've no idea about this error occured in all version prod and develop
Whats is wrong ?
Official React page says "Expected subtree parent to be a mounted class component. This error is likely caused by a bug in React. Please file an issue."

react 16.4.2
google-map-react "^1.0.8"

![image](https://user-images.githubusercontent.com/7715744/46191152-b210f800-c2f6-11e8-9103-8dbbf826a036.png)

Many thanks!

**Comment by itsmichaeldiego** [comment]
@kbalus I would love to help you but its very hard like this as I don't see your environment. Please add a live example from https://codesandbox.io or similar platform, and I will be happy to help you.

Please re-open the issue when doing so.

Thanks

**Comment by phillipj** [comment]
I just noticed that the `onGoogleApiLoaded` prop will be called with `null` as argument values in the case of errors: 

```js
this.props
  .googleMapLoader(bootstrapURLKeys, this.props.heatmapLibrary)
  .then( .. )
  .catch(e => {
    // notify callback of load failure
    this._onGoogleApiLoaded({ map: null, maps: null });
    console.error(e); // eslint-disable-line no-console
    throw e;
  });
```
[./src/google_map.js#L782](https://github.com/google-map-react/google-map-react/blob/d8d9dc3b63784e6a4ea2e6a7e629cd606c5985a5/src/google_map.js#L782)

That's not something I've encountered for. I'll put some safe guards in place to see if that makes any different to the errors I'm seeing.

**Comment by itsmichaeldiego** [comment]
@phillipj Awesome let me know what you find
