### ISSUE TITLE
reposition the OverlayView after changing content

### ISSUE THREAD

**Issue by adi-gabrielli** [google-map-react/google-map-react#652]
Hi,

I'm using the OverlayView to create custom markers which when clicked change to a small window which contains some details about the marker, when I click outside of this new window, it closes and shows the marker.
The problem is that the size of the second 'view' is bigger than the initial marker, so when it opens, the actual coordinates it points to are not correct since it uses the top-left position of the initial view.

How can I re-setup the x,y of the new window? Or at least register a listener for something after the new view gets loaded, where I can reposition the view?

**Comment by adi-gabrielli** [comment]
yeah...seems I have been doing it wrong. I was trying to create an OverlayView which contained the pin image and the details image for each location.
It seems the 'natural way' is to have one overlay which gets shown at the propper location for each marker click. And have the markers as actual markers. (at least in my case...)

**Comment by itsmichaeldiego** [comment]
@adi-gabrielli I am glad you could work it out, let me know if you need further help.
