### ISSUE TITLE
Old examples with new version google-map-react

### ISSUE THREAD

**Issue by J1Duran** [google-map-react/google-map-react#653]
Good, I hope you are well.
I have a que.stion, I want to implement this old example, with the new version and I can not find

**old example: https://github.com/google-map-react/old-examples/blob/master/web/flux/components/examples/x_main/main_map_block.jsx**

Since I've been doing tests with respect to the new version and the old examples, and they change several things.

So my question is, do I try to implement the old example with the new version, or is there an example?

thank you very much

**Comment by itsmichaeldiego** [comment]
@J1Duran We're working on examples in here https://github.com/google-map-react/google-map-react-examples/ but I've been really slow with it and I haven't received any help yet.

So if you want to start building this example on the new example repo, it would be amazing. Not many things have changed really, you could still make it work with a few twicks. 

Let me know if you need help and I will help you out.

**Comment by J1Duran** [comment]
Hello friend, happy to help.
I really had a lot of trouble adapting the example with the hover, because of the controllable theme. Adapt a version and I had to use the library "rc-tooltip" to adapt the information I wanted to show from each point on the map.
![image](https://user-images.githubusercontent.com/13131609/46626102-4ef84000-cb04-11e8-8bc6-fcdb21e08644.png)

**Comment by itsmichaeldiego** [comment]
@J1Duran That is great man, thank you so much. How do you feel about moving this example to our https://github.com/google-map-react/google-map-react-examples repo?

**Comment by J1Duran** [comment]
@itsmichaeldiego Ok I have no problems friend, delighted .. let me know the procedure.

**Comment by itsmichaeldiego** [comment]
@J1Duran Is pretty simple just clone https://github.com/google-map-react/google-map-react-examples and add one route and the example you created in one component.

**Comment by umarfarookshaik** [comment]
@J1Duran could you please move/commit your example to above repo, your code would save my time :)

**Comment by itsmichaeldiego** [comment]
@J1Duran +1 with @umarfarookshaik comment! Would be super nice, thanks

**Comment by itsmichaeldiego** [comment]
@J1Duran Looking forward to help you to add this example on [google-map-react-examples](https://github.com/google-map-react/google-map-react-examples)

**Comment by hockjootan** [comment]
@J1Duran Thank you for your package recommendation, after some struggle I managed to work it somehow. Handle on click / hover on marker With using latest react hooks along
<img width="995" alt="Screenshot 2020-11-12 at 3 31 40 PM" src="https://user-images.githubusercontent.com/30404522/98909431-c75c3700-24fc-11eb-9838-2484bf8a77e5.png">
