### ISSUE TITLE
fitBounds method from utils does not return zoom

### ISSUE THREAD

**Issue by maxchernin** [google-map-react/google-map-react#654]
Hello, using versions:
Windows 10,
google-map-react 1.0.9

when using the fitBounds method, im getting the new bounds and the center, but im getting NaN on the zoom property
the problem lies in line 113
 var zoomY = (0, _log2.default)(height / GOOGLE_TILE_SIZE / dy); <-- compiled
const zoomY = log2(height / GOOGLE_TILE_SIZE / dy); <-- source code

this returns NaN, **when dy is negative**.

**Comment by maxchernin** [comment]
also help will be appriciated on the pr ive opened

**Comment by itsmichaeldiego** [comment]
@maxcherning Would you provide me a live example where this is failing?

**Comment by itsmichaeldiego** [comment]
Fix from #655, was merged and deployed in version `1.1.0`
