### ISSUE TITLE
Clicks on subcomponents of markers get handled by Map before the subcomponent

### ISSUE THREAD

**Issue by evanseeds** [google-map-react/google-map-react#657]
I'm using this library to display markers on a map, which conditionally display a popup window with more information. I'd like to implement a click listener on the map itself so that when a user clicks outside of a popup, the popup can be closed. However, the map click listener triggers on click of the popup as well, even if stopping propagation or preventing default behavior. 

I commented with more details of my project at on the issue at https://github.com/google-map-react/google-map-react/issues/508, but wanted to create a new issue because I thought the description given was inexact. The event does not "bubble down" to the map but in fact gets handled before said events.

I've created a simple jsfiddle that shows this behavior at https://jsfiddle.net/seedsseedsseeds/d1o6vs5x/. Even with the `ev.preventDefault` and `ev.stopPropagation` calls in the popup click listener, the `closePopup` method is called before the click listener on the div with class `popup`. If you change the click listeners to console.logs you can see this happening directly.

Thank you

**Comment by shubh911** [comment]
+1

**Comment by Multi-Thinker** [comment]
+1 looking for same solution

**Comment by itsmichaeldiego** [comment]
@shubh911 @Multi-Thinker I think @evanseeds found a solution [here](https://github.com/google-map-react/google-map-react/issues/508#issuecomment-541784294), right?

**Comment by evanseeds** [comment]
@itsmichaeldiego yes, that solution has solved this issue for me
