### ISSUE TITLE
Markers are not visible when printing cluster map

### ISSUE THREAD

**Issue by klingberg** [google-map-react/google-map-react#658]
When I try to print a cluster map (e.g http://istarkov.github.io/google-map-clustering-example/) the markers appears as white squares.

![screenshot from 2018-10-16 12-38-27](https://user-images.githubusercontent.com/1440293/47011853-2fd06280-d143-11e8-82ba-2b89a5d71e70.png)

Not a major issue but if anyone has any idea why this happens I am all ears.

**Comment by itsmichaeldiego** [comment]
@klingberg Is this printing using google map print option or just screen print?

**Comment by klingberg** [comment]
This is just screen print.

**Comment by itsmichaeldiego** [comment]
@klingberg I am not sure I am following, you've got a map with a cluster, you take a screenshot and they look like squares? 🤔

**Comment by klingberg** [comment]
@itsmichaeldiego No, sorry for my poor description :)

Navigate to http://istarkov.github.io/google-map-clustering-example/
Choose print (as in print on paper).
In the preview and on paper the markers will appear as white squares.

**Comment by itsmichaeldiego** [comment]
@klingberg This is an old example, we're currently working on new ones in https://github.com/google-map-react/google-map-react-examples. You can find more [info here](https://github.com/google-map-react/google-map-react/issues/653) and [here](https://github.com/google-map-react/google-map-react/issues/524)
