### ISSUE TITLE
How to load maps in http instead of https

### ISSUE THREAD

**Issue by prp1** [google-map-react/google-map-react#659]
For some specific reason I need to load google maps in http, not https. I checked in code and there is no possibility exposed to change this. It's just defined like this:

`const BASE_URL = 'https://maps';`

Of course, I could load google maps manually myself and only then render google-map-react component, but then I would loose this nice feature of having markers already visible while google maps are still loading.

Any ideas how could I achieve what I need without introducing any new props to this library?

**Comment by itsmichaeldiego** [comment]
@prp1 Its actually not possible, we would have to pass new props or pass `BASE_URL` that overrides the actual `BASE_URL` if its defined, it would be an easy change, if you want to submit a PR I will review it and publish it in a new minor version

**Comment by prp1** [comment]
Ok, I will create a PR, thanks.
