### ISSUE TITLE
Uncaught TypeError: (0 , _.y) is not a function

### ISSUE THREAD

**Issue by cky-BryanChan** [google-map-react/google-map-react#662]
Is that google is giving us hard time? it was working for months and suddenly this pops up when you zoom in / out

![image](https://user-images.githubusercontent.com/22461288/47294181-4f9bd680-d5da-11e8-9e7c-0620d3cff01c.png)

![image](https://user-images.githubusercontent.com/22461288/47313965-4cbad900-d60e-11e8-9f4c-e6f80b1fafc2.png)

**Comment by itsmichaeldiego** [comment]
@cky-BryanChan Could you fix the problem?

**Comment by cky-BryanChan** [comment]
@itsmichaeldiego it's probably a google api's problem, it happens a few days and it's gone now. Thanks for replying

**Comment by itsmichaeldiego** [comment]
@cky-BryanChan No worries, let me know if you need further help.
