### ISSUE TITLE
How to change the default marker for the direction？

### ISSUE THREAD

**Issue by FrameLee** [google-map-react/google-map-react#665]
![image](https://user-images.githubusercontent.com/34339642/47488408-e5ec2880-d876-11e8-82ce-d4c58e257d68.png)

Sorry my english is pool. In this direction, origin is marker A destination is marker B. But I don't want use marker A and marker B, I want use other marker instead them. What should I do?

**Comment by itsmichaeldiego** [comment]
@FrameLee I am sorry but we currently don't support that, as the directions is a built-in solution of google maps. Probably you can check if there is a way to hide the dots for native google maps, if there is a way to do that you can also do that with this library.
