### ISSUE TITLE
onChildTouchDown equivalents?

### ISSUE THREAD

**Issue by timothyallan** [google-map-react/google-map-react#666]
Hey there, I've been sifting through the old issues, and the code and can't find a solid answer: Why is there no API for Touch events like an onChildTouchDown/Move/Up? I've got the movable markers working great on desktop, but mobile is a no go currently.

Is there some workaround I've missed somewhere to handle touch events for movable markers?

**Comment by itsmichaeldiego** [comment]
@timothyallan There is no touch events for this particular ones, this library has been built from user's requirements, so you can feel free to add this events and I will be happy to deploy a minor release.

Let me know if you need any help and I will be happy to provide it
