### ISSUE TITLE
markers appear above the gestureHandling overlay

### ISSUE THREAD

**Issue by drstonebraker** [google-map-react/google-map-react#667]
In certain circumstances, the map shows (by default) an overlay for gestureHandling to notify user of how to manipulate the map.  For example, if the map is embedded in a scrollable page, and you scroll past the map with the cursor over the map, it will display a message stating that user can press CMD + Scroll to zoom the map.

Problem is that the place markers appear above this message, when they ought to appear behind.

**Comment by itsmichaeldiego** [comment]
@drstonebraker Please provide a live example of the error and reopen the issue, I will be happy to help, thanks in advance.
