### ISSUE TITLE
Heat map won't load despite the props being present

### ISSUE THREAD

**Issue by saahilp** [google-map-react/google-map-react#668]
I'm trying to load the heatmap on the Google Map and I've verified that all the props are what they're suppsoed to be. Any idea what I might be missing?

![image](https://user-images.githubusercontent.com/15962647/47809846-3a305600-dd18-11e8-8def-a75dd2cd8b9d.png)

**Comment by itsmichaeldiego** [comment]
@saahilp Heatmap is working on my end, please provide a live-example and I will try to help you.
