### ISSUE TITLE
[Violation] Added non-passive event listener to a scroll-blocking 'touchstart' event.

### ISSUE THREAD

**Issue by FadiAboMsalam** [google-map-react/google-map-react#669]
Hi I have the following warning on console once i add the library

_[Violation] Added non-passive event listener to a scroll-blocking 'touchstart' event. Consider marking event handler as 'passive' to make the page more responsive_

am using the following version     **"google-map-react": "^1.0.9"**
here is my code inside my render

```
     <GoogleMapReact
          bootstrapURLKeys={{
            libraries: "drawing",
            language: process.env.REACT_APP_MAP_LANGUAGE,
            region: process.env.REACT_APP_MAP_REGION,
            key: process.env.REACT_APP_GOOGLE_MAPS_KEY
          }}
          defaultCenter={center}
          defaultZoom={zoom}
        />
```

```
  state = {
    center: {
      lat: 52.370216,
      lng: 4.895168
    },
    zoom: 7
}
```

**Comment by itsmichaeldiego** [comment]
@FadiAboMsalam please provide a live example, thanks
