### ISSUE TITLE
Change radius of circle

### ISSUE THREAD

**Issue by stacheski** [google-map-react/google-map-react#670]
I created a circle using google api, and binded it to the center of my marker, to be able to change the circle position like this:
    
                     onGoogleApiLoaded={({ map, maps }) => {

                      let marker = new window.google.maps.Marker({
                        position:center,
                        map: map,
                        title: 'Center of Map',
                        draggable: true
                      });

                      let circle = new window.google.maps.Circle({
                        strokeColor: '#FF0000',
                        strokeOpacity: 0.8,
                        strokeWeight: 2,
                        fillColor: '#FF0000',
                        fillOpacity: 0.3,
                        map,
                        center:latLng,
                        radius: radius * 1000,
                      });

                      circle.bindTo('center', marker, 'position');

                      let self = this;

                      window.google.maps.event.addListener(marker, "drag", function () {
                        circle.radius = self.state.radius * 1000;
                      });
                    }}
`
There's a way to change the radius of the circle using an input field that is outside the google map component? And then force the map to update after changing the radius?

Thank you in advance!

**Comment by itsmichaeldiego** [comment]
@stacheski Please provide a live example, otherwise its very hard to help. But in case it helps, whatever you can do with google maps itself, you can do it with this library by accessing `onGoogleApiLoaded` like you just did. So I guess yours is more a question for stackoverflow than a question about the library itself if I am not mistaken, if I am please let me know.
