### ISSUE TITLE
Custom Overlay with tiles from a Tile Server

### ISSUE THREAD

**Issue by ftier-tech** [google-map-react/google-map-react#672]
How would one go about creating a custom overlay with Tiles being fetched from a 3rd party Tile Server.  I have the array of Tiles from the 3rd party, but now I need to create my overlay with those tiles.  Are there any examples out there that I could reference?

Thanks!

**Comment by itsmichaeldiego** [comment]
@ftier-tech Anything that you can do in gmaps, you can do here. Please take a look at https://github.com/google-map-react/google-map-react/blob/master/API.md for more information on which tiles functions are available and how to get the `map` or `maps` object from `onGoogleMapAPILoaded` attr.
