### ISSUE TITLE
Rendering markers in IE11

### ISSUE THREAD

**Issue by alastairkitchen** [google-map-react/google-map-react#674]
Hey, I'm having issues rendering markers on the map in IE11, I get the following error:

"Cannot define property '$jscomp_hidden_0.3239633210234527': object is not extensible"

which seems to be linked to the GoogleMapMarkers component. The map is being added to the page but the markers aren't visible on the map. Any help would be massively appreciated.

![image](https://user-images.githubusercontent.com/5919195/48420305-001c7680-e752-11e8-9279-d3ad98d65aa2.png)

**Comment by itsmichaeldiego** [comment]
@alastairkitchen We currently don't support IE, and I don't have a way to test it, but PRS are welcome!

**Comment by itsmichaeldiego** [comment]
@alastairkitchen We've made some updates that might've fixed it, let me know if so.
