### ISSUE TITLE
Cannot remove Polylines from GoogleMap

### ISSUE THREAD

**Issue by klferreira** [google-map-react/google-map-react#675]
Straight to the point:

I think I found a bug when I try to remove Polylines from my map.

There are certain events in my application that changes the currently rendered markers to new ones and draws a Polyline between them.

When i "undo" this action, I want to remove the current markers and re-render the previous ones. That works just fine.

The problem is: The polyline between the previous markers stays on the map. I've tried polyline.setMap(null) (also forcing react to update my parent component), but the line is not removed.

Here is the code for the Polyline component:

```
class Polyline extends Component {

  renderPolylines() {
    const { markers, map, maps, geodesic, strokeColor } = this.props;
    
    let polyline = new maps.Polyline({
      path: markers,
      geodesic,
      strokeColor,
      strokeOpacity: 1,
      strokeWeight: 2
    });

    polyline.setMap(map);
  }

  componentWillUnmount() {
    this.state.polyline.setMap();
  }

  render() {
    this.renderPolylines();
    return null;
  }
}
```

If you need more information, please ask.

**Comment by grzeczko** [comment]
Use `static` when removing Polylines, like so:

` export default class Polyline extends Component {
  static line = [];

  renderPolylines () {
    const { id, markers, map, maps } = this.props

    if (Polyline.line[id]) {Polyline.line[id].setMap(null);}
    let line = new maps.Polyline({
      path: markers,
      geodesic: true,
      strokeColor: '#00a1e1',
      strokeOpacity: 1.0,
      strokeWeight: 4
    })
    Polyline.line[id] = line;
    Polyline.line[id].setMap(map) `

**Comment by crac7** [comment]
What was your solution @klferreira ?

**Comment by DieterVanmoortel** [comment]
You can use state to show and hide polylines like so

```
<Map google={this.props.google}
   zoom={this.state.zoom}
   minZoom={7}
   maxZoom={16}
   initialCenter={this.state.center}
  >
        {this.state.library.map((item) =>{
            return(
		 item.props.active && <Polyline
			 key={item.props.id}
			 path={item.props.path}
			 strokeColor="#0000FF" />
              )
	})}
</Map>
```

**Comment by SalmanKarim42** [comment]
> You can use state to show and hide polylines like so
> 
> ```
> <Map google={this.props.google}
>    zoom={this.state.zoom}
>    minZoom={7}
>    maxZoom={16}
>    initialCenter={this.state.center}
>   >
>         {this.state.library.map((item) =>{
>             return(
> 		 item.props.active && <Polyline
> 			 key={item.props.id}
> 			 path={item.props.path}
> 			 strokeColor="#0000FF" />
>               )
> 	})}
> </Map>
> ```


not working
