### ISSUE TITLE
Feature request - Pan map to contain a component

### ISSUE THREAD

**Issue by vitalybe** [google-map-react/google-map-react#682]
When the user interacts with library, sometimes the components would grow (e.g an info component appearing on click) and it would be really nice if the map would pan to contain the element.

Obviously, this isn't needed in all cases, but I thought it can be done with a property, something like:

    <GoogleMapReact>
        <MyComponent lat={123} lng={123} containByPanning={true} />
    <GoogleMapReact>

P.S Thank you for the a really nice, simple library with such a readable code. It was a joy to integrate it into our project.

**Comment by vertic4l** [comment]
@vitalybe you can do this by yourself. All you need is to code it :)

See: https://github.com/google-map-react/google-map-react/issues/753

But instead of using fitBounds you could also use google maps own panTo method.

**Comment by itsmichaeldiego** [comment]
Thanks @vertic4l, indeed that's the way.
