### ISSUE TITLE
map doesn't show

### ISSUE THREAD

**Issue by golestanirad** [google-map-react/google-map-react#683]
on the map it says: 
_This page can't load Google Maps correctly.
Do you own this website?_

**Comment by lohfu** [comment]
Since 2016 you have to provide an API key

+ https://cloud.google.com/blog/products/maps-platform/building-for-scale-updates-to-google
+ https://churchthemes.com/page-didnt-load-google-maps-correctly/

**Comment by itsmichaeldiego** [comment]
@golestanirad Question is answered, there is a working example here:

URL: https://google-map-react.github.io/google-map-react-examples/default
Source: https://github.com/google-map-react/google-map-react/

**Comment by itsmichaeldiego** [comment]
@golestanirad Unless you provide a live-example I won't be able to help you
