### ISSUE TITLE
v1.1.1 published without dist directory

### ISSUE THREAD

**Issue by lohfu** [google-map-react/google-map-react#684]
It appears the latest version (1.1.1) has been published without a `dist` directory, but the `./index.js` still requires './dist/index`.

**Comment by itsmichaeldiego** [comment]
@lohfu It works perfectly on my end, please provide a non-working example 😃

**Comment by lohfu** [comment]
well my bad, i had installed `google-maps-react@1.1.1`

**Comment by itsmichaeldiego** [comment]
@lohfu Does it work now?

**Comment by lohfu** [comment]
@itsmichaeldiego yes, when i installed your module instead of the other one it worked like a charm :stuck_out_tongue:

**Comment by itsmichaeldiego** [comment]
@lohfu Awesome!
