### ISSUE TITLE
Push react component as control

### ISSUE THREAD

**Issue by ftier-tech** [google-map-react/google-map-react#687]
I do apologize as this isn't an issue, but more of a "how-to".  I've looked around online to see if I could find the answer, but no luck.  It is possible to use a React Component as a Google Map Control?  I am using the ability to get access to the internal API, but would like to use a custom React Component instead of adding the control as in the Google example show in their example (https://developers.google.com/maps/documentation/javascript/examples/control-custom).  Any guidance would be much welcomed and certainly appreciated.

**Comment by itsmichaeldiego** [comment]
@ftier-tech You could use a ref and use your own component, but you would have to place it using css

**Comment by Pocket-titan** [comment]
You can create a custom MapControl component that accomplishes this:

```javascript
import React, { Component } from 'react'
import PropTypes from 'prop-types'
import { render } from 'react-dom'

class MapControl extends Component {
  static propTypes = {
    controlPosition: PropTypes.number,
  }

  shouldComponentUpdate(nextProps, nextState) {
    return !this.props.map && nextProps.map
  }

  componentDidMount() {
    this._render()
  }

  componentDidUpdate(prevProps, prevState) {
    this._render()
  }

  componentWillUnmount() {
		const { props } = this
    if (!props.map) return
		const index = props.map.controls[props.controlPosition].getArray().indexOf(this.el)
		props.map.controls[props.controlPosition].removeAt(index)
	}

  _render() {
    const { props } = this
    if (!props.map || !props.controlPosition) return
    render(
      <div ref={el => {
        if (!this.renderedOnce) {
          this.el = el
          props.map.controls[props.controlPosition].push(el)
        } else if (el && this.el && el !== this.el) {
          this.el.innerHTML = '';
          [].slice.call(el.childNodes).forEach(child => this.el.appendChild(child))
        }
        this.renderedOnce = true
      }}>
        {props.children}
      </div>,
      document.createElement('div')
    )
  }

  render() {
    return <noscript/>
  }
}

export default MapControl
```

Which you would then use like this in your MapComponent:
```javascript
class MapComponent extends Component {
  ...
  render() {
    return (
      <GoogleMap
        // the usual stuff: style, your apiKey
        onGoogleApiLoaded={({map, maps}) => {
          this.map = map
          this.maps = maps
          // we need this setState to force the first mapcontrol render
          this.setState({mapControlShouldRender: true})
        }}
        yesIWantToUseGoogleMapApiInternals
      >
        <MapControl map={this.map || null}
          controlPosition={this.maps ? this.maps.ControlPosition.TOP_LEFT : null}
        >
          <YourSuperCoolControlButton />
        </MapControl>
      </GoogleMap>
    )
  }
}
```
You can find all the possible values for ControlPosition [here](https://developers.google.com/maps/documentation/javascript/reference/control#ControlPosition). If you need any help, feel free to tag me.

**Comment by iki202** [comment]
Way to go Pocket-titan. Thank you!

**Comment by mdvorscak** [comment]
Thanks @Pocket-titan, I've recently had to use this solution on a newer react project (using hooks) and implemented it using hooks like this:

```ts
import React, { useEffect } from "react";
import { render } from "react-dom";

export const useMapControl = (
  map: google.maps.Map | null,
  controlPosition: google.maps.ControlPosition | null,
  children: React.ReactElement
) => {
  useEffect(() => {
    if (map && controlPosition) {
      render(
        <div ref={el => map.controls[controlPosition].push(el as HTMLElement)}>
          {children}
        </div>,
        document.createElement("div")
      );
    }
    return () => {
      if (map && controlPosition) {
        map.controls[controlPosition].clear();
      }
    };
  }, [map, controlPosition]);
};

// And then in the map component:
const [map, setMap] = useState<google.maps.Map | null>(null);
const [position, setPosition] = useState(google.maps.ControlPosition.BOTTOM_CENTER);
useMapControl(
    map,
    position,
    <Legend />
  );
```

Hopefully this helps some future person coming here from google (as I did).

**Comment by jackluo** [comment]
where is your google coming from?

**Comment by zamlahani** [comment]
Simpler solution provided by someone in an issue of another library, what do you think?

```
import React from 'react';
import ReactDOM from 'react-dom';

import CustomControl from './CustomControl/'; // my custom control, it can be a <button /> or whatever

const handleOnLoad = (map,maps) => {
  const controlButtonDiv = document.createElement('div');
  ReactDOM.render(<CustomControl onClick={() => console.log('hi')} />, controlButtonDiv);
  map.controls[maps.ControlPosition.TOP_RIGHT].push(controlButtonDiv);
};

<GoogleMapReact 
          yesIWantToUseGoogleMapApiInternals
          onGoogleApiLoaded={({ map, maps }) => handleOnLoad(map, maps)} />
```

**Comment by mageshkumar1598** [comment]
> Simpler solution provided by someone in an issue of another library, what do you think?
> 
> ```
> import React from 'react';
> import ReactDOM from 'react-dom';
> 
> import CustomControl from './CustomControl/'; // my custom control, it can be a <button /> or whatever
> 
> const handleOnLoad = (map,maps) => {
>   const controlButtonDiv = document.createElement('div');
>   ReactDOM.render(<CustomControl onClick={() => console.log('hi')} />, controlButtonDiv);
>   map.controls[maps.ControlPosition.TOP_RIGHT].push(controlButtonDiv);
> };
> 
> <GoogleMapReact 
>           yesIWantToUseGoogleMapApiInternals
>           onGoogleApiLoaded={({ map, maps }) => handleOnLoad(map, maps)} />
> ```

@zamlahani I have a doubt! How we will pass the state from the parent and use it inside the CustomControl component? Does it get reflected when ever the state changes?

**Comment by mageshkumar1598** [comment]
@zamlahani Can you please help me on this?

**Comment by zamlahani** [comment]
> magesh

Hi! the project was from 2 years ago, so I forgot

**Comment by LongTranDuy** [comment]
> Thanks @Pocket-titan, I've recently had to use this solution on a newer react project (using hooks) and implemented it using hooks like this:
> 
> ```ts
> import React, { useEffect } from "react";
> import { render } from "react-dom";
> 
> export const useMapControl = (
>   map: google.maps.Map | null,
>   controlPosition: google.maps.ControlPosition | null,
>   children: React.ReactElement
> ) => {
>   useEffect(() => {
>     if (map && controlPosition) {
>       render(
>         <div ref={el => map.controls[controlPosition].push(el as HTMLElement)}>
>           {children}
>         </div>,
>         document.createElement("div")
>       );
>     }
>     return () => {
>       if (map && controlPosition) {
>         map.controls[controlPosition].clear();
>       }
>     };
>   }, [map, controlPosition]);
> };
> 
> // And then in the map component:
> const [map, setMap] = useState<google.maps.Map | null>(null);
> const [position, setPosition] = useState(google.maps.ControlPosition.BOTTOM_CENTER);
> useMapControl(
>     map,
>     position,
>     <Legend />
>   );
> ```
> 
> Hopefully this helps some future person coming here from google (as I did).

That's very cool, but I am dealing with incase if `children` is a button then it's onClick event doesn't get fired. Do you know why?

**Comment by vladgardus** [comment]
@LongTranDuy I am having the same issue. Did you figure out a solution?
