### ISSUE TITLE
Pan doest not work on Firefox

### ISSUE THREAD

**Issue by MatBdry** [google-map-react/google-map-react#691]
Hi !

I got an error on firefox since the version 1.1.1. The pan return an error and the map crash:

![capture d ecran 2018-12-07 a 09 26 36](https://user-images.githubusercontent.com/15127641/49636516-1e992900-fa03-11e8-86e7-d1e5f2c7562e.png)

I fixed the version to 1.1.0, and all is ok.

**Comment by itsmichaeldiego** [comment]
@MatBdry Might have been a runtime error? `1.1.1` works for me at the moment, could you re-check?

**Comment by MatBdry** [comment]
It works now... But I used the option "yesIWantToUseGoogleMapApiInternals" which is not recommended ! Since I removed it, it seems to work correctly. Thanks for your work :)
