### ISSUE TITLE
google-map-loader getting called twice

### ISSUE THREAD

**Issue by vivex** [google-map-react/google-map-react#692]
Package versions are:
```
"google-map-react": "^1.0.0",
"prop-types": "^15.6.1",
"react": "^16.2.0",
"react-dom": "^16.2.0",
"react-scripts": "1.1.1",

```

i am getting following error: 

```
google_map_loader.js:58 Uncaught (in promise) Error: google map initialization error
    at eval (VM11547 google_map_loader.js:58)
```

**Comment by itsmichaeldiego** [comment]
@vivex Please try with latest version of `google-map-react` and tell me:

```
npm remove google-map-react
npm install google-map-react
```

**Comment by vivex** [comment]
@itsmichaeldiego  same problem with  google-map-react 1.1.1 also.

**Comment by itsmichaeldiego** [comment]
@viktorbezdek If you give me more info about what is the actual error I may be able to help

**Comment by itsmichaeldiego** [comment]
@viktorbezdek Did you try 

```
rm -rf node-modules/
rm -rf yarn.lock
yarn cache clean;
yarn;
```

**Comment by vivex** [comment]
![image](https://user-images.githubusercontent.com/5036512/49782679-34795780-fd3d-11e8-80b9-f3ce2101fdf9.png)

@itsmichaeldiego  getting above error

**Comment by vivex** [comment]
What i observed after putting several console logs in google_map_loader that:

it is trying to insert <script> tag twice for google map, because google_map_loader is getting called twice before even setting `window.google.maps` 

@itsmichaeldiego

**Comment by cstumph** [comment]
Experiencing a similar issue trying with a page where we use this component, but also a suto suggest component that uses the maps API. Is there no way to pass a shared instance into this?

**Comment by bensonodede** [comment]
Solution here: https://github.com/wellyshen/use-places-autocomplete/issues/107#issuecomment-683162018
