### ISSUE TITLE
Custom markers connected with redux are giving error

### ISSUE THREAD

**Issue by egeucak** [google-map-react/google-map-react#693]
Hello,

I have a custom react component, that is like;

```javascript
class PoiMarker extends Component {
    render() {
        return (
            <div>
                
            </div>
        );
    }
}

export default connect(
    mapStateToProps,
)(PoiMarker);
```
The problem is when I use this as a marker, giving it as a child prop, I get the following error in console, and marker is not showing up.
```
Uncaught Error: Could not find "store" in the context of "Connect(PoiMarker)". Either wrap the root component in a <Provider>, or pass a custom React context provider to <Provider> and the corresponding React context consumer to Connect(PoiMarker) in connect options.
```
I also checked my component to see if it is the root of the problem, but when I insert it in somewhere else other than map, it works fine. So I suppose this is a problem caused by the way library deals with google maps markers.

Also when I delete the connect part, and export the component by itself, it works fine again (But I want redux, because I don't want to spent time trying to pass props).

And I don't know if this is relevant, but this is how my reduxstore component looks like;
```javascript
const store = createStore(
    allReducers,
    composeWithDevTools(
        applyMiddleware(thunk, promise),
));

export default class ReduxStore extends React.Component {
    render() {
        return(
            <Provider store={store}>
                <App />
            </Provider>
        )
    }
}
```
Thanks in advance

**Comment by itsmichaeldiego** [comment]
@egeucak Can you provide a live example like in https://codesandbox.io/?

**Comment by egeucak** [comment]
Thanks for quick reply.

I reproduced my situation with minimal example, while keeping the same structure in the following sandbox. You can see the expected behavior if you comment out the "connect" part, and export the class itself.

[![Edit 4wnl0w3p87](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/4wnl0w3p87?module=%2Fsrc%2FMap%2FPoi%2Findex.js)

> @egeucak Can you provide a live example like in https://codesandbox.io/? Would be happy to help

**Comment by itsmichaeldiego** [comment]
@egeucak I see the problem:

You're trying to connect the Marker itself, but the component rendered should be a pure component. You're already connecting the map you just need to pass what you need in the props of the Marker.
