### ISSUE TITLE
fitBounds will fail if only one location

### ISSUE THREAD

**Issue by wende60** [google-map-react/google-map-react#694]
hi,

the util fitBounds works fine. However, my location list in some cases contains only one location. Calculating bounds will result in something like:

```
    const nw = { lat: 39.82017517089844, lng: -104.6876449584961 };
    const se = { lat: 39.82017517089844, lng: -104.6876449584961 };
```

nw and sw will be the same. Now calculating center and zoom like so:

```
        const { center, zoom } = fitBounds({
            se: { lat: se.lat, lng: se.lng },
            nw: { lat: nw.lat, lng: nw.lng }
        }, { width: mapWidth, height: mapHeight });
```

will endup somewhere in Russia. Now a little change like here:

```
    const nw = { lat: 39.92017517089844, lng: -104.7876449584961 };
    const se = { lat: 39.82017517089844, lng: -104.6876449584961 };
```

will fix that problem. Maybe i am wrong, but my expected behaviour would be to have a box around the given coordinates, even if they are the same...

regards, jo

**Comment by itsmichaeldiego** [comment]
@wende60 But when you have only one point, that point should be the center right? In that case you don't need to calculate 🤔

**Comment by wende60** [comment]
you are completely right. But as these coordinates usually come as a generated resultlist this needs extra conditions. IMHO fitBounds shoild be able to deal with that.

**Comment by wende60** [comment]
thanks for that hint, with the google build in fitBounds ist works fine for me! It also worked with the utils and a little condition ;)

**Comment by itsmichaeldiego** [comment]
@wende60 Im happy I was able to help! Let me know if you need further help.
