### ISSUE TITLE
Remove Fullscreen Control

### ISSUE THREAD

**Issue by developer2-distributed** [google-map-react/google-map-react#699]
Is there any way to remove full screen control?

**Comment by itsmichaeldiego** [comment]
@developer2-distributed 

Yes, here:

```javascript
createMapOptions: function (maps) {
    return {
      zoomControl: boolean,
      mapTypeControl: boolean,
      scaleControl: boolean,
      streetViewControl: boolean,
      rotateControl: boolean,
      fullscreenControl: boolean
    }
  }

 <GoogleMap  options={createMapOptions} ... />
```

src: https://github.com/google-map-react/google-map-react/blob/master/API.md#options-funcobject

**Comment by Singapuram** [comment]
Hello,
I want to hide default buttons on the google map (Map and Satellite), how can I do this. Please suggest.
here is my code.
![image](https://user-images.githubusercontent.com/78669287/131198432-85fcdb01-c7c5-4d21-a00a-c2dd66194b84.png)

 return (
      <GoogleMap
        id="gMap"
        mapContainerStyle={mapStyles}
        zoom={20}
        mapTypeId={google.maps.MapTypeId.SATELLITE}         
        onLoad={(map => maponload(map))}
      >

**Comment by coderkhalide** [comment]
> ```js
> options={createMapOptions}
> ```

Follow @itsmichaeldiego

And

mapTypeControl: false,
