### ISSUE TITLE
Smooth marker animation when updating marker position

### ISSUE THREAD

**Issue by gukii** [google-map-react/google-map-react#700]
Any recommendation on how to create an animation when a marker position gets updated over time (e.g. tracing a runner)? 

I tried to use a simple CSS class to animate marker position update without success:

.marker {
	transition: transform 500ms ease-in-out;
}

Thanks a lot

**Comment by itsmichaeldiego** [comment]
Well actually is the property location that is changing, but you can probably do something from inside your `<Marker />` component to do it smoothly

**Comment by ankittparikh** [comment]
@gukii did you find any solution?

**Comment by itsmichaeldiego** [comment]
@ankittparikh As I told @gukii, this can be achieved with CSS, adding transition to top or bottom, just check the CSS change when changing map position and animate that property.

**Comment by edi** [comment]
@itsmichaeldiego Hi. Given we cannot add an attributes, I decided to use the marker's title.

```css
div[title="animated-marker"] {
	transition: all .25s ease !important
}
```

The CSS is applied properly (as I can see it in the dev tools). However, it has no effect on the element as it still pops from one location to another. Can you please provide an actual example?

Regards

**Comment by hemkaran** [comment]
@edi I was also trying few ways to the same. The main problem I have found is that the components is unmounting and mounting again on `lat` `lng` change. Let me know if you have found some solution for this problem?

**Comment by edi** [comment]
@hemkaran My solution was to simply use a "transparent" icon (because that's the actual issue), and style its parent instead.

So for the marker in-app you can do this, note the title prop, as we need that to style it.

```jsx
<Marker
    title="animated-marker"
    position={lat,lng}
    icon={{
	path: window.google.maps.SymbolPath.CIRCLE,
	strokeWeight: 0,
	fillOpacity: 0,
	scale: 7
    }}
/>
```

And then apply some CSS as follows:
```css
div[title="animated-marker"] {
    border-radius: 50%
    background-color: #fff000
    border: 3px solid #000
    transition: all .25s ease
}
```

You can see how it works here:

![CleanShot 2023-05-21 at 23 14 18](https://github.com/google-map-react/google-map-react/assets/7712869/260a9348-397e-4a3f-8fff-d7c62cdd340a)


https://share.cleanshot.com/Bs22Hn9V

**Comment by josegutierro** [comment]
> @hemkaran My solution was to simply use a "transparent" icon (because that's the actual issue), and style its parent instead.
> 
> So for the marker in-app you can do this, note the title prop, as we need that to style it.
> 
> ```js
> <Marker
>     title="animated-marker"
>     position={lat,lng}
>     icon={{
> 	path: window.google.maps.SymbolPath.CIRCLE,
> 	strokeWeight: 0,
> 	fillOpacity: 0,
> 	scale: 7
>     }}
> />
> ```
> 
> And then apply some CSS as follows:
> 
> ```css
> div[title="animated-marker"] {
>     border-radius: 50%
>     background-color: #fff000
>     border: 3px solid #000
>     transition: all .25s ease
> }
> ```
> 
> Result is as follows:
> 
> ![CleanShot 2023-05-21 at 23 14 18](https://user-images.githubusercontent.com/7712869/239765939-260a9348-397e-4a3f-8fff-d7c62cdd340a.gif)

Hello!

Thanks for your solution. Problem is that animation is triggering also on zoom change

**Comment by Huh-David** [comment]
> > @hemkaran My solution was to simply use a "transparent" icon (because that's the actual issue), and style its parent instead.
> > So for the marker in-app you can do this, note the title prop, as we need that to style it.
> > ```js
> > <Marker
> >     title="animated-marker"
> >     position={lat,lng}
> >     icon={{
> > 	path: window.google.maps.SymbolPath.CIRCLE,
> > 	strokeWeight: 0,
> > 	fillOpacity: 0,
> > 	scale: 7
> >     }}
> > />
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > And then apply some CSS as follows:
> > ```css
> > div[title="animated-marker"] {
> >     border-radius: 50%
> >     background-color: #fff000
> >     border: 3px solid #000
> >     transition: all .25s ease
> > }
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > Result is as follows:
> > ![CleanShot 2023-05-21 at 23 14 18](https://user-images.githubusercontent.com/7712869/239765939-260a9348-397e-4a3f-8fff-d7c62cdd340a.gif)
> >       
> >         [
> >           
> >         
> >             ![CleanShot 2023-05-21 at 23 14 18](https://user-images.githubusercontent.com/7712869/239765939-260a9348-397e-4a3f-8fff-d7c62cdd340a.gif)
> >           ](https://user-images.githubusercontent.com/7712869/239765939-260a9348-397e-4a3f-8fff-d7c62cdd340a.gif)
> >         
> >         
> >           
> >             
> >               
> >             
> >             
> >               
> >               
> >             
> >           
> >           [
> >             
> >               
> >             
> >           ](https://user-images.githubusercontent.com/7712869/239765939-260a9348-397e-4a3f-8fff-d7c62cdd340a.gif)
> 
> Hello!
> 
> Thanks for your solution. Problem is that animation is triggering also on zoom change

For anyone having issues with this. You can just make the title conditionally with a variable like `isAnimationInProgress`.

**Comment by niteshgiri-7** [comment]
How to apply rotation to the marker?
Let's say I am using a vehicle icon,and I need to rotate the vehicle with certain angle.Could we do this using Marker?
