### ISSUE TITLE
add infoWindow

### ISSUE THREAD

**Issue by roeib** [google-map-react/google-map-react#704]
How can I add infoWindow to marker after a click

**Comment by clarkjo12** [comment]
i cant find this anywhere, why'd it get closed?

**Comment by byeokim** [comment]
> How can I add infoWindow to marker after a click

I had the same question. I think adding info window component in the marker component, and conditionally rendering info window component using onChildClick event handler might be a solution. Hope that following code helps.

```javascript
const Marker = props => (
  <React.Fragment>
    <div
      style={{
        border: "5px solid white",
        borderRadius: 20,
        height: 20,
        width: 20
      }}
    />
    {/* Below is info window component */}
    {props.show && (
      <div
        style={{
          width: 100,
          height: 100
        }}
      >Info window</div>
    )}
  </React.Fragment>
)

class App extends React.Component {
  constructor(props) {
    super(props)
    this.state = {
      center: {
        lat: /* some lat */,
        lng: /* some lng */
      },
      zoom: 17,
      show: false
    }
  }

  _onChildClick = (key, childProps) => {
    this.setState({show: !this.state.show})
  }

  render() {
    return (
      <div style={{height: "100vh", width: "100%"}}>
        <GooleMapReact
          bootstrapURLKeys={{key: APIKey}}
          defaultCenter={this.state.center}
          defaultZoom={this.state.zoom}
          onChildClick={this._onChildClick}>
          <Marker
            lat={/* some lat */}
            lng={/* some lng */}
            show={this.state.show}
          />
        </GooleMapReact>
      </div>
    )
  }
}

```

**Comment by itsmichaeldiego** [comment]
@byeokim Could you add this to [google-map-react-examples](https://github.com/google-map-react/google-map-react-examples)?

**Comment by byeokim** [comment]
Sure. Happy to contribute.

**Comment by waynekhalifa** [comment]
I added an info window like you explained, but there is one problem that I can't solve, that box get out of the map viewport. is there any way that I can solve this?

**Comment by byeokim** [comment]
Could you describe the problem more clearly? If I read correctly, the solution might be:
(Note that `<InfoWindow>` is beside `<GoogleMapReact>`)
```js
const InfoWindow = props => (
  props.show ? (<div style={{width: 100, height: 100}}>Info window</div>) : null
)

const Marker = props => (
  <React.Fragment>
    <div
      style={{
        border: "5px solid white",
        borderRadius: 20,
        height: 20,
        width: 20
      }}
    />
    <InfoWindow
      show={props.show}
    />
  </React.Fragment>
)

class App extends React.Component {
  constructor(props) {
    super(props)
    this.state = {
      center: {
        lat: /* some lat */,
        lng: /* some lng */
      },
      zoom: 17,
      show: false
    }
  }

  _onChildClick = (key, childProps) => {
    this.setState({show: !this.state.show})
  }

  render() {
    return (
      <div style={{height: "100vh", width: "100%"}}>
        <InfoWindow 
          show={this.state.show}
        />
        <GooleMapReact
          bootstrapURLKeys={{key: APIKey}}
          defaultCenter={this.state.center}
          defaultZoom={this.state.zoom}
          onChildClick={this._onChildClick}>
          <Marker
            lat={/* some lat */}
            lng={/* some lng */}
            show={this.state.show}
          />
        </GooleMapReact>
      </div>
    )
  }
}
```

**Comment by Med-All** [comment]
Is there any example of the InfoWindow as a wrapper to the Google Maps' InfoWindow?

**Comment by byeokim** [comment]
@Med-All Did you mean [this](https://github.com/google-map-react/google-map-react-examples/blob/master/src/examples/MarkerInfoWindowGmapsObj.js)?

**Comment by Mrinal2806** [comment]
how can i add a closing tag to the infowindow

**Comment by byeokim** [comment]
If using above example:

```js
const InfoWindow = props => (
  props.show ? (<div style={{width: 100, height: 100}}>{props.children}</div>) : null
)

...

render() {
    return (
      <div style={{height: "100vh", width: "100%"}}>
        <InfoWindow 
          show={this.state.show}
        >
          Info window
        </InfoWindow>

...
```

Note that `{props.children}` is added to `<div>` tag.

**Comment by Mrinal2806** [comment]
Thanks for the help, I would also prefer to make Info-window closing and opening. how can i add the closing option in info-window.

**Comment by byeokim** [comment]
Hope that this code helps:

```js
const InfoWindow = props => (
  props.show
    ? (
      <div style={{width: 100, height: 100}}>
        <div
          onClick={props.handleClose}
          style={{border: "1px solid black", position: "absolute", top: 5, right: 5}}
        >
          X
        </div>
        <div>
          {props.children}
        </div>
      </div>
    )
    : null
)

...

class App extends React.Component {

...

  handleClose = () => this.setState({show: false})

  render() {
      return (
        <div style={{height: "100vh", width: "100%"}}>
          <InfoWindow 
            show={this.state.show}
            handleClose={this.handleClose}
          >
          Info window
        </InfoWindow>

...
```

**Comment by leogoesger** [comment]
I think the difficulty of using a prop is that we have to manually determine where to put the info window. Let's say a marker is on the very top of the map, an ideal place to put info window would be below the marker. Is there an api I could use for this?

**Comment by IBanda** [comment]
@leogoesger  did you ever figure that issue out? 
Please have a look at this [Codesandbox ](https://codesandbox.io/s/brave-banach-mx1zn) if that's the similar behavior you were referring to.

**Comment by tanner-schmutte** [comment]
@IBanda this link was super helpful thank you.. although the InfoBox does not display when the map is expanded to full screen, any idea why?

**Comment by IBanda** [comment]
@tanner-schmutte When google maps is in full screen it only shows the children to the Map component. however the react laag appends a layer(div) which is used to calculate the positioning at the end of the document. so as a workaround I decided to add a custom layer in the map component  when it loads, that way it works both ways. you can have a look at this [Codesandbox](https://codesandbox.io/s/google-map-react-with-infobox-visible-onfullscreen-405s5)

**Comment by tanner-schmutte** [comment]
@IBanda hmm that is tricky for sure. I tried using your code and it works great for the expanded map, but unfortunately, when the map is not full screen the InfoBox is displaying like 200px below where it was before

**Comment by IBanda** [comment]
@tanner-schmutte That's strange I would have to take a look to know for sure what's causing that

**Comment by tanner-schmutte** [comment]
@IBanda yea it's odd.. I think the only thing I have different from your code was onMouseOver and onMouseLeave instead of onClick

thanks for the responses btw.. I'm about to crash

**Comment by IBanda** [comment]
@tanner-schmutte Initially used those as well I just changed to onClick before sharing it with you. Let me know when you fix it.

**Comment by tanner-schmutte** [comment]
@IBanda will do

**Comment by bodfaj13** [comment]
passing on onClick props on the marker element can also do the trick.
