### ISSUE TITLE
Google Maps 1 Call Per Day Seems to Apply for all Examples Except for the New Ones

### ISSUE THREAD

**Issue by edward-hong** [google-map-react/google-map-react#707]
This issue has to do with #635.

Essentially Google Maps under the free tier only allows for one call per day where the map will load correctly. Otherwise, there will be watermarks saying 'For development purposes only' over the map. Adding the API key to `bootstrapURLKeys` doesn't fix this issue as Google just checks whether the call has been used on that key for the day and if it has it'll load the development version of the map.

According to [this post](https://github.com/google-map-react/google-map-react/issues/635#issuecomment-417857838) from #635, @itsmichaeldiego provided a working example in CodeSandBox and also says the main example is working correctly as well. Here's a screenshot of the CodeSandBox example:

![screen shot 2019-01-08 at 12 53 35 pm](https://user-images.githubusercontent.com/16217130/50800887-30922280-1347-11e9-899f-4700934aa403.png)

And this is a screenshot of the [main example](https://google-map-react.github.io/google-map-react/map/main/):

![screen shot 2019-01-08 at 1 02 50 pm](https://user-images.githubusercontent.com/16217130/50800955-8cf54200-1347-11e9-900d-b4d494bbb691.png)

However the new examples from the [google-map-react-examples](https://google-map-react.github.io/google-map-react-examples/default) repo are working correctly.

I was wondering what's the difference between the two different sets of examples? Are the new examples using an API key that's being paid for so the quota's been increased?

**Comment by itsmichaeldiego** [comment]
@edward-hong I am glad you ask, the old examples are super outdated, so we've been migrating to the new examples. The version used by the old examples is `0.3.34` or something like that, we are currently at `1.1.2`, a lot of stuff happened in between, not only the API key.

I am sorry we couldn't find time to finish the new examples, we're looking for contributors that want to add examples to the repo so we can replace the old ones.

**Comment by itsmichaeldiego** [comment]
@edward-hong Oh, I think I see what you mean, the google map won't be out of developer mode unless you add an api key
