### ISSUE TITLE
Problem with chinese (cn)

### ISSUE THREAD

**Issue by francescovenica** [google-map-react/google-map-react#708]
When I try to render a map on `cn` I get some connection error...this is the component:

```
              <GoogleMapReact
                bootstrapURLKeys={{
                  key: options.key,
                  language: 'cn',
                  region: 'cn',
                  libraries: 'places',
                }}
                options={{
                  streetViewControl: true,
                  styles
                }}
                yesIWantToUseGoogleMapApiInternals={true}
                defaultCenter={center}
                defaultZoom={zoom}
              >
```

I can see that all the request are to maps.cn but not these 2 `AuthenticationService.Authenticate` and `QuotaService.RecordEvent` that are still to `google.com`...

**Comment by itsmichaeldiego** [comment]
@francesco Maybe this is related to https://github.com/google-map-react/google-map-react/issues/574 ? It seemed to be a google map problem

**Comment by maxchernin** [comment]
@itsmichaeldiego does the library code load the google maps api as
http://maps.google.cn (HTTP)
instead of 
https://maps.googleapis.com (HTTPS) 
?

**Comment by itsmichaeldiego** [comment]
@maxchernin Its using HTTPS, you can check that logic [here](https://github.com/google-map-react/google-map-react/blob/master/src/loaders/google_map_loader.js#L3)

**Comment by maxchernin** [comment]
@itsmichaeldiego then im not sure why its working? isnt https blocked in china, to my understanding only https://maps.google.cn works in china

**Comment by itsmichaeldiego** [comment]
@maxchernin Oh sorry I get what you meant before, If you set region to cn it will work:

```bootstrapURLKeys={{ region:"cn", key:"my key" }}```

[check source code](https://github.com/google-map-react/google-map-react/blob/master/src/loaders/google_map_loader.js#L6)
