### ISSUE TITLE
Add support for contextmenu within overlayview

### ISSUE THREAD

**Issue by jurgenzz** [google-map-react/google-map-react#710]
I've seen around some issues about "right click" on markers, where you'd like to see the context menu.

E.g., rendering a custom popup with text, which you could select and copy, where a contextmenu would be handy for users, which don't use "ctrl+c".

There are few hacks around (which you can actually do by yourself), but maybe you could add as API?

For example, where initMap is called, after OvelayView is created, add something like

```
     if (this_.props.allowContextMenu) {
         maps.OverlayView.preventMapHitsAndGesturesFrom(div);
         div.addEventListener('contextmenu', function(e) { 
            e.stopPropagation()
         })
      }
```

**Comment by itsmichaeldiego** [comment]
@jurgenzz Thanks! PRS are welcome!

**Comment by itsmichaeldiego** [comment]
@jurgenzz Are you planning on working on this or should I close the issue?
