### ISSUE TITLE
streetview?

### ISSUE THREAD

**Issue by smolleyes** [google-map-react/google-map-react#711]
hi!

thanks for the lib but how can we add streetview controls? 

thanks

**Comment by itsmichaeldiego** [comment]
@smolleyes Try to search in the repository first! The answer is here: https://github.com/google-map-react/google-map-react/issues/251

**Comment by smolleyes** [comment]
hi

i did... :) 

i was searching this ... 

<GoogleMapReact **options={{streetViewControl:true}}** /> 

adding some docs on this options key maybe a nice idear :) 

thanks for the lib again !
