### ISSUE TITLE
Map object instance persistence support

### ISSUE THREAD

**Issue by KevinRamsunder** [google-map-react/google-map-react#712]
I have a use case where I'd like to re-use the `Map` instance created in the `_initMap` method (https://github.com/google-map-react/google-map-react/blob/master/src/google_map.js#L589) so that you don't need to initialize a new map every time this component is called.

Has any thought been put into supporting this? I'd be interested in making the necessary changes to implement this, but wanted to hear about any comments or concerns if there were any first.

**Comment by itsmichaeldiego** [comment]
@KevinRamsunder That's done man! Check out [the documentation](https://github.com/google-map-react/google-map-react/blob/master/API.md#ongoogleapiloaded-func)

Example: https://github.com/google-map-react/google-map-react-examples/blob/master/src/examples/Main.js#L69

**Comment by KevinRamsunder** [comment]
Thanks @itsmichaeldiego, I noticed that method as well. However, we don't have a way of passing the Map object back down to each subsequent component. For example, on this line https://github.com/google-map-react/google-map-react/blob/master/src/google_map.js#L589 we could change it to something like...

```
const map = this.props.providedMapObject || new maps.Map(
          ReactDOM.findDOMNode(this.googleMapDom_),
          mapOptions,
};
```

Goal here is to prevent additional calls to the `maps.Map` constructor for each additional GoogleMap component.

Let me know if I'm misunderstanding what you meant.
