### ISSUE TITLE
On default marker title is not visible

### ISSUE THREAD

**Issue by kdmatrosov** [google-map-react/google-map-react#714]
I set default marker with title, but title is not visible
```
<GoogleMap
              bootstrapURLKeys={{ key: props.key }}
              center={this.state.center}
              zoom={16}
              yesIWantToUseGoogleMapApiInternals={true}
              onGoogleApiLoaded={({ map, maps }) => this.renderMarker(map, maps)}
            />
```
```
renderMarker = (map, maps) => {
    new maps.Marker({
      map: map,
      position: new maps.LatLng(55.7482273, 37.5403716),
      title: 'Empire'
    });
  };
```
`"google-map-react": "^1.1.2"`

![img](http://joxi.ru/eAOn5d4UxMopx2.png)

**Comment by itsmichaeldiego** [comment]
@kdmatrosov Thanks for the report, this is a really low priority bug because this library is not really built for using it with google's google markers, but custom components, PRs are super welcome though! In case you want to collaborate!

**Comment by negati-ve** [comment]
@kdmatrosov use label property instead of title 

```
renderMarker = (map, maps) => {
    new maps.Marker({
      map: map,
      position: new maps.LatLng(55.7482273, 37.5403716),
      label: 'Empire'
    });
  };
```

**Comment by Uptimist** [comment]
> @kdmatrosov use label property instead of title
> 
> ```
> renderMarker = (map, maps) => {
>     new maps.Marker({
>       map: map,
>       position: new maps.LatLng(55.7482273, 37.5403716),
>       label: 'Empire'
>     });
>   };
> ```
thanks! That works! May be you know how to change the font style?))
