### ISSUE TITLE
places autocomplete on touch does not work [from mobile]

### ISSUE THREAD

**Issue by saikatharryc** [google-map-react/google-map-react#715]
.pac-container populates with pac-items as input changes
when item is tapped on mobile or simulator (any iPhone device), pac-container is dismissed but places_changed event does not fire.

**Comment by itsmichaeldiego** [comment]
Please provide more information and a live example in order for us to help! Thanks

**Comment by saikatharryc** [comment]
Not required anymore! thanks for the quick reply by the way. 😂

**Comment by itsmichaeldiego** [comment]
@saikatharryc Ok! Glad that you found your way then 👍

**Comment by lorenzobalzani** [comment]
I still have this issue
