### ISSUE TITLE
Incorrect marker position on full screen mode version 1.1.2

### ISSUE THREAD

**Issue by saadbinsaeed** [google-map-react/google-map-react#717]
Hi I am having an issue with the marker's **latitude** and **longitude** on full screen mode. Currently using version `1.1.2` while not in full screen mode marker do move correctly, but while in full screen mode it does not move correctly. Please take a look at code 
```
/* @flow */
import React, { PureComponent } from 'react';
import GoogleMapReact from 'google-map-react';

/* Map configuration */
const mapOptions = maps => {
    return {
        mapTypeId: maps.MapTypeId.HYBRID,
        mapTypeControl: true,
        zoomControlOptions: {
            position: maps.ControlPosition.TOP_RIGHT,
            style: maps.ZoomControlStyle.SMALL
        },
        resetBoundsOnResize: true,
        mapTypeControlOptions: {
            position: maps.ControlPosition.TOP_RIGHT,
            style: maps.MapTypeControlStyle.DROPDOWN_MENU,
            mapTypeIds: [maps.MapTypeId.SATELLITE, maps.MapTypeId.HYBRID, maps.MapTypeId.TERRAIN]
        }
    };
};

/**
 * A map component
 */
export default class Location extends PureComponent<Object, Object> {

    static defaultProps = {
        color: ''
    };

    state = {
        latitude: this.props.latitude,
        longitude: this.props.longitude
    };

    /**
     * onclick map will change the coordinates
     */
    mapClicked = (mapProps: Object) => {
        this.setState({ latitude: mapProps.lat, longitude: mapProps.lng });
    };

    /**
     * Lifecycle hook: Executed on component render.
     * @returns {XML}
     */
    render() {
        const { latitude, longitude } = this.state;
        return (
            <div style={{ height: '300px' }}>
                <GoogleMapReact
                    bootstrapURLKeys={{ key: 'XYZ', libraries: 'places' }}
                    center={{ lat: latitude, lng: longitude }}
                    defaultZoom={11}
                    options={mapOptions}
                    onClick={this.mapClicked}
                >
                    <div style={{ width: '10px', height: '10px', backgroundColor: 'red' }} lat={latitude} lng={longitude} text={'Location'} />
                </GoogleMapReact>
            </div>
        );
    }
}

```

**Comment by lusineterpetrosyan** [comment]
I think I have the same issue.
I think it has to do with wrappers not resizing.

**Comment by itsmichaeldiego** [comment]
@saadbinsaeed @lusineterpetrosyan What you can do is re-draw when window resizes, take a look at [this example](https://github.com/google-map-react/google-map-react-examples/blob/master/src/examples/Main.js#L28) in [google-map-react-examples](https://github.com/google-map-react/google-map-react-examples/)

**Comment by JanKolenko** [comment]
@saadbinsaeed @lusineterpetrosyan @itsmichaeldiego On full screen mode it does not calculate full screen window x and y coords correctly (see x and y coords on top left click in full screen) instead it still calculates relative coords to you map container, you can solve this problem by adding css to your google map container like this

```
position: fixed;
left: 0;
top: 0;
```

**Comment by Caruso33** [comment]
@JanKolenko 
Could you tell how to add these styles to the container?
If I use your code for the <div> which wraps the GoogleMap component, it doesn't work nor does adding styles directly to the GoogleMap component.

**Comment by saadbinsaeed** [comment]
@JanKolenko yes you are right actually the i am using a react component instead of that `div` but before reporting the issue i tried to make code simpler and mistakenly added that `div`

**Comment by saadbinsaeed** [comment]
@Caruso33 @JanKolenko @lusineterpetrosyan I made a new project to isolate the component and to make sure that its not getting affected by any other dependency or code and **it works**. So its not a library issue. I should have tested it before reporting the issue.
