### ISSUE TITLE
Remove InfoWindow 'X' close button

### ISSUE THREAD

**Issue by dersar00** [google-map-react/google-map-react#719]
Hi!
I'm using InfoWindow without marker, I render that when map was loaded, any ideas how I can remove the 'x' close button from it?

**Comment by itsmichaeldiego** [comment]
@dersar00 If you provide me a live example I can help you out!

**Comment by grdpr** [comment]
@dersar00  I'm trying to render a default InfoWindow but without success. Could you share how are you doing it? Thanks!
