### ISSUE TITLE
Specify Google Maps version

### ISSUE THREAD

**Issue by jglesner** [google-map-react/google-map-react#720]
Is there a way to specify the Google Maps version?  There is a way to do this on the Script tag when referencing the library directly, but I do not see how this can be done using google-map-react.  The recent 3.35 update changed the InfoWindow DOM and I would prefer to go back to the previous version 3.34. Such a feature would achieve the same objective as defined here: 

https://developers.google.com/maps/documentation/javascript/versions#version-number

**Comment by itsmichaeldiego** [comment]
@jglesner Yes, you can do it through 

```javascript
<GoogleMapReact
    bootstrapURLKeys={{
    key: 'YOUR_KEY',
    v:'3.30'
  }}
```
