### ISSUE TITLE
Render multiple elements on map

### ISSUE THREAD

**Issue by dersar00** [google-map-react/google-map-react#723]
Hello, I'm trying to render multiple elements like in your example, with one element everything is work good, but when I try to do it using js map method. With data that I got from props everything ok, I'm see it in my console, example of log below

    Latitude - 48.75689485857136
    Longitude - 23.001915875244208
    SceneName - Zhdenijevo

my SceneMapComponent file:

    import React from 'react';
    import GoogleMapReact from 'google-map-react';

    const defaultMapOptions = {
      fullscreenControl: false,
    };

    const AnyReactComponent = ({ text }) => (
        <div style={{
          color: 'white', 
          background: 'grey',
          padding: '15px 10px',
          display: 'inline-flex',
          textAlign: 'center',
          alignItems: 'center',
          justifyContent: 'center',
          borderRadius: '100%',
          transform: 'translate(-50%, -50%)'
        }}>
          {text}
        </div>
    );
    
        export const SceneMapComponent = props => (
        <div style={{ height: '100vh', width: '100%',  position: 'absolute' }}>
            <GoogleMapReact
                bootstrapURLKeys={{ key: 'myKey' }}
                defaultCenter={{ lat: 48.429, lng: 22.7058 }}
                defaultZoom={9}
                options={defaultMapOptions}
                onClick={ (e) => props.onMapClick(e) }
                onGoogleApiLoaded={({ map, maps }) => props.renderScenes(map, maps)}
                yesIWantToUseGoogleMapApiInternals
            >
                {props.Scenes.map( scene => {
                        
                        let lat=scene.coordinates[0];
                        let lng=scene.coordinates[1];
                        let sceneName=scene.name;
                
                        console.log(`Latitude - ${lat}\nLongitude - ${lng}\nSceneName - ${sceneName}`);
                    
                        <AnyReactComponent 
                            lat={lat} 
                            lng={lng} 
                            text={sceneName} 
                        />
                    })
                }         
            </GoogleMapReact>
        </div>
    )

    export default SceneMapComponent;

**Comment by dersar00** [comment]
Here is the jsbin [link](https://jsbin.com/bovewateva/edit?js,output) where you can check it, in the map we should see 3 points, but now we have only the hardcoded.

**Comment by og24715** [comment]
@dersar00 
It seems that because you have not been returning anything by the callback of the .map method.
You should correct your code to return AnyReactComponent inside the callback of the .map method as follows.
I hope it helps you :D

```js
{props.Scenes.map(scene => {
  let lat=scene.coordinates[0];
  let lng=scene.coordinates[
  let sceneName=scene.name;

  console.log(`Latitude - ${lat}\nLongitude - ${lng}\nSceneName - ${sceneName}`)

  return (
    <AnyReactComponent 
      lat={lat} 
      lng={lng}
      text={sceneName}
    />
  );
})}
```

**Comment by dersar00** [comment]
@og24715 thank you!
