### ISSUE TITLE
how to keep good performance while rendering hundreds of markers?

### ISSUE THREAD

**Issue by xr** [google-map-react/google-map-react#724]
Hi, thanks for the amazing library. I have a problem hope could get some hints, I have tried to search  in issues quite a bit, but i still didn't find a suitable solution.

I have some data (got from websocket) which will keep updating all the time. Those data are used to render hundreds of markers and move the markers' geo location as well.

what i'm done is like the following:

```
render(){
	<GoogleMapReact
		bootstrapURLKeys={{ key: '' }}
		center={this.props.center}
		defaultZoom={15}
	>
		{this.props.dataArray.map(info => {
			const { lat, lng, id } = info;
			return <Marker lat={lat} lng={lng} id={id}/>;
		})} 
	</GoogleMapReact>
}
```

however, as this.props.dataArray keep changing, the render method got called all the time which cause the page stop reacting.

the `Marker` component is already pureComponent, I noticed that the `GoogleMapReact` is extending Component instead of PureComponent. Wonder how could i prevent the `GoogleMapReact` itself rendering all the time, or are there any suggestions?

thanks.

**Comment by sevicbb** [comment]
@xr Any tips on how to handle this?
