### ISSUE TITLE
on click zoom-in & zoom-out & fullscreen it fires event in onClick happens in phone

### ISSUE THREAD

**Issue by saikatharryc** [google-map-react/google-map-react#725]
Hi, when click on **+** & **-** that is Zoom in & Zoom-out in phone browsers and phone applications.
it fires event on onClick. this happens in desktop browsers (chrome) Toggle to some phone view.
 
My code looks like this:
```
 <GoogleMapReact
                                        options={this.createMapOptions}
                                        bootstrapURLKeys={{
                                            key: config.GAPIKEY,
                                            libraries: ["places"]
                                        }}
                                        initialCenter={
                                            this.state.fields.location
                                        }
                                        center={this.state.fields.location}
                                        defaultZoom={15}
                                        zoom={this.state.zoom}
                                        layerTypes={[
                                            "TrafficLayer",
                                            "TransitLayer"
                                        ]}
                                        heat={true}
                                        gestureHandling="greedy"
                                        onClick={t => this.onChangeBoarding(t)}
                                        yesIWantToUseGoogleMapApiInternals
                                        onGoogleApiLoaded={({ map, maps }) =>
                                            this.apiHasLoaded(map, maps)
                                        }
                                    >
...Markers Goes here...
</GoogleMapReact>
```

in my case its triggering `onChangeBoarding()` with some lat lng which is not inside the map view when clicking on zoom out.
when click on zoom in the lat lng is in the map view only.
just to mention, i'm not clicking on the map. clicking on zoom in zoom out works as expected, problem is it calls the function mentioned in `onClick` 
*NOTE:* its happening not only in zoom-in zoom-out, but its happening on click fullscreen control too.
but in custom control button it works as expected. doesnt fire the onClcik of the component too.

**Comment by itsmichaeldiego** [comment]
@saikatharryc could you provide a live example of the bug? Thanks

**Comment by saikatharryc** [comment]
@itsmichaeldiego  can you provide email or something ?
 i can just share privately those credentials and the live link of that.

**Comment by itsmichaeldiego** [comment]
@saikatharryc Sorry man, a live example would be a code sandbox or something where I can take a look directly and see what's up, thanks.
