### ISSUE TITLE
Options do not register

### ISSUE THREAD

**Issue by BamItsPixel** [google-map-react/google-map-react#727]
Hello, I've done several searches and tried several things but to no avail.

I'd like to pass some options to my map and AFAIK the code below should work but the function `createOptions` is never called. Does anyone know how to pass options to the map please?

```
import React from 'react';
import {withScriptjs, withGoogleMap, GoogleMap, Marker} from "react-google-maps";

function createOptions(maps) {
   alert("HELLO!!");
   return {
      mapTypeId: maps.MapTypeId.SATELLITE
   }
}

const Map = withScriptjs(withGoogleMap(props =>
   <GoogleMap ... options={createOptions} />
));

export default Map;
```

**Comment by itsmichaeldiego** [comment]
@BamItsPixel Yeah AFAIK you cannot create the options on the map based on the `maps` component, because you don't have access to `maps` until the api is loaded, check this: https://github.com/google-map-react/google-map-react#use-google-maps-api
