### ISSUE TITLE
Component Position control

### ISSUE THREAD

**Issue by aakhan89** [google-map-react/google-map-react#730]
Want this
![image](https://user-images.githubusercontent.com/38126236/54130281-ea823980-4431-11e9-9966-ee7b66aa5aae.png)

Current is
![image](https://user-images.githubusercontent.com/38126236/54130359-0dace900-4432-11e9-91cb-61fdd2d75350.png)
![image](https://user-images.githubusercontent.com/38126236/54130515-55337500-4432-11e9-9beb-3134ec377fe2.png)

`<GoogleMapReact
                  bootstrapURLKeys={{ key: '' }}
                  defaultCenter={this.props.center}
                  defaultZoom={this.props.zoom}
                  options={mapOptions} >
                  <MapControls  />
                <AnyReactComponent
                    lat={}
                    lng={}
                    text={'test}/>
                </GoogleMapReact>`

**<MapControls  />** is a component which i want to fix position

**Comment by itsmichaeldiego** [comment]
@aakhan89 The problem is that you're passing the MapControls component as a children of GoogleMapReact, the only children that are accepted are markers with a lng and lat properties. You need to place the MapControls outside the GoogleMapReact component, but inside its wrapper, and then align normally to where you want.

**Comment by aakhan89** [comment]
@itsmichaeldiego 

Thanks for you reply and I got the point..

Also I have placed **`MapControls Component`** outside the **`GoogleMapReact component,`** but inside its wrapper, and **`MapControls Component`** showing out from Google Map I want to put it **MapControls** above goolemap and position want to fix as leftTop

**Comment by aakhan89** [comment]
@itsmichaeldiego 

here is Live example

https://codesandbox.io/s/v0xzo4ny5l
