### ISSUE TITLE
Trigger the click event of a marker programmatically

### ISSUE THREAD

**Issue by yaroslav-perec** [google-map-react/google-map-react#731]
I want to start dragging my marker immediately when I add it to my map, the marker becomes draggable when you click on it.
How do I programmatically trigger a click event? Or can I achieve this behavior in a different way?

**Comment by itsmichaeldiego** [comment]
@yaroslav-perec Thanks for using our library, in this case I cannot help you as this is not related to the library itself, I would ask this in StackOverflow.
