### ISSUE TITLE
Wrong recomputed onChange center position

### ISSUE THREAD

**Issue by tomwagner** [google-map-react/google-map-react#732]
When the `GoogleMapReact` component receives updated center prop, it triggers new onChange event, but there is returned wrong coordinates. You can see it in console logs in this example: https://codesandbox.io/s/71yoyz62q6. This broken state remains for the rest of component lifecycle.

**Comment by aakhan89** [comment]
same question is mine but in addition I want to set position of **`AnyReactComponent`** on Google Map

the position of **`AnyReactComponent`** should be left top, i tried below but not working:

`position:'absoulte',
            top: '0',
            left: '0',`

**Comment by itsmichaeldiego** [comment]
@aakhan89 check https://github.com/google-map-react/google-map-react/blob/master/API.md#positioning-a-marker

**Comment by aakhan89** [comment]
> 
> 
> @aakhan89 check https://github.com/google-map-react/google-map-react/blob/master/API.md#positioning-a-marker

@itsmichaeldiego  Thanks for your reply..

But this isn't working fine for me, because I wanted to fix **`AnyReactComponent `** position fixed always as left top, and via this solution I am unable to fix the position, I have to adjust position for multiple screen size..

Can you please provide the desired solution it will be highly appreciated

**Comment by itsmichaeldiego** [comment]
@aakhan89 With the solution I provided, you can fix the problem you described. You need to transform the axis of the object.

Please provide a live example and I can help you out

**Comment by tomwagner** [comment]
Could you please reopen this issue? It's not resolved. Please check the codesandbox example (https://codesandbox.io/s/71yoyz62q6). The whole thread is about returned onChange event with wrong recomputed coordinates and not about position of marker..

**Comment by aakhan89** [comment]
> 
> 
> @aakhan89 With the solution I provided, you can fix the problem you described. You need to transform the axis of the object.
> 
> Please provide a live example and I can help you out

Okay I will provide the live example..

also I request to you please reopen this issue as @tomwagner's didn't solved..

@tomwagner  I am really sorry for interrupt in this

**Comment by aakhan89** [comment]
> 
> 
> @aakhan89 With the solution I provided, you can fix the problem you described. You need to transform the axis of the object.
> 
> Please provide a live example and I can help you out

here is Live example

https://codesandbox.io/s/v0xzo4ny5l

**Comment by itsmichaeldiego** [comment]
@aakhan89 Your example is not working, please open a new issue as this is not related.

Sorry @tomwagner, will take a look soon

**Comment by aakhan89** [comment]
@itsmichaeldiego 

Kindly see this https://github.com/tomchentw/react-google-maps/issues/975

**Comment by itsmichaeldiego** [comment]
@aakhan89 That's another library bro

**Comment by reket** [comment]
@itsmichaeldiego ping

**Comment by ianldgs** [comment]
Additionally, the internal location of the component (probably the state) seems to be wrong. The map doesn't move to the new `center`.

I managed to get around the issue by using the `defaultCenter` prop, not sure if you have the same case.

```diff
<GoogleMap
...
-center={center || {lat: 52.378, lng: 4.9}}
+defaultCenter={{lat: 52.378, lng: 4.9}}
+center={center}
/>
```

**Comment by itsmichaeldiego** [comment]
@reket @tomwagner This is a collaborative library, PRs are welcome!

**Comment by gtherond** [comment]
Ok, I've the same issue, willing to help if ever required, but I've got a design question first, why did you choose to forbidden props change? Redux user here and it's common/easier for us to simply use the props than having an additional step where we transform those props into state.

**Comment by onlysli** [comment]
Same problem here, any updates?

**Comment by gtherond** [comment]
> Same problem here, any updates?

I've chose to migrate my app and use: @react-google-maps/api as it's more active.

**Comment by lightcap** [comment]
I think this is actually expected behavior. Each time you zoom in you're getting a slightly more specific coordinates since you're zoomed in further and getting a bit higher resolution with each click.

@tomwagner does that make sense to you?

**Comment by itsmichaeldiego** [comment]
I think you're right @lightcap, works fine for me too
