### ISSUE TITLE
get current zoom level using zoom_changed callback?

### ISSUE THREAD

**Issue by eldyvoon** [google-map-react/google-map-react#733]
How do I get current zoom level with zoom_changed callback function?

```
<GoogleMapReact
  bootstrapURLKeys={{
    key: process.env.GOOGLE_MAP_KEY
  }}
  defaultZoom={10}
  options={maps => ({
    minZoom: 14,
    zoom_changed: map => {
      global.window.setTimeout(function() {
        console.log('zoom changed, but how to get current zoom level?')
      }, 1000)
    }
  })}
>
```

Didn't find anything in ```maps```

**Comment by grazinskis** [comment]
Why not use the [onChange](https://github.com/google-map-react/google-map-react/blob/master/API.md#onboundschange-func-deprecated-use-onchange) callback?

**Comment by poptocrack** [comment]
Did you managed to do this?

**Comment by eldyvoon** [comment]
@poptocrack I use the onChange method.

**Comment by bhavikji** [comment]
@grazinskis @eldyvoon : Is there any way to check the change is a mouse scroll event on `onChange()` function
