### ISSUE TITLE
Doesn't work in IE 11

### ISSUE THREAD

**Issue by a-sergeichik** [google-map-react/google-map-react#743]
There is a problem in IE11 when rendering markers on the map. I'm getting 'Cannot define property '$jscomp_hidden_0.7236542694685333': object is not extensible'. 
Steps to reproduce: 

- Clone [new examples](https://github.com/google-map-react/google-map-react-examples)
- yarn
- yarn start
- Open http://localhost:3000/default in IE11

![ie11error](https://user-images.githubusercontent.com/3018293/55903644-d4a19900-5bd6-11e9-9dd2-a168488ff304.PNG)

**Note** Old examples which use React 14 work fine , the issue is reproducible with new examples and React 16.

**Comment by MihkelPuusepp** [comment]
Same issue. 
google-map-react 1.1.4
react 16.8.1
Crashes on map load.

google-map-react 1.0.3
react 16.8.1
Production build works. Development throws this error.

**Comment by alololox** [comment]
What flag are you looking for to determine production environment?

**Comment by vertic4l** [comment]
what do you mean with flag? 

you should have a development build and a production build e.g.:

npm run dev => webpack --mode development --progress --colors
npm run prod => webpack -p --mode production --progress --colors

for example...

And the later one does some additional stuff which gets GoogleMapReact to work with IE11.

That's it.
