### ISSUE TITLE
How to implement Heat map option? 

### ISSUE THREAD

**Issue by fuegod03** [google-map-react/google-map-react#746]
Me and a few more developers cannot find a way to add the heat feature to <SimpleMap /> Component. Can you guys help me? 

I've tried to add `updateHeatmap={true}  heatmapLibrary={true}`to `<GoogleMapReact />`

here is my code
`import React, { Component } from 'react';
import GoogleMapReact from 'google-map-react';

const AnyReactComponent = ({ text }) => <div ><img style={{height:"40px"}}  src="https://image.flaticon.com/icons/svg/1329/1329665.svg"/></div>;
const handleApiLoaded = (map, maps) => {
  // use map and maps objects
};
class SimpleMap extends Component {

  static defaultProps = {
    center: {
      lat: 40.6462668,
      lng: -74.2586487
    },
    zoom: 11
  };

  render() {
    return (
      // Important! Always set the container height explicitly
      <div style={{ height: '100vh', width: '100%' }}>
        <GoogleMapReact
          bootstrapURLKeys={{ key:"Personal info}}
          defaultCenter={this.props.center}
          defaultZoom={this.props.zoom}
          yesIWantToUseGoogleMapApiInternals
          onGoogleApiLoaded={({ map, maps }) => handleApiLoaded(map, maps)}
          layerTypes={['FusionTablesLayer', 'TransitLayer']}
updateHeatmap={true}
  heatmapLibrary={true}
        >
          <AnyReactComponent
            lat={40.6462668}
            lng={-74.2586487}
            text
          />
        </GoogleMapReact>
      </div>
    );
  }
}

export default SimpleMap;
`

**Comment by itsmichaeldiego** [comment]
@fuegod03 Just need to check the examples my friend: [google-map-react-examples/heatmap](https://github.com/google-map-react/google-map-react-examples/blob/master/src/examples/Heatmap.js)
