### ISSUE TITLE
How to change default location and use it with props?

### ISSUE THREAD

**Issue by fuegod03** [google-map-react/google-map-react#747]
I can't seem to find a solution to my problem. I've tried to add `this.props` to `  
static defaultProps = {
    center: {
      lat: this.props.latitude,  **from Parent component**
      lng: this.props.long    **from Parent component**
    },
    zoom: 11
  };`

And I recieve "can not find latitude of undefine"
Also, it seems like I cant find this.props inside "defaultProps"

**Comment by itsmichaeldiego** [comment]
@fuegod03 Just need to check the examples my friend: [google-map-react-examples/main](https://github.com/google-map-react/google-map-react-examples/blob/master/src/examples/Main.js)
