### ISSUE TITLE
Broken examples possibly due to API key

### ISSUE THREAD

**Issue by malorie16** [google-map-react/google-map-react#749]
Your examples are breaking due to an API key not being passed somewhere: https://developers.google.com/maps/documentation/javascript/error-messages#no-api-keys

All of your examples (the ones that still exist) show this message and a console warning saying the above. 

<img width="1488" alt="Screen Shot 2019-05-06 at 12 13 13 PM" src="https://user-images.githubusercontent.com/37854050/57249128-000e7c80-6ff9-11e9-9596-1cba6ae37e1a.png">

**Comment by itsmichaeldiego** [comment]
@malorie16 Yes thanks, this is known and there're issues created to tackle this.

**Comment by RaphaelSilv** [comment]
> @malorie16 Yes thanks, this is known and there're issues created to tackle this.

where can one find them?
