### ISSUE TITLE
Polygon vertexes and right click

### ISSUE THREAD

**Issue by nelsonlho** [google-map-react/google-map-react#750]
I looked at the Google Map API and it says I should get the vertex upon clicking a vertex of an editable Polygon

I haven't been able to get any success with React Google Map with right clicks. No events would be fired. However, mouse down events work on polygon vertices

Is there any way to fire a right click event when the user clicks on an editable polygon's vertex?

**Comment by itsmichaeldiego** [comment]
@nelsonlho Yes but you might need to submit a PR that catches that event from the library end

**Comment by langer-man** [comment]
https://www.npmjs.com/package/easy-drawing

this may be another view of point
