### ISSUE TITLE
Default known places info missing in map

### ISSUE THREAD

**Issue by Wiland** [google-map-react/google-map-react#751]
Hi,

I'm trying to add a map in one project, but my client is asking me to show all the information about known places as it's shown in Google Maps (Shopping malls, Gas stations, etc). I haven't been able to do it with this library.

I expect to see the map like this:
![image](https://user-images.githubusercontent.com/5203894/57544247-6eff1480-731c-11e9-8c95-6cf6c284a328.png)

But instead, I'm getting this:
![image](https://user-images.githubusercontent.com/5203894/57544273-850cd500-731c-11e9-833a-4fa3e70ed3fa.png)

As you can see, there a lot of information missing.

Here is a piece of code I'm using to test: [https://stackblitz.com/edit/react-rvfpjj?file=index.js](https://stackblitz.com/edit/react-rvfpjj?file=index.js)

I'll appreciate any help you can give me.

Regards.

**Comment by itsmichaeldiego** [comment]
@Wiland This is an option of google maps itself, you can pass it down on the `options` prop

**Comment by Tuoki** [comment]
Actually I am also struggling with same problem. Can you provide example what kind options I need to pass that I will get places to appear?

**Comment by Tuoki** [comment]
@Wiland I found out what options @itsmichaeldiego mean here is options which provide default view of Google Map:  `const options: MapOptions = {
    streetViewControl: true,
    disableDefaultUI: false,
    mapTypeControl: true,
    styles: [
        {
            featureType: 'poi',
            elementType: 'labels',
            stylers: [{ visibility: 'on' }],
        },
    ],
} `

**Comment by Wiland** [comment]
@itsmichaeldiego @Tuoki Thanks for your help guys!! That works perfectly well.

**Comment by itsmichaeldiego** [comment]
@Wiland @Tuoki No problem fellas!!! Happy to help
