### ISSUE TITLE
Cannot find heatmap in typescript

### ISSUE THREAD

**Issue by chaomediashaker** [google-map-react/google-map-react#755]
version : 1.1.4

Hi, I wish to know is the heatmap added to the typescript version? 

Update: I tested in 2 projects, 1 is in js React, 1 is in ts React.
JS React is working great,
but for the ts has the following problem:
1. I have to add a heatmap interface in the index.ts in node modules to use the heatmap props, otherwise it will throw syntax error.

2. After I added that, it will not show anything.

3. If I rewrite it into a JS component and then import it in a JS page of the typescript project, it will still not working.

**Comment by itsmichaeldiego** [comment]
@chaomediashaker I think you can just skip using .ts into the map component, right? I know it should work but I wouldn't prioritize it. 

If you want further help, please provide a live example and I will ask one of our contributors to help you.
