### ISSUE TITLE
Using SVG components as markers logs warnings to console in React v16.8.6

### ISSUE THREAD

**Issue by daffodilistic** [google-map-react/google-map-react#756]
Hi,

I'm having warnings when I use an SVG as a React component directly in the JSX:

> Received `false` for a non-boolean attribute `$hover`.
> 
> If you want to write it to the DOM, pass a string instead: $hover="false" or $hover={value.toString()}.
> 
> If you used to conditionally omit it with $hover={condition && value}, pass $hover={condition ? value : undefined} instead.
>     in svg (created by SvgComponent)
>     in SvgComponent (created by TestSvg)
>     in div (created by GoogleMapMarkers)
>     in div (created by GoogleMapMarkers)
>     in GoogleMapMarkers
>     in div
>     in Unknown (created by GoogleMap)
>     in div (created by GoogleMap)
>     in GoogleMap (created by TestSvg)
>     in div (created by TestSvg)
>     in TestSvg (created by App)
>     in div (created by App)
>     in App

Codepen: https://codesandbox.io/embed/festiveishizakadezpw-dezpw

Is there any way to silence this warnings?

**Comment by tlenex** [comment]
Warning seems to disapear if you do this like that:
https://codesandbox.io/embed/festive-ishizaka-dezpw-1pjom

**Comment by syarul** [comment]
@tlenex 
> Warning seems to disappear if you do this like that:
> https://codesandbox.io/embed/festive-ishizaka-dezpw-1pjom

this removes the warning yes, but panning the map will move the marker as well.
