### ISSUE TITLE
drag and click events on child component

### ISSUE THREAD

**Issue by smolleyes** [google-map-react/google-map-react#760]
hi

Search a lot to deal with this problem but can t find...

I use my own marker (nothing special..) 

in my map i use

onChildMouseUp={this.onMarkerDragEnd}
onChildMouseMove={this.onMarkerMove}
onChildMouseDown={this.onMouseDown}

everything works, just when i click a marker it fire the drag event directly ... how can i do to have both working ? (tried stopPropagation and preventDefault...not working) 

thanks

**Comment by itsmichaeldiego** [comment]
@smolleyes This is a known problem in general and not with this library itself, I suggest you look in StackOverflow, there're workarounds to this

**Comment by iDevTJ** [comment]
I know im too late, but you can set state variable and intiate value as false
`this.state = {dragged: false}`

and then do this steps:
- in onChildMouseDown event update the dragged variable to FALSE using setState
- in onChildMouseMove event update the dragged variable to TRUE using setState
- in onChildMouseUp event check the value of dragged , if TRUE, then don't apply your onClick event, if FALSE, apply your onClick event,
- and finally don't forget to set it to false in the end of the onChildMouseUp execution


hope that answer your question.

**Comment by itsmichaeldiego** [comment]
Thanks @iDevTJ, its appreciated anyways
