### ISSUE TITLE
Centering the map with multiple markers

### ISSUE THREAD

**Issue by Mauro74** [google-map-react/google-map-react#763]
How do I find the center of the map when I have more than 2 markers? When I have only 2 I've done it like this:

```
midPoint(trackingLocation, deliveryLocation) {
    if (deliveryLocation) {
      return [
        trackingLocation.lat + (deliveryLocation.lat - trackingLocation.lat) * 0.5,
        trackingLocation.lng + (deliveryLocation.lng - trackingLocation.lng) * 0.5
      ];
    } else {
      return trackingLocation;
    }
  }
```

But how do I calculate the center when I have 5 markers?

Thank you

**Comment by jjavierdguezas** [comment]
I think this is outside this repo, but because I like math I think you should see [Centroid on Wikipedia](https:// /wiki/Centroid)

**Comment by itsmichaeldiego** [comment]
I agree that this is not an issue with the library itself, therefore I am closing it
