### ISSUE TITLE
Link in docs leads to a malware website

### ISSUE THREAD

**Issue by gtupak** [google-map-react/google-map-react#766]
Hey guys, the link of "Simple example" at [this docs page](https://github.com/google-map-react/google-map-react/blob/master/DOC.md) leads to a site saying that my computer is infected. Maybe provide another link? :)

**Comment by itsmichaeldiego** [comment]
@gtupak Thanks for this!! This example was before in webpackbin and It seems that their domain was bought and replaced by a malware website.

I fixed this now to point to the main example in [google-map-react-examples](https://github.com/google-map-react/google-map-react-examples), will adapt the docs later.
