### ISSUE TITLE
Is there a way to change map type?

### ISSUE THREAD

**Issue by honb** [google-map-react/google-map-react#770]
Hi,

I want to change map type: roadmap, satellite, hybrid and terrain
Is there a simple config to update map type?

Thanks in advance.

**Comment by itsmichaeldiego** [comment]
You found the solution right @honb ?

**Comment by mohitjohar** [comment]
options={function (maps) { return { mapTypeId: "hybrid", } }}

**Comment by mohitjohar** [comment]
<GoogleMapReact
 options={function (maps) { return { mapTypeId: "hybrid", } }}
 center={center} zoom={5} bootstrapURLKeys={{ key: "your api key"}}>
</GoogleMapReact>
