### ISSUE TITLE
SetPadding in google maps using google-map-react

### ISSUE THREAD

**Issue by the-yadu** [google-map-react/google-map-react#772]
I am trying to setPadding to google maps using google-map-react, but I don't see any option to set so. 

https://developers.google.com/maps/documentation/android-sdk/map#map_padding

The exposed google map and maps object does not have setPadding option.

Just to be clear, I am not trying to set style padding. I am trying to set padding to the map so that any react child can avoid not visible areas.

**Comment by itsmichaeldiego** [comment]
@the-yadu You can access `map` object like in here https://github.com/google-map-react/google-map-react-examples/blob/master/src/examples/Main.js#L69 by using `onGoogleApiLoaded`, and then do `map.setPadding()` as stated by the documentation you shared

**Comment by the-yadu** [comment]
setPadding inside map object does not exist as you explained.
![image](https://user-images.githubusercontent.com/7404181/65382241-d6db5800-dd1d-11e9-83c9-bc85a0a8dd47.png)

**Comment by itsmichaeldiego** [comment]
@the-yadu I don't know what you're showing here, anything that you can do with google-maps itself you can do with this library, check [documentation here](https://github.com/google-map-react/google-map-react#use-google-maps-api) and just check google-map documentation, either with `map` or `maps` object you can access to all features from google maps

**Comment by GraceeFlower** [comment]
Hi @the-yadu, any process of the thing you mentioned below? I cannot use `setPadding` by `map.setPadding` as well, have you implemented that? Thank you!

**Comment by McGern** [comment]
Just checking, but are the people wanting to use setPadding trying to do this on a website or an android app? Just been looking at the setPadding only seems to be an android thing and isn't a method on the web api. Would love someone to prove me wrong though, because I want to put padding on the map to move the logo and terms of service stuff.
