### ISSUE TITLE
ADA Failing Elements

### ISSUE THREAD

**Issue by alexpolicastro** [google-map-react/google-map-react#775]
When running a ADA compliance audit I keep seeing this error.

**Image elements do not have [alt] attributes**

**Failing Elements**
`<img src="data:image/svg+xml,%3Csvg%20xmlns%3D%22http%3A%2F%2Fwww.w3.org%2F2000%2Fsvg%22%20width%3D%2218%22%20height%3D%2218%22%20viewBox%3D%220%20018%2018%22%3E%0A%20%20%3Cpath%20fill%3D%22%23666%22%20d%3D%22M0%2C0v2v4h2V2h4V0H2H0z%20M16%2C0h-4v2h4v4h2V2V0H16z%20M16%2C16h-4v2h4h2v-2v-4h-2V16z%20M2%2C12H0v4v2h2h4v-2H2V12z%22%2F%3E%0A%3C%2Fsvg%3E%0A" style="height: 18px; width: 18px;">`

Seems to be the map controls.

**Comment by ethanryan** [comment]
I'm seeing the same error as @alexpolicastro when running Lighthouse from the Audit tab in Chrome DevTools. 

![no-alt-attributes](https://user-images.githubusercontent.com/8107812/62876565-34c65a00-bcf3-11e9-8d97-118b40fbf53b.png)

This is affecting the scores for both Accessibility and SEO.

The issue appears to be these three svg images, which do not have [alt] attributes.

![google-map-react-svg-expand](https://user-images.githubusercontent.com/8107812/62876544-2aa45b80-bcf3-11e9-96cf-78a182a987b1.png)

![google-map-react-zoom-in-out](https://user-images.githubusercontent.com/8107812/62876551-2bd58880-bcf3-11e9-8fb9-94b1d20c66e3.png)

Lighthouse links to this page as a reference:

https://dequeuniversity.com/rules/axe/3.1/image-alt?application=lighthouse

 Providing an empty alt attribute for each of those `img` tags should resolve this issue, such as `alt=""`.

Or it could be more descriptive, such as:

`alt="full screen"`

`alt="zoom in"`

`alt="zoom out"`

**Comment by Tongboy** [comment]
Pretty sure those are google supplied components as part of the google maps API

You can test that by disabling the default UI in your component

something like:
```jsx
<GoogleMapReact
                    options={ {disableDefaultUI: true }}
                    onChange={this.handleMapChange}
                    bootstrapURLKeys={{ key: '' }}
                >
```

**Comment by alexpolicastro** [comment]
@ethanryan yeah found the same things. So I just disabled them, which actually works better anyway. @Tongboy yep.

Just silly they don't fix that on Google's end.

**Comment by itsmichaeldiego** [comment]
Hey guys, thanks for opening the discussion, but as this is an issue from google and not from our end, I need to close it.
