### ISSUE TITLE
fix Ensure text remains visible during webfont load" error on PageSpeed Insights

### ISSUE THREAD

**Issue by fdistorted** [google-map-react/google-map-react#776]
I am trying to optimize my web site.
looks like google-map-react adds link to style file with fonts (`<link type="text/css" rel="stylesheet" href="https://fonts.googleapis.com/css?family=Roboto:300,400,500,700|Google+Sans&display=swap">`).
Is it possible to change this link to `https://fonts.googleapis.com/css?family=Roboto:300,400,500,700|Google+Sans&display=swap` to prevent showing of "Ensure text remains visible during webfont load" error on PageSpeed Insights?

**Comment by itsmichaeldiego** [comment]
@fdistorted Yes it is possible, feel free to open a PR and I will make sure to merge it and release it, thanks in advance
