### ISSUE TITLE
Child mouse action function return event

### ISSUE THREAD

**Issue by eeliinaa** [google-map-react/google-map-react#777]
Hi, please can you return real event parameter for child action functions? 
These:
onChildMouseDown, 
onChildMouseUp, 
onChildMouseMove, 
onChildMouseEnter, 
onChildMouseLeave.
I need access to event.which to detect which mouse button is clicked. 
Thank you!

**Comment by itsmichaeldiego** [comment]
@eeliinaa Yes but we are all super busy so it will be faster if you submit a PR, I will try my best to merge it and release it as soon as possible

**Comment by itsmichaeldiego** [comment]
Please if you're still facing this issue open a new one with a live code example, thanks!
