### ISSUE TITLE
Add an option to not use the bootstrapURLKeys props

### ISSUE THREAD

**Issue by jacquesporveau** [google-map-react/google-map-react#779]
By not letting this prop be undefined you are forcing developers to use your script loading mechanism. It would be helpful to have that as a optional feature and if someone wants to load their script another way they should be able to do that.

**Comment by itsmichaeldiego** [comment]
@jacquesporveau I understand your point but that's the idea of our library, to make it super easy to add google maps, of course I am not against it, so PRs are welcome for this enhancement if you or someone else want to do it and need this feature
