### ISSUE TITLE
Issue setting minZoom, map renders correctly then jumps to a more zoomed in view after a second, unable to zoom back out.

### ISSUE THREAD

**Issue by bmtdh** [google-map-react/google-map-react#782]
Hi!
I know there are similar issues but everything I have tried hasn't worked. I am trying to effectively allow any zoom level to be reached. 

I have tried:
```
defaultZoom={1}
minZoomOverride={true}
minZoom={1} 
```

```
defaultZoom={0}
minZoomOverride={true}
minZoom={0} 
```

The map for a split second renders correctly then jumps back to a zoom level of around 3 and I am unable to zoom back out.
Any help would be greatly appreciated as I need to be able to see a view of the entire world.

**Comment by itsmichaeldiego** [comment]
@bmtdh Could you please provide a codesandbox? Its not possible to figure it out with this. But just for your info, this library doesn't work in "entire world" view, because of the calculation of markers.
