### ISSUE TITLE
Change lifecycle hook componentWillReceiveProps

### ISSUE THREAD

**Issue by Raz1990** [google-map-react/google-map-react#783]
Please update the library to not use componentWillReceiveProps:

![image](https://user-images.githubusercontent.com/30901390/64527362-69d3c580-d30e-11e9-8fe3-b77a47e742a6.png)

Text form:

Warning: componentWillReceiveProps has been renamed, and is not recommended for use. See https://fb.me/react-async-component-lifecycle-hooks for details.

* Move data fetching code or side effects to componentDidUpdate.
* If you're updating state whenever props change, refactor your code to use memoization techniques or move it to static getDerivedStateFromProps. Learn more at: https://fb.me/react-derived-state
* Rename componentWillReceiveProps to UNSAFE_componentWillReceiveProps to suppress this warning in non-strict mode. In React 17.x, only the UNSAFE_ name will work. To rename all deprecated lifecycles to their new names, you can run `npx react-codemod rename-unsafe-lifecycles` in your project source folder.

Please update the following components: GoogleMap

**Comment by itsmichaeldiego** [comment]
@Raz1990 I tagged this issue with help wanted, this is a collaborative library and PRS are welcome, thanks in advance

**Comment by tyxou** [comment]
if you're still looking for help, I'll be glad to take a look.

**Comment by itsmichaeldiego** [comment]
@tyxou That would be amazing thanks!

**Comment by sebalaini** [comment]
following, I have the same issue

**Comment by tyxou** [comment]
Terribly sorry for delay as I didn’t find this reply before now!! Will see how it can be fixed and revert.

On 04 Nov 2019, at 03:49, Michael Diego <notifications@github.com> wrote:

﻿

@tyxou<https://github.com/tyxou> That would be amazing thanks!

**Comment by yashank09** [comment]
Hello @tyxou ! I'm still facing the same warnings in my project. Any updates yet? :)

**Comment by tyxou** [comment]
I'm terribly sorry guys because I wasn't aware I was given permission to push changes (ie: to be compliant with React v16.3+). Will look it up and push asap. Again I'm terribly sorry and apologize for this mishap!!!

**Comment by tyxou** [comment]
Sincerely apologize as I haven't found the required time to resolve this issue. I'm 4 weeks behind deadline on a project I'm working on, and currently working against the clock! 
This issue is the 1st thing on my TODO list once I'm done with current project, but hopefully someone less busy might find time to rectify before.

**Comment by itsmichaeldiego** [comment]
@tyxou We sure can wait, thanks in advance!

**Comment by itsmichaeldiego** [comment]
Thanks @tyxou, hope someone comes in before, but it is nice to count on you if not!

**Comment by lanre-mark** [comment]
Hi @itsmichaeldiego @tyxou I still have the same warnings in my project. Any hope on solving this soon?

**Comment by itsmichaeldiego** [comment]
@lanre-mark We're looking for someone to create a PR with those changes :) @tyxou offered themself but I haven't seen any PR yet

**Comment by lanre-mark** [comment]
I forked the repo and ran these commands on the src folder npx react-codemod rename-unsafe-lifecycles but getting errors.

**Comment by lanre-mark** [comment]
I forked the repo and ran these commands on the src folder npx react-codemod rename-unsafe-lifecycles but getting errors.

**Comment by lanre-mark** [comment]
@itsmichaeldiego I forked the repo and ran these commands on the src folder `npx react-codemod rename-unsafe-lifecycles` but getting errors. 

I have attached a text file containing the errors, I haven't done this before but incase you understands the prompts you could provide further instructions and I'd be happy to make it work.
[google_map_react--codemod-report.txt](https://github.com/google-map-react/google-map-react/files/4659002/google_map_react--codemod-report.txt)

**Comment by lanre-mark** [comment]
@itsmichaeldiego Have you had a chance to look into this?

**Comment by itsmichaeldiego** [comment]
@lanre-mark If you take a quick dive into the code itself, you will see there's no need for you to run a codemode, `componentWillReceiveProps` its only used one time in here: [src/google_map.js#L305](https://github.com/google-map-react/google-map-react/blob/master/src/google_map.js#L305)

A while ago I've renamed `componentWillReceiveProps` to `UNSAFE_componentWillReceiveProps` to suppress this warning in non-strict mode. Did you have the chance to try again? Could you provide an screenshot or more context? Wondering why you're still getting the warning (if you are)?

If you or anyone would like to contribute, just updating this lifecycle method to use `componentDidUpdate` instead would do the work.

**Comment by HadeerFawzy** [comment]
Any updates on this issue?

**Comment by itsmichaeldiego** [comment]
@HadeerFawzy What is the problem you're facing?

**Comment by HadeerFawzy** [comment]
@itsmichaeldiego warning that I can't use `UNSAFE_componentWillReceiveProps` in strict mode.

**Comment by shivamjjha** [comment]
`index.js:1 Warning: Using UNSAFE_componentWillReceiveProps in strict mode is not recommended and may indicate bugs in your code. See https://fb.me/react-unsafe-component-lifecycles for details.

* Move data fetching code or side effects to componentDidUpdate.
* If you're updating state whenever props change, refactor your code to use memoization techniques or move it to static getDerivedStateFromProps. Learn more at: https://fb.me/react-derived-state

Please update the following components: GoogleMap`

**Comment by matteoATDY** [comment]
> `index.js:1 Warning: Using UNSAFE_componentWillReceiveProps in strict mode is not recommended and may indicate bugs in your code. See https://fb.me/react-unsafe-component-lifecycles for details.
> 
> * Move data fetching code or side effects to componentDidUpdate.
> * If you're updating state whenever props change, refactor your code to use memoization techniques or move it to static getDerivedStateFromProps. Learn more at: https://fb.me/react-derived-state
> 
> Please update the following components: GoogleMap`

I am getting this as well

**Comment by mukhtorov** [comment]
I know it is not good idea, but if you remove `<React.StrictMode>` in index.js. It'll work

**Comment by itsmichaeldiego** [comment]
We've already fixed this. Please update to latest version 👍

**Comment by itsmichaeldiego** [comment]
Let me know if it works folks!

**Comment by bobbyaxe61** [comment]
> Let me know if it works folks!

There is no version 2.1.6 in the npm library I get "No matching version found for google-maps-react@^2.1.6."

**Comment by itsmichaeldiego** [comment]
@bobbyaxe61 Probably was removed because it had an issue, If you do `npm install google-map-react@^` you will get the available versions. Please update to latest and lmk
