### ISSUE TITLE
onChildMouseEnter not triggered if child have not lat,lng.

### ISSUE THREAD

**Issue by Fi1osof** [google-map-react/google-map-react#785]
If child have no lat,lng props it's rendered in center of, but events onChildMouseEnter, onChildMouseLeave and onChildClick not triggered.

**Comment by itsmichaeldiego** [comment]
@Fi1osof Thanks for using this library, sadly, in our case, child must have lat and lng. 

If you want any help, please explain why you need this and give more detailed explanation, this is not the best way to open an issue.

**Comment by Fi1osof** [comment]
@itsmichaeldiego, scenario:
1. I add some child (and see them in center of map)
2. I drag this item and handle new lat,lng for them.
Profit.

Otherwise, for add new child with lat,lng i have to do React.cloneElement(element, {...center}); This is not useful.

**Comment by itsmichaeldiego** [comment]
@Fi1osof I see, well, you could provide a default lat and lng, right?

**Comment by Fi1osof** [comment]
@itsmichaeldiego for this i must know lat, lng. I can only from GoogleMapReact instance (which must be a parent), or pass callback (and i can not do this if not pass eventCallbacks into <GoogleMapReact />). This not useful.

**Comment by itsmichaeldiego** [comment]
@Fi1osof Yes but you know where your map is right? You must have a center for it? You can just place it on the coordinates of the center? 

This library expects you to to pass lat and lng, otherwise it won't work, but you can open a PR if you want. I will do my best to merge it and deploy it as soon as I can

**Comment by Fi1osof** [comment]
@itsmichaeldiego 
```
import React, { PureComponent } from 'react';

class MapWrapper extends PureComponent {

  render() {

    const {
      children,
    } = this.props;

    return (
      <GoogleMapReact
        defaultCenter={{
          lat: 34,
          lng: 34,
        }}
      >
        {children}
      </GoogleMapReact>
    );
  }
}

export default MapWrapper;
```

I do not know map center in upper component which pass children (especially when the map is moved with the mouse). Yes, i can add code above and will know, but now i did not.

```
This library expects you to to pass lat and lng, otherwise it won't work
```
But shows children in center of shown map.

**Comment by itsmichaeldiego** [comment]
@Fi1osof Ok yes they are rendered in the middle by default, and events should work as expected, not sure why they don't  to be honest, its clearly a bug
