### ISSUE TITLE
Draw polyline on map draw in google map react.

### ISSUE THREAD

**Issue by bhavikji** [google-map-react/google-map-react#787]
Hey folks, I am looking for the support for drawing polyline over the map as given in here:
[Zillow](https://www.zillow.com/homes/for_sale/1.0-_baths/?searchQueryState={%22pagination%22:{},%22usersSearchTerm%22:%22Pleasant%20Hill%20Falmouth%20ME%22,%22mapBounds%22:{%22west%22:-70.33858361694337,%22east%22:-70.19267144653321,%22south%22:43.67669512485485,%22north%22:43.753869073273215},%22isMapVisible%22:true,%22mapZoom%22:13,%22filterState%22:{%22hoa%22:{%22max%22:100},%22baths%22:{%22min%22:1},%22sortSelection%22:{%22value%22:%22days%22},%22parkingSpots%22:{%22min%22:2}},%22isListVisible%22:true}) As the user clicks on draw user enables to draw polyline over map and select the area of search. Is there any support for that?

**Comment by itsmichaeldiego** [comment]
@bhavikji Hey man! If you can do it with google maps, you can do it with this library, just need to access the `map` or `maps` object depending on which one you need, check [documentation here](https://github.com/google-map-react/google-map-react#use-google-maps-api)

**Comment by Orinameh** [comment]
> @bhavikji Hey man! If you can do it with google maps, you can do it with this library, just need to access the `map` or `maps` object depending on which one you need, check [documentation here](https://github.com/google-map-react/google-map-react#use-google-maps-api)

I think the issue here is that, the magic needs to be done inside onGoogleApiLoaded props which is called once(immediately the map renders). I currently face this issue as I can't draw a polyline when a marker is clicked as onGoogleApiLoaded must have been called by then. Any pointers to achieve this ?

**Comment by itsmichaeldiego** [comment]
@Orinameh You can capture the click and then use the `map` to draw the polyline, right?

**Comment by RafaelFerreiraTVD** [comment]
Also, you can save the map and maps objects to the state and use it everywhere 👍

**Comment by mohitgupta8767** [comment]
> > @bhavikji Hey man! If you can do it with google maps, you can do it with this library, just need to access the `map` or `maps` object depending on which one you need, check [documentation here](https://github.com/google-map-react/google-map-react#use-google-maps-api)
> 
> I think the issue here is that, the magic needs to be done inside onGoogleApiLoaded props which is called once(immediately the map renders). I currently face this issue as I can't draw a polyline when a marker is clicked as onGoogleApiLoaded must have been called by then. Any pointers to achieve this ?

I am also facing the same issue. How can i achieve this?

**Comment by pegues** [comment]
I'm experiencing the same problem.
