### ISSUE TITLE
🐛 Float Zoom levels are parsed to int - no incremental zooming

### ISSUE THREAD

**Issue by A-Tokyo** [google-map-react/google-map-react#788]
**Describe the bug 🐛**

- Setting the zoom level to floating point numbers doesn't work, the onChange is simply fired again parsing the float into an int.
- eg: setting zoom level to `11.2` will trigger an onChange with `11`

**To Reproduce 🔍**

1. set zoom level to 11.2
1. notice how the onChange is fired, overriding the 11.2 with 11

**Expected behavior 💭**

 zoom level should remain 11.2

**Screenshots 🖥**
- <img width="1054" alt="Screen Shot 2019-09-26 at 10 41 21 AM" src="https://user-images.githubusercontent.com/12428415/65672988-4321c880-e04a-11e9-9ab7-d00189610a1d.png">

**code example**:
- https://github.com/A-Tokyo/google-map-react-demos/blob/master/incremental-zoom/src/components/Map/Map.js

**Environment:**

 - OS: MacOS
 - Browser: chrome
 - Version: 77.0 (latest)

**Additional context**

Happy to help with a PR! but can't seem to understand where the process of parsing is happening, any pointers would help!

**Comment by itsmichaeldiego** [comment]
@A-Tokyo Sorry for the delayed answer, I think what you're looking for is [google_map.js#L365](https://github.com/google-map-react/google-map-react/blob/master/src/google_map.js#L365)

**Comment by A-Tokyo** [comment]
@itsmichaeldiego No worries!, I don't quite understand the answer :D So how can I make float point zooming points work? 🤔 I don't fully get what the line does

**Comment by itsmichaeldiego** [comment]
@A-Tokyo I pointed out to you where zoom is being handled so you can debug

**Comment by A-Tokyo** [comment]
@itsmichaeldiego Thanks! I get it now, will try to figure it out 💪🏼

**Comment by A-Tokyo** [comment]
@itsmichaeldiego I spent sometime on it and I am starting to think it's not available from GoogleMap's end. As far as I read, zoom level HAS to be an `int`.

It's clear tho that Google themselves are using floating point numbers as zoom levels on maps.google.com , maybe the feature is not out yet.

**Comment by itsmichaeldiego** [comment]
@A-Tokyo Thanks, I thought so too, when you double click in google maps, it goes 1 by 1, the difference is when you zoom on mobile, that it looks more smooth.

Okey so, let me know when you have some news, I will close the issue meanwhile.
