### ISSUE TITLE
A div is created around the map that doesn't take the parent containers height.

### ISSUE THREAD

**Issue by Ianohurr** [google-map-react/google-map-react#789]
**Describe the bug 🐛**
When the map is used, a div is placed around it that doesn't accept the parent containers height.
This div will accept the width, but will automatically make the height 0. Since this happens, the map will escape the parent container.

**To Reproduce 🔍**

1. Create a div with a fixed width and height
2. Place map in div with width:100% and height:100%

`<div style={{height:'500px',width:'500px'}}>
               <Map
                google={this.props.google}
                zoom={8}
                initialCenter={{ lat: 47.444, lng: -122.176}}
                style={{height:'100%',width:'100%'}}
                />
  </div>`

**Expected behavior 💭**

For the map to fill the container and not escape it

**Screenshots 🖥**

![pic of container](https://user-images.githubusercontent.com/10428220/65730172-ba208680-e075-11e9-80bf-84dca0e2d7fc.JPG)
![map escaping container](https://user-images.githubusercontent.com/10428220/65730173-bab91d00-e075-11e9-852e-2394b65cae83.JPG)

**Environment:**

 - OS: windows 10
 - Browser: firefox
 - Version: 69.0.1

I fixed this problem by setting an id on my parent container and setting the first div child of that container to height:100%.

`#mapBox div:first-child {
    position: relative !important;
    height: 100% !important;
}`

**Comment by langer-man** [comment]
Maybe you can combine it with  https://jinjilynn.github.io/#/

**Comment by sebalaini** [comment]
same problem here, there are too many useless `div` around the map,
here what I have to do to make the map fix the container created from the library.
I just insert the style manually and I didn't create yet the parent container that ideally would be called Contacts.

The first `div` doesn't have style be default, the second is set to `position:absolute` already

![Screenshot 2019-11-09 at 21 49 10](https://user-images.githubusercontent.com/17096352/68535661-9e2f2680-033d-11ea-8f2b-50ed11713a2f.png)

here the code I'm using at the moment.

`export class MapContainer extends Component {
  render () {
    return (
      <Map
        google={this.props.google}
        zoom={14}
        style={mapStyles}
        initialCenter={{
          lat: -1.2884,
          lng: 36.8233
        }}
      />
    )
  }
}`

**Comment by itsmichaeldiego** [comment]
You can just pass style prop to the component as you're doing, but you always need to set a fixed height to the parent.

I believe this work as expected, check our examples, they work perfectly without that hack you're doing.
