### ISSUE TITLE
Move marker(s) on touch enabled devices.

### ISSUE THREAD

**Issue by mesh-newbie** [google-map-react/google-map-react#792]
**Describe the bug 🐛**

Cant "drag" a marker on a touch-enabled device, though clicking within the space of the marker (icon) "does" move it after releasing finger.

**To Reproduce 🔍**

Create a map with a single marker that is draggable. 

1. Dragging on say a desktop, the marker follows the mouse.
2. Dragging on a touch-enabled device (e.g ipad, iphone/simulator) nothing happens during the drag "mousemove" event. [understandable given its a finger/touch and not a mouse]
3. Have set draggable={false} on map for testing.
4. Can see touch events when added manually... though granted its x,y and not lat/lng :-(
maps.event.addDomListener(window, "touchmove", ev => {
5. Have set gestureHandling: "greedy", scrollWheel: false, panControl: false on map options

**Expected behavior 💭**

Would like to be able to drag a marker around the map.

**Environment:**

 - OS: [ iOS / mac os / android]
 - Browser [chrome, safari]
 - Version [latest]

**Additional context**

May not be possible to achieve this because of the google maps api and how it handles touch events. :-( Google searching didn't give any exact answers.

**Comment by itsmichaeldiego** [comment]
@mesh-newbie Is this a problem you're facing with our library, or a problem with google maps itself? Have you tried doing so in pure google maps?

**Comment by mesh-newbie** [comment]
hi @itsmichaeldiego . tbh i don't recall as this was noted 12 months ago.

**Comment by itsmichaeldiego** [comment]
@mesh-newbie Ok! Yeah sorry I was not that active back then and seems that it escaped my fingers.

**Comment by andreitopli** [comment]
@itsmichaeldiego I am having the same issue currently, where on mobile view I cannot trigger `onChildMouseMove` and if I add the eventListener manually then there's no access to lat/lng. Not sure how to get around this. Any help ?
