### ISSUE TITLE
Maker offset when zoom out

### ISSUE THREAD

**Issue by JerryMissTom** [google-map-react/google-map-react#794]
Thanks for this project. I come across a bug when render  Icon Maker  in Google map. when zoom in, the maker in right  position, but the  maker will have offset when zoom out. The screenshot pics are as follows:
First pic, the maker is in the sea.
![屏幕快照 2019-10-10 下午4 40 38](https://user-images.githubusercontent.com/15966403/66553007-ee6b6b00-eb7c-11e9-9bfe-2eb21fb70694.png)
In fact, the real position is on the land when zoom in
![屏幕快照 2019-10-10 下午4 41 25](https://user-images.githubusercontent.com/15966403/66553055-02af6800-eb7d-11e9-9890-aa2c28dccfd9.png)
The code as follows:
```
const GoogleMapMaker = () => <Icon type="environment" theme="filled" />
...
 <GoogleMapReact
         ...
         zoom={5}
        options={{ gestureHandling: 'greedy' }}
   >
     <GoogleMapMaker lat={location.latitude} lng={location.longitude} /> 
 </GoogleMapReact>
```

**Comment by itsmichaeldiego** [comment]
@JerryMissTom This is in the docs: https://github.com/google-map-react/google-map-react/blob/master/API.md#positioning-a-marker

**Comment by JerryMissTom** [comment]
@itsmichaeldiego Thanks a lot, you do  me a big favor

**Comment by itsmichaeldiego** [comment]
@JerryMissTom No worries man!

**Comment by Daniel-Griffiths** [comment]
Adding ` transform: translate(-50%, -50%)` on the marker fixed it for me too 😄

**Comment by itsmichaeldiego** [comment]
Do you guys think it would make sense to change default position to that one? I think it does, or at least bottom-center like default marker...

**Comment by JerryMissTom** [comment]
In my opinion, when zoom in or out, it is better that the marker has no offset. But maker or requirement is different in different project, we will change default position in some scenario.
