### ISSUE TITLE
Marker positions change with zoom

### ISSUE THREAD

**Issue by peterwdj** [google-map-react/google-map-react#796]
**Describe the bug 🐛**
The position of the markers on the map is different at different zoom levels. 

**To Reproduce 🔍**

1. Pass in a custom marker to the map:
```
    <div className='Office-map-container'>
      <GoogleMapReact
        bootstrapURLKeys={{ key: process.env.REACT_APP_GOOGLE_MAPS_API_KEY || '' }}
        defaultCenter={{
          lat: 51.551486,
          lng: -0.051235399999995934
        }}
        defaultZoom={12}
      >
        <MapMarker
          lat={51.551486}
          lng={-0.051235399999995934}
        />
      </GoogleMapReact>
    </div>
```
2. Run your local server, and visit the page rendering the map
3. Change zoom level in and out
4. See position of marker changing with zoom level

A live example helps a lot! 

**Expected behavior 💭**
The marker should remain in the same position on the map, regardless of zoom level.

**Screenshots 🖥**
Exaggerated zoom to demonstrate the issue more clearly; the marker should be in north-east London, but zoomed out, the position changes (here, in France)

![Screenshot 2019-10-10 at 22 08 30](https://user-images.githubusercontent.com/27166958/66606925-03f78980-ebab-11e9-81ad-95237392360c.png)
![Screenshot 2019-10-10 at 22 09 13](https://user-images.githubusercontent.com/27166958/66606926-03f78980-ebab-11e9-99c4-3c4b30cd2a3c.png)

**Environment:**

 - OS: Linux (Ubuntu Unity, 16.04)
 - Browser: Chrome
 - Version v1.1.5

**Comment by peterwdj** [comment]
This can be closed! I've realised that this was due to issues with positioning the top left of the marker at the lat lang - rather than the bottom centre that I really need it to be.

Sorry for any waste of time!

**Comment by kisildev** [comment]
Hello, I have a similar problem, when I move or scale the map, the marker remains in the center of the map, but it must be attached to a specific point. Could you help to understand what the problem is?

**Comment by itsmichaeldiego** [comment]
@peterwdj No problem, I am glad you found the issue, I think at some point we should position the markers on the center by default
