### ISSUE TITLE
Could use help on some really slow list scrolling/rendering with mouseovers (and changing the map according to hover state)

### ISSUE THREAD

**Issue by kpennell** [google-map-react/google-map-react#798]
I love google-maps-react and have used it for many projects. 

I'm stuck on how to handle a large dataset efficiently. I have a list of items and then map pins that correspond to those items. When one hover on the list, the map icon opens. This is the way many popular maps work. The user hovers on the list item and the map changes color or an info window pops open. But the way I have this setup in React currently just isn't working. So I have a parent list:

    <div className={classes.parentList}>
    
    {filtereditems.map((item, index) => (
    <ShowCard
    key={index}
    item={item}
    setCardMarkerHover={this.setCardMarkerHover}
    resetCardMarkerHover={this.resetCardMarkerHover}
    />
    ))}
    </div>;
    

Then, within my List items, I call the prop functions like so

    onMouseEnter={e => props.setCardMarkerHover(item.node.id)}
    onMouseLeave={e => props.resetCardMarkerHover()}

These functions `setCardMarkerHover` and `resetCardMarkerHover` call setState, which then rerenders everything(!) so that my map markers change. The infowindow pops open on the right marker. Here are the functions:

    setCardMarkerHover = id => {
    this.setState({
    hoveredCardId: id,
    })
    }
    
    resetCardMarkerHover = () => {
    this.setState({
    hoveredCardId: "",
    })
    }

`hoveredCardId` then gets passed to the Map and Markers (pins), and they change according to whether that marker matches the same index/id for the list items being hovered. The challenge, as you can likely imagine, is that this really bogs my list down. It no longer scrolls smoothly because so many parts of the DOM are having to repaint/rerender as the mouse enters and exits the different list items. React-virtualized solves this problem through `windowing` but this seems like extreme overkill. What would another way to be able to hover on a child list item and have it change something else in another child component without triggering so much repainting?

**Comment by itsmichaeldiego** [comment]
@kpennell This is related on how to use React and mount/unmounting objects and not to the library itself, I think StackOverflow would be a better place for this, as this is for issues / bugs or new features

**Comment by kpennell** [comment]
Fair. Ok.

**Comment by itsmichaeldiego** [comment]
@kpennell You might even have more chances of being helped as SO has more subscribers than to this library
