### ISSUE TITLE
Nearby places API

### ISSUE THREAD

**Issue by Multi-Thinker** [google-map-react/google-map-react#801]
is there a way/component/API to use or have places API for nearby feature (if there is some react component or react way to do this with google-map-react)? or should people switch to vanilla JS with "yesIWantToUseGoogleMapApiInternals" just after doing map in react, almost kills whole purpose of doing map in react if we have to use Vanilla JS again.

**Comment by itsmichaeldiego** [comment]
@Multi-Thinker Your question is quite confusing, I am pretty sure you can formulate this better explaining what do you want to accomplish? Provide an example also of what you want to do

**Comment by chrismclarke** [comment]
I think I've just come across the same issue, so for clarity:

Google provides an additional api to interact with it's `places` library, such as searching for nearby points of interest on the map. In order to enable this SDK, an additional query parameter `&libraries=places` needs to be passed into the script loader, i.e.:
```
<script type="text/javascript" src="https://maps.googleapis.com/maps/api/js?key=YOUR_API_KEY&libraries=places"></script>
```
Is there a way currently to include this?

**Comment by chrismclarke** [comment]
To answer the question, you can simply add the parameter to the `bootstrapURLKeys` method, i.e.
```
bootstrapURLKeys={{ key: API_KEY, libraries: "places" }}
```

**Comment by abidRahim** [comment]
@chrismclarke 
I'm trying to do this, this should work, right ?
```
bootstrapURLKeys={{
    libraries: ['geometry', 'places'],
    key: API_KEY
}}
```
Because i need both `geometry` and `places` library. Geometry seems to be working fine but getting `undefined` for  places  library

**Comment by chrismclarke** [comment]
Should do, I have some old code working with places and visualization libs:
```
<GoogleMapReact
          bootstrapURLKeys={{
            key: apiKey,
            libraries: ["places", "visualization"]
          }}
          center={center}
          defaultZoom={zoom}
          yesIWantToUseGoogleMapApiInternals
          onGoogleApiLoaded={({ map, maps }) => this.apiIsLoaded(map, maps)}
        >
```
If you still can't get it working you might want to create an online code sandbox or similar and troubleshoot either here or StackOverflow.
