### ISSUE TITLE
Responsive infowindow

### ISSUE THREAD

**Issue by r0jx0** [google-map-react/google-map-react#804]
First of all, this is not a bug, but I have troubles find a solution to a problem with google-map-react, and I don't know whereelse I can ask for a solution.

I'm trying to make an infowindow but the content of it is not always the same, so it makes the infowindow be bigger of smaller and they are not positioned  into the marker. How  can I make the infowindow appear always into the marker regardless of the content of it.

Thank you in advance and sorry again for the using the bug report system to ask a question.

**Comment by itsmichaeldiego** [comment]
Please provide a live example so we can help you, thanks!
