### ISSUE TITLE
Margin prop usage

### ISSUE THREAD

**Issue by akfzambrana** [google-map-react/google-map-react#807]
I'm trying to pass an array of numbers to this prop and I can't understand how it works.
I tried to pass something like this `margin:{[0, 0, 0, 100]};`
What I need is to pass a value to move the "center" of the map to right leaving some space on the left free. Can you please help me to understand how this prop works? or can you provide some example of how to use?

**Comment by QuintonPang** [comment]
Have you figured it out yet?
