### ISSUE TITLE
Searchbox problem in modals

### ISSUE THREAD

**Issue by mimre73** [google-map-react/google-map-react#808]
when put map in modals and want to search a place result shown behind of modal!
[
![zxcs](https://user-images.githubusercontent.com/43402867/68068682-a3540a80-fd6c-11e9-84a9-c0fcab78223f.png)
](url)
any solution?

**Comment by itsmichaeldiego** [comment]
@mimre73 Might be a `z-index` issue? Please provide a live example otherwise I cannot be of further help!

**Comment by smartdev10** [comment]
this is the solution

```
.pac-container {
  z-index: 1100 !important;
}
```
