### ISSUE TITLE
ImageOverlay?

### ISSUE THREAD

**Issue by msaracevic** [google-map-react/google-map-react#812]
I am evaluating this library for an project. The markers are awesome, but I can't find info about Ground Overlays.

While the initial idea was that I could probably use custom marker which could do the same thing, the problem comes when trying to position the overlay correctly. Markers seem to support center property only, where as ground overlay supports corners and then aligns the image on map

```
LatLngBounds(
        new LatLng(40.712216, -74.22655),       // South west corner
        new LatLng(40.773941, -74.12544)        // North east corner
);
```

Is there an example how to be able to use [Ground Overlays](https://developers.google.com/maps/documentation/javascript/groundoverlays)?

**Comment by itsmichaeldiego** [comment]
@msaracevic You can use `onGoogleAPILoaded` and access the `map` or `maps` object, then you can do anything that you can do with regular gmaps, [link here](https://github.com/google-map-react/google-map-react/blob/master/API.md#ongoogleapiloaded-func)
