### ISSUE TITLE
Does this library supports custom maps? 

### ISSUE THREAD

**Issue by AdiBev** [google-map-react/google-map-react#814]
Hi, I need to create custom map and custom marker. I know I can add custom markers here I was wondering if I can do the same with map. I'm importing json styles from here https://mapstyle.withgoogle.com/ and I want to apply this on the map. If this map have this support can you point me to the right direction? 
Thank you

**Comment by itsmichaeldiego** [comment]
@AdiBev Yes you can pass the options on `styles`

```
createMapOptions: function (maps) {
    return {
      panControl: false,
      mapTypeControl: false,
      scrollwheel: false,
->  styles: [{ stylers: [{ 'saturation': -100 }, { 'gamma': 0.8 }, { 'lightness': 4 }, { 'visibility': 'on' }] }]
    }
  }

 <GoogleMap  options={createMapOptions} ... />
```
