### ISSUE TITLE
Change language

### ISSUE THREAD

**Issue by SpiritOfSpirt** [google-map-react/google-map-react#816]
**Describe the bug 🐛**

I want to dynamically change language on page and on map.

**To Reproduce 🔍**

Change language in 
      bootstrapURLKeys={{ 
                                key: myKey,
                                language: this.state.lang,
                            }}

**Expected behavior 💭**

When I change state map should change language on the screen

**Environment:**

 - OS: windows
 - Browser: chrome (Brave)
 - Version: 1.0.1 Chromium: 78.0.3904.108

**Additional context**

If I pressed F5 the map change language. But if I forceUpdate (or just update the state) it won't change language. When I look at "https://maps.googleapis.com/maps/api/js/ViewportInfoService"
in parameters I found 4sen, but it should be 4suk or 4sru (when I changed the state).

**Comment by itsmichaeldiego** [comment]
@SpiritOfSpirt That's because the initial load of the map (the <script>`) is already loaded, best thing you can do is to reload the page when changing language

**Comment by itsmichaeldiego** [comment]
@SpiritOfSpirt Follow up in #949
