### ISSUE TITLE
CORS issues for second component

### ISSUE THREAD

**Issue by archydeberker** [google-map-react/google-map-react#818]
**Describe the bug 🐛**

I'm seeing the same error as in https://github.com/google-map-react/google-map-react/issues/491, but only after I add a *second component* that uses google-map-react.

**To Reproduce 🔍**

1. Add a component that uses react google map
2. It works fine
3. Add a second
4. Doesn't work! I get the CORS error identified in https://github.com/google-map-react/google-map-react/issues/491

A bit of investigation suggests that the first all to Google Maps is made *without* an `Origin` in the header, but a subsequent one has the `Origin`, and that's where the problems begin...

<img width="890" alt="image" src="https://user-images.githubusercontent.com/9258253/70011413-e6a6c200-1540-11ea-8d63-3a82d3e3abd2.png">
<img width="686" alt="image" src="https://user-images.githubusercontent.com/9258253/70011677-ef979380-1540-11ea-91b5-61b38c70c82a.png">

**Expected behavior 💭**

Both calls to work as expected

**Environment:**

 - OS: Mac
 - Browser: Chrome
 - Version: 1.1.4

**Additional context**

The solution suggested in https://github.com/google-map-react/google-map-react/issues/491
is to check that there are no restrictions on the Google Maps API itself. I can confirm this is the case.

**Comment by DanceParty** [comment]
Could this possibly be related to having two google object instances? I remember facing something similar a while back when I was trying to use this library and streetview together.

**Comment by itsmichaeldiego** [comment]
I think this is related to having two object instances yes, can't you fix it by just mounting / unmounting?

**Comment by itsmichaeldiego** [comment]
I think this is related to having two object instances yes, can't you fix it by just mounting / unmounting?

**Comment by archydeberker** [comment]
Yes, I think that's what it was! The super confusing part was that I was mistakenly using a second component from the similarly named https://github.com/tomchentw/react-google-maps, which produced this weird assymetric behaviour. I'll close this issue.

**Comment by itsmichaeldiego** [comment]
@archydeberker I am glad you found a solution!
