### ISSUE TITLE
Issue with bounds longitude with supercluster and google-map-react.

### ISSUE THREAD

**Issue by alex-semenyuk** [google-map-react/google-map-react#819]
I use this example https://github.com/istarkov/google-map-clustering-example. I have the problem when I'm moving map to right or left from initial position - my clusters are disappearing. I see that bounds longitude is changed in wrong way on moving. It doesn't work starting with 1.0.5 till 1.1.5 google-map-react.  
cc:@istarkov
Thanks!

**Comment by satyendrasingh092** [comment]
Facing the same issue. Is there a way to come out of it

**Comment by alex-semenyuk** [comment]
@satyendrasingh092 You can consider workround - always send the same boundary values for longitude and latitude [-180, -85, 180, 85] and different zoom.

**Comment by itsmichaeldiego** [comment]
It should work fine on new versions, let me know if that's not the case, if so, lets open a new issue with more detailed info and a live example, so we can help you out!
