### ISSUE TITLE
Is there any way to update the circle's center using state?

### ISSUE THREAD

**Issue by tosifkhan01** [google-map-react/google-map-react#820]
Basically my aim is to draw a circle and change it's center on state change.

**The problem I'm facing is "onGoogleApiLoaded" is called only once, I'm not able to call this function or change the radius or circle on state update, is there any way I can achieve my goal?**

        <GoogleMapReact
          bootstrapURLKeys={{ key: process.env.GOOGLE_API_KEY }}
          center={this.state.center}
          zoom={this.state.zoom}
          onGoogleApiLoaded={({map, maps}) => {
              new google.maps.Circle({
              strokeColor: '#FF0000',
              strokeOpacity: 0.8,
              strokeWeight: 2,
              fillColor: '#FF0000',
              fillOpacity: 0.3,
              map,
              center: this.state.center, //{lat:22.704892, lng:75.909964}
              radius:this.state.radius //800,
          })
          }}
          yesIWantToUseGoogleMapApiInternals={true}
          >
             <MyChildComponent/>
       </GoogleMapReact>

**Comment by markom983** [comment]
Any info about this problem? How to render again google map to get new radius value?

**Comment by karldanninger** [comment]
@tosifkhan01 and @markom983 could you explain a little more? You can store `maps` and `map` variables to use _outside_ this function. Just store both of those variables somewhere.

From your example I can see you are using `new google.maps.Circle` when you should be using `new maps.Circle`

**Comment by tosifkhan01** [comment]
> Any info about this problem? How to render again google map to get new radius value?

@markom983 you can do it by using the key in GoogleMapReact component and then update the key whenever you want to change the radius, I couldn't find any other way to do it.

**Comment by tosifkhan01** [comment]
> @tosifkhan01 and @markom983 could you explain a little more? You can store `maps` and `map` variables to use _outside_ this function. Just store both of those variables somewhere.
> 
> From your example I can see you are using `new google.maps.Circle` when you should be using `new maps.Circle`

@karldanninger you can do store those variables if you want to use them outside.

I followed Maps JavaScript API, to create a circle using new google.maps.Circle
have a look at the documentation.

https://developers.google.com/maps/documentation/javascript/examples/circle-simple#maps_circle_simple-javascript

```
  // Construct the circle for each value in citymap.
  // Note: We scale the area of the circle based on the population.
  for (const city in citymap) {
    // Add the circle for this city to the map.
    const cityCircle = new google.maps.Circle({
      strokeColor: "#FF0000",
      strokeOpacity: 0.8,
      strokeWeight: 2,
      fillColor: "#FF0000",
      fillOpacity: 0.35,
      map,
      center: citymap[city].center,
      radius: Math.sqrt(citymap[city].population) * 100
    });
  }

```

**Comment by karldanninger** [comment]
@tosifkhan01 You are using the wrong instance of `google` which is outside the context of this library.

If you want a hook to **update** (like what you are originally asking for) then you need to use the instance of `maps` **from this package**, and **not** `google`.

I hope that is clear.

**Comment by karldanninger** [comment]
```
import React, { useState, useEffect } from "react";
import GoogleMapReact from "google-map-react";

export default function App() {
  const [mapReference, setMapReference] = useState(null);
  const [mapsReference, setMapsReference] = useState(null);

  useEffect(() => {
    if (mapReference && mapsReference) { // if not null
      const myCircle = new mapsReference.Circle({
        strokeColor: "#FF0000",
        strokeOpacity: 0.8,
        strokeWeight: 2,
        fillColor: "#FF0000",
        fillOpacity: 0.3,
        mapReference,
        center: { lat: 22.704892, lng: 75.909964 },
        radius: 800
      });
    }
  }, [mapReference, mapsReference]);

  return (
    <div
      className="App"
      style={{ height: 400, width: 400, backgroundColor: "pink" }}
    >
      <GoogleMapReact
        onGoogleApiLoaded={({ map, maps }) => {
          setMapReference(map);
          setMapsReference(maps);
        }}
        yesIWantToUseGoogleMapApiInternals={true}
      ></GoogleMapReact>
    </div>
  );
}
```

This will give you more flexibility when to update using hooks.

**Comment by tosifkhan01** [comment]
> ```
> import React, { useState, useEffect } from "react";
> import GoogleMapReact from "google-map-react";
> 
> export default function App() {
>   const [mapReference, setMapReference] = useState(null);
>   const [mapsReference, setMapsReference] = useState(null);
> 
>   useEffect(() => {
>     if (mapReference && mapsReference) { // if not null
>       const myCircle = new mapsReference.Circle({
>         strokeColor: "#FF0000",
>         strokeOpacity: 0.8,
>         strokeWeight: 2,
>         fillColor: "#FF0000",
>         fillOpacity: 0.3,
>         mapReference,
>         center: { lat: 22.704892, lng: 75.909964 },
>         radius: 800
>       });
>     }
>   }, [mapReference, mapsReference]);
> 
>   return (
>     <div
>       className="App"
>       style={{ height: 400, width: 400, backgroundColor: "pink" }}
>     >
>       <GoogleMapReact
>         onGoogleApiLoaded={({ map, maps }) => {
>           setMapReference(map);
>           setMapsReference(maps);
>         }}
>         yesIWantToUseGoogleMapApiInternals={true}
>       ></GoogleMapReact>
>     </div>
>   );
> }
> ```
> 
> This will give you more flexibility when to update using hooks.

@karldanninger Thanks man (y)
