### ISSUE TITLE
Types for "meters2ScreenPixels" (typescript)

### ISSUE THREAD

**Issue by JamieS1211** [google-map-react/google-map-react#821]
**Is your feature request related to a problem? Please describe 🙏**
I am trying to use the "meters2ScreenPixels" function exported from the utils section of the project however there is not types exported from @types/google-map-react for this. Issue #753 is the same kind of issue however in that instance there was a workaround you mentioned via using the google maps api for this. I have had a fiddle but can't get anything to work. I also have had a look at @types/googlemaps where the types are supplied in the workaround and can't see anything relating to "meters2ScreenPixels" hence I can only assume this workaround won't work.

**Describe the solution you'd like 🤔**
Any workaround solution that you know of or for inclusion of this type int he @types/google-maps-react lib

**Describe alternatives you've considered ✨**
Workaround as mentioned

**Additional context**
Error message"
Could not find a declaration file for module 'google-map-react/utils'. '/Users/user/Documents/project/node_modules/google-map-react/utils/index.js' implicitly has an 'any' type.
  If the 'google-map-react' package actually exposes this module, consider sending a pull request to amend 'https://github.com/DefinitelyTyped/DefinitelyTyped/tree/master/types/google-map-react`ts(7016)

Many thanks for reading, hope this is in the right section.

**Comment by itsmichaeldiego** [comment]
Can you provide the fiddle? Otherwise its too hard to be able to help! Thanks

**Comment by JamieS1211** [comment]
The issue was that the types from @types/google-map-react had no types for the utils functions.

I made a commit to the types that has since been merged fixing the issue

https://github.com/DefinitelyTyped/DefinitelyTyped/pull/41598
https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/google-map-react/utils.d.ts

**Comment by itsmichaeldiego** [comment]
@JamieS1211 Can you created a PR with that? Thanks in advance

**Comment by JamieS1211** [comment]
The pull request is for the Defiantly typed project augmenting this package for typescript. The first link in my previous message was the pull request to that project that has been merged.
