### ISSUE TITLE
Dynamically changed markers doesn't apply on the map

### ISSUE THREAD

**Issue by michalica** [google-map-react/google-map-react#825]
**Describe the bug 🐛**

I am using arround 1000 markers that are clustered. I used this example: 
https://github.com/Tim152/clustering-google-map-react

When I change state to 500 markers render method of component is executed but GoogleMap component is not updated. 

**To Reproduce 🔍**

Codesandbox with issue: 
https://codesandbox.io/s/google-clustering-map-7m588

To rerpoduce: Click on "small data" button. Nothing happend but if you zoom the map it will get updated

**Expected behavior**
GoogleMap component should update immediately after state is changed

**Comment by isharifyltd** [comment]
same here too

**Comment by itsmichaeldiego** [comment]
@michalica Did you find the solution? Does @isharifyltd's solution works for you?
