### ISSUE TITLE
Uncaught TypeError: Cannot read property 'overlayMouseTarget' of null

### ISSUE THREAD

**Issue by abidRahim** [google-map-react/google-map-react#829]
**Cannot read property 'ovelayMouseTarget' of undefined**
Received this bug from bugSnag.

This seems to be from the file /google-map-react/dist/GoogleMapReact.js
line number : 1338
        `var panes = this.getPanes();`
        `panes.overlayMouseTarget.appendChild(div);`

**Environment:**

 - OS: Windows 10
 - Browser: Chrome
 - Version: 79.0.3945

**Comment by sabotag** [comment]
I have a same problem
