### ISSUE TITLE
grid on map

### ISSUE THREAD

**Issue by Stevemoretz** [google-map-react/google-map-react#831]
Hi I'm using your library and am trying to put a gird on a map.Couldn't find a way to do this yet. What I mean is to grid 10 meteres by 10 meters for example.so I can click on each cell and get the center lat and lon.
https://i.stack.imgur.com/mtHUF.png
The live example is here : https://what3words.com/blame.crash.pace How am I supposed to make this grid?Please help thank you so much in advance

**Comment by itsmichaeldiego** [comment]
Did you try using google api? https://github.com/google-map-react/google-map-react#use-google-maps-api
