### ISSUE TITLE
How to access Google Maps ref? Can I fit the bounds with the ref?

### ISSUE THREAD

**Issue by adithyamaheshb** [google-map-react/google-map-react#833]

**Comment by EGoldbergM** [comment]
You should save state for map onGoogleApiLoaded, then fitbounds with ref when you need

            <GoogleMapReact
              bootstrapURLKeys={{ key: '' }}
              defaultCenter={center}
              defaultZoom={defaultProps.zoom}
              yesIWantToUseGoogleMapApiInternals
              onGoogleApiLoaded={({ map, maps }) => handleApiLoaded(map, maps)}
              onChange ={({ bounds }) => handleOnChange(bounds)}                  
            >

       const [myMap, setMyMap] = useState(null);
       const fitBounds = (map) => {
          const bounds = new window.google.maps.LatLngBounds();
          myPlaces.map(place => {
            bounds.extend(place.pos);
            return place.id;
          });
          map.fitBounds(bounds);          
        };
    
        const handleApiLoaded = (map, maps) => {
            setMyMap(map)
            fitBounds(map);
        };

        const handleOnChange = (bounds) => {
                if (bounds.nw.lat >= 45 || bounds.se.lat <= -85) {
                    fitBounds(myMap);
                }
         };

**Comment by ziaulrehman40** [comment]
@EGoldbergM getting this:
```
index.jsx:28 Uncaught TypeError: Cannot read property 'fitBounds' of null
    at fitBounds (index.jsx:28)
    at handleOnChange (index.jsx:38)
    at Object.onChange (index.jsx:98)
    at GoogleMap._this._onBoundsChanged (google_map.js:733)
    at GoogleMap._this._initMap (google_map.js:234)
    at google_map.js:909
```

**Comment by karldanninger** [comment]
Hey @ziaulrehman40, have you tried this?

```
const mapBounds = { south: -90, west: 180, north: 90, east: -180 };

 <GoogleMapReact
   onGoogleApiLoaded={({ map, maps }) => {
      map.fitBounds(mapBounds);
   }
  ...
/>
```

If you have a basic reproduction, that would help me help you a lot :)

**Comment by ziaulrehman40** [comment]
I have managed to get it to work by saving map ref from onGoogleApiLoaded, and when I have data of pointers, i call `fitBounds` from @EGoldbergM 's comment to adjust center of the map as per pointers.

Is simple enough, only if i had seen documentation(is there proper documentation for these methods?)

Also this should be closed

**Comment by karldanninger** [comment]
The beauty of this package is most API's you will be interacting with are in those 2 objects from within `ongoogleApiLoaded` most documentation you will need to interact with is the Google Maps Javascript API.

For anyone coming across this issue, look here https://github.com/google-map-react/google-map-react#use-google-maps-api

**Comment by itsmichaeldiego** [comment]
Thanks @karldanninger
