### ISSUE TITLE
How to stop maps from loading Roboto font

### ISSUE THREAD

**Issue by hc-codersatlas** [google-map-react/google-map-react#836]
Hi, for users that already use Roboto or don't want to is there a way to stop it from loading? Google maps loads a particular version, which is just more to download for no reason when a site usually has its own fonts setup already. Thanks.

**Comment by imollov** [comment]
This worked for me: https://gist.github.com/boffey/8516b0091649161cb09e244d63076256

**Comment by jshikanova** [comment]
Hello, is there any proper solution to fix this issue? Roboto is my default font and google-map-react inserting it into head breaks font-weight of material-ui Typography components for some reason
Thanks in advance

**Comment by Neuromancer93** [comment]
I too am having this issue. Is there a verified solution for React?

**Comment by lh15** [comment]
I added the script from @imollov at the bottom of the body and it worked fine. (Still kind of annoying though)
