### ISSUE TITLE
Marker not showing on street view

### ISSUE THREAD

**Issue by hashmatmuqbil** [google-map-react/google-map-react#838]
**Describe the bug 🐛**

**To Reproduce 🔍**

A live example helps a lot! 

**Expected behavior 💭**

**Screenshots 🖥**

**Environment:**

 - OS: [e.g. iOS / windows / mac / android]

**Additional context**

**Comment by swkidd** [comment]
#762 

You can add markers to streetview if you use the api internals prop
https://developers.google.com/maps/documentation/javascript/examples/streetview-overlays

note: explicitly calling maps.getStreetView() charges as 'dynamic street view' (as of writing $14 / 1000 requests) as opposed to 'static street view' ($7 / 1000).
https://developers.google.com/maps/documentation/javascript/usage-and-billing

`...

const handleApiLoaded = (map, maps) => {
  // add markers to panorama 
};

...

<GoogleMapReact
  bootstrapURLKeys={{ key: /* YOUR KEY HERE */ }}
  defaultCenter={this.props.center}
  defaultZoom={this.props.zoom}
  yesIWantToUseGoogleMapApiInternals
  onGoogleApiLoaded={({ map, maps }) => handleApiLoaded(map, maps)}
>
  <AnyReactComponent
    lat={59.955413}
    lng={30.337844}
    text="My Marker"
  />
</GoogleMapReact>`


I might be trying to implement this in the future. Any ideas?  What files in this library would provide a good starting point?
