### ISSUE TITLE
load map with respect to marker in center. On page load I have multiple markers as per location and when I am clicking on particular location, my map is not loading my selected location in Center. 

### ISSUE THREAD

**Issue by aman0591** [google-map-react/google-map-react#839]

**Comment by anthonyvespoli** [comment]
you can add the center prop to the google map component and it will update when the values update. it takes an object param ```{lat: 11.1, lng: 11.1}```

**Comment by simplenotezy** [comment]
@anthonyvespoli Unfortunately this does not seem to work in the latest version.
