### ISSUE TITLE
Return wrong boundary when crossing longitude -180

### ISSUE THREAD

**Issue by ampup-tott** [google-map-react/google-map-react#840]
**Describe the bug 🐛** Version [1.1.6]
Google Map React returns wrong boundaries when I scroll the map to cross -180 longitude. After crossing -180 longitude, all locations on Earth are returned completely inaccurate 

**Environment:**

 - OS: [e.g. Linux]
 - Browser [e.g. chrome]

- Scroll to Border longitude -180
![image](https://user-images.githubusercontent.com/58297510/75951966-f6d39200-5edf-11ea-96c7-92eaba5f8a87.png)

- get wrong boundary at America
![image](https://user-images.githubusercontent.com/58297510/75952070-38fcd380-5ee0-11ea-9c6a-a24879e1f444.png)

If you rotate map some round (east -> west) -> longitude can be > 600

**Comment by jasonperrone** [comment]
This issue is marked a closed but I am seeing the same issue now on the latest version of this app.

**Comment by jasonperrone** [comment]
@ampup-tott Did you figure something out?

**Comment by jasonperrone** [comment]
@ampup-tott Can you tell me why you closed this issue?

**Comment by WaveRunning** [comment]
hello，Is this issue resolved?
