### ISSUE TITLE
API key security risk using .env

### ISSUE THREAD

**Issue by TS22082** [google-map-react/google-map-react#846]
If you follow the docs on homepage 

```javascript
      <div style={{ height: '100vh', width: '100%' }}>
        <GoogleMapReact
          bootstrapURLKeys={{ key: /* YOUR KEY HERE */ }}
          defaultCenter={this.props.center}
          defaultZoom={this.props.zoom}
        >
          <AnyReactComponent
            lat={59.955413}
            lng={30.337844}
            text="My Marker"
          />
        </GoogleMapReact>
      </div>
```
you are hard coding your api key client on the client side.

The best you could do is hide this in a .env file like

```javascsript
client/.env
REACT_APP_MAP_KEY=<"your-google-api-key">
```

But according to the REACTJS docs that's not secure either.
https://create-react-app.dev/docs/adding-custom-environment-variables/

How are people getting around this issue? I want to be able to make a request to my backend and return the data needed to map but I cant put together how that could work with the GoogleMapReact component. ehh?

**Comment by cooperbrislain** [comment]
https://developers.google.com/maps/api-key-best-practices

**Comment by TS22082** [comment]
from docs:

Visit the credentials panel.
Select the API key that you want to set a restriction on. The API key property page appears.
Under Key restrictions, select Application restrictions.
Select one of the restriction types and supply the requested information following the restriction list.

for me this meant I had to restrict the api key to the https address given to me by heroku.

NOTE: you will need a separate dev and production key or else the dev enviroment wont work once you restrict the api key to the production environment.
