### ISSUE TITLE
reuse the setCenter of the googleMap API Object, not just inside onGoogleApiLoaded

### ISSUE THREAD

**Issue by DevChrisDev** [google-map-react/google-map-react#847]
how can i use google apis functionality outside the function onGoogleApiLoaded

const handleApiLoaded = (map, maps) => {
    map.streetViewControl = true;
    map.overviewMapControl = true;
    
   // can only use the setCenter function inside here
  };

want to use it here so that i can use it multiple times.
onButtonClick = () => {
    mapCopy.setCenter({})
}

**Comment by karldanninger** [comment]
Hey @DevChrisDev you can just cast those two params, and then you can use them anywhere you want.

Example:

```
let mapReference = null;
let mapsReference = null;
```
```
onGoogleApiLoaded={({ map, maps }) => {
  mapReference = map;
  mapsReference = maps;
```
