### ISSUE TITLE
Marker it's not exported correctly - ^1.1.7

### ISSUE THREAD

**Issue by FilipeVeber** [google-map-react/google-map-react#848]
**I'm newbie in React so I apologize for any amateur behavior/code**

**The bug**

When I try tu use the default Google Marker, my map doesn't load anymore and two errors appears in the console.

**Steps to reproduce**:

1 - Import the **Map** and the **Marker** from the library: 
![1 - importar](https://user-images.githubusercontent.com/17495320/77429528-8e7a2100-6db8-11ea-97d9-739c190559ed.PNG)

2 - In the **return** statement, put the Map and inside the tag, put the Marker:
![2 - return statement](https://user-images.githubusercontent.com/17495320/77433055-a1dbbb00-6dbd-11ea-92f4-a9e9905dd8ba.jpg)

3 - Refresh the page, and open de browser console:
![3 - console error](https://user-images.githubusercontent.com/17495320/77429532-8fab4e00-6db8-11ea-957c-487364d76f05.PNG)

**Expected behavior**
The map loads with a Marker at the position passed to it

**Environment:**

 - OS: Windows
 - Browser: Chrome
 - Versions:
     - react: ^16.12.0
     - react-dom: ^16.12.0
     - google-map-react Version: ^1.1.7

**Comment by oziniak** [comment]
it seems like the lib doesn't export any default Marker component. You can render native markers https://github.com/google-map-react/google-map-react-examples/blob/master/src/examples/MarkerInfoWindowGmapsObj.js
