### ISSUE TITLE
Google Place Id

### ISSUE THREAD

**Issue by samuelcastro** [google-map-react/google-map-react#851]
**Is your feature request related to a problem? Please describe 🙏**

It'd be super helpful to show up markers based on googlePlaceId.

**Describe the solution you'd like 🤔**

The solution would allow users to create markers using googlePlaceId instead of just lat/long, something like this:

```typescript
<GoogleMapReact
     bootstrapURLKeys={{ key: GOOGLE_MAPS_API_KEY || '' }}
     defaultCenter={defaultProps.center}
     defaultZoom={defaultProps.zoom}>

   <AnyReactComponent googlePlaceId="123123" text="My Marker"  />

</GoogleMapReact>
```

**Describe alternatives you've considered ✨**

So far the only alternative to this problem would be convert googlePlaceId into a location and get the lat/long as described here: https://developers.google.com/maps/documentation/javascript/examples/geocoding-place-id

Any thoughts on this?

Thanks!

**Comment by karldanninger** [comment]
Hey @samuelcastro, I ran into a similar problem. I agree that it would be nice, but that feature comes at the cost of a separate API all together, right? Maybe that could be baked into this package.

I've had success with https://github.com/shukerullah/react-geocode#readme which goes a bit further and you can just search for "New York City" and get the coords to supply your Markers.

**Comment by samuelcastro** [comment]
Hey @karldanninger thanks for sharing that. Now that I see your reply (almost a year late lol).

I've been using the google geocoder js directly to do that: https://developers.google.com/maps/documentation/javascript/geocoding
