### ISSUE TITLE
Google Map - reset issue

### ISSUE THREAD

**Issue by samirkaturde** [google-map-react/google-map-react#853]
Hi Team,

I want to reset my google map position to original position when I click on button. Below is my code

import React, { useState, useEffect } from 'react';
import getConfig from 'next/config';

import GoogleMap from '../../../components/GoogleMap';

const { publicRuntimeConfig } = getConfig();

const LOS_ANGELES_CENTER = { lat: 34.0522, lng: -118.2437 };
// const bounds = null;

const getInfoWindowString = (place) => `
    <div>
      <div style="font-size: 16px;">
        ${place.name}
      </div>
      <div style="font-size: 14px;">
        <span style="color: grey;">
        ${place.rating}
        </span>
        <span style="color: orange;">${String.fromCharCode(9733).repeat(
    Math.floor(place.rating),
  )}</span><span style="color: lightgrey;">${String.fromCharCode(
  9733,
).repeat(5 - Math.floor(place.rating))}</span>
      </div>
      <div style="font-size: 14px; color: grey;">
        ${place.types[0]}
      </div>
      <div style="font-size: 14px; color: grey;">
        ${'$'.repeat(place.price_level)}
      </div>
      <div style="font-size: 14px; color: green;">
        ${place.opening_hours.open_now ? 'Open' : 'Closed'}
      </div>
    </div>`;

// Refer to https://github.com/google-map-react/google-map-react#use-google-maps-api
const handleApiLoaded = (map, maps, places) => {
  const markers = [];
  const infowindows = [];
  let activeInfoWindow;
  places.forEach((place, index) => {
    const ind = index.toString();

    markers.push(
      new maps.Marker({
        position: {
          lat: place.geometry.location.lat,
          lng: place.geometry.location.lng,
        },
        map,
        label: ind,
        icon : '/images/Webp.net-resizeimage.png',
      }),
    );

    infowindows.push(
      new maps.InfoWindow({
        content: getInfoWindowString(place),
      }),
    );
  });

  markers.forEach((marker, i) => {
    marker.addListener('click', () => {
      if (activeInfoWindow) {
        activeInfoWindow.close();
      }
      infowindows[i].open(map, marker);
      activeInfoWindow = infowindows[i];
    });
  });
};

function MarkerInfoWindowGmapsObj({ pageProps: { data } }) {
  const [places, setPlaces] = useState([]);
  const [center, setcenter] = useState(LOS_ANGELES_CENTER);
  const resetBoundsOnResize = true;

  // eslint-disable-next-line no-undef
  const handleClick = () => {
    setcenter({ lat: 34.05221, lng: -118.243712 });
    console.log(' center ', center);
  };

  useEffect(() => {
    fetch('/places.json')
      .then((response) => response.json())
      .then((res) => {
        res.results.forEach((result) => {
          result.show = false; // eslint-disable-line no-param-reassign
        });
        if (res.results.length > 0) {
          setPlaces(res.results);
        }
      });
  }, []);

  return (
    <div>
      {Array.isArray(places) && places.length > 0 ? (
        <div>
          {console.log(' Google map render >>>>>>>>>>>>>>>>>>>>> ')}
          <GoogleMap
            defaultZoom={10}
            defaultCenter={center}
            center={center}
            bootstrapURLKeys={{
              key: 'API KEY',
            }}
            yesIWantToUseGoogleMapApiInternals
            resetBoundsOnResize={resetBoundsOnResize}
            onGoogleApiLoaded={({ map, maps }) => handleApiLoaded(map, maps, places)}
          />
          <input onClick={handleClick} type="button" value="Reset" />
        </div>
      ) : (
        <p>Map Not Loaded</p>
      )}
    </div>
  );
}

MarkerInfoWindowGmapsObj.getInitialProps = async () => {
  const result = await fetch(
    `${publicRuntimeConfig.API_BASE_URL}cms/page/about-us/facility-locations`,
  ).then((r) => r.json());
  return {
    data: result,
  };
};

export default MarkerInfoWindowGmapsObj;

**Comment by karldanninger** [comment]
Hey! I'd be happy to help you with this issue, could you create a sample repo to look at?

**Comment by samirkaturde** [comment]
HI Karl,

Thanks for the reply. I have resolved this issue.

Samir Katurde | Web Developer

samir.katurde@raweng.com | Skype: samir.katurde01
Raw Engineering LLC. | Powering the Digital Enterprise

Get the blueprint for scalable enterprise mobile apps. Download the case
study.
<https://www.built.io/assets/blt3e43678ca4d03e24/Builtio_casestudy_VMware_VMworld2014.pdf>
