### ISSUE TITLE
Markers wrong position on zoom out

### ISSUE THREAD

**Issue by wahlforss** [google-map-react/google-map-react#854]
My markers are not staying in the correct position when zooming out. Look at my pictures

![image](https://user-images.githubusercontent.com/73305/78567335-cce3f700-7820-11ea-9a53-fa3fa2536d5a.png)

![image](https://user-images.githubusercontent.com/73305/78567350-d2d9d800-7820-11ea-927e-61c63c95ac33.png)

**Comment by EliranGooner** [comment]
Having the same issue.

**Comment by JackZheng10** [comment]
@EliranGooner @wahlforss I had the same issue. Dug around the issues here and found a reference to this: https://github.com/google-map-react/google-map-react/blob/master/API.md#positioning-a-marker

In my case, I just had to add that to the container around my img I was using as the marker. Hope this helps.

**Comment by EliranGooner** [comment]
@JackZheng10 Thank you for the suggestion. After trying what you and people in the threads advised, I'm still not able to get the marker to stop floating.
I tried multiple CSS suggestions, also tried to wrap this container around the component itself other instead of inside the component.
Perhaps the only difference in my code is that I set the height and width of the image with a class using rem, without it the image is too big.  Do you reckon I should edit the actual image to be small enough to fit in the map?

**Comment by JackZheng10** [comment]
@EliranGooner It's worth a shot! The image that I'm using for my marker is small enough to not warrant resizing.

If it helps, here's my code for that component:
![image](https://user-images.githubusercontent.com/44103100/78643467-4eb83c80-7882-11ea-97e0-43f98c757692.png)

And here's where I render it:
![image](https://user-images.githubusercontent.com/44103100/78643536-64c5fd00-7882-11ea-945b-4735b7716d31.png)

I'm using material-ui for the frontend.

**Comment by EliranGooner** [comment]
@JackZheng10 Tried resizing the image and still no dice.
Perhaps there's something I'm missing, here's my code (using gatsby btw):
```
const MapMarker = () => {

  return <div className={styles.img_div} >
    <img src={logo}  />
  </div> 
}
```
css:
```
.img_div {
  position: absolute;
  transform: translate(-50%, -50%);
}
```
Using this component here:
```
<GoogleMapReact
          bootstrapURLKeys={{ key: `${process.env.GOOGLE_MAPS_KEY}` }}
          defaultCenter={center}
          defaultZoom={18}
          >
            <MapMarker 
            lat={center.lat}
            lng={center.lng}
            />
          </GoogleMapReact>
```

**Comment by karldanninger** [comment]
Try to treat all markers that you place as 0px by 0px divs. They will grow from the top left corner depending on your design decisions. @JackZheng10's styling is the correct approach. Use `transform: translate(-50%, -50%)` and/or absolute positioning for best results!

https://github.com/google-map-react/google-map-react/blob/master/API.md#positioning-a-marker

**Comment by ColinTS** [comment]
> Try to treat all markers that you place as 0px by 0px divs. They will grow from the top left corner depending on your design decisions. @JackZheng10's styling is the correct approach. Use `transform: translate(-50%, -50%)` and/or absolute positioning for best results!
> 
> https://github.com/google-map-react/google-map-react/blob/master/API.md#positioning-a-marker

Thanks for this, but while this works for keeping the marker in the same location when zooming in and out it now moves the marker when you pan across the map, keeping it in the center of the map no matter where you pan to. Any ideas?

**Comment by borm** [comment]
```
translateZ(0) translate(-50%, -50%)
```

**Comment by itsmichaeldiego** [comment]
Seems that this is a concurring issue, should we set them by default at bottom center?

**Comment by Jahchap** [comment]
I was facing the same issue with width in "rem" as well as "em" (height was set to "auto") and tweaking ```translate()``` to suit my marker solved it.

In my case, changing ```translateZ(0) translate(-50%, -50%)``` to ```translateZ(0) translate(-50% -100%)``` made it fixed and I was able to confirm it against Google's own pin at the exact same position at any zoom level.

**Comment by Jahchap** [comment]
> @JackZheng10 Thank you for the suggestion. After trying what you and people in the threads advised, I'm still not able to get the marker to stop floating.
> I tried multiple CSS suggestions, also tried to wrap this container around the component itself other instead of inside the component.
> Perhaps the only difference in my code is that I set the height and width of the image with a class using rem, without it the image is too big. Do you reckon I should edit the actual image to be small enough to fit in the map?

I was facing the same issue with width in "rem" as well as "em" (height was set to "auto") and tweaking ```translate()``` to suit my marker solved it.

In my case, changing ```translateZ(0) translate(-50%, -50%)``` to ```translateZ(0) translate(-50% -100%)```  (or ```translate(-50%, -50%)``` to ```translate(-50% -100%)```) made it fixed and I was able to confirm it against Google's own pin at the exact same position at any zoom level.

**Comment by wallace-sf** [comment]
To me what worked is set the anchor of an icon marker. The x of an anchor must have half of an icon sized. Example: 
```js
const customMarker = new L.icon({
    iconUrl: '/images/icons/location-pointer.svg',
    iconSize: [35, 46],
    iconAnchor: [17, 46]
});
```

**Comment by 24suixinsuoyu** [comment]
`mMap.addMarker(MarkerOptions().position(markerLocation).icon(icon).anchor(0.5f, 0.5f))`

worked for me.

**Comment by Akshay2342** [comment]
problem Not solved for me even after trying them all check my code once : 
`
 <div style={{ height: '90vh', width: '100%' }}>
                <GoogleMapReact
                     key={mapKey}
                    bootstrapURLKeys={{ 
                    key: process.env.NEXT_PUBLIC_GOOGLE_MAPS_API_KEY, 
                    libraries: ['geometry'] 
                    }}
                    center={coordinates} // Step 3: Use the center state here
                    defaultCenter={{lat: 10.99835602,
                    lng: 77.01502627}}
                    defaultZoom={14}
                    zoom={14} 
                    margin={[50, 50, 50 ,50 ]}
                    // options={{ styles : mapStyles,}}
                    yesIWantToUseGoogleMapApiInternals
                    onChange={handleOnChangeMap}
                >


            <Marker
                lat={coordinates.lat}
                lng={coordinates.lng}
            />

`
Marker component : 

`    const Marker = ({ lat, lng, place }) => {
        return (
            <div
                style={{
                    position : 'absolute',
                    transform: 'translate(-50%, -50%)',
                    background: 'white',
                }}
            >
            <Image
                src={Pointer}
                alt="Pointer"
                width={30}
                height={30}
            />
            </div>
        );
    };
`

**Comment by dev-charan** [comment]
const marker = new window.google.maps.Marker({
          position: config.position,
          icon: {
  scaledSize: new window.google.maps.Size(16, 20),
  origin: new window.google.maps.Point(0, 0),
  anchor: new window.google.maps.Point(8, 20), // Set anchor to bottom center of the icon
}  ,
          map: mapRef.current,
        });

**Comment by subhasish-smiles** [comment]
Still facing same issue. Please help.
