### ISSUE TITLE
Can't select/highlight text in elements rendered on the map

### ISSUE THREAD

**Issue by karldanninger** [google-map-react/google-map-react#855]
**Describe the bug 🐛**

When I render elements on the map, you can't select the text within divs. I've tried these methods on the element, but I still can't select the text

```
onMouseEnter={e => {
  e.preventDefault();
  e.cancelBubble = true;
   if (e.stopPropagation) {
     e.stopPropagation();
   }
   map.setOptions({
      draggable: false,
  });
}}
```

**To Reproduce 🔍**

1. Render elements with text
2. Try to highlight some text within the map

**Expected behavior 💭**

Ability to select/highlight text

**Screenshots 🖥**

![Screen Shot 2020-04-07 at 4 58 28 PM](https://user-images.githubusercontent.com/792464/78718933-1865d600-78f1-11ea-8fd1-8f515f8ae0a8.png)

Thank you for the hard work on this package. I greatly appreciate it so much.

**Comment by karldanninger** [comment]
I've solved this by using a combination of things.

```
// map.js - Save "maps" reference
const [mapReference, setMapReference] = useState(null);
const [mapsReference, setMapsReference] = useState(null);

<GoogleMapReact
  yesIWantToUseGoogleMapApiInternals
  onGoogleApiLoaded={({ map, maps }) => {
    setMapReference(map);
    setMapsReference(maps);
  }}
>
  <Marker lat={lat} long={long}/>
</GoogleMapReact>

// marker.js - set a reference to the marker and pass it to Modal
const markerRef = useRef(null);

<Container ref={markerRef}>
  <Modal markerRef={markerRef} />
  ...
</Container>

// modal.js - stop clicks from propagating to the map in modal
if (mapsReference) {
  mapsReference.OverlayView.preventMapHitsAndGesturesFrom(markerRef.current);
}
```

I hope this helps anyone struggling with the same issue.

**Comment by AnatoleLucet** [comment]
@karldanninger Hi :wave:, your solution seems to partially work in my case.
I have a `<Marker />` component which contain a marker and an info window (the info window is not a separated component).
I'm using the `onClick` event on the map component to move this marker where the user clicked.
By using `preventMapHitsAndGesturesFrom` I can select the text and click the elements in my marker BUT when I release the click the marker is still moved.
Doesn't `preventMapHitsAndGesturesFrom` prevent `onClick` (on the map component) from firing?

I put the `preventMapHitsAndGesturesFrom` in a `useEffect` but it doesn't seem to matter, it does the same if it's in the render scope.
```tsx
// marker component
useEffect(() => {
  // `maps` is comming from props
  // `infoRef` is the info window ref
  if (maps && infoRef) {
    maps.OverlayView.preventMapHitsAndGesturesFrom(infoRef.current);
  }
}, [maps]);
```

**Comment by karldanninger** [comment]
@AnatoleLucet Interesting... You may want to use more conditionals surrounding your logic for when to call it, and when not to call it.

You can setState like `isMouseInsideInfoWindow` `onHover` so `preventMapHitsAndGesturesFrom` is only active when hovering in the info window in your case, and back to normal otherwise.

**Comment by AnatoleLucet** [comment]
@karldanninger Yes I thought about that but wondered if there were a less "hacky" way. Thanks!
