### ISSUE TITLE
GoogleMapReact does not render in Firefox mobile version

### ISSUE THREAD

**Issue by dmatis2** [google-map-react/google-map-react#856]
**Describe the bug 🐛**

I'm using Material-UI and I have `GoogleMapReact` wrapped in `Paper` component. In Chrome (both mobile & desktop) and in Firefox (only desktop) it renders correctly. I also iterate over an array of locations to render multiple Markers with Person icon from Material-UI. The code is below:

```
<Paper className={classes.maps}>
        <h1>hello world</h1>
        <GoogleMapReact
          bootstrapURLKeys={{ key: process.env.REACT_APP_MAPS_KEY }}
          defaultCenter={{ lat: 48.7152163, lng: 16.2587324 }}
          defaultZoom={4}
        >
          {clientsData
            .filter((client) => client.country)
            .map((client) => (
              <div key={client.id} lat={client.lat} lng={client.lng}>
                <Tooltip title={client.username}>
                  <PersonIcon className={classes.icon} />
                </Tooltip>
              </div>
            ))}
      </GoogleMapReact>
</Paper>
``` 

**To Reproduce 🔍**

1. Go to [this link](https://domosino.gitlab.io/thesis-webapp/#/) in both Chrome and Firefox
2. Turn on Responsive Design Mode and set width under `960px`
3. See that in Chrome is map rendered and in Firefox isn't

**Expected behavior 💭**

Rendering map in Firefox on mobile like in Chrome.

**Screenshots 🖥**

Live example [here](https://domosino.gitlab.io/thesis-webapp/#/)

**Environment:**

 - OS: Ubuntu, Android
 - Browser: Firefox
 - Version 75.0 (Ubuntu), 68.7.0 (Android)

**Additional context**

**Comment by karldanninger** [comment]
Hey @dmatis2 I took a look at your link. I think you have a bug with your CSS that Chrome is gracefully handling for you. The problem becomes apparent in Firefox. Check your styles and see what is causing it. It looks like even though you have width and height set to 100% in the containing div, you need to adjust your parents box model to behave properly.

Your map is rendering in Firefox, it's container is just 0px by 0px.

See attached.

![Screen Shot 2020-04-14 at 11 58 07 AM](https://user-images.githubusercontent.com/792464/79246771-a12bc700-7e47-11ea-9a8a-2013d1b05a1b.png)

**Comment by dmatis2** [comment]
Hi, thanks! I'll look at it tommorow and I'll write the results then.

**Comment by dmatis2** [comment]
Thank you so much. I need to add this into styling of the wrapper of the GMap wrapper: 

```
"& > div": {
        width: "100% !important",
        height: "inherit !important",
      },
```
