### ISSUE TITLE
Google Map React and InfoWindow - problem with onChildClick

### ISSUE THREAD

**Issue by Med-All** [google-map-react/google-map-react#863]
First I had a problem to get displayed InfoWindow for selected marker but I have it figured out with a code below

```
    // InfoWindow component
    const InfoWindow = (props) => {
    
        const infoWindowStyle = {
            position: 'relative',
            top: '-110px',
            left: '-100px',
            width: 300,
            backgroundColor: 'white',
            boxShadow: '0 2px 7px 1px rgba(0, 0, 0, 0.3)',
            padding: 10,
            fontSize: 14,
            zIndex: 100,
        };
    
        const infoWindowClose = {
            float: 'right',
            fontSize: 11,
        };
    
        return (
            <div style={infoWindowStyle}>
                <div style={infoWindowClose} onClick={setSelectedMarker('')}>X</div>
                <div style={{ fontSize: 16 }}>
                    Marker ID: {props.id} <br/>
                    Latitude: {props.lat} <br/>
                    Longitude: {props.lng} <br/>
                </div>
    
            </div>
        );
    };

```
Main component:

```
    const [selectedMarker, setSelectedMarker] = useState('');
    
    ....
    
    const _onChildClick = (key, childProps) => {
        setShowInfoView(!showInfoView);
        setSelectedMarker(childProps.id);
    };
    
    
    return (
    
    	....
    
    	<GoogleMapReact
    	    bootstrapURLKeys={{
    	        key: process.env.REACT_APP_GOOGLE_KEY
    	    }}
    	    zoom={zoom}
    	    yesIWantToUseGoogleMapApiInternals
    	    onGoogleApiLoaded={({map}) => {
    	        mapRef.current = map;
    	    }}
    	    onChange={({zoom, bounds}) => {
    	        setZoom(zoom);
    	        setBounds([
    	            bounds.nw.lng,
    	            bounds.se.lat,
    	            bounds.se.lng,
    	            bounds.nw.lat
    	        ]);
    	    }}
    	    onChildClick={_onChildClick}
    	>
    	        
    	    {clusters.map(cluster => {
    	        const [longitude, latitude] = cluster.geometry.coordinates;
    	        const
    	            {
    	                cluster: isCluster,
    	                point_count: pointCount
    	            } = cluster.properties;
    
    	        if (isCluster) {
    	            return (
    					....
    	            )
    	        }
    	        if (!isCluster) {
    	            return (
    	                <Marker
    	                    key={cluster.properties.id}
    	                    lng={longitude}
    	                    lat={latitude}
    	                    show={showInfoView}
    	                    marker={cluster}
    	                    id={cluster.properties.id}
    	                >
    	                    <div>
    	                        <Fragment>
    	                            <RoomIcon
    	                                color={"secondary"}
    	                                cursor={"pointer"}
    	                                onClick={() => {
    	                                    mapRef.current.panTo({
    	                                        lat: latitude,
    	                                        lng: longitude
    	                                    });
    	                                    onMarkerClick(props);
    	                                }}
    	                            />
    	                            {selectedMarker === cluster.properties.id &&
    	                                <InfoWindow
    	                                    id={cluster.properties.id}
    	                                    lng={longitude}
    	                                    lat={latitude}
    	                                /> }
    	                        </Fragment>
    	                    </div>
    	                </Marker>
    	            );
    	        }
    	    })}
    
    	</GoogleMapReact>
    
    ...
    
    )

```

but as the outcome I have got other problems with `onChildClick` which I'm not able to solve:

- `onChildClick` is not working when `<InfoWindow>` component is moved above `<RoomIcon>` component in the code above
- when I will try to get a workaround for `onChildClick` it will slide/push marker with InfoWindow out of the location to keep it on the center of the screen rather than at the location.

Any thoughts on that?

**Comment by karldanninger** [comment]
Hey @Med-All you are really close! Your solution looks similar to mine. I used to use onChildClick like you, but then I removed it as it doesn't work well in full-screen mode.

Try calling  `_onChildClick` in your <RoomIcon onClick={ /* call it here */} />`

I ended up adding this code to close infowindows if you click anywhere else

```
<GoogleMapReact
  onClick={e => {
    if (!e.event.target.closest('.info-window')) {
      updateSelectedMarker(null);
    }
  }}
/>
```

I hope this helps you.

**Comment by Med-All** [comment]
@karldanninger Thanks for the tips. The second one is very useful. 

There is apparently something buggy with `onChildClick` function. Per your suggestion I have moved it to the `<RoomIcon>` and moved `<InfoWindow>` component above the icon as

    	                <Marker
    	                    key={cluster.properties.id}
    	                    lng={longitude}
    	                    lat={latitude}
    	                    show={showInfoView}
    	                    marker={cluster}
    	                    id={cluster.properties.id}
    	                >
    	                    <div>
    	                        <Fragment>
    	                            {selectedMarker === cluster.properties.id &&
    	                                <InfoWindow
    	                                    id={cluster.properties.id}
    	                                    lng={longitude}
    	                                    lat={latitude}
    	                                /> }
    	                            <RoomIcon
    	                                color={"secondary"}
    	                                cursor={"pointer"}
    	                                onClick={() => {
    	                                    mapRef.current.panTo({
    	                                        lat: latitude,
    	                                        lng: longitude
    	                                    });
                                            _onChildClick(cluster.properties.id, longitude latitude);
    	                                    onMarkerClick(props);
    	                                }}
    	                            />
    	                        </Fragment>
    	                    </div>
    	                </Marker>

I have no longer marker positioning problem when `<InfoWindow>` is displayed but `<InfoWindow>` itself is displayed under the icon rather than above it.

Any thoughts on that?

**Comment by karldanninger** [comment]
Yeah, I have an idea for you. Change your `Fragment` to a div with `position: relative` and then make your `InfoWindow` have `position: absolute; bottom: 0, left: calc(-50% + 150px);` the 150px should be half of the width of your infowindow, and it should align right in the middle.

You could also use `transform: translateX(-50%);` to align it properly.

We set the parent to relative, so the absolute position items are anchored to it.

**Comment by Med-All** [comment]
Great - generic idea switching from `<Fragment>` to `<div>` with some CSS tweaks did the job.

I think I'm good with a workaround but it will be good that contributors take a look at `onChildClick` issue.

**Comment by Med-All** [comment]
@karldanninger Is there any way to disable dragging when mouse is over the InfoWindow? Is not letting in to highlight and copy text from it.

**Comment by karldanninger** [comment]
@Med-All this is something I have struggled with for _months_... I'm going to write a blog post about it. This isn't an issue with this package, but just with the complexity that comes with consuming the Google Maps API. But the gist is this:

In your `Marker` component, set up a reference and pass it to your Infowindow like this:

```
const Marker = () => {
const markerRef = useRef(null);
return (
  <div ref={markerRef}>
    <Infowindow markerRef={markerRef} />
...
```

In your `Infowindow` component, do this before this

```
const Infowindow = ({ markerRef }) => {
mapsReference.OverlayView.preventMapHitsAndGesturesFrom(markerRef.current);
...
```

This assumes you've saved your `mapsRef` I see from your earlier code snippets you are setting `mapRef`, but have more APIs available to you in `maps` as well:

```
onGoogleApiLoaded={({map, maps}) => {
  mapRef.current = map;
  mapsRef = maps
}}
```

I hope this helps you.

**Comment by karldanninger** [comment]
A little more context on #855
