### ISSUE TITLE
Draw circles dynamically (on async data)

### ISSUE THREAD

**Issue by RiatIO** [google-map-react/google-map-react#869]
I can't figure out how to draw circle (with radius) dynamically after the data is fetched from external server. onGoogleApiLoaded is just loaded once, and using the map reference is not working as expected. 

Any ideas?

**Comment by Haqverdi** [comment]
can you provide example?

**Comment by itsmichaeldiego** [comment]
Without more description or example / code snippets is super hard, will close until that is provided

**Comment by LuisArturoMR** [comment]
Hi, I'm trying the same, but only show the first circle.


`yesIWantToUseGoogleMapApiInternals={true}`
`onGoogleApiLoaded={({ map, maps }) => apiIsLoaded(map, maps)}`            

```
const apiIsLoaded = (map, maps) => {
    new maps.Circle({
      strokeColor: '#0353A4',
      strokeOpacity: 0.8,
      strokeWeight: 2,
      fillColor: '#0353A4',
      fillOpacity: 0.3,
      editable: false,
      map,
      center: {
        lat: geofences[geofenceSelected].coordinates.latitude,
        lng: geofences[geofenceSelected].coordinates.longitude,
      },
      radius: geofences[geofenceSelected].radius,
    });
  };
```

I'm not using a component inside the maps, only the Circles, but what I need is to move to the circle when is selected, the map moves but the circle doesn't appear.

Any idea? Thanks!
