### ISSUE TITLE
button on google-map-react component not showing in IOS/Xcode simulator

### ISSUE THREAD

**Issue by siriwerkelin** [google-map-react/google-map-react#870]
I am using google-map-react for my map component. In my project I have a button that shows perfectly well when I use localhost in the browser, but when I deployed the app and simulated it using capacitor and Xcode it doesn't show. I have tried using different z-indexes but it doesn't seem to make a difference. Does this have anything to do with that I have the button placed outside GoogleMapReact but still wrapped in the react component?

This is what renders:

```
render() {
    return (
      <div style={{ height: "100%", width: "100%" }}>
        <GoogleMapReact
          bootstrapURLKeys={{ key: "myAPIkeyI" }}
          defaultCenter={this.props.center}
          center={this.state.center}
          options={this.createMapOptions}
          onChange={this._onChange}
          defaultZoom={this.props.zoom}
          yesIWantToUseGoogleMapApiInternals
          onGoogleApiLoaded={({ map, maps }) => {
            this.apiIsLoaded(map, maps);
          }}
        >
       
        </GoogleMapReact>
        <IonButton fill="clear" className="center-btn" onClick={()=>{this.setCenter()}}>
          <IonIcon color="secondary" slot="icon-only" icon={navigateCircleSharp}></IonIcon></IonButton>
      </div>
```

And this is my css styling:

```
.center-btn{
    position: fixed;
    z-index: inherit;
    height: fit-content;
    width: fit-content;
    right: 0em; 
    bottom: 3em;
    font-size: 2em;
}
```

**Comment by itsmichaeldiego** [comment]
Hey @siriwerkelin , could you provide a live example so I can play around? Very hard from this standpoint. Also this is more a problem with JS usage than with the library itself, therefore I will move ahead and close the issue, but feel free to post a live example and I will see if I can help you out
