### ISSUE TITLE
Polylines on rerenders

### ISSUE THREAD

**Issue by BagchiMB** [google-map-react/google-map-react#871]
**Describe the bug 🐛**

If we want to draw the polylines we can draw it using onGoogleApiLoaded callback function, but when the component re renders the onGoogleApiLoaded is not called again therefore Polylines are not updated, but the markers are updated, is there any other way to access map, maps so that we can use the google api which stays consistent at every re render

**Comment by karldanninger** [comment]
Hey @BagchiMB, check out my comment here https://github.com/google-map-react/google-map-react/issues/863#issuecomment-622069011 take a look at the last code snippet. Try to set the `map` and `maps` API's to a global variable. This way, you can use them outside of `onGoogleApiLoaded`. This will let you call `map` to create overlay layers for your polylines when you need to.

**Comment by BagchiMB** [comment]
Hey @karldanninger,
Can you tell me where I should probably declare my Global element ? I am using classed based component approach, do you have any code ??, I am little new Thanks for the help.

**Comment by BagchiMB** [comment]
Hey again @karldanninger ,
With your help I was able to change my polylines, but ran into another issue, the previously generated polylines, are also staying, any help there ?

**Comment by BagchiMB** [comment]
Sorry man for continuously disturbing you @karldanninger ,
I was able to solve that using the polyline.setMap(null) function, but there is a performance issue as I render all the polylines again and again.
thanks for your help, I would have never done this without your help. Thanks again mate !!!

**Comment by karldanninger** [comment]
I'm glad you figured it out @BagchiMB 😀

From what you are describing, you are on the correct path.
https://developers.google.com/maps/documentation/javascript/examples/polyline-remove

Can you explain more about performance issues?

**Comment by BagchiMB** [comment]
Hey @karldanninger 
I have many polylines, so at every render by using the above mentioned function polyline.setMap(null), I clear all the polylines, and then again set them using my state.
It would have been better if only the updated/new polylines would have changed, as the number of polylines will increase this might cause an issue, I guess
