### ISSUE TITLE
google map react bootstrapURLKeys not working

### ISSUE THREAD

**Issue by AdrielHigor** [google-map-react/google-map-react#872]
**Describe the bug 🐛**

I've been trying to implement google-map-react to my project but for some reason I can't get it to work. Before anyone comment talking about the defaultZoom or to check if the api_key is valid, the answer is, I've already checked the map it renders as it should, but says "development purposes only", and the key is valid and working with other components. I've come to the conclusion that the bootstrapURLKeys isn't properly rendering the params I'm sending... I've checked the console and it logs NoApiKey, and in fact in the script<> tag there isn't any api_key. It isn't working with the examples on the github page too.  

`
         import GoogleMapReact from 'google-map-react';

                <GoogleMapReact
                    bootstrapURLKeys={{
                        key: 'mykey',
                    }}
                    defaultCenter={position}
                    defaultZoom={zoom}
                    // onClick={onClickReact}
                >
                </GoogleMapReact>
`

this is basically my code

**To Reproduce 🔍**

1. Basically do yarn add google-map-react 
2. Copy the example in the github page
3. yarn start

**Expected behavior 💭**

Expected to see a clean map with all the info.

**Environment:**

 - OS:  windows 
 - Browser Microsoft Edge
 - Version 1.1.7

**Comment by karldanninger** [comment]
This package works as expected.
Have you enabled Maps JavaScript API for your API key?

![Screen Shot 2020-05-25 at 10 06 40 PM](https://user-images.githubusercontent.com/792464/82853728-829ffd80-9ed4-11ea-88a8-2d2ce9662638.png)

Check here: https://console.cloud.google.com/google/maps-apis/api-list

**Comment by itsmichaeldiego** [comment]
Thanks for helping out, great answer @karldanninger
