### ISSUE TITLE
Maps stopped working on latest chromium version

### ISSUE THREAD

**Issue by ahmedu007** [google-map-react/google-map-react#876]
**Describe the bug 🐛**

Thanks for the great library. Since after upgrading chrome to `version 83` the maps have stopped loading completely. There is an error in initialisation of the maps, this is the error that pops up:

![image](https://user-images.githubusercontent.com/30743917/83520285-5b00f480-a4d5-11ea-8fdd-82f114cdff28.png)

**To Reproduce 🔍**

Update chrome to latest version: 
`Version 83.0.4103.61 (Official Build) (64-bit)` at the time of raising this bug

Update Ms Edge to:
`Version 85.0.534.0 (Official build) Canary (64-bit)`

**Expected behavior 💭**
Map to render

**Screenshots 🖥**

![image](https://user-images.githubusercontent.com/30743917/83520588-cea30180-a4d5-11ea-8172-54428de8ab4e.png)

**Environment:**

 - OS: Mac
 - Browser [Chrome, Ms Edge]

**Additional context**
It works fine on the versions upto `81` of chrome fine. It works great on safari as well. 
This error isn't helpful, and any tips suggestions would be great. Thanks

**Comment by karldanninger** [comment]
Could it be something else? Still works for me and all of my hosted clients.
I suspect there is something else that is failing.

A code sample or demo repo would go a long way.

**Comment by ahmedu007** [comment]
It probably is something else, and its driving me nuts. I've tested the library on a brand new CRA, and map renders as expected, so it is something to do on our side, but I'm not even sure where to look. I tried to create a minimal repro case, but it works on Code sandbox too 🤷‍♂️ 

I understand this isn't an issue with the library, as it renders fine on Safari and Firefox. It also worked perfectly fine on Chrome version < 83. 

This is all what's left of the code on the project,
![image](https://user-images.githubusercontent.com/30743917/83772517-5ece7b80-a67b-11ea-8cd1-21c59993a6d4.png)

Which renders:
![image](https://user-images.githubusercontent.com/30743917/83772573-6e4dc480-a67b-11ea-8c09-c7b628a48721.png)

**Comment by karldanninger** [comment]
The first thing I notice is your `defaultCenter` value.

Try this:

```
defaultCenter={{ lat: 40.7128, lng: -74.0060 }}
```

**Comment by ahmedu007** [comment]
I think we've figured it out. It's not because of the library, but since Chrome > 83 has introduced Trusted Types and Google Maps use them, the cookie policy script it blocking the api request to load maps. Still haven't got a solution yet, but we know where to look. Thanks for your time Karl, really appreciate it. I'm gonna close the ticket now.

**Comment by itsmichaeldiego** [comment]
I hope you found a solution @ahmedu007 👍
