### ISSUE TITLE
Heatmap Layer options are not updated

### ISSUE THREAD

**Issue by DirkRusche** [google-map-react/google-map-react#877]
**Describe the bug 🐛**

Heatmap options are not updated when changed in props.

**To Reproduce 🔍**

1. Include the Heatmap by passing data over `heatmap`
2. Update a value in the `options` object
3. See how the Heatmap is not updated

**Expected behavior 💭**

When I update the `options` object I'm expecting that the appropriate options are passed to the Google Heatmap element. That isn't happening
**Environment:**

 - OS: Mac
 - Browser: Safari

**Additional context**

I will provide a pull request.

**Comment by karldanninger** [comment]
@itsmichaeldiego @DirkRusche looks like the fix is merged. Should this issue be closed?
