### ISSUE TITLE
onClick returns wrong lat and lng when maximized (full screen)

### ISSUE THREAD

**Issue by tairosonloa** [google-map-react/google-map-react#879]
**Describe the bug 🐛**
This is similar to #614, but only happens when map is maximized (in full screen).

**To Reproduce 🔍**

1. Set an `onClick` function which sets a marker using the `lat` and `lng` provided by the click event.
2. Click on full screen on the map component.
3. Click in the center of the map.
4. The marker is located on the upper left corner.

**Expected behavior 💭**
The marker should be placed where clicked, so the coordinates returned should be the ones from the place clicked.

**Environment:**

 - OS: macOS Catalina 10.15.5
 - Browser: Brave 1.9.80 (Chromium 81.0.4044.138)
 - Version: 1.1.7

**Comment by itsmichaeldiego** [comment]
Please provide a live example, seems to work fine on my end

**Comment by tairosonloa** [comment]
It's still failing. Here is a live demo

![Screen Recording 2020-07-02 at 09 56 38](https://user-images.githubusercontent.com/14878189/86332552-f7402780-bc4a-11ea-9aa2-7f51b73627c0.gif)

**Comment by itsmichaeldiego** [comment]
@tairosonloa That is a GIF not a live demo, something like codesandbox.

**Comment by dennisat** [comment]
I have the same issue, not easy to make a codesandbox.
