### ISSUE TITLE
Can't call setState on a component that is not yet mounted

### ISSUE THREAD

**Issue by kevinRoomies** [google-map-react/google-map-react#880]
**Describe the bug 🐛**

When I try to use the map, I always get the same error in the console:
`Can't call setState on a component that is not yet mounted. This is a no-op, but it might indicate a bug in your application. Instead, assign to 'this.state' directly or define a 'state = {};' class property with the desired state in the GoogleMapMarkers component.

in GoogleMap (at MyComponent.jsx:32)`

**To Reproduce 🔍**

1. Import the map in your component
2. Add it to your render method in a div with the props bootstrapURLKeys, defaultCenter, defaultZoom
3. Start your app
4. See error in console

**Expected behavior 💭**

Have a map displayed in the div I made for it.

**Environment:**

 - OS: Windows
 - Browser: Brave
 - Version: 1.9.80 (Chromium: 81.0.4044.138 (Official Build) (64-bit))

**Comment by itsmichaeldiego** [comment]
@kevinRoomies Were you able to fix the issue?

**Comment by kevinRoomies** [comment]
@itsmichaeldiego No, I used another module because this one had too many issue, like not working with negative coordinate. The new one I use has no issue at all and even include street view.

**Comment by itsmichaeldiego** [comment]
What are you using atm @kevinRoomies ? We're trying to improve this library atm

**Comment by kevinRoomies** [comment]
@itsmichaeldiego [@react-google-maps/api](https://github.com/JustFly1984/react-google-maps-api)

**Comment by itsmichaeldiego** [comment]
@kevinRoomies Oh yeah but that one does not renders custom markers right?

**Comment by kevinRoomies** [comment]
@itsmichaeldiego it does not I think, didn't search too if I could do it or not, but at least it handles negative coordinates :D
