### ISSUE TITLE
How to specify MapOptions?

### ISSUE THREAD

**Issue by miliu99** [google-map-react/google-map-react#881]
For example, I want to set disableDoubleClickZoom: true as the MapOption. How can I do that?

**Comment by karldanninger** [comment]
You have access to the API here https://github.com/google-map-react/google-map-react#use-google-maps-api

`map.setOptions({ disableDoubleClickZoom: true });`

All options listed here: https://developers.google.com/maps/documentation/javascript/reference/map#MapOptions

It's recommended you use `gestureHandling` moving forward

**Comment by miliu99** [comment]
That works great. Thanks.

Now, I want to center the map to the double-click point, but I can't get double click event triggered. I tried to add onDoubleClick to GoogleMapReact element, it's not firing. I also tried to map.addListener('dblclick', () => {...}), but it doesn't work either. Do you have any idea?
