### ISSUE TITLE
Items in Map jumping on zoom for a second.

### ISSUE THREAD

**Issue by TimoRuetten** [google-map-react/google-map-react#882]
It seems that still the points are jumping while the map is zooming. I think this issue is related to this problem:
https://github.com/google-map-react/google-map-react/issues/556

You can see this problem also in your own example:
http://google-map-react.github.io/google-map-react/map/main/

When change the zoom the items are "jumping" to a wrong position for a second. When the zoom finished the items are on the correct position.

Google Maps Version: 3.41.3a
google-map-react version: 1.1.7

**Comment by itsmichaeldiego** [comment]
@TimoRuetten Hey Timo, that [example you're pointing to](http://google-map-react.github.io/google-map-react/map/main/) it is old and it is pointing to an old version of the library, not to `1.1.7` as you're stating here. 

The fix you're mentioning is already done. Please check this example instead: 
https://google-map-react.github.io/google-map-react-examples/default

**Comment by TimoRuetten** [comment]
Thanks for the reply @itsmichaeldiego . Unfortunately the example you referenced is not available anymore (even not from the new Docs link). Maybe a typo?

Anyways - I am rly confused why my markers still jumping. I will try to figure out - because I am already using the latest versions. Strange.

**Comment by itsmichaeldiego** [comment]
@TimoRuetten Maybe try to go here https://google-map-react.github.io/google-map-react-examples and click `default`? and that would work.

That is totally weird, could you provide a live example or check which version of gmap react you are requesting in your network tab? That could tell us something.

Feel free to share your code and I will do my best to help you out, we should be able to make it work

**Comment by skizzo** [comment]
While seeing this work in the Storybook is nice, it doesn't help much since the code of these examples can't be viewed.

**Comment by itsmichaeldiego** [comment]
@skizzo Yes, we haven't had time to work on that yet, im sorry for that. PRs are welcome though!
