### ISSUE TITLE
Recalling DirectionsService Infinitely

### ISSUE THREAD

**Issue by OculusMode** [google-map-react/google-map-react#884]
**Direction Service being called on every rerender 🐛**

To be precise this is a very very common use case which is also happening in your own example of direction service.
What happens is once i get the response in callback, i set it in state and because of that component gets re rendered and API call goes again until 5 to 10 calls, after which google stops sending data saying we're exceeding our limit.

**To Reproduce 🔍**

1. Just check the error in examples which gives error in console while we search for direction b/w origin and destination.
URL: https://react-google-maps-api-docs.netlify.app/#directionsservice (example above)

**Expected behavior 💭**
It will be better if we can just call it once or some method is provided.
For the solution i currently made an API call of google like below

```
const directionsService = new google.maps.DirectionsService()
directionsService.route({
        origin,
        destination,
        travelMode: travelMode || 'DRIVING',
        waypoints
      }, (result, status) => 
          if (status === google.maps.DirectionsStatus.OK) {
              if (result) {
                  setDirections(result)
              }
        } 
      })

```
Can we have an initial call by some option or perhaps a hook maybe?

**Screenshots 🖥**

![Screenshot 2020-06-23 at 6 43 16 PM](https://user-images.githubusercontent.com/37273899/85407876-69e14100-b581-11ea-9c68-68411de6cd9d.png)

**Environment:**

 - OS: All
 - Browser All

**Comment by aazcast** [comment]
I am facing the same problem.

**Comment by OculusMode** [comment]
@aazcast It's indeed a problem, however, you can make a call like above and remove <DirectionService /> for now to make it work!
Just make a call once maps get loaded. You can use their hook for that or callback. up to you. and then just put the call like that and set direction and voila!

**Comment by karldanninger** [comment]
@itsmichaeldiego this is the wrong repo...

**Comment by itsmichaeldiego** [comment]
Good catch @karldanninger

**Comment by OculusMode** [comment]
Then which is the right repo? Can't get why this was closed.

**Comment by itsmichaeldiego** [comment]
@OculusMode Seems that you are pointing out to https://react-google-maps-api-docs.netlify.app/#directionsservice, this is not `react-google-maps` but `google-map-react`

**Comment by OculusMode** [comment]
Oh okay. My bad. really sorry for this.
