### ISSUE TITLE
Control to show the traffic layer on the map

### ISSUE THREAD

**Issue by docsss** [google-map-react/google-map-react#885]
Hello, i'm using this library at the first time and having a small misunderstanding :)
Is there the implemented rule to show the traffic control,
or how can i implement this in the best view in case if this option is not yet implemented ?

**Comment by itsmichaeldiego** [comment]
@docsss Have you implemented traffic layer in Google Maps already? You can do anything that you can do with GoogleMaps by exposing the map and maps API, check this link: https://github.com/google-map-react/google-map-react#use-google-maps-api
