### ISSUE TITLE
Heatmap Layer not showing // Api example demo link down 

### ISSUE THREAD

**Issue by ianlennymatthews** [google-map-react/google-map-react#887]
**Describe the bug 🐛**

**To Reproduce 🔍**

Current config for component:   
            <div style={containerStyle}>
                <GoogleMapReact
                mapContainerStyle={containerStyle}
                defaultZoom={10}
                defaultCenter={center}
                heatmapLibrary={true}
                heatmap={{ heatMapData }}
                yesIWantToUseGoogleMapApiInternals
                bootstrapURLKeys={{
                    key: "",
                    libraries: ['visualization'],
                }}
                >
            {heatMapData.positions.map(data => (
                <Marker
                    key={data.id}
                    text={`marker: ${data.id}`}
                    lat={data.lat}
                    lng={data.lng}
                />
            ))}
                </GoogleMapReact>
            </div>

Able to render map and see markers on map with correct lat and long values, but no heat overlay is shown. Tried to follow API demo example [here](https://github.com/google-map-react/google-map-react/blob/master/API.md#example-demo) but link is down 
A live example helps a lot! 

**Expected behavior 💭**

**Screenshots 🖥**

**Environment:**

 - OS: [e.g. iOS / windows / mac / android]
ioS
chrome

**Additional context**

**Comment by itsmichaeldiego** [comment]
Hello @ianlennymatthews You can check this example that is working https://github.com/google-map-react/google-map-react-examples/blob/master/src/examples/Heatmap.js 

You can see it [live here](https://google-map-react.github.io/google-map-react-examples/?path=/story/heatmap-examples--base) (try hard-refresh if it doesn't render the first time, we're working on it atm)

**Comment by Edsonzh** [comment]
Hi, I'm getting the same issue. I cannot make the heatmap showing even by following the example. Here is my code:
`
const mapOptions = {
    bootstrapURLKeys: {
        key: <API_KEY>,
        libraries: ['visualization'],
        language: 'en'
    },
    defaultCenter: {
        lat: xx,
        lng: yy
    },
    defaultZoom: 13,
    style: { width: '100%', height: '521px', position: 'relative' },
    heatmapLibrary: true,
}

const Map = ({ positions }) => {
    const [heatMapData, setHeatMapData] = React.useState();

    React.useEffect(() => {
        if (positions) {
            const data = positions.map((position) => ({
                lat: position.lat,
                lng: position.lng,
                weight: Math.floor(Math.random() * Math.floor(5)),
            }));
            const heatmap = {
                positions: data,
                options: {
                    radius: 20,
                    opacity: 1,
                },
            };
            setHeatMapData(heatmap);
        }
    }, [positions]);

    return <div>
        <GoogleMapReact {...mapOptions} heatmap={heatMapData} />
    </div>
}`
