### ISSUE TITLE
License

### ISSUE THREAD

**Issue by gyto23** [google-map-react/google-map-react#891]
Would you be consider to put a License file into the root of the project to follow a directory standards. I am using a licensing reader which is reading a project license and converts it to the project file system which later used for law stuff.

**Comment by itsmichaeldiego** [comment]
@gyto23 Yes, feel free to create a pull request and we'll approve it.

**Comment by gyto23** [comment]
@itsmichaeldiego thanks, will send a updated version tomorrow morning (CT)

**Comment by itsmichaeldiego** [comment]
Thanks @gyto23, looking forward to it!
