### ISSUE TITLE
How to add my location button in Google Maps?

### ISSUE THREAD

**Issue by Zhanadil1509** [google-map-react/google-map-react#893]
I'd like to know if it's possible to add as default controls option my location button.

![изображение](https://user-images.githubusercontent.com/29205903/88169996-b7af9e80-cc3e-11ea-947e-5f31ba46b304.png)

Is there any way to make it as default or I need to make button with geolocation and then trigger the click event on that button in order to navigate user to the current location?

**Comment by itsmichaeldiego** [comment]
@Zhanadil1509 Yes, you can add it using map options, same way you do with normal google maps:
https://github.com/google-map-react/google-map-react/blob/master/API.md#options-funcobject

**Comment by Zhanadil1509** [comment]
please, give me example

**Comment by tienthegainz** [comment]
@Zhanadil1509 Have you found the solution

**Comment by felixlucien** [comment]
Not helpful, there is no option in the native options to enable this feature.
