### ISSUE TITLE
Change Marker Origin

### ISSUE THREAD

**Issue by amirhoseinsalehi** [google-map-react/google-map-react#894]
Hi
how I can change marker Origin ?
now its origin is (0, 0) but I want to change it :|

**Comment by itsmichaeldiego** [comment]
Hey @amirhoseinsalehi! You can [check in the API.md#positioning-a-marker](https://github.com/google-map-react/google-map-react/blob/master/API.md#positioning-a-marker), but basically you can do a transform origin:

```javascript
const greatPlaceStyle = {
  position: 'absolute',
  transform: 'translate(-50%, -50%)', // if you want center / center
}

const Marker = (props) => (
  <div style={greatPlaceStyle}>
      {props.text}
  </div>
);
```
