### ISSUE TITLE
Map reloads on almost every page interaction

### ISSUE THREAD

**Issue by zeekrey** [google-map-react/google-map-react#902]
Hey there,

I implemented google-map-react as described and the map reloads on almost any page interaction. This is how it looks:

![GIF](http://g.recordit.co/2S74Z0otUY.gif)

I'm creating a codesandbox to show the behavior in detail. But there is nothing special going on. I checked if React rerenders the component but it doesn't. The reload triggers seems to be fired by the google maps sdk itself.

```javascript
<GoogleMapReact
                bootstrapURLKeys={{
                    key: API_KEY,
                    libraries: ['places'],
                }}
                defaultCenter={location.center}
                defaultZoom={location.zoom}
                yesIWantToUseGoogleMapApiInternals
                onGoogleApiLoaded={({ map, maps }) => {
                    apiLoaded(map, maps)
                }}
            >
```

Does anybody experienced such an issue already?

**Comment by zeekrey** [comment]
Ah, I used `useEffect` in an other components which leaded to a rerender. Switching to `useCallback` solved the problem. 🤗

**Comment by itsmichaeldiego** [comment]
Happy you found the issue!
