### ISSUE TITLE
Re-render Map on state change

### ISSUE THREAD

**Issue by pargeter** [google-map-react/google-map-react#904]
Hi,

Apologies if this already in the API, but I'm not seeing an example that satisfies what i'm trying to achieve.

I've essentially got the following code which is outputting a map and my handleApiLoaded function is adding markers and a polyline as i need.

Question is if the user then interacts with another react component on the screen and updates the state (eg a date), how can I initiate another refresh of the map?

onGoogleApiLoaded will obviously only fire on first load, but how can I call the same function or another to update markers, etc?
 
`<GoogleMapReact bootstrapURLKeys={{
                                key: 'xxxxxxxx',
                                libraries: 'geometry',
                            }} 
                            defaultCenter={defaultProps.center} 
                            defaultZoom={defaultProps.zoom}
                            yesIWantToUseGoogleMapApiInternals 
                            onGoogleApiLoaded={({ map, maps })=>
                                 handleApiLoaded(map, maps)
                            }
    ></GoogleMapReact>`

**Comment by itsmichaeldiego** [comment]
The thing is that you're changing the default values, and not the values, In order for it to change you need to provide `center` instead of `defaultCenter`. Let me know if that works!
