### ISSUE TITLE
Markers text flickering on initial load

### ISSUE THREAD

**Issue by dankremniov** [google-map-react/google-map-react#905]
**Describe the bug 🐛**

Markers text flickers on initial load of a map. This behaviour seems to be caused by multiple rerenders of `GoogleMapMarkers` shortly after initial render (caused by `updateCounter` state changes).

**To Reproduce 🔍**

This bug is reproducible on the main example for this library:
https://google-map-react.github.io/google-map-react/map/main/ 

**Screenshots 🖥**

![google-map-react-flickering](https://user-images.githubusercontent.com/2664100/89463856-68518e00-d767-11ea-9fc3-76da9218fc87.gif)

**Environment:**

I tried it on the latest Chrome/Safari on macOS as well as the latest Safari on iOS. However, I expect this behaviour to be browser independent.

**Comment by itsmichaeldiego** [comment]
@dankremniov This example you're pointing to its outdated, have you tried using this library yourself?

**Comment by dankremniov** [comment]
@itsmichaeldiego, yes, I have. My use case can be simplified to something similar to https://jsbin.com/ruwogapuke/1/edit?js,output (another example from the repo) and the flickering behaviour still persists:

![ezgif com-video-to-gif](https://user-images.githubusercontent.com/2664100/89510474-84d1e280-d7c8-11ea-9149-d1fcd98ccd26.gif)

Did you close the issue because it is an expected behaviour or you are not experiencing that?

**Comment by karldanninger** [comment]
@dankremniov I think you are experiencing Flash of Invisible Text (FOIT or FOUT) just based off of your gif.

https://en.wikipedia.org/wiki/Flash_of_unstyled_content

Since these marker components sit on top of the map, you have control over the font render. There are a couple schemes you can google for to improve this. But first try setting a `font-family: sans-serif;` or any system font directly to your marker component to confirm my theory.

**Comment by karldanninger** [comment]
When I open the example you linked, I don't see a flicker, I can see a serif font, something like `Times New Roman` flicker quickly. That's how I came to that suspicion.

**Comment by dankremniov** [comment]
@karldanninger, that is a very good point, thank you! It was actually FOIT caused by Roboto font loaded by the Google Maps when map is initially rendered. Changing marker's font-family explicitly to the font used across our website fixed the issue.

**Comment by itsmichaeldiego** [comment]
@dankremniov Happy you both could figure it out, thanks @karldanninger
