### ISSUE TITLE
Polygon and Polyline

### ISSUE THREAD

**Issue by dilippatidar** [google-map-react/google-map-react#906]
How i can draw a Polyline, Polygon and Circle on Map for specific coordinates. Please provide any example link.

**Comment by itsmichaeldiego** [comment]
This issue wasn't created following [any of the issue templates](https://github.com/google-map-react/google-map-react/tree/master/.github/ISSUE_TEMPLATE)

Also, this question has been asked before multiple times, please look through the issues and you will find the answer.

Regards

**Comment by sspeng123** [comment]
> This issue wasn't created following [any of the issue templates](https://github.com/google-map-react/google-map-react/tree/master/.github/ISSUE_TEMPLATE)
> 
> Also, this question has been asked before multiple times, please look through the issues and you will find the answer.
> 
> Regards

hi , this is [google-map-react] , it is not [google-maps-react]
