### ISSUE TITLE
How can I set MapTypeId.

### ISSUE THREAD

**Issue by AxeemHaider** [google-map-react/google-map-react#907]
I'm looking to change `mapTypeId` here is what I'm looking 
[https://developers.google.com/maps/documentation/javascript/maptypes](https://developers.google.com/maps/documentation/javascript/maptypes)

I'm not able to see any option can you please let me know how can I set it ?

**Comment by itsmichaeldiego** [comment]
@AxeemHaider Seems that you didn't look that much, you can pass an `options` prop to the map, check the following

https://github.com/google-map-react/old-examples/blob/master/web/flux/components/examples/x_options/options_map_page.jsx#L54

**Comment by AxeemHaider** [comment]
ok thanks but where can i get all available options and these documentation ?
