### ISSUE TITLE
Updating center not working using state hooks

### ISSUE THREAD

**Issue by Tsangares** [google-map-react/google-map-react#913]
**Describe the bug 🐛**

When using state hooks in a FunctionComponent, and assigning

    <GoogleMap center={location}> </GoogleMap>

The center does not change even though the value for location is changing because of a hook.

**To Reproduce 🔍**

    import { IonContent, IonPage } from '@ionic/react'; 
    import React,{useState,useEffect} from 'react';                                                                                                                                     
    import` GoogleMap from 'google-map-react';   

    interface MouseEvent{                                                                                                                                                               
     x: number;                                                                                                                                                                      
     y: number;                                                                                                                                                                      
     lat: number;                                                                                                                                                                    
     lng: number;                                                                                                                                                                    
     event: any;                                                                                                                                                                     
    };  
    const Home: React.FC = () => {
     const [location,setLoc] = useState({lat: -34 lng: 150}); 
     const onMapClick=(info: MouseEvent)=>{                                                                                                                                          
        let lat=info.lat;                                                                                                                                                           
        let lng=info.lng;                                                                                                                                                           
        console.log(lat,lng);                                                                                                                                                       
        setLoc({lat: lat, lng: lng});                                                                                                                                               
     };
     return (
       <IonPage>
       <GoogleMap                                                                                                                                                              
              bootstrapURLKeys={{ key: key}}                                                                                                                                      
              center={location}
              onClick={onMapClick}
        ></GoogleMap>
        </IonPage>
     )
    }

Later when `setLoc` is called, the state of `location` is changed, but google maps does not respond to the change in the value of `location`. The state of this should be recentering the map on where the cursor clicked.

**Additional context**

I am making an ionic page using react typescript.
Reference on hooks: https://reactjs.org/docs/hooks-state.html
I have a feeling this has something to do with using[ `useRef`](https://reactjs.org/docs/hooks-reference.html#useref)

**Comment by Tsangares** [comment]
Figured it out. Placed the state variable in a dictionary so the reference is held:

    import { IonContent, IonPage } from '@ionic/react'; 
    import React,{useState,useEffect} from 'react';                                                                                                                                     
    import` GoogleMap from 'google-map-react';   

    interface MouseEvent{                                                                                                                                                               
     x: number;                                                                                                                                                                      
     y: number;                                                                                                                                                                      
     lat: number;                                                                                                                                                                    
     lng: number;                                                                                                                                                                    
     event: any;                                                                                                                                                                     
    };  
    const Home: React.FC = () => {
     const [location,setLoc] = useState({lat: -34 lng: 150}); 
     const mapState={location: location}; // <- This is now a holding the reference!
     const onMapClick=(info: MouseEvent)=>{                                                                                                                                          
        let lat=info.lat;                                                                                                                                                           
        let lng=info.lng;                                                                                                                                                           
        console.log(lat,lng);                                                                                                                                                       
        setLoc({lat: lat, lng: lng});                                                                                                                                               
     };
     return (
       <IonPage>
       <GoogleMap                                                                                                                                                              
              bootstrapURLKeys={{ key: key}}                                                                                                                                      
              center={mapState.location} //<- Changed to the dictionary
              onClick={onMapClick}
        ></GoogleMap>
        </IonPage>
     )
    }

**Comment by simplenotezy** [comment]
@Tsangares Not sure exactly why what you did would work, I tried the exact same thing, and it didn't help creating an additional reference.
