### ISSUE TITLE
Render directions dynamically based on state changes 

### ISSUE THREAD

**Issue by cschratz** [google-map-react/google-map-react#916]
I'm attempting to implement an application that adds locations of US National Parks specified by state from user inputs. Those markers are then added to the map dynamically through a Marker component to the map. After the user has added all the parks, I want to be able to render the directions from a starting location, that passes through all the parks and ends at the last one. From what I've seen though, the access to the Google Maps API is closed after the first render of the map. I'm unable to access the maps.DirectionService after initial map render. Is there a way that I can gain access to that again, so once all the markers are loaded onto the map, the user can then click to generate the route?

**Comment by karldanninger** [comment]
Hey Conor, I'm not sure I fully understand. You can store the map and maps reference and call them at any time (after your data is loaded)

Could you provide a minimal repo with your issue clearly displayed?

**Comment by cschratz** [comment]
Hey Karl, I guess I'm not fully understanding how to react with the GoogleMapReact component. Whenever I update the state within the component that contains the GoogleMapReact, I expected the handleApiLoaded to get called again, thus granting me access to the map and maps objects. I'm going to provide the code of my personal Map component below and maybe that will help. 


```javascript
 const Map = (props) => {

  const [myMarkers, setMarkers] = React.useState([]);

  const [center, setCenter] = React.useState({ lat: 39.82, lng: -98.57 });

  useEffect(() => {
    setMarkers(props.parks);
    setCenter({ lat: 39.82, lng: -98.57 });
  }, [props.parks])

  const handleApiLoaded = (map, maps, myMarkers) => {
    console.log('test')
    const directionsService = new maps.DirectionsService();
    const directionsDisplay = new maps.DirectionsRenderer();
    directionsService.route({
      origin: 'New Orleans, LA',
      destination: 'Memphis, TN',
      waypoints: [{location: 'Mobile AL'}],
      travelMode: 'DRIVING'
    }, (response, status) => {
      if (status === 'OK') {
        directionsDisplay.setDirections(response);
        const routePolyline = new maps.Polyline({
          path: response.routes[0].overview_path
        });
        routePolyline.setMap(map);
      } else {
        window.alert('Directions request failed due to ' + status);
        }
      });
};

  return (
    <div>
    <div style={{ height: '80vh', width: '100%' }}>
      <GoogleMapReact
        bootstrapURLKeys={{ key: "" }}
        center={center}
        zoom={5}
        yesIWantToUseGoogleMapApiInternals
        onGoogleApiLoaded={({ map, maps }) => handleApiLoaded(map, maps, myMarkers)}
      >
        {myMarkers.map(park => (
          <Marker
          key={park.url}
          lat={park.lat}
          lng={park.lng}
          name={park.name}
          url={park.url}
          />
        ))}
      </GoogleMapReact>
    </div>
    </div>
  );
};

export default Map;
```

**Comment by cschratz** [comment]
Ideally, once all the markers have been added to the map, I want to allow the user to click a button that will generate the route using all the markers that have been saved in the myMarkers state as way points. I'm just confused on how to go about that within the GoogleMapReact component.

**Comment by karldanninger** [comment]
@cschratz that is definitely possible with this library. I'd be happy to help. I'm out of the office today, but can help create/contribute a demo repo to work on with you.

**Comment by cschratz** [comment]
Karl, that would be super helpful! Thank you so much. I'll be on the look out for your response whenever you get around to it.

**Comment by karldanninger** [comment]
Hey @cschratz I had a spare 10 minutes to whip this codesandbox up for you. Try to follow how I saved the reference for map and maps, and you now can use those references to handle things like updating your directions calls, etc.

https://codesandbox.io/s/nice-hill-nl1wj?file=/src/App.js

**Comment by cschratz** [comment]
Hey @karldanninger that example was incredibly helpful. I got it up and running, thank you so much!

**Comment by aline-matos** [comment]
> Hey @cschratz I had a spare 10 minutes to whip this codesandbox up for you. Try to follow how I saved the reference for map and maps, and you now can use those references to handle things like updating your directions calls, etc.
> 
> https://codesandbox.io/s/nice-hill-nl1wj?file=/src/App.js

@karldanninger I know that the issue is closed, but from the example you gave, I would like to know if it's possible to use the map references in the map loading event, without having to click on an action button. Your example is awesome! Thanks in advance.

**Comment by karldanninger** [comment]
Hey @aline-matos there's lots you can do with hooks :) 

Could you give more context on your issue? You can write to karl@danninger.co if it's not a real "issue" for github.
