### ISSUE TITLE
UI Testing of <GoogleMapReact /> causes an error.

### ISSUE THREAD

**Issue by Lolibai** [google-map-react/google-map-react#917]
**Describe the bug 🐛**

 Nothing special, just using `GoogleMapReact` in my code and tried to run some tests using `react test renderer`. The result was unexpected as I received an error: see screenshot down below.

Mocking the library does not help.

**To Reproduce 🔍**

1. Use Map Component any where.
2. Render Wrapper or Simply Component it self in react test renderer ```renderer.create(<Wrapper><GoogleMapReact {...} /></Wrapper>```
3. run ```npm run test``` or ```jest <options>```

**Expected behavior 💭**

Expect to have lib mocks some where near the sources.

**Screenshots 🖥**

<img width="694" alt="Screenshot 2020-08-12 at 11 41 42" src="https://user-images.githubusercontent.com/11733376/90012460-13080600-dcac-11ea-9a06-f6cf67f75c89.png">

**Environment:**

 - OS: mac
 - Browser: chrome
 - Lib Version: 2.0.4

**Additional context**

Meanwhile I use ```process.env.NODE_ENV !== 'test'``` and just ignoring the render in code. Feels bad...

**Comment by itsmichaeldiego** [comment]
Please provide a live example, thanks!
