### ISSUE TITLE
After the Map mounts, when you go back to the page that has the mounted API, the component interactivity breaks

### ISSUE THREAD

**Issue by HelloIcanBarelyCode** [google-map-react/google-map-react#918]
Hello, I am a big fan of the library!

However, the react components break after the map is unmounted and then remounted again.

For example, I am using the Haversine formula in a marker to position a pop up on the map depending on where the marker is in relation to the center of the map. While this works perfectly on mount, it breaks after the map is unmounted unless I refresh the page and load a new instance.

I believe the code that is breaking this is related to: shouldUnregisterMapOnUnmount, where when you remount the component, the child listeners will come back, but the react components themselves will break.

Thanks!

I am using:  "google-map-react": "^1.1.7", "react": "^16.8.6" and "react-router": "^4.2.0",

**Comment by itsmichaeldiego** [comment]
Could you provide a live example for that? Thanks

**Comment by HelloIcanBarelyCode** [comment]
Couldn't reproduce, but this was user error.

Sorry.
