### ISSUE TITLE
Being billed at google for using this library

### ISSUE THREAD

**Issue by Warqus** [google-map-react/google-map-react#919]
It is not really a bug, but I don't know where to post this question otherwise.

I am being billed for using the JavaScript Maps Api. On the following page it states the Maps Embed API is free of charge.

https://developers.google.com/maps/documentation/embed/usage-and-billing
![image](https://user-images.githubusercontent.com/14151318/90631028-57525380-e222-11ea-9030-b39102d6be06.png)

This is the billing info:
![image](https://user-images.githubusercontent.com/14151318/90630902-24a85b00-e222-11ea-9fa9-59a866c3e6d7.png)

this is how I use this library:
![image](https://user-images.githubusercontent.com/14151318/90631377-f2e3c400-e222-11ea-81e0-dd577e71546d.png)

**Comment by karldanninger** [comment]
Hey @Warqus google maps is definitely not free - but you get $200 USD worth of credits a month. Did you pass that? Otherwise you'll see that 3 euro subtracted from your end of month invoice...

(Says the guy who hands over $500 a month to our Google overlords)

**Comment by Warqus** [comment]
@karldanninger Thanks for the fast reaction :)

No, I haven't got to that point yet, but in case I reach that limit, I want to know what I am being billed for.

My question is then, why do they state it is free of charge?

**Comment by karldanninger** [comment]
I just looked at your image again. I'm not sure where you got that - here's the pricing:

https://cloud.google.com/maps-platform/pricing/sheet

Dynamic maps free up to 28,000

**Comment by Warqus** [comment]
The link below states that the basic version is free of charge.

https://developers.google.com/maps/documentation/embed/usage-and-billing

The following link explains the difference between embed, embed advanced and dynamic map:

https://stackoverflow.com/a/50507639

I thought this library used the embed basic version... Is there any way to use the basic version (read; excluding the Directions mode, Street View mode, or Search mode) instead of the dynamic version. I only use the map to display markers and interact with them.

**Comment by karldanninger** [comment]
Sorry it's early in the morning and I haven't had my coffee yet.
You had a link in your original issue.

That is for the Maps Embed API, not to be confused with Maps Dynamic API (which is what you are using when consuming this library)

The Embed API is very basic iframe usage https://developers.google.com/maps/documentation/embed/get-started

**Comment by karldanninger** [comment]
Unfortunately not @Warqus. Even simple markers as components in JavaScript you will need the Dynamic API over the Embed.

Keep in mind the embed API is very basic. You're ability to construct custom markers with it is extremely limited as well since it's all built using URL parameters fed into an iframe.

**Comment by Warqus** [comment]
Aah that is unfortunate.. Thanks for all the info!
