### ISSUE TITLE
How to use my js url?

### ISSUE THREAD

**Issue by Millyn** [google-map-react/google-map-react#920]
Hello, every .

Because we are in China, public networks can not access Google.

so we need to use our google js api url .

I find it possible to set region cn, but that's not what we need, we have our own global CDN js.

thanks .

**Comment by itsmichaeldiego** [comment]
We do support that! Try this way:

```javascript
<GoogleMap 
  bootstrapURLKeys={{
    key: YOUR_MAP_KEY,
    language: 'cn',
    region: 'cn',
  }}
/>
```

**Comment by itsmichaeldiego** [comment]
Closing the issue as I've no answer, let me know if that works for you, otherwise I will reopen
