### ISSUE TITLE
Not able to make up the application so that i can make some contributation

### ISSUE THREAD

**Issue by HiteshRajpal** [google-map-react/google-map-react#925]
Hi Team,
While making up the server i am getting an compile time error which is 
Failed to compile.

./src/App.js
Module not found: Can't resolve 'google-map-react' in 'C:\Users\Hitesh Rajpal\Documents\Open Source Projects\google-map-react\example\src'
![image](https://user-images.githubusercontent.com/12680827/90960769-a1a53000-e4c1-11ea-89a2-2a5ac7d2e91c.png)

If there is a step missing let me know so that i can start the server and explore and may be contribute , 
I was also trying to search to contact the owner but i was not able to do that ,
Thanks,

**Comment by itsmichaeldiego** [comment]
@HiteshRajpal Hey! Please check this link https://github.com/google-map-react/google-map-react#manual-link-install

**Comment by HiteshRajpal** [comment]
![image](https://user-images.githubusercontent.com/12680827/91662360-9f655600-eaff-11ea-922e-aff1cc5b8776.png)

**Comment by itsmichaeldiego** [comment]
@HiteshRajpal Did you check if you've the styled-components module installed?
