### ISSUE TITLE
Center map problem

### ISSUE THREAD

**Issue by caioaletrocadock** [google-map-react/google-map-react#926]
**Describe the bug 🐛**

I tried to update the center of map using the current user position, simple task.
But the map doesn't update with the new center when loading the page (when using codesandbox, if you change the code, the center will update, but on page load, it will not).

**To Reproduce 🔍**

Use the sample:
https://codesandbox.io/s/googlemapreact-center-problem-1ck23

**Expected behavior 💭**

Center the map when the state is updated

**Long explanation**

I hope that's not a trivial issue, I've been using this repo in years, but recently when I came back to him, I saw that problem.
Thanks a lot, that's a amazing tool!!

**Comment by itsmichaeldiego** [comment]
It works fine for me, what do you mean exactly? I think you're having a rendering issue here.

**Comment by caioaletrocadock** [comment]
WHAT? I should have printed the error message.
Have no idea what was the problem... but I solved in my project using a hook from react-hook-geolocation to call the api.
It seems a problem when trying to update the location using the setLocation call inside the geolocation callback.
But after all, something has changed and fixed the problem.
I think I lost 2 hours on that :D

Thank at all!!

**Comment by itsmichaeldiego** [comment]
@caioaletrocadock I am happy you could find a solution!
