### ISSUE TITLE
Fail to complie

### ISSUE THREAD

**Issue by HiteshRajpal** [google-map-react/google-map-react#929]
![image](https://user-images.githubusercontent.com/12680827/91662207-81e3bc80-eafe-11ea-9758-8d8bda6542bc.png)

After linking the local , getting the error after running the npm start command

**Comment by itsmichaeldiego** [comment]
You need to run `yarn` in the example folder to install the package.

**Comment by HiteshRajpal** [comment]
when using npm install link error is coming 
![image](https://user-images.githubusercontent.com/12680827/91837805-23d3e800-ec6a-11ea-90b1-46e968ec19c1.png)

this error is coming after the npm link google-map-react

**Comment by HiteshRajpal** [comment]
Hi Michael,
i change the link to file on my local system package.json file of example directory. then npm install worked.
after that i can see this page .
![image](https://user-images.githubusercontent.com/12680827/91839377-934ad700-ec6c-11ea-8b1b-07a239ad29cf.png)

so is it correct loading ? i am asking because i am not able do any actions on the screnn , i can just see the map and scroll around

**Comment by itsmichaeldiego** [comment]
Yes, exactly, if you're interested in more examples you can check the README or go checkout https://github.com/google-map-react/google-map-react-examples
