### ISSUE TITLE
Is there a way to render components returned from child components...

### ISSUE THREAD

**Issue by pixels-farm** [google-map-react/google-map-react#930]
Hi all!
I am curious if there is a way to make this work:

`<Map>
    <SomeOtherComponentThatReturnsMarkersAsynchronously />
</Map>`

I have a project where i'm trying to make weather layer to work with the map. But all i get is a bunch of div's with lat and lng props. It works if i put them directly as children to Map but won't work if they are returned from the nested component. 
Thanx in advice!

**Comment by itsmichaeldiego** [comment]
Yeah we don't really support that, there're many ways you can achieve what you want without having a wrapper. I might need to look at the whole code to figure it out, but my advice is try different way, maybe that wrapper can wrap the map instead?
