### ISSUE TITLE
Scroll inside custom infowindow

### ISSUE THREAD

**Issue by vvav3** [google-map-react/google-map-react#935]
Hi. I am having the same issue as described here:
https://github.com/google-map-react/google-map-react/issues/448

I implemented infowindow component similar to this example:
https://github.com/google-map-react/google-map-react-examples/blob/master/src/examples/MarkerInfoWindow.js

Disabling scroll on hover is a bad idea, it won't work for touch screen.
I can't use 'ctrl+scroll' option and I really don't want to use react components instead of google's api to draw markers/infowindows.

Is there any way around it? I wonder how google map itself does it, I guess it uses separate layer for infowindows.

**Comment by itsmichaeldiego** [comment]
CCing @karldanninger in case he has an example for this, I haven't used InfoWindow that much. 

Did you see this comment though? https://github.com/google-map-react/google-map-react/issues/448#issuecomment-333599943

**Comment by vvav3** [comment]
Yes, I used onMouseEnter but it doesn't work on touchscreen

**Comment by itsmichaeldiego** [comment]
@vvav3 So I think your issue then is "onMouseEnter does not work on touchscreen", right? Would you like to update the issue and we can re-open it?
