### ISSUE TITLE
Concating "undefined" to Google API Key string

### ISSUE THREAD

**Issue by appclever** [google-map-react/google-map-react#936]
Hi,

I'm using the Google-map-react with Gatsby 2.23.12. The settings are bellow. When the page is loaded, I got an error: 
Google Maps JavaScript API error: InvalidKeyMapError.

The Google API Key in console is actually looking something like MY_GOOGLE_API_KEY.concat("undefined"): "s32TjhgsdADJK12412undefined"

On screenshot below, I'm using the .env. I was trying to paste the key right in the settings like string, same problem. 

**Screenshots 🖥**

![Zrzut ekranu 2020-09-3 o 13 23 58](https://user-images.githubusercontent.com/66114195/92109112-c023f900-ede8-11ea-8fe9-e2c2a1ed4db5.png)

Help, please :)

**Comment by jamesjeong94** [comment]
Which version of google-map-react are you using? A similar, if not the same, issue was resolved on 2.1.3. I'd suggest updating.

**Comment by itsmichaeldiego** [comment]
Yes, this was fixed in `2.1.3`, please update to latest version and you will get the issue fixed.

Sorry for that!
