### ISSUE TITLE
How can I make it so that my polygons are visible based on a variable I update?

### ISSUE THREAD

**Issue by SantosOMartinez** [google-map-react/google-map-react#937]
I have created an object that contains keys for every polygon in the map. Their value is a boolean based on if it should be visible or not. It works great when the map loads since it takes the object values and makes them render but when I try to change the object value it does not reflect on the map. 

I am currently placing these values in the onGoogleApiLoaded property of the GoogleMapReact component. What property should I be using in this component to feed these values and make it toggle the polygon visibility?

I thought I could just change the visible property of the maps.polygon but that does not seem to be the case. I even tried making it so that it uses setMap(map) when visible and setMap(null) when it shouldn't be visible.

**Comment by SantosOMartinez** [comment]
Better yet, how can I access the polygons so that I can edit them kind of like what is possible for the markers? I wish to add even more features to these polygons including the ability to hide them. For example, when I click a polygon I wish to have a custom popup appear. This popup would be a custom component so that I can style it as I wish.

**Comment by itsmichaeldiego** [comment]
Hello! In order to help you we always ask for a live example, I can't give you further help without that.

I think you can achieve most things by just using the `onGoogleApiLoaded ` https://github.com/google-map-react/google-map-react#use-google-maps-api

BTW: Did you check the issues related to this? https://github.com/google-map-react/google-map-react/issues?q=is%3Aissue+polygon+is%3Aclosed

**Comment by SantosOMartinez** [comment]
How do I give a live example? Sorry I am kind of new to this :)

**Comment by SantosOMartinez** [comment]
```
{!data ? <MapLoading /> : null}
      <GoogleMapReact
        bootstrapURLKeys={{ key: process.env.REACT_APP_GOOGLE_KEY }}
        defaultCenter={defaultCenter}
        defaultZoom={defaultZoom}
        options={createMapOptions}
        yesIWantToUseGoogleMapApiInternals
        onGoogleApiLoaded={({ map, maps }) =>
          handleApiLoaded(map, maps, pVisibility)
        }
      >
        {stations.map((station) =>
          markerVisible(pVisibility, station.CLIMATEZONE) ? (
            <Marker
              key={station.STATIONID}
              lat={station.LATITUDE}
              lng={station.LONGITUDE}
              station={station}
            />
          ) : null
        )}
      </GoogleMapReact>
```

In here the pVisibility is an object that has all of the polygons with a boolean of true or false in respect of if it should be visible.

The object looks like this
```
{
    easternInterior: true,
    northernCoastal: true,
    northernSlopes: true,
    outlyingIslands: true,
    southernCoastal: true,
    southernSlopes: true,
    westernInterior: true,
  }
```
Inside the handleApiLoaded function looks something like this.
```
export const handleApiLoaded = (map, maps, visible) => {
  const {
    easternInterior,
    northernCoastal,
    northernSlopes,
    outlyingIslands,
    southernSlopes,
    southernCoastal,
    westernInterior,
  } = visible;

  // Construct the polygon.
  const easternInteriorPolygon = createPolygon(
    easternInteriorCoords,
    easternInteriorColor,
    easternInterior
  );
  easternInteriorPolygon.setMap(map);
.
.
.
```
Where the createPolygon function just creates a new maps.Polygon
```
function createPolygon(coords, color, visibility) {
    return new maps.Polygon({
      paths: coords,
      strokeColor: color,
      strokeOpacity: strokeOpacity,
      strokeWeight: strokeWeight,
      fillColor: color,
      fillOpacity: fillOpacity,
      visible: visibility,
    });
  }
```
The problem comes when the maps api has already loaded. 
If in my app I try to change the value of this object which works, the polygons wont update to reflect the new state change. aka(the visible property in the maps.Polygon does not reflect the new values in the pVisibility object)

My guess is that onGoogleApiLoaded is only executed when the google api is loaded...
Which makes sense I suppose :)


What I'm trying to do is have the polygons update their values in real time when I change the values of this object in my app.

**Comment by SantosOMartinez** [comment]
I saw that in this post: https://github.com/google-map-react/google-map-react/issues/863

they tried to set the map and maps API's to a global variable. This way, they could use them outside of onGoogleApiLoaded.
But I cant seem to replicate that. If I wish to expose these two values of map and maps to be called whenever I wish. how could I do that?

**Comment by SantosOMartinez** [comment]
@itsmichaeldiego Can this issue please be reopened for discussion? I wish to elaborate more, however possible.

**Comment by itsmichaeldiego** [comment]
@SantosOMartinez Hey! So this is more help with how to use google maps in general, its not an issue with the library itself. That is why I close the issue, otherwise this platform would work like StackOverflow 😂 and its not mean for that.

In order to create a live example, you can access a website like https://codesandbox.io/ and create yours with React, you then add `google-map-react` library and add your code there, that way I can see what you're doing and how you're doing it for me to provide help.

**Comment by itsmichaeldiego** [comment]
Looking at the code, it seems that the problem is that you're doing `new maps.Polygon` instead of using the instance of maps you're using.

**Comment by SantosOMartinez** [comment]
I think the code that I have written is too much to put into a codesandbox. May I invite you to the repository instead? @itsmichaeldiego  @karldanninger

**Comment by karldanninger** [comment]
Hey @SantosOMartinez feel free to add me to your repo.. I'd be happy to take a look and help you.

**Comment by SantosOMartinez** [comment]
@karldanninger Aw thank you so much! I sent you the invite.

**Comment by itsmichaeldiego** [comment]
Yeah you can invite me too @SantosOMartinez

**Comment by SantosOMartinez** [comment]
The two main things I'm trying to figure out with polygons is, how can I hide them or reveal them when I change my variables to true or false, and how can I make it so that when I click a polygon I can display a popup with the names of the respective climate zones. I'm currently really stuck in this problem.

**Comment by andreabrss** [comment]
@SantosOMartinez  I'm having the same issue with the polygons...cant toggle them to be visible/hidden. Interenstingly the first 2 toggle works - visible - hidden - visible again but then geodesicPolyline becomes undefined. 

I'm new to google maps so any help would be greatly appreciated. 

`  const toggleChecked = () => {
      if(checked){
      geodesicPolyline?.setMap(null);
    }
      else {
        renderPolylines(); 
      }
      setChecked(!checked);
  }

  const renderPolylines = () => {
    geodesicPolyline = new googleMaps.Polyline({
      path:  markers,
      geodesic: true,
      strokeColor: '#00a1e1',
      strokeOpacity: 2,
      strokeWeight: 2,
      googleMap
    });
    geodesicPolyline.setMap(googleMap);
    fitBounds();
  };

  const fitBounds = () => {
    const bounds = new googleMaps.LatLngBounds();
    for (const marker of markers) {
      bounds.extend(new googleMaps.LatLng(marker.lat, marker.lng));
    }
    googleMap.fitBounds(bounds);
  };

  return (
      <div className={classes.container}>
        <GoogleMapReact
          ref={(ref)=> {mapRef.current = ref;}}
          onGoogleApiLoaded={({ map, maps}) => {setGoogleMaps(maps); setGoogleMap(map);}}
          options={createMapOptions}
          bootstrapURLKeys={{ key: window.ENV_DATA.REACT_APP_MAPS_KEY }}
          defaultCenter={defaultProps.center}
          defaultZoom={defaultProps.zoom}
        >
          <Toggle lat={6.15500000} lng={1.41083333} checked={checked} toggleChecked={toggleChecked} />
        </GoogleMapReact>
      </div>
        );
`

**Comment by SantosOMartinez** [comment]
@andreabrss So basically how I managed to solve this issue was using the onGoogleApiLoaded property of the google map React component. There I made the two inputs map and maps go to a function I created called handleMapLoad.

Which I stored in a different file.

So it would look something like this:
```js
<GoogleMapReact>
        bootstrapURLKeys={{ key: process.env.REACT_APP_GOOGLE_KEY }}
        defaultCenter={defaultCenter}
        defaultZoom={defaultZoom}
        options={createMapOptions}
        yesIWantToUseGoogleMapApiInternals
        onGoogleApiLoaded={({ map, maps }) => handleMapLoad(map, maps)}
</GoogleMapReact>
```

Then in this new file I declared two variables to hold these values and then made the function point to these variables.

```js

export let gMap;
export let gMaps;

export function handleMapLoad(map,maps){
    gMap = map;
    gMaps = maps;
}
```
This would let me access the two variables of the map even after the function was done. So I could call things like
```js
 const polygon1 = new gMaps.Polygon({
    paths: coords,
    strokeColor: color,
    strokeOpacity: strokeOpacity,
    strokeWeight: strokeWeight,
    fillColor: color,
    fillOpacity: fillOpacity,
});

polygon1.setMap(gMap);

```
to create new polygons and set them to the map.

Now to answer your question, What I made to toggle on and off these polygons:

Once I had these polygons created I could use the setMap() function I just showed above to either set them visible 
```js
polygon1.setMap(gMap);
```
or hide them
```js 
polygon1.setMap(null);
``` 

If you wish to make these polygon's toggle based on a function then you can just create a function that does that:

```js
export function togglePolygon(toggle){
    polygon1.setmap( toggle ? gMap : null);
}
```
You could then just call this function anywhere in your application and give it a boolean to toggle the polygon.

If you are planning on making a large group of polygons I would recommend you use an array to store each polygons reference instead of a static variable such as polygon1 which I used in this example. And you could call them from an index to set them individually on or off.

Hope this helps and if you have any other question feel free to hit me up! 😄

**Comment by andreabrss** [comment]
@SantosOMartinez thanks for the swift help, my problem was that I have always created a new polygon object, it works now, thank you!
