### ISSUE TITLE
When Marker clicks on corner/edges of the map and Info Window auto adjust within a bound is not working. (hided infowindow)

### ISSUE THREAD

**Issue by mathavan161293** [google-map-react/google-map-react#938]
When Marker clicks on corner/edges of the map.
Info Window auto adjust within a bound is not working.

![Capture](https://user-images.githubusercontent.com/22838322/92566930-97917880-f29a-11ea-9df9-1cb264bf286d.JPG)

we need auto adjust to view like this below
![Capture2](https://user-images.githubusercontent.com/22838322/92567072-c871ad80-f29a-11ea-983f-317878ccacbf.JPG)

**Comment by itsmichaeldiego** [comment]
Could you provide a live example? I think your issue might be related to CSS but I need to see your implementation.

PST: So nice that you're working on vegan restaurants!

**Comment by mathavan161293** [comment]
CSS issues means?
how to auto adjust it inside boundary?
[2020-09-10 11-00-20-578.zip](https://github.com/google-map-react/google-map-react/files/5199346/2020-09-10.11-00-20-578.zip)

check the above video.
need like default info window works for auto adjusting within a boundary.

if CSS works means how to use it?

can you provide me any solution?

**Comment by itsmichaeldiego** [comment]
@mathavan161293 For us to provide you a solution / help we need a live example from codesandbox. Thanks in advance

**Comment by mathavan161293** [comment]
check the code below
https://codesandbox.io/s/google-map-react-info-window-6io4i

**Comment by SueCheng** [comment]
I have the same issue with you, @mathavan161293
