### ISSUE TITLE
custom Info Window need like default google map for auto adjust within a boundary is not working.

### ISSUE THREAD

**Issue by mathavan161293** [google-map-react/google-map-react#939]
how to auto adjust it inside boundary?
[2020-09-10 11-00-20-578.zip](https://github.com/google-map-react/google-map-react/files/5199387/2020-09-10.11-00-20-578.zip)

check the above video. (watch till end)
need like default info window works for auto adjusting within a boundary.

**Comment by itsmichaeldiego** [comment]
@mathavan161293 For us to provide you a solution / help we need a live example from codesandbox. Thanks in advance

**Comment by mathavan161293** [comment]
check the code below
https://codesandbox.io/s/google-map-react-info-window-6io4i
