### ISSUE TITLE
Is it possible to toggle a heatmap layer? 

### ISSUE THREAD

**Issue by vitaly-scentroid** [google-map-react/google-map-react#940]
**Problem:** 
I can't find a way to toggle the heatmap when needed.

**What I've tried:**
**1.** I've tried to toggle the data in "heatmap" prop with hooks - Heatmap is either not showing upon initialization, and crashes when I try to display it, OR It is always showing and ignores my hook condition. heatmap={activeControl === 1 ? heatmapData : 0}
**2.** I've tried to toggle heatmapLibrary prop with the same hook, which had same results.

**Comment by itsmichaeldiego** [comment]
@vitaly-scentroid We need a live example in order to help you. At least a code snippet
