### ISSUE TITLE
Warning: Using UNSAFE_componentWillReceiveProps in strict mode is not recommended and may indicate bugs in your code

### ISSUE THREAD

**Issue by salahmak** [google-map-react/google-map-react#944]
**Describe the bug 🐛**
this error is thrown whenever the maps component in loaded, like there is no 'special case' to trigger, it just gets thrown whenever i use the library.

**To Reproduce 🔍**
just use the library and it will be thrown

live example: https://codesandbox.io/s/fervent-bouman-ijrou?file=/src/App.js

**Screenshots 🖥**

![image](https://user-images.githubusercontent.com/49586511/93690032-086f3680-facc-11ea-8b31-2044e196d561.png)

**Environment:**

 - OS: linux
 - Browser: Brave (chromium based)
 - Version: last version

**Comment by davecthomas** [comment]
same here - OSX Chrome

**Comment by itsmichaeldiego** [comment]
Yes, thanks @AhmedMajied ! PRS are welcome if you want to do it yourself :)

**Comment by hongdung6992** [comment]
I also had the same issue, to be fix this, I deleted <React.StrictMode>, but that is not a good solution

**Comment by itsmichaeldiego** [comment]
@hongdung6992 Yeah that's not the way to go, this is just a warning in case you upgrade to **React 17**, which will be rolled out at the end of this year, I recommend you to ignore it until we fix it.

There's a lot of code depending on `componentWillReceiveProps` in our library, which need to be moved carefully to other different lifecycle methods, we need to do it at some point but its just me lately so! If someone wants to do it they're welcome!

**Comment by itsmichaeldiego** [comment]
Published in `2.1.6` :shipit:. Please confirm that it works for you all, thanks. 👍

**Comment by franciscocobas** [comment]
@itsmichaeldiego It is available at NPM right now?
