### ISSUE TITLE
Accessibility issues

### ISSUE THREAD

**Issue by CarstenHoyer** [google-map-react/google-map-react#945]
**Is your feature request related to a problem? Please describe 🙏**

Yes. On my site, with a map, when I run the Siteimprove Accessibility Checker or WAVE Chrome extensions, I see multiple issues related to WCAG level A (and possibly AA?). These issues seems to be out of my reach - related to ie gm-bundled-control elements.

**Describe the solution you'd like 🤔**

I would like the map to be WCAG compliant and accessible.

**Describe alternatives you've considered ✨**

Here is a thread where people consider alternatives.
https://stackoverflow.com/questions/18748402/google-maps-and-wcag-2-0-level-a

**Comment by itsmichaeldiego** [comment]
Can you share those "multiple issues" that you see?

**Comment by CarstenHoyer** [comment]
Sorry, on a closer look, this does not seem to be related to this module - so I am closing the request.
