### ISSUE TITLE
Cannot drag the marker on mobile view in 2020

### ISSUE THREAD

**Issue by rashrazak** [google-map-react/google-map-react#960]
Hi guys, I need help, I know this problems occurred previously (2018) and it fixed by changing the version  v:3.30
this time i try to drag in mobile view but its not working..

unfortunately when i creating the 
`new maps.Marker({
            position: {lat,lng},
            map,
            title: 'Hello World!',
            draggable:true
          });`

it works like a charm, it drags as well

**Comment by deguilardi** [comment]
duplicated: https://github.com/google-map-react/google-map-react/issues/959

**Comment by itsmichaeldiego** [comment]
Im sorry to hear this is a problem again! You can always set the version in `bootstrapURLKeys` to bypass the issue by doing:

```jsx
<GoogleMapReact 
  bootstrapURLKeys={{
    v: '3.30',
  }}
/>
```
