### ISSUE TITLE
Weird looking: My map looks divided into square pieces.

### ISSUE THREAD

**Issue by karahancerenes** [google-map-react/google-map-react#967]
**Describe the bug 🐛**

My map looks divided into square pieces. I just use 'SimpleMap' example, nothing much. I can't understand what caused the problem. 

**To Reproduce 🔍**

```
import React, { Component } from 'react';
import GoogleMapReact from 'google-map-react';

const AnyReactComponent = ({ text }) => <div>{text}</div>;

class SimpleMap extends Component {
  static defaultProps = {
    center: {
      lat: 59.95,
      lng: 30.33
    },
    zoom: 11
  };

  render() {
    return (
      // Important! Always set the container height explicitly
      <div style={{ height: '100vh', width: '100%' }}>
        <GoogleMapReact
          bootstrapURLKeys={{ key: "MY_URL_KEY" }}
          defaultCenter={this.props.center}
          defaultZoom={this.props.zoom}
        >

        </GoogleMapReact>
      </div>
    );
  }
}

export default SimpleMap;
```

**Screenshots 🖥**

![react-map-problem](https://user-images.githubusercontent.com/33702287/97774537-bc52ef80-1b69-11eb-8116-a7b633c3e009.PNG)

**Environment:**

 - OS: windows 
 - Browser: chrome

**Additional context**

I looked at the issues and can't find reletad one. Thanks, in advance.

**Comment by sametyildirima** [comment]
I have experienced the same same issue. Can you write here, if you find your answer?

**Comment by itsmichaeldiego** [comment]
This is odd, can you folks please provide a live example? I tried and it works fine on my end

**Comment by karahancerenes** [comment]
@itsmichaeldiego thanks for your response and for providing a starting point for the solutionl. When I tried codesandbox, I saw that there was no such problem and I examined the effect of other components to GoogleMap component in my project step by step. I realized that the <img> tag I used in the css of another component was affecting the google map component and I fixed it.

**Comment by itsmichaeldiego** [comment]
@karahancerenes Nice!! Yes, it seems from the picture that it was some kind of border-radius, happy you found the solution!
