### ISSUE TITLE
Firebase deploy not showing map

### ISSUE THREAD

**Issue by Sotatek-CanPham** [google-map-react/google-map-react#969]
**Describe the bug 🐛**

I was trying to deploy react map on Firebase hosting and got blank page. 
Full error: 
**k(...): Nothing was returned from render. This usually means a return statement is missing. Or, to render nothing, return null.**

**To Reproduce 🔍**

1. Create a GoogleMapReact component
2. Deploy it on FIrebase

A live example helps a lot! 

**Expected behavior 💭**

I got no problem showing map on local host. So I expect the same on FIrebase.

**Screenshots 🖥**
On local:
![image](https://user-images.githubusercontent.com/44857670/97826089-395da080-1cf3-11eb-98b9-8940efee2794.png)

On firebase:
![image](https://user-images.githubusercontent.com/44857670/97825969-e1269e80-1cf2-11eb-9090-a69bc2795428.png)

**Comment by itsmichaeldiego** [comment]
Your error seems to be related to your production build and not our library
