### ISSUE TITLE
Question: How do I use Google API on a page that does not show the Map component

### ISSUE THREAD

**Issue by marnixhoh** [google-map-react/google-map-react#974]
Hi,

I am wondering how I can use the Google API without using/displaying the Map component? I know `google-map-react` uses `@googlemaps/js-api-loader` under the hood to do this.

So my question is, is it safe to just use `@googlemaps/js-api-loader ` or is there some 'correct' way I can load the Google API using `google-map-react`, without actually using the Map component?

Thank you!

**Comment by itsmichaeldiego** [comment]
TLDR: If you don't need to display the map, then you don't need this library at all. Its heavier and will be more complicated to achieve what you want.

**Comment by egisz** [comment]
I disagree, in my case I use standalone search box for places in main page header, but in other sub pages I also use map.
So I want only load search box once page opens, but later on also map.
Is there an example for that?

**Comment by marnixhoh** [comment]
@egisz Exactly! that is my use case too! I have created a work around where I check manually if the Google API has loaded already. For my particular use case, this came out pretty hacky...

Would be great if it would be possible to grab the Google API from the google-map-react import, in such a way that when the map is displayed later on, it doesn't get requested twice and vice versa

**Comment by egisz** [comment]
Hi, I disagree, in my case I use search box for places in page header, but in other sub pages I also use map.
So I want only load search box once page opens, but later on also map.
Is there an example for that?

**Comment by egisz** [comment]
I just found possible solution in this discussion #303, More specifically, this [comment](https://github.com/google-map-react/google-map-react/issues/303#issuecomment-305637815)
Will try to test it

**Comment by marnixhoh** [comment]
Thanks for sharing that. My solution seems to work for now. But by quickly glancing at #303 it seems to offer a better solution
