### ISSUE TITLE
Syntax Error in IE11 at version 2.1.4 and higher

### ISSUE THREAD

**Issue by pkaufi** [google-map-react/google-map-react#976]
**Describe the bug 🐛**

Updating `google-map-react` version to a version > `2.1.3` breaks the loading of maps on IE11.
If I go to the line of the error
<img width="197" alt="Screenshot 2020-12-02 at 08 11 44" src="https://user-images.githubusercontent.com/39113949/100840358-0cc5b180-3476-11eb-8338-16772d11c277.png">
 I see the following code:
<img width="615" alt="Screenshot 2020-12-02 at 08 16 07" src="https://user-images.githubusercontent.com/39113949/100840777-abeaa900-3476-11eb-9e95-4e118bb732c8.png">
which is a problem for IE11, as `class` is not a valid `ES5` syntax and IE11 doesn't understand it.
Somehow from version `2.1.4` the `class` sneaked into the bundle and breaks it for older browsers.

**To Reproduce 🔍**

Check `README.md` in reproduction repository https://github.com/pkaufi/ie11-google-map-react

**Expected behavior 💭**

Using `google-map-react` should work in IE11.

**Environment:**

 - OS: Windows 10
 - Browser: Internet Explorer
 - Version: 11

**Comment by irvv17** [comment]
IE11 is almost deprecated bro...

I think this is not an issue and is not relevant to the component itself.

[check this for more information](https://github.com/outdatedbrowser/outdated-browser/issues/270)

**Comment by pkaufi** [comment]
> IE11 is almost deprecated bro...
> 
> I think this is not an issue and is not relevant to the component itself.
> 
> [check this for more information](https://github.com/outdatedbrowser/outdated-browser/issues/270)

I know, tell me about it. Sadly, a big enough part of our website visitors are still using IE11 so that the decision was to support it. Not everyone is at the liberty to freely decide which browser to support and which not.

It might not be an issue for you, but that doesn't mean it's not for others. If the decision of the creator is to not support IE11 anymore, I'll just stick to version `2.1.3`. It would be great to mention it somewhere in the `README.md` then.

**Comment by Jeremie-Chauvel** [comment]
Hi @pkaufi,

looking into this issue as I have to support IE11 as well, I found out a great ressource on transpilling `node_modules` packages https://github.com/babel/babel-loader/issues/171, might be what you need as well.

**Comment by itsmichaeldiego** [comment]
@pkaufi Im sorry for you, but no we don't support IE anymore, although if you want to submit a PR I am happy to help you out.

What I wonder is, why would it stop working in `2.1.4`? I don't think of anything new that might break it.

**Comment by pkaufi** [comment]
> Hi @pkaufi,
> 
> looking into this issue as I have to support IE11 as well, I found out a great ressource on transpilling `node_modules` packages [babel/babel-loader#171](https://github.com/babel/babel-loader/issues/171), might be what you need as well.

Will check that one out for sure, thank you for pointing it out 👍 



> @pkaufi Im sorry for you, but no we don't support IE anymore, although if you want to submit a PR I am happy to help you out.
> 
> What I wonder is, why would it stop working in `2.1.4`? I don't think of anything new that might break it.
> 
> I think you should check @Jeremie-Chauvel's [comment](https://github.com/google-map-react/google-map-react/issues/976#issuecomment-740149900)

The only thing I saw that could've caused it, is the addition of `@googlemaps/js-api-loader`. If this one is not transpiled to ES5, it might've caused the issues. 
Anyway, I completely understand your position, I'd also go into that direction. About time for IE11 to leave the world wide web for good :)

**Comment by NeliHarbuzava** [comment]
Needed to include `@googlemaps/js-api-loader` for Babel transpilation.

So my code is like this:
```js
const modulesToTranspile = ['@googlemaps/js-api-loader'];

// webpack config for babel-loader
include: modulesToTranspile.map(moduleName =>
    path.resolve(__dirname, `../../../../node_modules/${moduleName}`)
),
exclude: [new RegExp(`node_modules\/(?!(${modulesToTranspile.join('|')}))`)]

```
