### ISSUE TITLE
Hi guys, needed guidance

### ISSUE THREAD

**Issue by VietQuoc356** [google-map-react/google-map-react#984]
Just doing a project for school about covid, I'm sure these question have been asked many times.
These errors do not break the application, but my console is pretty red.

- Received false for a non-boolean attribute $hover.;
- React does not recognize the $getDimensions prop on a DOM element. [...];
- React does not recognize the $dimensionKey prop on a DOM element. [...];
- React does not recognize the $geoService prop on a DOM element. [...];
- React does not recognize the $onMouseAllow prop on a DOM element. [...];
- Received true for a non-boolean attribute $prerender.;
- Invalid attribute name: $hover;
- Invalid attribute name: $getDimensions;
- Invalid attribute name: $dimensionKey;
- Invalid attribute name: $geoService;
- Invalid attribute name: $onMouseAllow;
- Invalid attribute name: $prerender.

I don't know how to fix, any help would but much appreciated. thanks

```
const API_KEY = `${process.env.REACT_APP_API_GOOGLEMAP_KEY}`;

function Map(props) {
  const [result, setLatest] = useState([...props.countryCovidStats]);

  const toggleShowModal = (index) => {
    let newResults = [...result];
    newResults[index].showModal = !result[index].showModal;
    setLatest(newResults);
  };

  return (
    <div style={{ height: "100vh", width: "97%", border: "0", margin: "20px" }}>
      <GoogleMapReact
        bootstrapURLKeys={{ key: API_KEY }}
        defaultCenter={{ lat: 46, lng: 2 }}
        options={{ styles: MapStyle.light, scrollwheel: false }}
        defaultZoom={0}
      >
        {result.map((data, index) => {
          const getColorInfected = () =>
            data.increment.toString() === "NaN" || data.increment === Infinity
              ? "grey"
              : data.increment < 55
              ? "green"
              : data.increment > 90
              ? "red"
              : "gold";
          return (
            <div
              key={index}
              lat={data.countryInfo.lat}
              lng={data.countryInfo.long}
            >
              <div>
                <button
                  onClick={() => toggleShowModal(index)}
                  className="marker"
                  style={{ color: getColorInfected() }}
                >
                  <FaGenderless />
                </button>
                {data.showModal && (
                  <Modal index={index} data={data} close={toggleShowModal} />
                )}
              </div>
            </div>
          );
        })}
      </GoogleMapReact>
    </div>
  );
}

export default Map;
```

**Comment by badazz91** [comment]
@VietQuoc356 you need to wrap your custom HTML for your marker(s) into a component - That will solve it. See here: https://github.com/google-map-react/google-map-react/issues/583
