### ISSUE TITLE
`onChange` event stop working when container display value is none initially and then changed to block.

### ISSUE THREAD

**Issue by hugo-licon** [google-map-react/google-map-react#985]
**Describe the bug 🐛**

`onChange` event stop working when container display value is none initially and then changed to block.

**To Reproduce 🔍**

1. Set the container display style to `none`
2. Now programmatically (after pressing a button or something) set the display to block.
3. The `onChange` event stopped working. `onDragEnd` works just fine.

[Code sandbox](https://codesandbox.io/s/onchange-issue-gj75l)

**Environment:**

 - OS: Ubuntu
 - Browser Chrome
 - Version: 2.1.9

**Additional context**
Sometimes it works but most of the time it doesn't

**Comment by IBanda** [comment]
Hi sorry
Just for clarity. Do you mean that when you toggle the map the change event doesn't fire any more?

**Comment by hugo-licon** [comment]
@IBanda Yes. Initially, the map is set `display: none` and there is a button on top to change the display to `block` but when you do this the `onChange` event doesn't fire anymore, the `onDragEnd` is still working but I need the onChange event.

**Comment by IBanda** [comment]
I’m not sure exactly why this behavior exists I will find some time to look into it, but conditionally rendering the map using the showMap state seems to preserve the onChange event listener.

**Comment by IBanda** [comment]
@hugo-licon so when the map is set to display:none or it's container in this case, it has a size of 0x0 which means it has bounds of 0. To fix this you can either use the resetBoundsOnResize prop or instead of using display use visibilty which will still allow google maps to read the size of the map.
I hope this helps 🙂

**Comment by hugo-licon** [comment]
@IBanda Thanks for that :100:. it worked.
