### ISSUE TITLE
Zoom is not reset after changing zoom or defaultZoom value

### ISSUE THREAD

**Issue by dionkas** [google-map-react/google-map-react#986]
**Describe the bug 🐛**

I am using the center and zoom/defaultZoom props to show a location on the map. Using local state, I can change the location and zoom to show a different location. However, once I click zoom in or zoom out via the buttons (or scroll in/out to zoom), the zoom of the map is locked at that level. I am trying to always reset the zoom to what the defaultZoom/zoom property is set to via the local state.

Any ideas how to set the zoom whilst changing the center of the map?

**Comment by IBanda** [comment]
Is it possible you could provide a CodeSandbox or any of your liking?

**Comment by dionkas** [comment]
This is my map component wrapped in a div.

I set the location object using an input box and passing it down as props to my map. Each time a new location is set it centers to that (and i log the center and zoom and they are as expected). However when I change zoom level via the buttons or scrolling and change location it no longer zooms to what i set in the location.zoom prop.

`        <GoogleMapReact
          className="map-container"
          bootstrapURLKeys={{ key: API_KEY }}
          center={location.center}
          zoom={location.zoom}
          options={(maps) => ({
            minZoom: 12,
            maxZoom: 17,
            clickableIcons: false,
          })}
        >
          {markers).map((marker) => (
            <AnyComponent
              key={marker.id}
              lat={jmarker.location.latLng.lat}
              lng={markerk.location.latLng.lng}
              text="My marker"
            />
        </GoogleMapReact>`

**Comment by IBanda** [comment]
Google-map-react internally checks for equality on the zoom prop, if it's the same then it won't set the zoom  which is the case in this instance, furthermore google maps keeps track of it's own zoom which you notice in the onChange or onZoomAnimationEnd. So that's why the zoom doesn't automatically reset to your default, however to resolve this you could keep track of the zoom value in the onChange and use it when you change location.
I hope this helps.

**Comment by dionkas** [comment]
Thank you for your pointer. I am trying to keep track of the zoom by using state then use that for my zoom. No luck so far!

**Comment by dionkas** [comment]
Did it! had to also set zoom level in my handleChange function:
```
  function handleChange(e) {
    setCurrentAddress(location.address)
    setZoomLevel(e.zoom)
```

**Comment by IBanda** [comment]
Great!! 
Glad I could help.🙂

**Comment by IBanda** [comment]
close #985

**Comment by karldanninger** [comment]
Thank you @IBanda <3
