### ISSUE TITLE
How to add Border radius on Map component?

### ISSUE THREAD

**Issue by eminaydin** [google-map-react/google-map-react#987]
As the question speaks itself, ı am trying to add `border radius` on Map component but couldn't manage to do so by playing with `options` or `style` props. I would appreciate any help.

**Comment by karldanninger** [comment]
<div style={{borderRadius: '10px', overflow: 'hidden'}}>
  <GoogleMapReact ... />
</div>

**Comment by eminaydin** [comment]
Well, I have tried this solution even before opening this pr and as it didn't work out I wanted to reach out and ask for help.
