### ISSUE TITLE
Tooltip in full screen mode

### ISSUE THREAD

**Issue by Andrey-Mayanov** [google-map-react/google-map-react#988]
Hello. Please tell me what the problem may be: I use https://material-ui.com/api/tooltip/ for map markers, when I make the map full screen, the tooltips are not displayed. I tried different versions of the z-index property, but it doesn't help. In the Elements tab, I can see the tooltip, but it's always behind the map. Thanks!

**Comment by IBanda** [comment]
@Andrey-Mayanov Please provide a Codesandbox or any of your liking. It will make it easier to help you.

**Comment by Andrey-Mayanov** [comment]
Map component: 
```
<div style={{ height: "500px", width: "100%" }}>
    <GoogleMapReact
      bootstrapURLKeys={{ key: XXX }}
      options={{ minZoom: 2, maxZoom: 6 }}
    >
      {markers.map((marker) => (
        <MapMarker
          key={`marker-${marker.id}`}
          lat={marker.latitude}
          lng={marker.longitude}
          cloudType={marker.type}
          region={marker.name}
          value={marker.total}
          color={marker.color}
          startDate={startDate}
          endDate={endDate}
        />
      ))}
    </GoogleMapReact>
  </div>
```

MapMarker:
```
<Tooltip
    title="text"
    interactive
  >
    <div
      className={classes.marker}
    >
      <span style={{ transform: "rotate(45deg)" }}>{value >= ONE_CENT ? formattedValue : ""}</span>
    </div>
  </Tooltip>
```

Tooltip is a component of material-UI.

**Comment by IBanda** [comment]
When google maps enters full screen mode it only shows what's contained between these tags <GoogleMapReact></GoogleMapReact>, Hence why markers are visible, but the problem is the tooltip is added outside of the google maps component by the Material-ui library.( I believe they do this to help with positioning the tooltip on the page).
For it to work you need find a way to have the tooltip be within the google maps component

**Comment by Andrey-Mayanov** [comment]
Oh, that's a very useful description of behavior! Thank you very much!

**Comment by IBanda** [comment]
@Andrey-Mayanov , I managed to hack up something that might be of assistance to you check it out and see what you can do with it. here's the link to the [Codesandbox](https://codesandbox.io/s/google-map-react-with-infobox-visible-onfullscreen-405s5)

**Comment by Andrey-Mayanov** [comment]
@IBanda, Yes, I have already written a custom element, huge thanks for your help!=)
