### ISSUE TITLE
The map is breaking with ad blockers

### ISSUE THREAD

**Issue by pcnascimento** [google-map-react/google-map-react#991]
**Describe the bug 🐛**

Some users of my application report that if they use one ad blocker (like Disconnect), the ga it's not created and the map breaks.

**To Reproduce 🔍**

1. install this ad blocker (https://chrome.google.com/webstore/detail/disconnect/jeoacafpbcihiomhlakheieifhpjdfeo?hl=en)
2. Go to your application that use this library
3. Click to see the map in your application

**Screenshots 🖥**

<img width="579" alt="Captura de Tela 2021-01-13 às 09 11 54" src="https://user-images.githubusercontent.com/68568193/104431949-67c3eb80-5580-11eb-8a43-364dd167d920.png">

![Captura de Tela 2021-01-13 às 09 18 36](https://user-images.githubusercontent.com/68568193/104431903-5975cf80-5580-11eb-9384-8db13eb4c05f.png)

**Environment:**
 - Version: "^2.1.9",

**Comment by itsmichaeldiego** [comment]
This problem is not related to the library itself! I am guessing its a problem between this ad blocker and google maps api itself.

**Comment by pcnascimento** [comment]
Sorry, but I disagree. This library is responsible for loading the google script, right? So, makes sense the solution should be on your side. But thanks, I will try find a solution.

**Comment by itsmichaeldiego** [comment]
@pcnascimento So your error is with the google script then? Could you find out more? Let me know and I will take a look
