### ISSUE TITLE
Can I set channel option when generating googleMapReact?

### ISSUE THREAD

**Issue by apple77y** [google-map-react/google-map-react#992]
**Is your feature request related to a problem? Please describe 🙏**

https://developers.google.com/maps/premium/reports/usage-reports#channels
I want to use this option when I get the google map object.

**Describe the solution you'd like 🤔**

``` ts
<GoogleMapReact
        bootstrapURLKeys={{ key: process.env.GOOGLE_MAPS_API_KEY, client: "your_channel" }}
      >
  {children}
</GoogleMapReact>
```

**Describe alternatives you've considered ✨**

I guess there is no alternative way.

**Comment by IBanda** [comment]
@apple77y Did you figure this out?

**Comment by apple77y** [comment]
@IBanda You can solve this like below.

```
  {
    key: `${GOOGLE_MAPS_API_KEY}&channel=YOUR_CHANNEL`,
  },
```
