### ISSUE TITLE
Change markers after initial loading

### ISSUE THREAD

**Issue by zzehli** [google-map-react/google-map-react#993]
I want to be able to add more markers or change a new set of marker after i trigger an event on the page.  

In my project, I want to be able to toggle away the fire markers when I click the `fire` button. And click `storm` to make snow locations appear/disappear in a similar way.
![Screenshot 2021-01-18 211548](https://user-images.githubusercontent.com/62496205/104983462-707a4e80-59d2-11eb-9372-2b627cce0cfa.png)

**Comment by IBanda** [comment]
use state to hold the markers, then just update the state according to what you intend to display.

**Comment by zzehli** [comment]
> use state to hold the markers, then just update the state according to what you intend to display.

I think for it to function, you need to hold the markers in a div inside the `<GoogleMapReact>` and toggle the div away with onClick. But that is not allowed inside the `<GoogleMapReact>`

```
return (
        <div className="map">
            <GoogleMapReact
                bootstrapURLKeys={{ key: '' }}
                defaultCenter={ center }
                defaultZoom={ zoom }
            >
                {markers} //add a div here with onClick() to hold the markers 
            </GoogleMapReact>
            {locationInfo && <LocationInfoBox info={locationInfo} />}
        </div>
    )
```

**Comment by IBanda** [comment]
why do you want the div to have the onClick method?

**Comment by zzehli** [comment]
I changed the `marker`s to a function and change the parameter with onClick elsewhere, but it does not trigger a re-render.

**Comment by zzehli** [comment]
@IBanda could you be more specific how I can do it? Now I have the following code. I want to press the buttons on the top left of the screen to toggle different markers. To render different markers, I will pass different parameter to the `marker(idx)` function. But I am having trouble figuring out how to set up the hooks/if it is possible.

Basically I want to press
```
const Map = ({ eventData, center, zoom }) => {
    const [locationInfo, setLocationInfo] = useState(null);
    const [infoBox, setInfoBox] = useState(true);
    const [alertIcon, setAlertIcon] = useState(); 

    function marker(idx) {return eventData.map((ev, index) => {
        if(ev.categories[0].id === idx) {
            console.log(idx);
            return <LocationMarker key = {index} lat={ev.geometries[0].coordinates[1]} lng={ev.geometries[0].coordinates[0]} onClick={() => {
                setLocationInfo({ id: ev.id, title: ev.title });
                setInfoBox(!infoBox);
            }} />
        }
        return null
    })}
    
   

    return (
        <div>
            <div id="mySidenav" className="sidenav">

                //click here and trigger event, pass parameter to function
                <a href="#" id="Fire" onClick = {() => {
                    setAlertIcon(()=>marker(10));
                }}>Fire</a>
                <a href="#" id="Storm">Storm</a>
            </div> 
 
            <Header/>
            {/*reload this component*/}
            <div className="map">
                <GoogleMapReact
                    bootstrapURLKeys={{ key: process.env.REACT_APP_API_KEY }}
                    defaultCenter={ center }
                    defaultZoom={ zoom }
                >
                    {alertIcon} //here is the problem
                                // supposed to make markers rerender upon onClick events
                </GoogleMapReact>
 
                {infoBox && 
                    <div  onClick={()=> setInfoBox(!infoBox)}>
                        {locationInfo && <LocationInfoBox info={locationInfo}/>}
                    </div>
                }
            </div>
        </div>
    )
}
```

**Comment by IBanda** [comment]
Hey have a look at this [sandbox ](https://codesandbox.io/s/romantic-leakey-pr6gl)

**Comment by mac066** [comment]
[IBanda](https://github.com/IBanda)
Really thanks for your replay but I've one issue when I've add new marker or relocate the marker re-rendering doen't work. You can view it at  [fork](https://codesandbox.io/s/fancy-haze-dsph7m) plz click the add button it doesn't add any marker
