### ISSUE TITLE
Version 2.1.9 (?) reports broken dependency on react@^16.0,0

### ISSUE THREAD

**Issue by SomervilleTom** [google-map-react/google-map-react#995]
**Describe the bug 🐛**

When I use npm (v6.14.11) to install `google-map-react`, it attempts to install v2.1.9.  A subsequent `npm list --depth=0` reports:
```
npm ERR! peer dep missing: react@^16.0.0, required by google-map-react@2.1.9
npm ERR! peer dep missing: react-dom@^16.0.0, required by google-map-react@2.1.9
```
When I use yarn (v1.22.5), I get the following during the yarn install:
```
warning " > google-map-react@2.1.9" has incorrect peer dependency "react@^16.0.0".
warning " > google-map-react@2.1.9" has incorrect peer dependency "react-dom@^16.0.0".
```
According the package's `package.json`, I've installed `react@17.0.1` and `react-dom@17.0.1`.

I'm new enough to all this that I'm also confused by the difference between the released version reported here (v2.0.4) and installed by npm (v2.1.9). I also am not sure that any of this is even a problem.

**To Reproduce 🔍**

1. Build CRA package on CentOS 7 (`npx create-react-app foobar`) using CRA v17.0.1.
2. CD into new directory
3. NPM: run `npm install google-map-react`, then `npm list --depth=0`
Result:
```
$ npm list --depth=0
databrowser@0.1.0 /opt/react/databrowser_mvp/databrowser
├── @material-ui/core@4.11.3
├── @material-ui/icons@4.11.2
├── @material-ui/styles@4.11.3
├── @testing-library/jest-dom@5.11.9
├── @testing-library/react@11.2.3
├── @testing-library/user-event@12.6.2
├── axios@0.21.1
├── google-map-react@2.1.9
├── node-fetch@2.6.1
├── UNMET PEER DEPENDENCY react@17.0.1
├── UNMET PEER DEPENDENCY react-dom@17.0.1
├── react-google-recaptcha@2.1.0
├── react-router@5.2.0
├── react-router-dom@5.2.0
├── react-scripts@4.0.1
├── typescript@4.1.3
└── web-vitals@0.2.4

npm ERR! peer dep missing: react@^16.0.0, required by google-map-react@2.1.9
npm ERR! peer dep missing: react-dom@^16.0.0, required by google-map-react@2.1.9
```
4. YARN: Run `yarn add google-map-react`.
Result:
```
$ yarn add google-map-react
yarn add v1.22.5
[1/4] Resolving packages...
[2/4] Fetching packages...
info fsevents@2.3.1: The platform "linux" is incompatible with this module.
info "fsevents@2.3.1" is an optional dependency and failed compatibility check. Excluding it from installation.
info fsevents@1.2.13: The platform "linux" is incompatible with this module.
info "fsevents@1.2.13" is an optional dependency and failed compatibility check. Excluding it from installation.
[3/4] Linking dependencies...
warning " > @testing-library/user-event@12.6.3" has unmet peer dependency "@testing-library/dom@>=7.21.4".
warning " > google-map-react@2.1.9" has incorrect peer dependency "react@^16.0.0".
warning " > google-map-react@2.1.9" has incorrect peer dependency "react-dom@^16.0.0".
[4/4] Building fresh packages...
success Saved lockfile.
success Saved 3 new dependencies.
info Direct dependencies
└─ google-map-react@2.1.9
info All dependencies
├─ @googlemaps/js-api-loader@1.11.1
├─ @mapbox/point-geometry@0.1.0
└─ google-map-react@2.1.9
Done in 7.46s.
```
**Expected behavior 💭**

I expected a clean install with either npm or yarn.

I'm also surprised to get v2.1.9 instead v2.0.4. 

**Environment:**

 - OS: Centos 7 on AWS EC2 large instance

**Additional context**

I'm a very experienced developer (30+ years of professional software development experience), but relatively new (six months) to nodejs/npm/react.

**Workaround**

I was able to get a clean install by reverting to react@16.14.0: `npm install --save react@16.14.0 react-dom@16.14.0`. After doing that, `google-map-react` installs cleanly. I don't yet know if this change has other impacts on the project.

**Comment by kamrankhanwastaken** [comment]
Will there be an update on this by any chance? I cannot revert to an older version of react and react-dom because of conflicts with another module dependency so wondering where to go from here. :(

**Comment by SomervilleTom** [comment]
> Will there be an update on this by any chance? I cannot revert to an older version of react and react-dom because of conflicts with another module dependency so wondering where to go from here. :(

I gave up on this package in favor of `@react-google-maps/api`. While having its own issues, especially with documentation, I've had no particular problem using current versions of React.

I've had the most success by installing using yarn: `yarn add @react-google-maps/api`. As in all things with `npm` and `react`, your mileage may vary.

**Comment by countzyx** [comment]
This seems to work ok -

`npm i google-map-react --legacy-peer-deps`

**Comment by itsmichaeldiego** [comment]
Hey folks, this should be ok now, we just released a patch for this.
