### ISSUE TITLE
trigger redraw through GoogleMapApiInternals

### ISSUE THREAD

**Issue by cindylouwhovian** [google-map-react/google-map-react#996]
New to both React and google-map-react. I am tryin to load geojson through a button click.  I dunno if this is a feature or bug request??  The idea is that clicking the button should load the geojson.   I have tried a lot of things but below is the simplified version which I thought might work.  Is this possible?

                                          import React from "react";
                                          import GoogleMapReact from "google-map-react";
                                          import "./styles.css";
                                          
                                          const mapProps = { center: { lat: -28.2723379, lng: 137 }, zoom: 4 };
                                          
                                          export default function App() {
                                            const [isOn, setIsOn] = React.useState(false);
                                            const handleCheckboxChange = (e) => setIsOn(e.target.checked);
                                            
                                            const mapStyles = { height: 500, width: "100%" };
                                          
                                            const handleApiLoaded = (map, maps, isOn) => {
                                              console.log("isON", isOn);
                                          
                                              if(isOn) {
                                               map.data.loadGeoJson(   
                                                "https://storage.googleapis.com/mapsdevsite/json/google.json"
                                                );
                                               }
                                            }
                                          
                                            return (
                                              <div className="App">
                                                <input
                                                  id="checkbox"
                                                  type="checkbox"
                                                  checked={isOn}
                                                  onChange={handleCheckboxChange}
                                                />
                                                <label htmlFor="checkbox">Load GeoJson</label>
                                                <div style={mapStyles}>
                                                  <GoogleMapReact
                                                    {...mapProps}
                                          /*           someOtherPropToTriggerComponentUpdate={isOn} */
                                                    yesIWantToUseGoogleMapApiInternals
                                                    onGoogleApiLoaded={({ map, maps }) => handleApiLoaded(map, maps, isOn)}
                                                    />
                                                </div>
                                              </div>
                                            );
                                          }

**Comment by IBanda** [comment]
Hi @cindylouwhovian 
I did created a [Codesandbox](https://codesandbox.io/s/affectionate-field-lhowx) you can take a look at.
Also take a look at these two react hooks [useEffect](https://reactjs.org/docs/hooks-reference.html#useeffect) and [useRef](https://reactjs.org/docs/hooks-reference.html#useref) if you're not familiar with them. 
Since you used a checkbox I assumed you want to toggle the GeoJson so I added that functionality as well 
I hope this helps.
