### ISSUE TITLE
ZoomControlOptions not working

### ISSUE THREAD

**Issue by scottkatzelnick** [google-map-react/google-map-react#999]
**Describe the bug 🐛**

Is this working in the Curren release? I cannot get it working:

<pre><code>function createMapOptions(maps) {
  return {
    styles: mapStyles,
    zoomControl: true,
    ZoomControlOptions: {
      position: maps.ControlPosition.TOP_LEFT,
      style: maps.ZoomControlStyle.SMALL,
    },
    mapTypeControl: false,
    streetViewControl: false,
    rotateControl: false,
    scaleControl: false,
    fullscreenControl: false,
  }
}</code></pre>

A per closed issue #6 , this should now be implemented.

**Screenshots 🖥**

As you can see the zoom control is still in the default lcation...
<img width="2048" alt="image" src="https://user-images.githubusercontent.com/32975303/107752994-7ae7e980-6ced-11eb-89b9-dc129c6204a5.png">

**Environment:**

 - Framework: Next.js 10.0.1 [React]
 - Browser Any
 - Package Version 2.1.9

**Comment by IBanda** [comment]
@scottkatzelnick use zoomControlOptions (lowercase 'z')

**Comment by scottkatzelnick** [comment]
> @scottkatzelnick use zoomControlOptions (lowercase 'z')

Thank you @IBanda
